### ISSUE TITLE
Option or easy access button for source migration

### ISSUE THREAD

**Issue by Cjojojojo** [CarlosEsco/Neko#1007]
### Describe your suggested feature

Other forks works on migration with ease for it is already in options or easy acces parts.

Placing the "find from other sources" button for missing chapters will be a big help if it is placed in manga panel > three dots at the top right corner > Find from other sources.

Then it will take you something like in extensions but limited only to atleast (1) one source/extension

### Other details

If not possible, at least put it in Neko settings. I know it's a bit hard work but i have faith in this team. I always want the Neko for it's clean UI compared to others, i'm not saying they are bad but for me this one stand outs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Are you asking to have the merge option in the actual reader?

**Comment by Cjojojojo** [comment]
Yeaah, like in the upper top right or in an options menu.

This is not a hate comment btw, i'm just kinda confused in the description
which says "Look at an additional source for missing chapters not hosted on
MangaDex", is this refers to the merge?

**Comment by CarlosEsco** [comment]
Yes.  Migration is moving to a different source entirely like other Tachi's support.  Merge is combing a source chapters within the mangadex entry.  As for adding it in the manga view.  I dont think that would make sense. If there are any missing chapters you already know right off the bat with the missing chapter count on the manga info screen

**Comment by Cjojojojo** [comment]
Great, thanks!
