### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by Cjojojojo** [CarlosEsco/Neko#1008]
### Describe your suggested feature

Where do i exactly go or click to migrate from other sources like Mangalife?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This is a question for discord

**Comment by Cjojojojo** [comment]
Awesome, thanks!
