### ISSUE TITLE
Using the back gesture anywhere outside a manga chapter closes or crashes the app. 

### ISSUE THREAD

**Issue by LinkofHyrule89** [CarlosEsco/Neko#1015]
### Steps to reproduce

1. Finish reading a chapter. 
2. Click back to go to the chapters list. 
3. Press back to go to the manga list
4. The app closes or crashes. 

### Expected behavior

It would go back to the previous manga list instead of closing. 

### Actual behavior

It closes or crashes when you use the back gesture outside of a chapter. 

### Crash logs
[NekoLog.txt](https://github.com/CarlosEsco/Neko/files/8946898/NekoLog.txt)

### Neko version

2.9.2

### Android version

Android 13 Beta June 5th

### Device

Google Pixel 4a 5G

### Other details

This bug has been around the past two or three versions. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This is a known issue with Android 13 and with how j2k has currently implemented.

**Comment by CarlosEsco** [comment]
Do you still have this issue?

**Comment by CarlosEsco** [comment]
should be resolved
