### ISSUE TITLE
Mark `readableAt` as nullable

### ISSUE THREAD

**Issue by GSculerlor** [CarlosEsco/Neko#1018]
### Steps to reproduce

can be reproduced when trying to update Nisekoi (`/ce16b1c3-d6bb-41e0-8671-d8b065248ba2`). Chapter 182 has null `readableAt` thus making Neko fail to update that manga. 

I have a [branch on my fork](https://github.com/GSculerlor/Neko/tree/nullable-readableat) to fix this by letting `publishAt` as a default value but it will basically revert [this attempt to fix 2037 thingy](https://github.com/CarlosEsco/Neko/commit/cb9dcd714fa7291c53a19dc1eda4199b7550f772). so that's why I open issue report first to to make sure the desired behavior for this one (by showing 2037 date or hide the date `TextView`).

### Expected behavior

Neko should be able to fetch updates on the manga with nullable `readableAt` chapter(s) 

### Actual behavior

Neko fail to fetch updates

### Crash logs

```md
! Error trying to view chapters Unexpected JSON token at offset 5482: Unexpected 'null' value instead of string literal at path: $.data[2].attributes.readableAt JSON input: .....00:00+00:00","readableAt":null,"createdAt":"2022-06-07T15:10..... kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 5482: Unexpected 'null' value instead of string literal at path: $.data[2].attributes.readableAt JSON input: .....00:00+00:00","readableAt":null,"createdAt":"2022-06-07T15:10..... - Nisekoi
```

### Neko version

Stable 2.9.2, reproducible on `master`

### Android version

Android 12

### Device

Emulator (Android Studio)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Should be good soon. The field shouldn't be nullable at all.  I sent a reindex request to dex
