### ISSUE TITLE
Pages not loading

### ISSUE THREAD

**Issue by GyuminLeo** [CarlosEsco/Neko#1019]
### Steps to reproduce

1. Open/download manga
2. Error

### Expected behavior

Pages should load

### Actual behavior

Doesn't load

### Neko version

2.9.2

### Android version

Android 12

### Device

LG Velvet

### Other details

![Screenshot_20220626-141053](https://user-images.githubusercontent.com/63228390/175800384-07148967-ab12-4a40-8806-ac58023da916.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by GyuminLeo** [comment]
> Which chapter did you try to open?

Every mangaplus ones wont work
Ch.0 and Ch5.5 works

**Comment by CarlosEsco** [comment]
can you click it to get the error, then dump a crash log here?

**Comment by GyuminLeo** [comment]
> can you click it to get the error, then dump a crash log here?

App version: 2.9.2 (standard, 335be3ce7, 144, 2022-06-20T14:33:22.387017)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211103.001
Device brand: lge
Device manufacturer: LGE
Device name: caymanlm
Device model: LM-G910N
Device product name: caymanlm_fg
--------- beginning of main
06-30 01:28:24.510 15282 15338 E FrameEvents: updateAcquireFence: Did not find frame.
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	├ eu.kanade.tachiyomi.source.online.handlers.PageHandler$fetchPageList$2.invokeSuspend(PageHandler.kt:49)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	└ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
06-30 01:28:26.039 15282 15341 E ||NEKO  : error processing page list 
06-30 01:28:26.039 15282 15341 E ||NEKO  : kotlinx.serialization.MissingFieldException: Field 'englishPopup' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.MangaPlusErrorResult', but it was missing at path: $.error at path: $.error
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:2)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:3)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at eu.kanade.tachiyomi.source.online.handlers.external.MangaPlusHandler.fetchPageList(MangaPlusHandler.kt:15)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at eu.kanade.tachiyomi.source.online.handlers.external.MangaPlusHandler$fetchPageList$1.invokeSuspend(Unknown Source:12)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
06-30 01:28:26.039 15282 15341 E ||NEKO  : Caused by: kotlinx.serialization.MissingFieldException: Field 'englishPopup' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.MangaPlusErrorResult', but it was missing at path: $.error
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:2)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:2)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:2)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at eu.kanade.tachiyomi.source.online.models.dto.MangaPlusResponse$$serializer.deserialize(MangaPlusDto.kt:1)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at eu.kanade.tachiyomi.source.online.models.dto.MangaPlusResponse$$serializer.deserialize(MangaPlusDto.kt:2)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:13)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:1)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	... 9 more
06-30 01:28:26.039 15282 15341 E ||NEKO  : Caused by: kotlinx.serialization.MissingFieldException: Field 'englishPopup' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.MangaPlusErrorResult', but it was missing
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:3)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at eu.kanade.tachiyomi.source.online.models.dto.MangaPlusErrorResult.<init>(MangaPlusDto.kt:1)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at eu.kanade.tachiyomi.source.online.models.dto.MangaPlusErrorResult$$serializer.deserialize(MangaPlusDto.kt:1)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at eu.kanade.tachiyomi.source.online.models.dto.MangaPlusErrorResult$$serializer.deserialize(MangaPlusDto.kt:2)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:13)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:1)
06-30 01:28:26.039 15282 15341 E ||NEKO  : 	... 15 more
06-30 01:28:26.085 15282 15282 E ||NEKO  : 	├ eu.kanade.tachiyomi.ui.reader.ReaderActivity.setInitialChapterError(ReaderActivity.kt:1)
06-30 01:28:26.085 15282 15282 E ||NEKO  : 	└ eu.kanade.tachiyomi.ui.reader.ReaderPresenter$init$10.invoke(ReaderPresenter.kt:2)
06-30 01:28:26.085 15282 15282 E ||NEKO  : kotlinx.serialization.MissingFieldException: Field 'englishPopup' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.MangaPlusErrorResult', but it was missing at path: $.error at path: $.error
