### ISSUE TITLE
Dark mode display issue

### ISSUE THREAD

**Issue by oge2k** [CarlosEsco/Neko#1030]
### Steps to reproduce

1.click on About
2. Display options not showing well in some dark mode

### Expected behavior

The options should show like this 
![Screenshot_20220630-232639](https://user-images.githubusercontent.com/46646966/176797318-8331ec16-0d74-4d14-8e4e-49a304024e4d.png)

### Actual behavior

This is how it displays if you use dark mode mangadex, dark mode grey wolf, dark mode outrun, dark mode midnight dusk, dark mode neko green, dark mode chocolate strawberry.
![Screenshot_20220630-232654](https://user-images.githubusercontent.com/46646966/176797554-ffb1be72-f804-423a-9d8b-61cc62d71bdc.png)

### Neko version

2.9.3

### Android version

Android 10

### Device

Umidigi A9 pro

### Other details
I use the pure dark mode option i dont think it affects these themes if you do not use pure dark mode option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0
