### ISSUE TITLE
Neko won't install new version in the app

### ISSUE THREAD

**Issue by Uniter343** [CarlosEsco/Neko#1031]
### Steps to reproduce

1. Click "check for update" (or just restart the app to get the "new version available!" pop up
2. Click update
3. Wait

### Expected behavior

The app should open the install page once the update is downloaded

### Actual behavior

Nothing happens.
Upon reopening the app or checking for updates the same thing happens (you once again download the update).

### Neko version

2.9.2

### Android version

Android 12

### Device

Xiaomi Mi 11T Pro

### Other details

I have to download the APK from GitHub for each update (then the normal option for updating appears when opening the APK).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by Curstantine** [comment]
Had the same issue where it would not update at certain times, usually downloading the apk from github and "updating" it from the package installer makes the next version work fine.

**Comment by Uniter343** [comment]
Yeah as said in the issue it happens to me every time, i always have to download from GitHub because updating in the app doesn't work.

**Comment by gcpadua** [comment]
This issue just happened with me. My guess is that our android skin is blocking the session installer that the app uses. Having an option to use the native installer instead of the session installer would solve this issue.
The workaround for this problem that doesn't involves just installing the latest APK for MIUI phones is to go to developer settings and disabling MIUI optimizations.

**Comment by danuharyp** [comment]
It's been quite a while but it's working now, can download and update from the notification bar on my phone. Cheers!

**Comment by Uniter343** [comment]
Yes, can confirm it's been working again for a few months now.
