### ISSUE TITLE
Add Filter Original Language of the Manga in the Mangadex Settings

### ISSUE THREAD

**Issue by bhanuharya** [CarlosEsco/Neko#1034]
### Describe your suggested feature

I'm aware that we can use the original language in the browse filtering, but I have to pick the original language filter every time I'm browsing for a new title when mainly I just read titles from Japanese and Korean original language. If this feature implemented, user doesn't have to do extra steps again if they have preferences for the original language filter.

The feature is available on mangadex and the original tachiyomi.

![image](https://user-images.githubusercontent.com/52481318/177276069-91c90aaf-e8ec-44ab-862b-3bb278bab605.png)

![image](https://user-images.githubusercontent.com/52481318/177275939-23460765-4cab-45ca-97e7-2d45bcab52f6.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
As of 2.11.0 you can set the filters how you want in the browse screen then save it, and set it as a default for every search
