### ISSUE TITLE
Missing Chapters logic not counting initial gap

### ISSUE THREAD

**Issue by curche** [CarlosEsco/Neko#1036]
### Steps to reproduce

1. Open this link as a MangaDex (English) user: https://mangadex.org/title/9f39246a-8b05-4b19-b822-727e748723dc/aharen-san-wa-hakarenai?page=1
2. Notice that Neko shows there are 7 missing chapters. Check what's the oldest chapter (scroll to bottom or use sort)
3. First chapter in list is Ch 67. Most recent chapter is Ch 144

### Expected behavior

There are 7 missing chapters between Ch 67 - 144.
Nothing about Ch 1 - Ch 66

### Actual behavior

There should actually be 7 missing chapters + 66 missing chapters from the start

### Neko version

2.9.3

### Android version

Android 12

### Device

jasmine_sprout

### Other details

Might be nice to check for initial gap separate from missing in between but honestly it shudnt matter because imo the Missing Chapters is just an indication to Merge the mange to fill in gaps if required

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0
