### ISSUE TITLE
Page gap

### ISSUE THREAD

**Issue by leo341500** [CarlosEsco/Neko#1037]
### Describe your suggested feature

I use a surface duo, and the lack of a page gap option causes the inner edge of the pages to disappear into the gap. Adding an option to set a gap of a configurable amount of pixels between the pages would entirely fix that. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
I'm assuming you mean on the double page spread?

**Comment by leo341500** [comment]
> I'm assuming you mean on the double page spread?

Yes indeed

**Comment by leo341500** [comment]
Oh yeah just to add, the gap in the duo hides 88 pixels that are still rendered in software, so i'd need a gap of 88 pixels between the pages to have them display correctly. Though a configurable value would still be better considering the duo 2 has a 66 pixels gap, and there may be more dual display phones in the future.

**Comment by CarlosEsco** [comment]
Will probably be on the backburner for a while.  Talked to Jay from J2K and he mentioned its bit tough to do, especially if its a legit dual page, and not one stitched together

**Comment by leo341500** [comment]
Oh yeah if its a true dual page straight from the server, you'd need to render two single pages instead, thats kinda ass. Otherwise thanks for at least considering it, and have a good [insert timezone appropriate time].

**Comment by CarlosEsco** [comment]
2.10.11
