### ISSUE TITLE
Low quality covers not working in library

### ISSUE THREAD

**Issue by UkeCat69** [CarlosEsco/Neko#1038]
### Steps to reproduce

Having low res thumbnails only counts for browsing. When adding to library it switches to original quality

### Expected behavior

low quality covers

### Actual behavior

1.5mb "low quality" covers in cache

### Neko version

2.9.3

### Android version

Android 8.1

### Device

Redmi 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Was going to add this for the next release, but its going to require more changes then expected.  It's been broken since v5 covers have been out.

**Comment by CarlosEsco** [comment]
2.9.4.
