### ISSUE TITLE
Manga not syncing if using matching categories with MangaDex Library categories

### ISSUE THREAD

**Issue by sbxn14** [CarlosEsco/Neko#1045]
### Steps to reproduce

1. have categories that are named the same and ordered the same as the library categories of MangaDex (Plan to Read, Reading, Dropped, On-Hold, Re-Reading and Completed)
2. add manga to (For example) the Reading category of the library on Mangadex.org (webversion)
3. Go to mangadex settings in Neko and Sync Mangadex follows. (Make sure the relevant category is checked)

### Expected behavior

Manga gets synced properly on pressing the button and the toast appears.

### Actual behavior

No toast of "synced X new manga from MangaDex" and no synced manga.

### Neko version

2.9.4

### Android version

Android 10

### Device

Lenovo Tab M10 FHD Plus

### Other details

I figured since the library of mangadex has several categories (Plan to Read, Reading, Dropped, On-Hold, Re-Reading and Completed), i'd copy this structure and create it in the Neko app, figuring it would 'sync' the manga properly to category. This was not the case.

Everything works perfectly fine if I remove all the categories on Neko.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This isn't a bug because thats not how the feature works. 
Syncing from Dex will add manga that are followed to your library and thats it. 

It sounds like you were expecting something more along the lines of this.
https://github.com/CarlosEsco/Neko/issues/609
