### ISSUE TITLE
Downloading manga for later doesn't work

### ISSUE THREAD

**Issue by Firstbober** [CarlosEsco/Neko#1046]
### Steps to reproduce

1. Select any manga
2. Press download button

### Expected behavior

Progress bars in Recents > Download queue should move and make progress.

### Actual behavior

It just sits there and does nothing.
![image](https://user-images.githubusercontent.com/22197465/183132623-3380b0ed-1747-43e6-a26d-77791f2bde68.png)

### Neko version

2.9.4

### Android version

Android 11 - MIUI 12.6 by xiaomi.eu

### Device

POCO F3

### Other details

By default, Neko points to some random location in the file system, so when trying to download anything the "Resume" button in `Download queue` doesn't work and reverts to "Resume" again after flashing with "Pause" text. Fixed by changing path location and granting permissions to it at the same time. Maybe some toast or any other alert could be added to smoothen UX in these cases.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Were you out of space and thats why it wasnt downloading, or were they bad chapters?

**Comment by Firstbober** [comment]
None of these, I have around 100 GB of free space and chapters also work when reading, only download for later doesn't work. On TachiyomiJ2K there is no such problem.

**Comment by CarlosEsco** [comment]
after you click resume, can you go the settings and dump the crash log and attach it here

**Comment by Firstbober** [comment]
```
App version: 2.9.4 (standard, 1df62a6e6, 146, 2022-07-10T20:16:21.705146)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 release-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: alioth
Device model: M2012K11AC
Device product name: alioth
--------- beginning of system
--------- beginning of main
08-12 16:54:16.914 31869 31869 E hiyomi.mangade: Not starting debugger since process cannot load the jdwp agent.
08-12 16:54:17.789 31869 31955 E SQLiteLog: (284) automatic index on C(manga_id)
08-12 16:54:17.789 31869 31955 E SQLiteLog: (284) automatic index on R(manga_id)
08-12 16:54:17.789 31869 31955 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
08-12 16:54:17.832 31869 31957 E SQLiteLog: (284) automatic index on C(manga_id)
08-12 16:54:17.832 31869 31957 E SQLiteLog: (284) automatic index on mangas(_id)
08-12 16:54:19.419 31869 32034 E SQLiteLog: (284) automatic index on mangas(_id)
08-12 16:54:21.265 31869 31869 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
08-12 16:54:21.266 31869 31869 E libc    : Access denied finding property "ro.vendor.knock.type"
```

**Comment by CarlosEsco** [comment]
Nothing in the logs, have you tried clearing the queue and redownloading?

**Comment by Firstbober** [comment]
Several times.

**Comment by CarlosEsco** [comment]
Do you have any download restrictions on?  If so can you send a screen?  Finally can you enable verbose debugging, force close app, resume the download then send the log.

**Comment by Firstbober** [comment]
Here are the logs on Extra level: [log.txt](https://github.com/CarlosEsco/Neko/files/9363050/yourdocument.txt)

**Comment by CarlosEsco** [comment]
Did you get this directly from the /neko folder or dumping?  the dump doesnt include the extra logs, and that one is pretty empty

**Comment by Firstbober** [comment]
Where I can find log file? I am currently sending neko_crash_logs.txt from `/storage/emulated/0/Android/data/tachiyomi.mangadex/cache`.

**Comment by CarlosEsco** [comment]
it should be in the /storage/emulated/0/neko/logs

**Comment by Firstbober** [comment]
There is no `neko` directory. Maybe some permission issue? Though, it has access to files in device memory, if trusting permission view in app info.

**Comment by CarlosEsco** [comment]
interesting, can you verify the app has write permissions?  maybe thats the issue with the downloads

**Comment by Firstbober** [comment]
Uh, I allowed it to access all android files, and it works now. Thanks.
