### ISSUE TITLE
A way to choose language

### ISSUE THREAD

**Issue by Las974** [CarlosEsco/Neko#1047]
### Describe your suggested feature

On the website, we can choose the language 
![Screenshot_20220806-182225_Firefox](https://user-images.githubusercontent.com/72652814/183257626-b3db6caf-0d8a-4cbd-b928-7f7a84d7728b.jpg)

But not in the app
![Screenshot_20220806-182832_Neko](https://user-images.githubusercontent.com/72652814/183257638-d81d788a-6953-4579-9640-3d9ae07d327f.jpg)

I tried this option 
![Screenshot_20220806-182914_Neko](https://user-images.githubusercontent.com/72652814/183257659-e4c40418-df4a-4d4d-a1ea-2474501cb418.jpg)

But it doesn't change anything

So I'm asking if it is possible to add this features

Thank you in advance, and know that you've done a great job.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by Las974** [comment]
Édit : I found a way to overcome it : start to read on the desired language on the website and then sync with Neko

Sorry to bother you, have a great day

**Comment by CarlosEsco** [comment]
Once you enable the language, you need to swipe refresh the chapter list.  No need to do what you did.
