### ISSUE TITLE
[bug] Force close when open update setting

### ISSUE THREAD

**Issue by Ge2C** [CarlosEsco/Neko#105]
It's happen in version 1.2.3
Which is in general setting some of item it's force close the application when open, the item is:
- Library update rstriction
- Categories to include in global update

**Comment by arsonistAnt** [comment]
Are these options available in the non-release? I can't seem to find it.

**Comment by CarlosEsco** [comment]
You need to create category first.  Then the option will be there.

**Comment by arsonistAnt** [comment]
Figured out why its crashing, seems like library the `conductor-support-preference` is referencing a class that's no longer available in `androidx.preference:preference:1.1.0`.

We could either:

1. Revert back to `1.0.0` and it will work just fine.
2. Wait to see if my [pull request](https://github.com/inorichi/conductor-support-preference/pull/4) will be approved for this lib and update the gradle dependency.
3. Use my forked version of this lib that has the fix already applied & add to gradle.

**Comment by CarlosEsco** [comment]
I forked it.  Open the pull request against my fork I will merge and then you can upgrade to point to my fork
