### ISSUE TITLE
Alternative titles chips start padding 

### ISSUE THREAD

**Issue by CrepeTF** [CarlosEsco/Neko#1052]
### Steps to reproduce

Manga: https://mangadex.org/title/e34c3c84-94fc-4c6e-a68c-4138b92b0886

> Open synopsis 

### Expected behavior

No start padding

### Actual behavior

Has start padding

### Crash logs

N/a

### Neko version

2.10.0 the can you add the old ui back

### Android version

Android 12L

### Device

OnePlus 6t

### Other details

![Screenshot_20220816-193036_Neko](https://user-images.githubusercontent.com/70870719/184953449-e104c919-5f8b-4aef-81ce-980cc75f610b.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0.1
