### ISSUE TITLE
Select priority for backdrop chips

### ISSUE THREAD

**Issue by Seishirou101** [CarlosEsco/Neko#1053]
### Describe your suggested feature

Be able to select what is at the front for the backdrop chips

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Will have option to disable text on the chips instead

**Comment by CarlosEsco** [comment]
2.10.0.1
