### ISSUE TITLE
Ability to specify which content ratings get auto tracked

### ISSUE THREAD

**Issue by Basara-Hatake** [CarlosEsco/Neko#1054]
### Describe your suggested feature

Something like the Content Rating multiselect in the options for auto link tracking, so we can stop for example pornographic or erotica content from beeing auto linked
![image](https://user-images.githubusercontent.com/53382992/184968462-6e654159-baf5-483d-86c4-c1a21b9bc034.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0.1
