### ISSUE TITLE
The new UI sucks please change it back

### ISSUE THREAD

**Issue by thenewuisuckspleasechangeitback** [CarlosEsco/Neko#1055]
### Steps to reproduce

Look at the goddamn new UI at the manga page. It's split in two. It's awful.

### Expected behavior

It should not be split in two!

### Actual behavior

It's split in two!

### Neko version

newest

### Android version

12

### Device

who cares

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Lol
