### ISSUE TITLE
Chapter sort settings text gone with specific themes with pure black dark mode

### ISSUE THREAD

**Issue by bootlegsushi** [CarlosEsco/Neko#1056]
### Steps to reproduce

1. Enable pure black dark mode
2. Choose Neko Green, Outrun, Midnight Dusk, Mangadex, Grey Wolf, or Chocolate Strawberries themes
3. Open chapter sort settings

### Expected behavior

Text to accompany the arrow and check boxes

### Actual behavior

No text

### Neko version

2.10.0

### Android version

Android 12

### Device

Samsung Galaxy S20FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0.1
