### ISSUE TITLE
Landscape/Tablet UI doesn't load synopsis 

### ISSUE THREAD

**Issue by CrepeTF** [CarlosEsco/Neko#1057]
### Steps to reproduce

https://user-images.githubusercontent.com/70870719/185010572-72828bbd-f155-43ae-a2c6-98e2bc2cbb7e.mp4

### Expected behavior

Synopsis loads

### Actual behavior

Synopsis only loads in portrait 

### Neko version

2.10.0 the can you add the old ui back

### Android version

Android 12L

### Device

OnePlus 6t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0.1
