### ISSUE TITLE
Manga info overflow icon and filter icon overlap

### ISSUE THREAD

**Issue by CrepeTF** [CarlosEsco/Neko#1058]
### Steps to reproduce

![Screenshot_20220817-015511_Neko](https://user-images.githubusercontent.com/70870719/185010718-bdbfdaab-9583-46e1-9a56-408962d20abd.png)

### Expected behavior

They do not overlap

### Actual behavior

They overlap and make tapping the overflow confusing

### Neko version

2.10.0 the can you add the old ui back

### Android version

Android 12L

### Device

OnePlus 6t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0.1
