### ISSUE TITLE
Choose which chapters are merged

### ISSUE THREAD

**Issue by lavadragon15396** [CarlosEsco/Neko#1060]
### Describe your suggested feature

When merging a manga, to be able to choose which chapters from the other source are merged so there are no duplicates

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
No plans to add this atm
