### ISSUE TITLE
Pure Black Dark Mode changes some tracking info text to black

### ISSUE THREAD

**Issue by RairenMorioka** [CarlosEsco/Neko#1061]
### Steps to reproduce

1. Set theme to a dark theme with "pure black dark mode" enabled. Neko Green, Outrun, Midnight Dusk, MangaDex, Grey Wolf, and Chocolate Strawberries appear to be effected in my testing.
2. Open any manga in the library with associated tracking

### Expected behavior

This is with Midnight Dusk with the setting off, I would expect to have seen the background be black or nearly black with the white text as in v2.9.4.
![SmartSelect_20220816-203845_Neko](https://user-images.githubusercontent.com/10051995/185022909-af854ce2-5fcf-4d69-aa1a-0ce25b24cda1.jpg)

### Actual behavior

Status, chapter count, and rating all appear to be blacked out.
![SmartSelect_20220816-203909_Neko](https://user-images.githubusercontent.com/10051995/185023612-9948c14d-e3ef-487b-bdad-cdde90ff3dec.jpg)

### Neko version

2.10.0

### Android version

Android 12

### Device

Samsung Galaxy S20 FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0.1
