### ISSUE TITLE
Performance issues with the new manga info page.

### ISSUE THREAD

**Issue by Curstantine** [CarlosEsco/Neko#1062]
### Steps to reproduce

1. Open a manga.
2. Try to scroll.

### Expected behavior

Should scroll without giving you motion sickness even on low/mid-range devices.

### Actual behavior

It stutters!!

https://user-images.githubusercontent.com/69104500/185024978-71e134ad-d450-46f3-80b2-8332aec89780.mp4

### Neko version

2.10.0

### Android version

Android 12 (OneUI 4.1)

### Device

Samsung Galaxy M21

### Other details

Considering how this issue isn't reported yet, I'm sure this is only related to low/mid-end devices.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by megamit** [comment]
This is extra noticeable on my pixel 6 pro as it was previously a smooth 120 FPS and is now a laggy mess. Also the collapsing nav at the top makes scrolling feel weird

**Comment by CarlosEsco** [comment]
Made some tweaks.  Let me know in 2.10.0.1 if its any better

**Comment by chichibooxd** [comment]
Hello. The same issue is still present on 2.10.0.1 but only on mangas with several hundred chapters. In addition, the reader on those chapters sometimes take longer to load (Referring to the reader itself and not the page) compared to ones with less chapters.

**Comment by Curstantine** [comment]
re @CarlosEsco 
It's less but still stutters.

https://user-images.githubusercontent.com/69104500/185639833-a45c776c-290f-4346-bdc7-ab2133f813ea.mp4

**Comment by CarlosEsco** [comment]
let me know how 2.10.3 is

**Comment by Curstantine** [comment]
https://user-images.githubusercontent.com/69104500/187055413-42c16cb2-f310-4d4c-b7be-1dc267c4aff6.mp4

**Comment by CarlosEsco** [comment]
Let me know with 2.10.4

**Comment by Curstantine** [comment]
It's way better, but there are some stutter here and there.

https://user-images.githubusercontent.com/69104500/187109796-0de0b875-c035-48ae-9792-b0da738aac1e.mp4

**Comment by CarlosEsco** [comment]
yep i think its good as compose as can go for now.  Not a ton more optimizations i could do currently.
