### ISSUE TITLE
Option to switch between current and previous UI styles

### ISSUE THREAD

**Issue by Th3N3rdyGam3r** [CarlosEsco/Neko#1063]
### Describe your suggested feature

I prefer the previous UI for the series page since I like being able to use the entire length of my phone rather than adding unnecessary dead space. I suggest implementing a feature similar to what Sync for Reddit did after they got negative feedback with a similar change and have a screen on startup and setting to switch between the two styles. I'll be reverting for now until it's fixed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Enjoy being permanently on 2.9.x

**Comment by Th3N3rdyGam3r** [comment]
No problem, I'll be transferring my library to a better fork with less obnoxious maintainers. J2K even has a setting to disable the "Expanded toolbar" they added.
