### ISSUE TITLE
Manga info stuck in landscape mode

### ISSUE THREAD

**Issue by dvorak13** [CarlosEsco/Neko#1064]
### Steps to reproduce

1. Open Neko
2. Open Manga from library
3. Manga info page is stuck in landscape
flipping between landscape and portrait doesn't fix the issue.

### Expected behavior

When you open a manga, the info page should be in portrait mode.

### Actual behavior

When you open a manga, the info page is stuck in landscape mode
![Screenshot_20220816-223725_Neko 1](https://user-images.githubusercontent.com/111413279/185044890-02ddfacf-bed0-45cd-8562-9b07a68930e8.jpg)
![Screenshot_20220816-223743_Neko 1](https://user-images.githubusercontent.com/111413279/185044937-3afad970-1990-4297-b269-a4ec9e53b6e3.jpg)
.

### Neko version

2.10.0

### Android version

Android 11

### Device

Samsung Galaxy Tab S5e

### Other details

Log file in case it helps:
[2022-08-16-release.txt](https://github.com/CarlosEsco/Neko/files/9356744/2022-08-16-release.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0.1
