### ISSUE TITLE
"mark previous as read" bug

### ISSUE THREAD

**Issue by UkeCat69** [CarlosEsco/Neko#1066]
### Steps to reproduce

"mark previous as read" marks all chapters as read and deletes all above

### Expected behavior

in the previous version it deleted all chapters before. my settings were setup to delete 1 chapter after read one

### Actual behavior

all marked as read and deleted

### Neko version

2.10.0

### Android version

android 8.1

### Device

Redmi 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by UkeCat69** [comment]
![Screenshot_2022-08-17-10-08-04-274_tachiyomi mangadex](https://user-images.githubusercontent.com/91917374/185046716-be86f284-cab3-4a6c-add6-52e26d18774b.jpg)

**Comment by CarlosEsco** [comment]
Are you sure you don't have the setting to delete chapters when marked read enabled?

**Comment by UkeCat69** [comment]
> Are you sure you don't have the setting to delete chapters when marked read enabled?

On the screenshot you can see it marks all chapter ABOVE the chapter i clicked on to "mark previous as read"

**Comment by CarlosEsco** [comment]
Oh i gotcha

**Comment by CarlosEsco** [comment]
2.10.0.1
