### ISSUE TITLE
Status/Notification Bar is overlapping the heading "Similar Manga"

### ISSUE THREAD

**Issue by GoldMight948** [CarlosEsco/Neko#1067]
### Steps to reproduce

1. Open app
2. Open Manga
3. Click on similar works

### Expected behavior

The status/notification shouldn't overlap the heading 

### Actual behavior

![Screenshot_20220817_191816](https://user-images.githubusercontent.com/81867704/185153163-96e37787-921f-4804-8485-99cf7066f310.jpg)

### Neko version

2.10.0

### Android version

Android 8

### Device

Vivo 1806

### Other details

App version: 2.10.0 (standard, 867dcf9e3, 147, 2022-08-16T17:12:21.966188)
Android version: 8.1.0 (SDK 27)
Android build ID: O11019 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 1820
Device model: vivo 1820
Device product name: 1820

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0.1

**Comment by GoldMight948** [comment]
> 2.10.0.1

Thanks
