### ISSUE TITLE
Manga categories do not work for newly followed manga.

### ISSUE THREAD

**Issue by NinjaDebugger** [CarlosEsco/Neko#1068]
### Steps to reproduce

1. Open mangadex browse.
2. Open an unfollowed manga and follow it.
3. On the "add to category" screen, pick a category.  The button does not change to add to that category, it stays "add to Default"
4. Add to default category. If you have an actual default category it will be ignored in favor of "Default"
5. Go to the followed manga in the "Default" category.
6. Attempt to change the category. The button does not change, it remains "Keep in Default Category"
7. Press "Keep in Default Category" with another category selected.  The manga is kept in the "Default" category.

### Expected behavior

The manga should be added to only the selected categories, and the dialog should honor the config default category setting.

### Actual behavior

New manga can only be added to "Default" and cannot be moved from there.

### Neko version

2.10.0

### Android version

Android 12

### Device

Samsung Galaxy Note 20+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.0.1
