### ISSUE TITLE
Ui is kind of broken in a few ways

### ISSUE THREAD

**Issue by alidan** [CarlosEsco/Neko#1069]
### Steps to reproduce

for me go to any manga page and look in the upper right hand corner, try to scroll down

### Expected behavior

able to hit every button and scroll without issue

### Actual behavior

hit 1 of 3 buttons, and scroll in a laggy/inconstant way if it even scrolls and doesnt decided I actually want to go left and right

### Neko version

2.10.0

### Android version

I beleive android version 9 api 28

### Device

kindle fire hd 10 2021

### Other details

ok git ate my last post
![Screenshot_20220817-114056](https://user-images.githubusercontent.com/2681758/185202825-a2114ad4-09ef-4736-acc0-0163cee6d265.png)
![Screenshot_20220817-120144](https://user-images.githubusercontent.com/2681758/185202832-965b2dcd-fe7f-47d2-913f-028c38ca071b.png)

note the left side there are I beleive 5 buttons, but I only see the 5th one in landscape and just barely, while I also only have 3 vertically

while I like the theming, I don't have a powerful device, if I had my choice between the current theme and the old one, I would choose the old one over the potentially nicer new one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
I think if i am understanding correctly.
Part of it is this https://github.com/CarlosEsco/Neko/issues/1058

The other issue is performance? https://github.com/CarlosEsco/Neko/issues/1062

**Comment by alidan** [comment]
there is also the in library/tracked/artwork/similar/m... something buttons that kind of show up in landscape but disappear in portrait, along with scrolling deciding instead of scrolling you want to swipe left or right way to fast. 

but yea the other two issues are covered by those, not sure if others are in other reports yet or if they are worded in ways i'm not noticing them.

**Comment by CarlosEsco** [comment]
Can you open a ticket with more detail for "there is also the in library/tracked/artwork/similar/m... something buttons that kind of show up in landscape"

As for the sensitivity of marking chapters that is known
