### ISSUE TITLE
2.10 wipes entire library at random

### ISSUE THREAD

**Issue by nubbins-3e** [CarlosEsco/Neko#1070]
### Steps to reproduce

1. Update to 2.10 through app / clean install 2.10 and restore library
2. Do a library update
3. ?????? wait anywhere from minutes to hours, read manga, do other stuff in other apps
4. Entire library is empty

### Expected behavior

Neko should not delete entire library for no reason

### Actual behavior

Neko deletes entire library after random amount of time

### Crash logs

https://www.dropbox.com/s/bfozv208pxepgie/neko_crash_logs.txt?dl=0
https://www.dropbox.com/s/bvqh3foxnvdudyo/neko%20crash%20logs%202.txt?dl=0

### Neko version

2.10.0

### Android version

Android 12.1

### Device

Poco F3

### Other details

Unfortunately, seems to happen now on 2.9.4 too.

Have reproduced this issue 5 times in the past day. 1010 titles in library, always has been about this size for like the past 5 app versions. Doesn't matter if clean installed, or carried over library from 2.9. 

The latest automatic backup that 2.10.0 made is noticeably smaller than any of the backups from past year. They all range from 2.5-3.0MB, but the latest one is only 0.98MB. 

[newest bugged v210 backup.proto.gz](https://github.com/CarlosEsco/Neko/files/9366483/newest.bugged.v210.backup.proto.gz)
[older normal library backup.proto.gz](https://github.com/CarlosEsco/Neko/files/9366484/older.normal.library.backup.proto.gz)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Are you using a custom rom?

From discord 
![image](https://user-images.githubusercontent.com/2092019/185367359-e809bf7d-74ad-4b59-958f-f46a29e895f3.png)

**Comment by nubbins-3e** [comment]
> Are you using a custom rom?
> 
> From discord 
> ![image](https://user-images.githubusercontent.com/2092019/185367359-e809bf7d-74ad-4b59-958f-f46a29e895f3.png)
> 
> 

I do unfortunately, arrow 12.1. I didn't initially think it would be the culprit since arrow and neko have coexisted just fine for almost a year now (dozens of OTAs and 3 major android versions). I sent rom dev a message about it

I'm completely stumped - I've tried restoring every backup, I've tried building a completely new library by pulling MD follows (was great until it suddenly deleted every title except the last 15 alphabetically). 

There was a new OTA update but it was more than a week ago, no issues until yesterday. I'll see if I can roll back for now

Did my library just get too big for neko to handle? Was only this week it went past 1000 titles

**Comment by CarlosEsco** [comment]
Library size is fine.  The main issue is if there is a crash at all during db, your rom is corrupting the db file

**Comment by nubbins-3e** [comment]
I guess I drew the short stick again and I'm the only one with this problem? I sent the screenshot to rom dev, seems like he doesn't know how to fix/isn't willing to fix. Neko is just boned until I wipe all my data and clean install an earlier build?

**Comment by CarlosEsco** [comment]
Make a backup, uninstall the app, reinstall and restore. Hopefully whatever crashed during the db doesn't exist anymore

**Comment by arkon** [comment]
@CarlosEsco You could probably do [this](https://github.com/tachiyomiorg/tachiyomi/commit/ac4f98e152c66c388dd5f098725f4196df3a7339).

**Comment by nubbins-3e** [comment]
> Make a backup, uninstall the app, reinstall and restore. Hopefully whatever crashed during the db doesn't exist anymore 

I've done this 10 times in the past 24h, each with 2.9.4 and 2.10.0. No bueno. 

Problem is the crashing happens whenever - it's crashed in the middle of library update, right after update, just randomly while reading, and sometimes even corrupts (yeets most but not all of the library) without a crash. I think you're right, journal_mode seems to still be the problem

maybe ill try to get rid of some old finished titles to slim down database

**Comment by CarlosEsco** [comment]
> > Make a backup, uninstall the app, reinstall and restore. Hopefully whatever crashed during the db doesn't exist anymore 
> 
> I've done this 10 times in the past 24h, each with 2.9.4 and 2.10.0. No bueno. 
> 
> Problem is the crashing happens whenever - it's crashed in the middle of library update, right after update, just randomly while reading, and sometimes even corrupts (yeets most but not all of the library) without a crash. I think you're right, journal_mode seems to still be the problem
> 
> maybe ill try to get rid of some old finished titles to slim down database

I got something I will try for the next release
