### ISSUE TITLE
Unable to read filter options while in dark mode

### ISSUE THREAD

**Issue by Zoidberg1012** [CarlosEsco/Neko#1071]
### Steps to reproduce

1. Enable Dark Mode

2. Letters are ineligible 

### Expected behavior

Should be able to see the letters

### Actual behavior

Letters blend in the background

### Neko version

2.10.0

### Android version

android 11

### Device

Moto G9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Update app
