### ISSUE TITLE
MAL Tracking no longer updates automatically

### ISSUE THREAD

**Issue by IncogNinja25** [CarlosEsco/Neko#1074]
### Steps to reproduce

1. Have MAL tracking enabled
2. Activate chapter tracking in a manga
3. Read a manga chapter

### Expected behavior

Manga chapter to be automatically updated in MyAnimeList. 

### Actual behavior

After reading a manga chapter, the tracker doesn't automatically updates and you have to manually update it yourself. 

### Neko version

2.10.0.1

### Android version

Android 11

### Device

Samsung Galaxy A50

### Other details

I had no problems with the MAL tracking prior to updating the app to 2.10.0.1 but I am unsure if the problem lies with the Neko app or because MyAnimeList has recently updated their website.

But if I manually update the tracking, it does reflect in MAL. The tracking just doesn't update automatically. 

I have logged out of MAL tracking and logged back in but the problem still persists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
So mal is getting updated, the tracker inside has a ui issue that will be resolved in next release.  If you read a chapter, back out to library then enter the manga again you should see the correct tracker number

**Comment by IncogNinja25** [comment]
Got it, it does indeed update automatically and it's only a UI issue. Thanks for the quick reply and for all your hard work. 👍

**Comment by CarlosEsco** [comment]
2.10.2
