### ISSUE TITLE
Adding manga through browse doesn't add it to the default category 

### ISSUE THREAD

**Issue by Chef-Food** [CarlosEsco/Neko#1077]
### Steps to reproduce

Head to browse and select any manga to add to library 

### Expected behavior

It should add it to the default category selected in the settings 

### Actual behavior

Prompts a panel to select a category 

### Neko version

2.10.0.1

### Android version

12

### Device

Mi 11x

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.2
