### ISSUE TITLE
X To Remove Tracking with automatic tracking enabled

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#1078]
### Describe your suggested feature

Have the option to remove tracking with automatic tracking enabled, so if you remove something from your library that you never even read, you can remove it from the tracker as well.

### Other details

![Screenshot_20220819-113044_2](https://user-images.githubusercontent.com/51281790/185666128-7d140910-62e7-4f43-b2e1-bc9cbd72b74b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
As of right now, I dont plan to add this.  I don't want to have to track when a user manually removes the auto tracker and to not readd it (it gets added everytime you enter the manga details page unless it doesnt fit the content rating exclusion)

**Comment by TheTabbingman** [comment]
Could you make it be removable if you remove the manga from your library first?

**Comment by CarlosEsco** [comment]
that would be doable

**Comment by CarlosEsco** [comment]
2.10.2
