### ISSUE TITLE
Have to tap check box for hide chapter titles 

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#1080]
### Steps to reproduce

Tap hide chapter titles button

### Expected behavior

Be able to tap anywhere in the area

### Actual behavior

Have to tap the checkbox

### Neko version

2.10.0.1

### Android version

Android 12

### Device

Google Pixel 6

### Other details

https://user-images.githubusercontent.com/51281790/185712074-a575f91b-a5bf-4dd9-905e-1fea2c590663.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by TheTabbingman** [comment]
I also just noticed that it is the same way with the show all button

**Comment by CarlosEsco** [comment]
2.10.3
