### ISSUE TITLE
Neko takes approx. 2.5x longer to update the library compared to Tachiyomi

### ISSUE THREAD

**Issue by Takeshi-no-uta** [CarlosEsco/Neko#1081]
### Steps to reproduce

Update the library, either manually or automatically.

### Expected behavior

For it to take roughly 100 titles per minute, which is the speed of Tachiyomi.

### Actual behavior

It took me just over 26m:30s to update 1012 titles. 1 to 3 are skipped, usually.

### Neko version

2.10.0.1

### Android version

Android 11

### Device

Oneplus 7 Pro

### Other details

It seems that Tachiyomi threads the updates, which might speed it up comparatively.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Neko is threaded there is just more calls per an entry compared to Tachiyomi.  I can look into trying to optimize it some, but in reality it just needs more network calls due to the api.
