### ISSUE TITLE
401 error on mal auto tracking

### ISSUE THREAD

**Issue by alidan** [CarlosEsco/Neko#1082]
### Steps to reproduce

track/auto track, wait and it may happen

### Expected behavior

tracking works

### Actual behavior

tracking stopped working, a 401 error message appeared at the bottom

### Neko version

2.10.0.1

### Android version

I beleive android version 9 api 28

### Device

kindle fire hd 10 2021

### Other details

I was able to fix this by going to tracking, logging out of mal, and logging back in.
so potentially solutions to the problem are as follows

1) in a potential 401/other temporary errors, the program could track/remember what was not tracked (in cases where the manga is already being tracked by an external service) and queue up 'update these chapter' features

2) when it recognizes a 401 error has happened, a prompt to relog in front and center would be nice, possibly buttons to take me to the page and re log in. seeing as logging out and logging in fixed this, it would be nice to be told this in a blatant way rather than a small box at the bottom that goes away not telling me its an access problem. 

3) a potential once over 'check my manga and my tracking' pass, like the check for new manga one, that looks at all the manga you have, checks if it can be auto tracked and applies it, and checks the current read chapter and applies it to the best of its ability to tracked places. 

I don't know why this happened, or if this is normal, searching 401 doesn't seem to pick anything up so it's a potentially unique to me issue. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
this 100% normal, the new screen just now actually shows the error up and center.  It wasn't noticeable before unless you happened to open a tracker and sheet and realized mal was not matching correctly

**Comment by serjflint** [comment]
Yeah. MAL throws 401 at me all the time. Re-login helps.

**Comment by CarlosEsco** [comment]
2.11.6 should fix this issue
