### ISSUE TITLE
Migrating v3 entries to v5 with entries with the same ID already in library creates duplicates

### ISSUE THREAD

**Issue by loocool2** [CarlosEsco/Neko#1083]
### Steps to reproduce

1. Restore this backup https://cdn.discordapp.com/attachments/569823838305648640/1011391735210987531/tachiyomi_2022-08-22_01-38.proto.gz - Made in TachiSy r476
2. Migrate all entries to v5
3. Check to see if there are duplicate entries 

### Expected behavior

Entries with the same link are not removed from the library entirely

### Actual behavior

Two entries with the same MangaDex id are created

### Neko version

2.10.0.1

### Android version

Android 9

### Device

Amazon Fire HD 10 Plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Was a restore issue
