### ISSUE TITLE
v3 entries not in library being restored from backup

### ISSUE THREAD

**Issue by loocool2** [CarlosEsco/Neko#1084]
### Steps to reproduce

1. Restore this backup https://cdn.discordapp.com/attachments/569823838305648640/1011391735210987531/tachiyomi_2022-08-22_01-38.proto.gz - Made in TachiSy r476
2. v3 entries that were not present in the library are restored

### Expected behavior

Only the entries that are in the library should be restored

### Actual behavior

Entries that were not present in the library are restored as v3 entries

### Neko version

2.10.0.1

### Android version

Android 9

### Device

Amazon Fire HD 10 Plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.3
