### ISSUE TITLE
Backup losing Tracking

### ISSUE THREAD

**Issue by sedorr** [CarlosEsco/Neko#1085]
### Steps to reproduce

1. Manually back up on Android 12L pixel 3a
2. Restore backup on Android 13 pixel 4a

### Expected behavior

The backup restoring tracking as well

### Actual behavior

Tracking being lost

### Neko version

2.10.2

### Android version

Android 13

### Device

Pixel 4a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Are you sure your backup had tracking clicked, and you were logged into the trackers?  I had no issue on a small test I just performed

**Comment by sedorr** [comment]
I logged I after the restore, as I always did with j2k and vanilla tachyomi. Does noko require you to be logged in first?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CarlosEsco** [comment]
Are you sure you backed up with tracker clicked?  I am unable to emulate this.

**Comment by sedorr** [comment]
Yes. I'm sure I backed up with trackers.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CarlosEsco** [comment]
2.10.3
