### ISSUE TITLE
Kitsu auto tracking using Tokyo Ghoul

### ISSUE THREAD

**Issue by sedorr** [CarlosEsco/Neko#1086]
### Steps to reproduce

1. Turn on auto tracking for kitsu

### Expected behavior

Not doing anything or choosing the correct title

### Actual behavior

It instead tracks Tokyo Ghoul and doesn't allow you to manually change it

### Neko version

2.10.2

### Android version

Android 13

### Device

Pixel 4a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
I've had the auto track thing happen once, no clue why its always tokyo ghoul.  You can however still click the name in the tracker to search.   Do you happen to know what manga this happened on (if its all for you can you at least provide one i can test with)

**Comment by sedorr** [comment]
I just tried again and managed to reproduce it on soulless duchess. Though it happened quite a lot before, mainly on manwha as far as I could tell. I also couldn't change or remove(there is no little x) auto trackers an hour ago, now it seems to have started to work again so that I can at least change it. Before it would just immediately change it back to Tokyo ghoul.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sedorr** [comment]
I just tried again and managed to reproduce it on soulless duchess and.SSS-Class Suicide Hunter. Though it happened quite a lot before, mainly on manwha as far as I could tell. I also couldn't change or remove(there is no little x) auto trackers an hour ago, now it seems to have started to work again so that I can at least change it. Before it would just immediately change it back to Tokyo ghoul.

![Screenshot_20220823-152146](https://user-images.githubusercontent.com/34986602/186169482-38686874-8853-4b61-8062-655f3a097f65.png)

**Comment by CarlosEsco** [comment]
2.10.3
