### ISSUE TITLE
Make the backdrop cover extra large Switch not working

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#1100]
### Steps to reproduce

Tap backdrop cover extra large Switch

### Expected behavior

Should turn large backdrop on and off

### Actual behavior

Large backdrop stuck on

### Neko version

2.10.4

### Android version

Android 13

### Device

Google Pixel 6

### Other details

https://media.discordapp.net/attachments/569823838305648640/1013586485326389278/screen-20220828-180838.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.5
