### ISSUE TITLE
AMOLED themes

### ISSUE THREAD

**Issue by speedycatfish** [CarlosEsco/Neko#1101]
### Describe your suggested feature

Just wondering why they were removed. They were the themes I was using before this update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
1.  Didn't look good
2.  Provided no value, and caused more hindrance when new screens were added
4. Doesn't actually save battery https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/
