### ISSUE TITLE
Details not loading Sometimes

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#1102]
### Steps to reproduce

Go through library tapping manga in list

### Expected behavior

Details should be loaded for all opened manga.

### Actual behavior

Details are blank on some manga, and you have to refresh, or go out and back in.

### Neko version

2.10.5

### Android version

Android 13

### Device

Google Pixel 6

### Other details

This happens with manga that I have already tapped and loaded this update

https://user-images.githubusercontent.com/51281790/187273991-04c6457b-9794-44da-9f50-6bd327da3a59.mp4

https://user-images.githubusercontent.com/51281790/187274012-1eee3c44-ceff-4b2b-ab4f-37be00bb8cc3.mp4

https://user-images.githubusercontent.com/51281790/187274027-72f80d5a-49f4-43c1-b595-1d347290fd02.mp4

https://user-images.githubusercontent.com/51281790/187274046-e3dae610-2a60-4b49-ad95-a23e4dc50c37.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by TheTabbingman** [comment]
Also sometimes the description will be expanded by default. I don't know if that is related.

[Screen-20220829-135431 2-1.webm](https://user-images.githubusercontent.com/51281790/187279987-28c2e0eb-1218-4f75-82c4-ebd633537402.webm)

**Comment by CarlosEsco** [comment]
Should be good on 2.10.6
