### ISSUE TITLE
Default category always ask not always working

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#1104]
### Steps to reproduce

1. Set default category to always ask
2. Add manga to library

### Expected behavior

Should always pop up asking what category you want the manga in.

### Actual behavior

Sometimes just adds it to the "default" category.

### Neko version

2.10.6

### Android version

Android 13

### Device

Google Pixel 6

### Other details

Said to mention category race condition

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.7
