### ISSUE TITLE
top left back button comes down with minimal scrolling

### ISSUE THREAD

**Issue by alidan** [CarlosEsco/Neko#1105]
### Describe your suggested feature

I believe in the prior version of neko I don't believe I had to scroll much to get that button to drop down, quite a few of the manga I read are hundreds of chapters long, so I end up moving between several at a time. the current version of neko wants me to scroll all the way back up to the top when i'm in chapter view to get the back button, while it's not a big ask normally, I am using one of the weakest devices that probably still runs tachiyomi/neko (given how webcomics scroll on tachiyomi I can't imagine something weaker even working) and it is a bit difficult to get back up to the top.

im wondering if there is/could be a setting to either permanently show the back button when you are on the manga chapter select area, or if it would be possible to have any scroll up immediately drops the back button down. 

### Other details

I don't see this as a duplicate request, at least not with what I searched, I also dont see this as a feature to enable, but i possibly overlooked it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
thanks this was an unintended change, it will be fixed in next release

**Comment by CarlosEsco** [comment]
2.10.7
