### ISSUE TITLE
Smart (by theme) with black default.

### ISSUE THREAD

**Issue by CaidenBlock** [CarlosEsco/Neko#1106]
### Describe your suggested feature

With the removal of pure black dark mode, I only miss the ability to use smart background color with the black default. I would really appreciate if 'Smart (black)' could be added as an option, or possibly have 'Smart (by theme)' default to black on MD3 dark mode.

The smart bg color is a nice touch for some colored pages, but I'd prefer to not have to sacrifice the black default bg.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
there will be another option in the next release for smart background based on page and theme but use black

**Comment by CaidenBlock** [comment]
Thank you so much.

**Comment by CarlosEsco** [comment]
2.10.7
