### ISSUE TITLE
Crashing when opening reading settings with smart black mode enabled

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#1110]
### Steps to reproduce

1. Set background color to smart (based on page and theme but use black)
2. Open manga
3. Try to open reader settings

### Expected behavior

Reader settings should open

### Actual behavior

App crashes or you get kicked back to library.

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/9457092/neko_crash_logs.txt)

### Neko version

2.10.7

### Android version

Android 13

### Device

Google Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.8
