### ISSUE TITLE
Reading status is not pulled from MangaDex anymore 

### ISSUE THREAD

**Issue by zhang-li-80** [CarlosEsco/Neko#1111]
### Steps to reproduce

1. Add a manga from the MangaDex website, and make sure the reading status is Reading and followed.
2. Sync the manga into Neko (use sync MangaDex follows).
3. Open the manga in Neko (tracking status should have MangaDex set to Reading).
4. Open the manga in the website, and set the reading status to Dropped or Completed.
5. Open the manga in Neko again (need to return to manga list, and back).

### Expected behavior

On the second time the manga is opened in Neko, it should pull the Dropped/Completed status into Neko.

### Actual behavior

The status stays as Reading.

Refreshing the manga within this screen also sets the website status to Reading.

### Neko version

2.10.7

### Android version

Android 10

### Device

Redmi Note 7

### Other details

This stopped working in one of the 2.10.x versions. The 2.9.x versions were OK.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.8
