### ISSUE TITLE
Edit category not showing current category

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#1114]
### Steps to reproduce

1. Open manga
2. Edit category

### Expected behavior

Should show the current category that the manga is in.

### Actual behavior

Doesn't show what category it is in. And you have to refresh a bunch to get it to show.

### Neko version

2.10.8

### Android version

Android 13

### Device

Google Pixel 6

### Other details

![Screenshot_20220831-203507](https://user-images.githubusercontent.com/51281790/187934021-11e55a53-e34a-4553-bb1f-68bc92f774a0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.9
