### ISSUE TITLE
Return big manga icons

### ISSUE THREAD

**Issue by ItamiKyojin** [CarlosEsco/Neko#1128]
### Describe your suggested feature

In the updates menu, the manga icons (small manga covers) have shrunk since a few updates ago. I have difficulties telling them apart. An option to return them to their big size would be greatly appreciated. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by ItamiKyojin** [comment]
I may be... less smart. I was on the updates tab, but was looking for the All tab. Whoops.

**Comment by CarlosEsco** [comment]
Can you send a screenshot of what you mean

**Comment by ItamiKyojin** [comment]
Sorry, I meant to close this issue. But I will attach some screenshots of what I meant. As you can see, while the updates tab has small icons, my all tab has those lovely bid icons :)
![Screenshot_20220910-130446_Neko](https://user-images.githubusercontent.com/44494007/189480502-6bea614c-4a75-4110-83a7-4f538f9ba5b6.jpg)
![Screenshot_20220910-130443_Neko](https://user-images.githubusercontent.com/44494007/189480503-aec86e4b-484d-4d21-9ae7-4ea4e9cdbc79.jpg)
