### ISSUE TITLE
[bug] Triangle in play button not centered

### ISSUE THREAD

**Issue by integralfx** [CarlosEsco/Neko#113]
**Describe the bug**
Triangle in play button not centered

**To Reproduce**
1. Choose a manga
2. Go to chapters

**Expected behavior**
Triangle should be centered

**Screenshots**
![Play button](https://cdn.discordapp.com/attachments/569823838305648640/643272220575268867/unknown.png)

**Please complete the following information:**
 - Device: HTC One M8
 - Android Version: 9
 - Version: 1.3.0

**Additional context**

**Comment by CarlosEsco** [comment]
So close?  cause it is centered according to discord?

**Comment by integralfx** [comment]
Not too sure what to do tbh. It doesn't look like it's centered even tho it is mathematically...

Maybe have a poll and ask the users what they think?
