### ISSUE TITLE
"copied to clipboard: <manga title>" notification not showing

### ISSUE THREAD

**Issue by irdamulyar** [CarlosEsco/Neko#1130]
### Steps to reproduce

1. Open a manga
2. Long press the title
3. "copied to clipboard: <manga title>" notification not showing but it still copied to clipboard

### Expected behavior

"copied to clipboard: <manga title>" notification popped up like in previous release or original tachiyomi apk
Example on original tachiyomi apk:
![Screenshot_20220913-111244973](https://user-images.githubusercontent.com/100886449/189808012-3aea8759-61dc-47ea-91b4-899932916900.jpg)

### Actual behavior

"copied to clipboard: <manga title>" notification not showing but it still copied to clipboard

### Neko version

Stable 2.10.10

### Android version

Android 11

### Device

Redmi 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.11
