### ISSUE TITLE
Add new filter in "browse" section that hides empty manga

### ISSUE THREAD

**Issue by Adoridenn** [CarlosEsco/Neko#1131]
### Describe your suggested feature

A filter that would only show manga that has atleast 1 chapter available, checking this would hide all empty (zero chapters) manga.

Filter could be called "Hide Empty Manga" or "Has Available Chapters".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.11
