### ISSUE TITLE
Trackers issue

### ISSUE THREAD

**Issue by CR1MS0N24** [CarlosEsco/Neko#1139]
### Steps to reproduce

1. Login to trackers 
2. Refresh any manga in library
3. An error message pops up either indicating the manga was not found or error 404 on each tracker 

### Expected behavior

A stable connection from the tracking service to the tracker

### Actual behavior

![Screenshot_2022-09-17-23-14-54-049_tachiyomi mangadex](https://user-images.githubusercontent.com/87857932/190876689-61687dc4-5544-4ac1-aa7c-f2c73b166476.jpg)

### Neko version

2.10.11

### Android version

Android 10

### Device

Redmi 9C

### Other details

It does work after continuous refreshes but the issue reappears each time 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Do you have one that still has this issue, can you do the issue, then dump the crash log and attach it here?

**Comment by CR1MS0N24** [comment]
[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/9599899/neko_crash_logs.txt)

**Comment by CR1MS0N24** [comment]
Like that sorry first time posting a crash log

**Comment by CarlosEsco** [comment]
Are you on discord?  I think i will need a different log file, as that has an unrelated error

**Comment by CR1MS0N24** [comment]
ye should i dm you the crash log instead

**Comment by CarlosEsco** [comment]
dm me then I will give you instructions to get the more detailed log file

**Comment by CR1MS0N24** [comment]
ok sorry but whats your username

**Comment by CarlosEsco** [comment]
just ask in the neko channel and i will respond

**Comment by CR1MS0N24** [comment]
ill close this issue since it was an error on my end
