### ISSUE TITLE
Neko Application Closes

### ISSUE THREAD

**Issue by TheGoldenSun** [CarlosEsco/Neko#1140]
### Steps to reproduce

Loading the Neko app should be faster without allowing it to close automatically.

### Expected behavior

Improve the loading sequence within the Neko manga app since some chapters loads to the next automatically without letting the user manually do it own their own.

### Actual behavior

Neko frequency crashes whenever I read any type of manga that suits my taste it suddenly kicks me out of the Neko application for no reason.

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/9592786/neko_crash_logs.txt)

### Neko version

2.10.11

### Android version

Android 11

### Device

SM-S124DL

### Other details

Library and manga updates sometimes takes it's time to load whenever I plan to read or scroll to look for another manga to read. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by TheGoldenSun** [comment]
Based on #1142 I also encountered the same issue as well whenever I try to filter out other scanlators groups to locate the correct order of chapters they always appear to be missing, especially when I had done what #1142 did as well.

**Comment by CarlosEsco** [comment]
Let me know how 2.10.12 goes
