### ISSUE TITLE
Bug when trying to read a chapter

### ISSUE THREAD

**Issue by guilhermeikr** [CarlosEsco/Neko#1141]
### Steps to reproduce

1. Open Neko.
2. Open Berserk and try to read a Merged chapter.
3. The bug happens.

### Expected behavior

The chapter should upload it, I've read more than 200  Berserk merged chapters in the best quality and this never happens.

### Actual behavior

There was this bug 
![Screenshot_20220916-152458_Neko](https://user-images.githubusercontent.com/113773731/190883048-99b273e4-e431-41fd-8a5f-92694dd5ef3f.jpg)

### Crash logs

https://linksharing.samsungcloud.com/jnuV1AqYXTkM

### Neko version

Neko 2.10.11

### Android version

Android 12

### Device

Samsung A72

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.12
