### ISSUE TITLE
no manga added after sync

### ISSUE THREAD

**Issue by fadilr8** [CarlosEsco/Neko#1144]
### Steps to reproduce

1.installing latest version on new device
2. login into mangadex
3. sync mangadex follows

### Expected behavior

the Mangas I followed is synced and added to library

### Actual behavior

no manga is added to library

### Neko version

2.10.11

### Android version

android 11

### Device

realme Pad mini

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by AirKhaf** [comment]
Same issue 
Android 11, Realme X3, Neko 2.10.11

**Comment by CarlosEsco** [comment]
2.10.12
