### ISSUE TITLE
Delete Chapters Notification Timeout

### ISSUE THREAD

**Issue by goldbattle** [CarlosEsco/Neko#1146]
### Steps to reproduce

View a manga, download a chapter, try to click three dot menu and delete all chapters (or read).
Small notification will show asking if you want to undo.

### Expected behavior

This dialog should dismiss after a couple seconds.

### Actual behavior

Currently it stays until you either view a chapter or backout of the detailed manga view.

### Neko version

2.10.12

### Android version

12

### Device

Galaxy S21 FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.14
