### ISSUE TITLE
Weird size of images/icons in the descriptions

### ISSUE THREAD

**Issue by D-Brox** [CarlosEsco/Neko#1154]
### Steps to reproduce

Open a manga with images/icons on it's description.

### Expected behavior

The size of the images should be scaled according to their actual size.

### Actual behavior

Images appear with a giant size:
![Screenshot_2022-09-21-23-57-17-102_tachiyomi 
mangadex](https://user-images.githubusercontent.com/65723952/191648656-d4d08460-d059-4289-8799-ca1f964d01b1.jpg)
![Screenshot_2022-09-21-23-52-40-378_tachiyomi mangadex](https://user-images.githubusercontent.com/65723952/191648664-9a53e0d3-04e1-4a12-9675-7eb0c1dd394b.jpg)

### Neko version

2.10.12

### Android version

Android 12

### Device

Poco X4 Pro 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This is a limitation with the markdown library i am using and the fact that, Dex descriptions shouldn't have images anyways.  Will get the description fixed
