### ISSUE TITLE
[bug] Thumbnail images not loading

### ISSUE THREAD

**Issue by lightningdrake99** [CarlosEsco/Neko#116]
As seen in the screenshot, a large portion of the thumbnails do not load. This has been reproduced on multiple networks, and on two different devices. 

Device 1: LG G5 with Android 7.0
Device 2: Lenovo YT-X703F with Android 7.1.1

Both with the latest version of Neko

![Screenshot_2019-11-30-10-27-14-790](https://user-images.githubusercontent.com/18743032/69903277-dfbf5a00-135c-11ea-8645-22b9741e6820.jpeg)

**Comment by CarlosEsco** [comment]
If you click into one of the manga does the cover load?

**Comment by lightningdrake99** [comment]
Yes, after 15-20 seconds

**Comment by CarlosEsco** [comment]
Ok try something for me.  Make sure you are on 1.3.2 and then clear cache, cookies, db in advanced settings then try.

**Comment by lightningdrake99** [comment]
Nice, that fixed most of it!
![Screenshot_2019-11-30-14-00-27-752](https://user-images.githubusercontent.com/18743032/69905503-00e27380-137a-11ea-80c9-3e09e83cc520.jpeg)
![Screenshot_2019-11-30-14-01-56-679](https://user-images.githubusercontent.com/18743032/69905505-063fbe00-137a-11ea-8b5c-f47c0f2263b4.jpeg)

**Comment by CarlosEsco** [comment]
Yea the few that don't load is cause I am guessing what the extension is.  Jpg vs jpeg vs png.
