### ISSUE TITLE
Delete All Downloads not working

### ISSUE THREAD

**Issue by Cjojojojo** [CarlosEsco/Neko#1166]
### Steps to reproduce

1.Click the snackbar
2.Select remove downloads
3.Select "All"

### Expected behavior

All current downloads should be deleted

### Actual behavior

Deleting All downloads does not work

### Neko version

2.10.13

### Android version

Android 12

### Device

Oppo A74

### Other details

This bug is consistent from app version 2.10.12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
swipe the toast away.  It will go away in a timely matter on next release
