### ISSUE TITLE
Add option in menu for filtering already read manga out of the libary updates tab

### ISSUE THREAD

**Issue by Darkvramp** [CarlosEsco/Neko#117]
Real simple idea(though likely harder in execution ), adding a filter option to the options menu that weeds out the chapters you have read from the chapters you have not read in the library updates tab. Something that can be turned on and off at leasure.

An alternative would be a filter option on the library updates page itself. Same solution just different location and possible different headache.

I say this because my library updates tab can get a little messy with that I do and don't read at one time and sometimes i forget or dont read all my new chapters exactly as they show up so they can get buried, and it would be nice to see the list shrink abit as i have a looooong list.

**Comment by CarlosEsco** [comment]
This has been in Neko for a few releases now.
