### ISSUE TITLE
Font on "Latest" is black color 

### ISSUE THREAD

**Issue by conztanz045** [CarlosEsco/Neko#1179]
### Steps to reproduce

1.on browse
2.filter
3.latest

### Expected behavior

The font color should be white 

### Actual behavior

The font color on latest manga is black and that its blending on the manga 

### Neko version

2.10.14

### Android version

Android 9

### Device

Oppo A12

### Other details

![Screenshot_2022-10-04-15-23-16-86_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/79831076/193761429-4edafc4a-74eb-458d-86eb-c356d96234d9.jpg)
![Screenshot_2022-10-04-15-23-12-14_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/79831076/193761479-d664c305-b043-46ba-9459-51b3eb6d2d3f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.15
