### ISSUE TITLE
[bug] I log in for the first use to check follows and i get a json error

### ISSUE THREAD

**Issue by manolito62** [CarlosEsco/Neko#118]
**Describe the bug**
Error loading the follow list after login for the first time, "invalid json at 17: encountered an unknown key status", then after is logged the error number changes to 31

**To Reproduce**
1. - download current version "1.3.2" and install
2. Open app and click on 'follow" and then log in
3. error pops up "Invalid JSON at 17: Encountered an unknown key title"
4. close app and reopen and go to follow
5. error pops up "Invalid JSON at 31: Encountered an unknown key title"
6. force stop, clear cache, clear storage.
7. go to step 2.

**Expected behavior**
That the follows manga list loads up.

**Screenshots**
https://imgur.com/a/g1Hr4vq

**Please complete the following information:**
 - Device: Alcatel 1S - 5024J
 - Android Version: 9
 - Version: 1.3.2

**Additional context**
Can not download and read manga on my phone, only read online.

**Comment by CarlosEsco** [comment]
If you clear cookies and cache.  Then click browse and login.  Then go to follows does it still error?

**Comment by Mrfiregem** [comment]
I get the same issue with the follows tab, except it's line 39. All other tabs are fine. Clearing cookies doesn't fix it either. I use 2fa if that's relevant at all. Running Android 8.1.0

**Comment by CarlosEsco** [comment]
Fixed in latest version
