### ISSUE TITLE
"In Library" badge not showing when adding manga from its page

### ISSUE THREAD

**Issue by irdamulyar** [CarlosEsco/Neko#1180]
### Steps to reproduce

1. Go to "Browse" tab
2. Go to any manga
3. Add that manga to library
4. Go back to "Browse" tab and "In Library" badge not showing

### Expected behavior

"In Library" badge showing like when you long-press any manga in "Browse" tab

### Actual behavior

"In Library" badge not showing but manga still added to library when checked from its page or "Library" tab

### Neko version

Stable 2.10.14

### Android version

Android 11

### Device

Redmi 8

### Other details

https://user-images.githubusercontent.com/100886449/193872959-81d254d5-6189-4c85-803c-0df09b73087d.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.10.15
