### ISSUE TITLE
Downloaded manga not displaying

### ISSUE THREAD

**Issue by oge2k** [CarlosEsco/Neko#1185]
### Steps to reproduce

1. Go to library and open a manga
2. Download manga chapter
3. Neko canges the name of the manga from the japanese title to the english title from Mangadex 
4. Downloaded chapters stop displaying in neko despite them still being in the download files

### Expected behavior

The downloaded chapters should still display because neko automatically changes the name of the download folder

### Actual behavior

The download folder name gets changed but the downloaded chapters in the folder does not show in neko

### Neko version

2.10.15

### Android version

Android 10

### Device

Umidigi A9 pro

### Other details

![Screenshot_20221006-231409](https://user-images.githubusercontent.com/46646966/194678905-2afa2e0f-a4ab-4aa8-8da0-58e7af6320e9.png)
![Screenshot_20221006-231401](https://user-images.githubusercontent.com/46646966/194678907-ec9251f9-fd1a-48ea-8d48-119f1b90f0ab.png)
![Screenshot_20221006-231503](https://user-images.githubusercontent.com/46646966/194678911-1ef3293e-b0dd-4a14-a8d6-986d1fe19a94.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by info-iimon** [comment]
It seems to be an issue file permissions. By default, Neko seems to only be given permission to the Pictures and Movies folders. When I turn off the wifi and try to read manga, I get the error "<Directory to cbz (or manga folder) its looking for>:open failed:EACCESS Denied". One work around I've found only works if you use Graphene OS. You can set the Storage Scopes to the location where the Manga is Downloaded, restart the app, and everything should work fine.

**Comment by CarlosEsco** [comment]
2.11.5

**Comment by asdkant** [comment]
This is still happening as of `v2.13.1`

What I did was:
1. download a chapter
1. select a different alt name while the chapter was downloading
1. tried to read the chapter after it was downloaded

and the chapter loaded from the network (it took the usual time it takes to download each page) instead of loading from the download (pages loading instantly)

**Comment by hazamaitsuru** [comment]
This is happening to me in `2.16.1`. Manga download folders are not named the same as the titles I have chosen to use. If I manually rename the folders to match, the chapter icons show as downloaded but it will no longer access the downloaded pages.

**Comment by nonproto** [comment]
> This is happening to me in `2.16.1`. Manga download folders are not named the same as the titles I have chosen to use. If I manually rename the folders to match, the chapter icons show as downloaded but it will no longer access the downloaded pages.
> 
> This also prevents the "downloaded" filter from showing downloaded manga as the app does not recognize that they are, in fact, downloaded.

Can you open a new ticket
