### ISSUE TITLE
False positives in webtoon detection lock me in webtoon mode

### ISSUE THREAD

**Issue by asdkant** [CarlosEsco/Neko#1186]
### Steps to reproduce

Pick a manga detected as webtoon. 

The detection sometimes has false positives (mostly because mistakes by the uploader), and in some few instances the intended reading mode changes mid-publication from webtoon to paged.

### Expected behavior

I can't change the reading mode in cases where I *don't* want webtoon. The "reading mode" switch is greyed out and I get a message if I tap it.

### Actual behavior

I should be able to change the reading mode.

I don't mind the warning (it's a good idea, UX wise), but I should be able to override the lock if I'm really, **really, REALLY** sure I want to change the reading mode.

### Neko version

2.10.15

### Android version

Android 11 / OneUI 3.1

### Device

Samsung Galaxy Tab S5e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by asdkant** [comment]
Apparently the particular manga I was reading was uploaded as groups of pages stuck together as longstrips... so some kind of auto-cutting would be nice for these cases (I've seen it a couple of times)

**Comment by CarlosEsco** [comment]
splitting of longstrips in the main tachi is suspect at best  so for now i wont be taking it.  As for this situation report it on MangDex website so the tag is corrected.
