### ISSUE TITLE
[enhancement] show the rating on the info screen

### ISSUE THREAD

**Issue by henrik9999** [CarlosEsco/Neko#119]
It would be nice to see the mangadex rating on the info screen of the manga

**Comment by CarlosEsco** [comment]
Good idea, however currently their API doesn't send this back

**Comment by henrik9999** [comment]
maybe with v5

**Comment by BeeeQueue** [comment]
How about MAL/AniList ratings? It should be pretty easy to fetch based on the links on mandagex.

**Comment by henrik9999** [comment]
I think you closed the wrong issue?

**Comment by CarlosEsco** [comment]
Yep

**Comment by CarlosEsco** [comment]
2.0.15.3
