### ISSUE TITLE
Dates missing from merged chapters

### ISSUE THREAD

**Issue by henrik9999** [CarlosEsco/Neko#1194]
### Steps to reproduce

1. Open any Manga
2. Merge manga 

### Expected behavior

Merged chapter to have date

### Actual behavior

Merged chapter doesn't have date

### Neko version

2.10.15

### Android version

Android 12

### Device

Redmi note 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.0
