### ISSUE TITLE
Manga in library dont show up when searched in browse tab

### ISSUE THREAD

**Issue by AlphaByte02** [CarlosEsco/Neko#1200]
### Steps to reproduce

Search a manga that is already in your library directly in the browse tab

### Expected behavior

I see the manga with the badge "in library"

### Actual behavior

The manga dont show up.
If the manga searched is the only one the page is completely empty (even without the "no results found" image)
Important to point it out, if you just added the manga and go back it have the "in library" badge as expected.

![photo_2022-10-22_14-44-20](https://user-images.githubusercontent.com/47041609/197339647-39928fad-4be1-409c-8c61-0212262e7a24.jpg)
> In the photo above I have in library the serialized version of the manga and not the others

![photo_2022-10-22_14-35-47](https://user-images.githubusercontent.com/47041609/197339300-e551d585-fc17-4431-95b5-c821d39feb83.jpg)

### Neko version

2.10.15

### Android version

Android 9

### Device

One Plus 3

### Other details

This happens since a while ago (at least 3/4 version ago).
I also tried with different theme but the the result is the same,
If you look at the app log the manga if fetched correctly.

Thanks for the hard work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
There are two possible issues
1. The content rating for the manga doesn't match the default content rating you have set for search and you're not adding that content rating.
2. You have hiding the library manga in browse enabled which is on the top aop  bar

**Comment by AlphaByte02** [comment]
Yes, was the "hiding the library" in the browse tab. I wasn't aware of that option, the iconography is a bit confusing if I can say, but good to know.

Thanks for the fast reply.
