### ISSUE TITLE
Trying to save a filter causes crashes and filter is not saved

### ISSUE THREAD

**Issue by curche** [CarlosEsco/Neko#1202]
### Steps to reproduce

From somad#8690 on Discord
https://discord.com/channels/349436576037732353/569823838305648640/1033414085057974342

https://user-images.githubusercontent.com/72807749/197352679-62ffcd19-d536-44cc-bae0-dadce38a99ec.mp4

### Expected behavior

Filter should get saved and usable next time

### Actual behavior

Saving a filter crashes 

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/9844874/neko_crash_logs.txt)

### Neko version

2.11.0

### Android version

12

### Device

samsung m12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.1
