### ISSUE TITLE
List ID search doesn't update its query when changing values

### ISSUE THREAD

**Issue by curche** [CarlosEsco/Neko#1203]
### Steps to reproduce

1. choose a MD list. Eg: Tristan's good yuri list https://mangadex.org/list/1399a2c1-7bad-4f5b-a1a6-369ed7514fa4
2. open Neko
3. go to Browser
4. open Filter
5. go to List ID search
6. accidentally paste "good yuri" instead of list uuid (search fails)
7. now paste correct UUID 1399a2c1-7bad-4f5b-a1a6-369ed7514fa4 

### Expected behavior

it searches lists when valid UUID is given
it shows the error otherwise

### Actual behavior

it shows the error at step 6
but the error persists after correcting the id in step 7
if you now change it to `id:UUID` (because I thought that might work, like in tachiyomi mangadex extension)
then the search query updates and throws a new error
but then changing back to valid UUID still doesn't work

### Neko version

2.11.0

### Android version

12

### Device

SM-N770F

### Other details

I'm guessing this an isValidUUID check somewhere that's doing the opposite of what it should do

video in case the steps are boring
(just paste link into mpv)
https://cdn.discordapp.com/attachments/569823838305648640/1033403791711666196/recording_20221022_103413.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
was even more dumb, the error state wasn't being reset on a new search

**Comment by CarlosEsco** [comment]
2.11.1
