### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by miteigikuuhaku** [CarlosEsco/Neko#1211]
### Steps to reproduce

1. Open app

### Expected behavior

App remains open

### Actual behavior

App crashes after a few seconds

### Crash logs

App crashes before I can reach this.

### Neko version

2.11.2

### Android version

Android 13

### Device

Google Pixel 5

### Other details

Not really informative, I know, but it crashes before I can get anything worthwhile. Tried restarting app and clearing cache with no luck.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by kingkj52** [comment]
Same happening to me on a Pixel 4 XL. Was working fine, updated to latest, crashes began. Something in the latest update for sure. I'm on Android 12.

**Comment by JurijPietrowicz** [comment]
For me it crashes when opening recents. I've managed to grab a log.
[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/9863191/neko_crash_logs.txt)

**Comment by nobile01** [comment]
Android 13, Pixel 6 Pro. Crashes on boot unless I open the Settings, but if I go back to the Library I can see that all my downloads are gone (still showing in my storage) and soon enough it crashes. 

App version: 2.11.2 (standard, 5769e159e, 166, 2022-10-25T16:58:09.774275)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.021
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven

**Comment by CarlosEsco** [comment]
please manually  update to 2.11.3

**Comment by kingkj52** [comment]
Fixed for me. Thanks again!

**Comment by CarlosEsco** [comment]
There is a download badge bug, I will do another release of the same version in the next 30 mins or so.  Redownload if you don't want the download badges to be missing on start up
