### ISSUE TITLE
issue with browsing

### ISSUE THREAD

**Issue by CrabboKusanagi** [CarlosEsco/Neko#1212]
### Steps to reproduce

1. Opening the app and going to browse
2. Refreshing, scrolling, or applying filter 

### Expected behavior

It should open the list of manga to browse from that are scrollable and I am able to set filters to see specific genres

### Actual behavior

Instead I get Error:null or an Error:503 

There doesn't seem to be a reason why they switch and trying different combinations will produce the errors seemingly randomly. Refreshing the page with also change it from Error:503 to Error:null and vise versa

### Neko version

2.11.3

### Android version

12

### Device

Samsung Galaxy s21 Ultra 

### Other details

![Screenshot_20221026-210907_Neko](https://user-images.githubusercontent.com/116773401/198167973-e69b7e9d-14c6-4b3b-abdb-02b0ef0673fa.jpg)
![Screenshot_20221026-210900_Neko](https://user-images.githubusercontent.com/116773401/198167988-b46a22bf-806a-41c6-abd7-d35b5344cebc.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
this was likely cause Dex was down during this time
