### ISSUE TITLE
Crashing when browsing with filter

### ISSUE THREAD

**Issue by chichibooxd** [CarlosEsco/Neko#1214]
### Steps to reproduce

1. Open browse tab
2. Apply a filter
3. Scroll

### Expected behavior

Manga should appear

### Actual behavior

App crashes after scrolling for a while.

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/9884723/neko_crash_logs.txt)

### Neko version

2.11.3

### Android version

Android 11

### Device

Vivo Y11

### Other details

The scrolling time before crashing is variable.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
What filter were you applying?

**Comment by chichibooxd** [comment]
I used latest uploads sorting and language filter to japanese.

**Comment by CarlosEsco** [comment]
should be resolved as of yesterday's release
