### ISSUE TITLE
Filter in manga not showing up when downloading 

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#1215]
### Steps to reproduce

1. Download any manga
2. Open manga page and select filter

### Expected behavior

Filter pop up screen should show up

### Actual behavior

It doesn't show when chapters are being downloaded 

### Neko version

2.11.3

### Android version

Android 12

### Device

Samsung s21 ultra

### Other details

https://user-images.githubusercontent.com/59638889/198813938-5b370e38-a360-42c0-b9ad-85578fc3da45.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.5
