### ISSUE TITLE
Removing download 

### ISSUE THREAD

**Issue by Blockshift758** [CarlosEsco/Neko#1216]
### Steps to reproduce

https://user-images.githubusercontent.com/86203009/198891006-4aedc944-7280-4cf9-8f0f-a151e16c31cf.mp4

1. Download a chapter
2. Remove downloaded chapter

### Expected behavior

Immediately download should only be seen when downloading a chapter.

### Actual behavior

Immediately download also appears when removing a chapter.

### Neko version

2.11.3

### Android version

Android 10

### Device

Oppo A5s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.5

**Comment by Blockshift758** [comment]
Bug still happening on the recent update
https://user-images.githubusercontent.com/86203009/201073688-fe98262d-ce07-46a9-b06a-2939ae1a2c35.mp4

**Comment by CarlosEsco** [comment]
should be good in 2.11.6
