### ISSUE TITLE
Remove merged text messed up

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#1217]
### Steps to reproduce

1. Merge manga
2. Go to remove it

### Expected behavior

Remove text should say Remove merged

### Actual behavior

Says "MergeMangaTabled Source"

### Neko version

2.11.5

### Android version

Android 13

### Device

Google pixel 6

### Other details

![Screenshot_20221102-125432](https://user-images.githubusercontent.com/51281790/199566210-130a7ab0-2b53-4d96-940a-3f26d5b32422.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.6
