### ISSUE TITLE
Filter doesn't persist when manga is opened.

### ISSUE THREAD

**Issue by NinjaDebugger** [CarlosEsco/Neko#1218]
### Steps to reproduce

1) Have two saved filters, one default.

2) Filter by the non-default filter
3) Enter a manga's page.
4) Leave the manga's page.

The filter will have switched back to the default filter, and if you scroll down, the next time it loads a new set of manga, it will do so using the default filter.

### Expected behavior

The filter selected should persist even after you go into and exit a specific manga.

### Actual behavior

The filter switches to the default filter and further manga loaded will be from that filter instead of the originally selected filter.

### Neko version

2.11.5

### Android version

Android 12

### Device

Samsung Galaxy Note 20+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.6
