### ISSUE TITLE
Only supply the missing parts when merging chapters

### ISSUE THREAD

**Issue by Cjojojojo** [CarlosEsco/Neko#1219]
### Steps to reproduce

1.Go to manga
2. Click merge button

### Expected behavior

Only supply parts of manga/manhwa that is lacking
E.g

Do not add another whole manga to the existing manga, if Chapter 97 is missing Only merge or add chapter 97

### Actual behavior

Instead, the whole new manga was added or merge to the existing one. Making it congested or too many. A 100 chaps manga takes about 300+ when being merged

### Neko version

2.11.5

### Android version

Android 12

### Device

Oppo A74

### Other details

Only add the missing parts

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
If you read the changelog the deduplication was removed

**Comment by Cjojojojo** [comment]
It was not, Chainsaw Man has only 9 missing chapters but upon merging it took the whole manga from MangaLife, taking a total of 200+ chaps

**Comment by CarlosEsco** [comment]
Deduplication is what you want and what existed before, it has been removed. For anymore questions about ask on the discord neko channel.

**Comment by Cjojojojo** [comment]
No it was not changed, I added Chainsaw Man manga and try to fill the 9
missing chapters. Upon merging, it took the whole manga from MangaLife
instead of just filling in. It was now a total of 200+ chaps

**Comment by CarlosEsco** [comment]
Like I said ask on discord. If you need me to explain it again.
