### ISSUE TITLE
Reset, Save, and Filter buttons not visible on Samsung Galaxy Tab S4 in portrait

### ISSUE THREAD

**Issue by Warkock** [CarlosEsco/Neko#1226]
### Steps to reproduce

1. Open Neko on a Samsung Galaxy Tab S4 (or simulate it) in portrait
2. Click Browse
3. Click Search

### Expected behavior

Reset, Save, and Filter buttons are visible

### Actual behavior

Reset, Save, and Filter buttons are not visible
![bug](https://user-images.githubusercontent.com/55507476/200930100-642ebf3a-f0cc-445f-bf26-1a87a7ca3ef5.png)

### Neko version

v2.11.6

### Android version

10

### Device

Samsung Galaxy Tab S4

### Other details

It works fine in landscape. In portrait, the "Home page" and "Search" buttons at the bottom of the Browse tab are partially obscured.
![search_obscured](https://user-images.githubusercontent.com/55507476/200931003-12f5d0aa-1883-4b18-9dd6-84e295585402.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by fadilr8** [comment]
report, it happened on another tablet too

I am using realme Pad mini

**Comment by CarlosEsco** [comment]
Gonna be tough to fix this as I can't emulate it..

**Comment by MrComexs** [comment]
I have a samsung s7+ and I don't have this problem

**Comment by fadilr8** [comment]
Samsung s7 is not a tablet

**Comment by CarlosEsco** [comment]
Can you guys add DPI if possible?  I tried emulating it with a similar sized emulator but had no issues in portrait mode

**Comment by CarlosEsco** [comment]
@fadilr8 android 10?

**Comment by fadilr8** [comment]
@CarlosEsco android 11

**Comment by CarlosEsco** [comment]
should be good on 2.12.3

**Comment by fadilr8** [comment]
still not working on my device,
```
App version: 2.12.3 (standard, 034709ec0, 177, 2022-12-20T15:06:02.304986)
Android version: 11 (SDK 30)
Android build ID: RMP2106PU_11.A.14
Device brand: realme
Device manufacturer: realme
Device name: RE87CCL1
Device model: RMP2106
Device product name: RMP2106
--------- beginning of system
--------- beginning of main
12-22 05:11:41.018 18508 18508 E hiyomi.mangade: Not starting debugger since process cannot load the jdwp agent.
12-22 05:11:44.481 18508 18508 E SQLiteLog: (283) recovered 4 frames from WAL file /data/data/tachiyomi.mangadex/databases/tachiyomi.db-wal
12-22 05:11:44.502 18508 18594 E SQLiteLog: (284) automatic index on C(manga_id)
12-22 05:11:44.502 18508 18594 E SQLiteLog: (284) automatic index on R(manga_id)
12-22 05:11:44.502 18508 18594 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-22 05:11:44.643 18508 18615 E libc    : Access denied finding property "vendor.mali.config"
12-22 05:11:44.683 18508 18615 E libc    : Access denied finding property "persist.vendor.sf.fbc"
12-22 05:11:44.683 18508 18615 E libc    : Access denied finding property "persist.vendor.gpu.fbc"
12-22 05:11:44.683 18508 18615 E libc    : Access denied finding property "persist.vendor.vsp.fbc"
12-22 05:11:44.802 18508 18508 E Dialog  : show dialog view=DecorView@c6a4e04[MainActivity
```

![Screenshot_20221222-051653](https://user-images.githubusercontent.com/80534017/209012988-11aacbb5-476e-46f4-bb1c-30ada055de2b.png)

**Comment by CarlosEsco** [comment]
2.12.5
