### ISSUE TITLE
Option to "skip" duplicate chapters

### ISSUE THREAD

**Issue by BlepBlep** [CarlosEsco/Neko#1232]
### Describe your suggested feature

So, since Mangadex loves to keep multiple scanlations for releases, it gets really annoying trying to go through a manga with multiple scanlators. Neko has tried to get around this with a filter option, however that is not perfect, as manga with multiple scanlators often has groups that pass each other.
### Examples:
- Manga has a scanlator do all the chapters, but chapters 5, 10, 15, and 20 have "uncensored" versions uploaded by someone else. Neko will first do the censored version, and then when you're done, it will show the uncensored one. Filtering does not help as the censored versions are uploaded by the main group. The only way to combat this is to know ahead of time which chapters are what, and manually skipping them when you get to them.
- Manga has 2 scanlators, group A uploaded chapters 1-30, and group B uploaded chapters 15-50. Once you get to chapter 15, Neko will do... whatever one at random I suppose, (sometimes it does the most recent first, sometimes it doesn't, I have no idea how it works) and you'd have to manually go through and skip the duplicates. Once again the filter does not work as filtering group A removes the chapters that have **only** been done by them.

### My suggestion:
A setting that allows you to skip duplicate chapters. Maybe add a selectable option to prefer older/newer? Or even better, maybe when going to read a chapter with duplicates, have a popup being like "which group would you like to read?" and give dates for each upload so you can choose if you want a newer one? Maybe also mention which group you just read so you know? Or even save the selection until a new group pops up?

I'm not sure, this is just the most frustrating part about Mangadex and in turn, Neko. I have found myself just ignoring some manga that happen to have multiple groups for majority of the release, just because I don't want to deal with it.I'm not sure if any of it is possible, but I'd love to have some sort of fix for this issue, or any other suggestions would be great :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.8
