### ISSUE TITLE
Visual bug, text in Reader Settings overlapping

### ISSUE THREAD

**Issue by dustter** [CarlosEsco/Neko#124]
**Describe the bug**
Visual bug, text in Reader Settings overlaps, see included screenshot for more clear reference of what overlaps in particular.

**To Reproduce**
1. Go to Reader Settings
2. See the visual bug happening

**Expected behavior**
The elements should be split as usual.

**Screenshots**
![Screenshot_20200108-010815_Neko](https://user-images.githubusercontent.com/54286558/71939732-f48cda00-31b3-11ea-83b1-7ed29f98eddc.jpg)

**Please complete the following information:**
 - Device: Samsung Galaxy Note 8
 - Android Version: 9.0
 - Version: 1.5.0

**Additional context**
None, seems to be just a visual bug, functions work properly.

**Comment by CarlosEsco** [comment]
fixed in 1.5.1
