### ISSUE TITLE
[Bug] Komga merge source does not show covers in search

### ISSUE THREAD

**Issue by farahnur42** [CarlosEsco/Neko#1243]
### Steps to reproduce

To replicate: 
1. Log into a Komga server with no public DNS entry (i.e accessible over Cloudflare/Google/etc DNS) attached
2. Try to merge any title from Komga
3. No covers are shown in the search

### Expected behavior

Covers should be shown, they seem to be ignored because the merge search does not ignore DoH settings (not ideal for what is overwhelmingly a self-hosted server)

### Actual behavior

Covers aren't shown in search

### Neko version

2.11.7

### Android version

Android 12

### Device

Redmi Note 10 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.8
