### ISSUE TITLE
Manga incorrectly flagged as not in library able to be added as duplicate entries

### ISSUE THREAD

**Issue by kyjibo** [CarlosEsco/Neko#1245]
### Steps to reproduce

Browsing recent updates I saw multiple items missing the 'in library' badge

If I select these titles I see that all of the chapters are marked as read, but the in library <3 is not set. I can click the <3 and add these entries to my library, resulting in a duplicate entry.

I think a title ends up in this weird state when I click a chapter link on Reddit and then add the manga to my library by tapping the title and then adding it from the manga overview page.

### Expected behavior

These titles should show as already in my library.

### Actual behavior

The title shows as not in my library and can be added as a duplicate.

### Neko version

2.11.7

### Android version

Android 12

### Device

Galaxy S10e

### Other details

![Screenshot_20221118-235202_Neko](https://user-images.githubusercontent.com/2566398/202836957-a8b70391-0dcc-4201-a87a-6de83d5c7812.png)
![Screenshot_20221118-235208_Neko](https://user-images.githubusercontent.com/2566398/202836963-5d61d32d-79b1-4ad4-aca8-10767d62f77f.png)
![Screenshot_20221118-235243_Neko](https://user-images.githubusercontent.com/2566398/202836968-939d971c-12f2-4efe-ad39-16279e811b12.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
if you have any like this please remove from library, and add through browse.  Next release will fix the issue when coming from a deeplink
