### ISSUE TITLE
Chapters from filtered scanlators show as the next chapter in the recemts tab

### ISSUE THREAD

**Issue by kyjibo** [CarlosEsco/Neko#1246]
### Steps to reproduce

If you filter a scanlator on a particular manga and read past some filtered chapters, the recents page will show the earliest filtered chapter as the chapter to resume reading from.

### Expected behavior

The filtered chapter should be skipped when showing the first unread chapter in the recents view.

### Actual behavior

Filtered chapters are shown as the first unread chapter in the recent view.

### Neko version

2.11.7

### Android version

Android 12

### Device

Galaxy S10e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by kyjibo** [comment]
![Screenshot_20221128_105843_Neko](https://user-images.githubusercontent.com/2566398/204337239-d23a2545-6e40-4fbc-b7e5-c4e51600d9be.png)
![Screenshot_20221128_105811_Neko](https://user-images.githubusercontent.com/2566398/204337256-561f64ec-b965-4027-95f8-a46a2f36cea1.png)

**Comment by CarlosEsco** [comment]
So thats not showing the filtered out chapter, thats the chapter you read since its history.  I just dunno why in you scenario it stays white instead of read.  Can you attach screen shots of how this screen is configured.
