### ISSUE TITLE
add "group library by: original language" option

### ISSUE THREAD

**Issue by irdamulyar** [CarlosEsco/Neko#1247]
### Describe your suggested feature

add group library by original laguage option so it can separate between manga, manhwa, and manhua in library

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.8
