### ISSUE TITLE
The link in Links direct me to where it shouldn't be

### ISSUE THREAD

**Issue by Rich-Richie** [CarlosEsco/Neko#1251]
### Steps to reproduce

1. Go to "Mimicry Girls" in Neko
2. Select Links
3. Select Mangaupdates

### Expected behavior

It should have gone to Mimicry Girls, like what would happen if you use webview.

### Actual behavior

It went to Fruit Basket page instead.

### Neko version

2.11.7

### Android version

Android 12

### Device

Samsung Galaxy Tab S7 FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.8
