### ISSUE TITLE
While typing in the search bar in Filter, sometimes the cursor will move to left by one

### ISSUE THREAD

**Issue by Rich-Richie** [CarlosEsco/Neko#1252]
### Steps to reproduce

1. Type something in the search bar.
2. I can't give any further guide to reproduce it. It is inconsistent as far as I can tell. Sometimes, it happen with the first character, the third character, then the tenth character.

### Expected behavior

The cursor shouldn't move back at all.

### Actual behavior

The cursor move back by one character.

### Neko version

2.11.7

### Android version

Android 12

### Device

Samsung Galaxy Tab S7 FE 5G

### Other details

In my virtual keyboard, there's actually a left and right button at the corner right. However, I'm sure that I didn't accidentally press on it while I was typing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.8
