### ISSUE TITLE
duplicate setting

### ISSUE THREAD

**Issue by ID-86** [CarlosEsco/Neko#1256]
### Steps to reproduce

go to settings lol
settings > reader > reading

### Expected behavior

there should be only one option with the same functionality (skip chapters marked read)

### Actual behavior

there are two (skip chapters marked read)
![Screenshot_20221129-225346](https://user-images.githubusercontent.com/84634317/204657674-dc8ccb8f-6ab3-43e4-8113-ad55f34dc451.png)

### Neko version

2.11.8

### Android version

Android 13

### Device

Google Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.11.9
