### ISSUE TITLE
[Bug] Komga merge source does not show covers in search 

### ISSUE THREAD

**Issue by farahnur42** [CarlosEsco/Neko#1257]
### Steps to reproduce

To replicate: 
1. Log into a Komga server [in this case, with no public DNS entry (i.e accessible over Cloudflare/Google/etc DNS) attached]
2. Try to merge any title from Komga
3. No covers are shown in the search

### Expected behavior

Covers should be shown

### Actual behavior

Covers aren't shown in search

### Crash logs
<details><summary>Crash logs</summary>
<p>

App version: 2.11.8 (standard, d37e8502e, 172, 2022-11-29T14:35:15.500254)
Android version: 12 (SDK 32)
Android build ID: SQ3A.220705.004 release-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sweetin
Device model: M2101K6P
Device product name: sweetin
--------- beginning of crash
11-30 03:19:50.632 26668 26668 E AndroidRuntime: FATAL EXCEPTION: main
11-30 03:19:50.632 26668 26668 E AndroidRuntime: Process: tachiyomi.mangadex, PID: 26668
--------- beginning of main
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: Settings request failed.
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:102)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:108)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@18.0.1:11)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:3)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:6)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:1013)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:672)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
11-30 03:40:14.417 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
11-30 03:40:14.418 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
11-30 03:40:14.418 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
11-30 03:40:14.418 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
11-30 03:40:14.418 17242 20063 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
11-30 03:40:14.418 17242 20063 E FirebaseCrashlytics: 	... 27 more
11-30 03:40:14.418 17242 20063 E FirebaseCrashlytics: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-30 03:40:14.418 17242 20063 E FirebaseCrashlytics: 	... 41 more
11-30 03:40:14.690 17242 17242 E SQLiteLog: (283) recovered 1 frames from WAL file /data/data/tachiyomi.mangadex/databases/tachiyomi.db-wal
11-30 03:40:14.709 17242 20100 E SQLiteLog: (284) automatic index on C(manga_id)
11-30 03:40:14.709 17242 20100 E SQLiteLog: (284) automatic index on R(manga_id)
11-30 03:40:14.709 17242 20100 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-30 03:40:59.508 17242 20213 E ||NEKO  : 	├ eu.kanade.tachiyomi.data.image.coil.AlternativeMangaCoverFetcher.httpLoader(AlternativeMangaCoverFetcher.kt:337)
11-30 03:40:59.508 17242 20213 E ||NEKO  : 	├ eu.kanade.tachiyomi.data.image.coil.AlternativeMangaCoverFetcher$httpLoader$1.invokeSuspend(AlternativeMangaCoverFetcher.kt:14)
11-30 03:40:59.508 17242 20213 E ||NEKO  : 	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
11-30 03:40:59.508 17242 20213 E ||NEKO  : 	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:105)
11-30 03:40:59.508 17242 20213 E ||NEKO  : 	└ kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
11-30 03:40:59.508 17242 20213 E ||NEKO  : error loading image
11-30 03:41:01.384 17242 20210 E SQLiteLog: (284) automatic index on mangas(_id)
11-30 03:45:52.734 18640 18640 E hiyomi.mangade: Not starting debugger since process cannot load the jdwp agent.
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: Settings request failed.
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:102)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:108)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@18.0.1:11)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:3)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:6)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:1013)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:672)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	... 27 more
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-30 03:45:53.002 18640 20748 E FirebaseCrashlytics: 	... 41 more
11-30 03:45:53.337 18640 18640 E SQLiteLog: (283) recovered 42 frames from WAL file /data/data/tachiyomi.mangadex/databases/tachiyomi.db-wal
11-30 03:45:53.360 18640 20785 E SQLiteLog: (284) automatic index on C(manga_id)
11-30 03:45:53.360 18640 20785 E SQLiteLog: (284) automatic index on R(manga_id)
11-30 03:45:53.360 18640 20785 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-30 03:46:02.788 18640 20784 E ||NEKO  : 	├ eu.kanade.tachiyomi.data.image.coil.AlternativeMangaCoverFetcher.httpLoader(AlternativeMangaCoverFetcher.kt:337)
11-30 03:46:02.788 18640 20784 E ||NEKO  : 	├ eu.kanade.tachiyomi.data.image.coil.AlternativeMangaCoverFetcher$httpLoader$1.invokeSuspend(AlternativeMangaCoverFetcher.kt:14)
11-30 03:46:02.788 18640 20784 E ||NEKO  : 	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
11-30 03:46:02.788 18640 20784 E ||NEKO  : 	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:105)
11-30 03:46:02.788 18640 20784 E ||NEKO  : 	└ kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
11-30 03:46:02.788 18640 20784 E ||NEKO  : error loading image

</p>
</details>

### Neko version

2.11.8

### Android version

Android 12

### Device

Redmi Note 10 Pro

### Other details

This is for reopening #1243 updated with additional info + a crash log as instructed by cesco

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.12.0
