### ISSUE TITLE
Bring back pure black dark mode

### ISSUE THREAD

**Issue by MrComexs** [CarlosEsco/Neko#1258]
### Describe your suggested feature

Bring back the pure black dark mode from [2.9.0] and older builds.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
No plans to
