### ISSUE TITLE
Landscape mode independent back arrow & three dots menu elements

### ISSUE THREAD

**Issue by MrComexs** [CarlosEsco/Neko#1259]
### Describe your suggested feature

So when in neko in landscape mode while scrolling on the chapter list the back button on the left side panel hides away as well as the three bots menu on the right side panel can you make it that each of this element are independent from each (only when in landscape mode) other so when I scroll down the chapter list only the three dots hides and when I'm scrolling down the description the back arrow hides.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
No plans to add something like this.
