### ISSUE TITLE
Webview resizes to content, rather than take up screen size

### ISSUE THREAD

**Issue by jjp22191-cdfaq** [CarlosEsco/Neko#1262]
### Steps to reproduce

Watch the video and keep an eye on the bottom part of the screen.

The Webview seems to resize itself depending on the content, when the loading indicators are appearing (next page, art tab, etc).

On the end of the video, the MangaDex menu is clicked, but it does not appear (appears white).

This has happened in version 2.11.8 and 2.11.9. 2.11.7 was good.

### Expected behavior

The bottom gap show not appear.

Clicking the MangaDex menu should show the menu.

### Actual behavior

See video.

### Neko version

2.11.9

### Android version

Android 10

### Device

Redmi Note 7

### Other details

https://user-images.githubusercontent.com/119740760/205443347-9bcd898a-4771-4a69-a962-1cdf59babe09.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.12.2
