### ISSUE TITLE
Skip duplicate chapters does not work

### ISSUE THREAD

**Issue by Cjojojojo** [CarlosEsco/Neko#1263]
### Steps to reproduce

1.Go to manga with "double chapters"
e.g  chapter 1, chapter 1, chapter 2, chapter 3, chapter 4, chapter 4

2. Try the filter in Reader 'skip duplicate chapters"

### Expected behavior

It should skip the chapter with the same number, and continue chronologically

### Actual behavior

No chapters has been skip, only the "skip chapters marked read" that works

Skip duplicate chapters does not

### Neko version

2.11.9

### Android version

Android 12

### Device

Oppo A75

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Can you exit the reader then go back in after. It might be a bug when setting it in the reader only

**Comment by Cjojojojo** [comment]
I tried to that lately, but still to no avail. It does not skip duplicate chapter

**Comment by CarlosEsco** [comment]
Send the link of the manga

**Comment by Cjojojojo** [comment]
https://mangadex.org/title/a77742b1-befd-49a4-bff5-1ad4e6b0ef7b/chainsaw-man

**Comment by Cjojojojo** [comment]
Thank you it's now working ;)

**Comment by CarlosEsco** [comment]
2.12.2
