### ISSUE TITLE
Random crashes upon multiple actions in 2.12.1

### ISSUE THREAD

**Issue by Colin1224** [CarlosEsco/Neko#1270]
### Steps to reproduce

1. Open app
2. Open any manga
3. Choose any alt title and tap it
4. Experience crash

### Expected behavior

App does not crash.

### Actual behavior

App title changes, then immediately crashes.

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/10221055/neko_crash_logs.txt)

### Neko version

2.12.1

### Android version

13

### Device

Google Pixel 6 Pro

### Other details

Happens with any manga, either in library or not. Happens when choosing an alt title or tapping reset to go back to the original title. Manga title actually does get changed.

Using the app more, I realized that there are more crashes through various other actions, such as making a chapter as read or unread or toggling airplane mode on and off.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by m-arndt** [comment]
the same happens to me when manually setting a chapter or chapters to unread/read

**Comment by CarlosEsco** [comment]
2.12.2
