### ISSUE TITLE
Neko not showing homepage / my follows / search in browse page unless side navigation is forced

### ISSUE THREAD

**Issue by YanYangC** [CarlosEsco/Neko#1273]
### Steps to reproduce

Launch the app on the Z Fold 3 and go to the browse tab.

### Expected behavior

![Screenshot_20221218-171432_Neko](https://user-images.githubusercontent.com/59201727/208297047-a3890037-150e-47e4-9ebe-bb158ce049b0.png)

### Actual behavior

![Screenshot_20221218_111054_Neko](https://user-images.githubusercontent.com/59201727/208297012-97a61e6c-b976-443d-87d1-1e1140736f69.png)

As seen, there is no search option visible with the bottom navigation.

This happens on the Z Fold 3, when launching the app whilst the device is unfolded. untested when launching folded as app only used when unfolded.

### Neko version

2.12.2

### Android version

Android 13

### Device

Samsung Galaxy Z Fold 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
should be good on 2.12.3
