### ISSUE TITLE
Cannot login to mangadex

### ISSUE THREAD

**Issue by Zaryu** [CarlosEsco/Neko#1274]
### Steps to reproduce

1. Open Neko and go to mangadex settings
2. Type on user credentials
3. Get error, that the username or password are not matching

### Expected behavior

Login should be working if credentials are correct (which they are, same credentials in browser are working)

### Actual behavior

Credentials are correct, but login won't work, as it says that the password or username are nit correct

### Crash logs

1649183328168|E|||NEKO|	├ eu.kanade.tachiyomi.util.system.RxCoroutineBridgeKt$runAsObservable$1$job$1.invokeSuspend(RxCoroutineBridge.kt:9)
	└ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
error in coroutine bridge
kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@2389749

--
Complete content of the log

### Neko version

2.12.2

### Android version

13 ( OnePlus Oxygen OS 13 AND Samsung One Ui 5.0)

### Device

Samsung Galaxy Tab S8 Ultra & OnePlus 9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [x] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Did you happen to change your password on the website? Currently the api still uses the legacy login and so there are "two" login sources of truth on Dex

**Comment by Zaryu** [comment]
No,  nothing at all, also created a new acc with a spare email and same result

**Comment by CarlosEsco** [comment]
Well new accounts will have issues too.  For now wait until I migrate and do a release with the Oauth login

**Comment by Zaryu** [comment]
Sure, got it thank you for your extraordinary fast support

**Comment by CarlosEsco** [comment]
2.12.3
