### ISSUE TITLE
Cannot update / sync library

### ISSUE THREAD

**Issue by Dyl-M** [CarlosEsco/Neko#1275]
### Steps to reproduce

1. Open Neko
2. Refresh library / Sync Mangadex follows

### Expected behavior

Step 2 should trigger the library  update, displaying a progress bar in the notification area.

### Actual behavior

No progress bar displaying and (off course) the library does not update.

### Crash logs

No log available. The only thing we can see is a notification remaining fixed without showing more information.
![Screenshot_2022-12-20-08-55-35-581_tachiyomi mangadex](https://user-images.githubusercontent.com/57560342/208613951-675448a7-87e9-4dd3-adc3-4137d427d571.jpg)

### Neko version

2.12.2

### Android version

Android 12

### Device

Redmi Note 11 Pro

### Other details

It probably related to issue #1274 and the few operations that the Mangadex team performs around its authentication system.
![image](https://user-images.githubusercontent.com/57560342/208614401-a56d1bb7-13ab-43f1-8b5c-0705897a4f67.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Was probably a side effect of what they did.  I had the same issue.  When previously no issue on this release.

**Comment by Dyl-M** [comment]
> Was probably a side effect of what they did. I had the same issue. When previously no issue on this release.

Seems like it yeah
But it looks like the problem was solved with the 2.12.3 release. So thank you for the hard work. :)
