### ISSUE TITLE
crash on updating manga list

### ISSUE THREAD

**Issue by alidan** [CarlosEsco/Neko#1278]
### Steps to reproduce

swipe down
wait

### Expected behavior

neko checks for new manga

### Actual behavior

hang, nothing responds, followed by a crash

### Crash logs

[neko_crash_logs (4).txt](https://github.com/CarlosEsco/Neko/files/10268535/neko_crash_logs.4.txt)

### Neko version

2.12.2

### Android version

9 (SDK 28)

### Device

kindle fire hd 10 2021

### Other details

neko kind of likes to hang and have me force a restart kind of often, but now its just crashing way to often with the last two updates, I dont know if its because I am currently on a kindle fire, or if its the app itself, im guessing its me being on a kindle, so this may get resolved in a few days whne I move to an s7+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
update to 2.12.3 then login again
