### ISSUE TITLE
Chapter with no Volume unavaible

### ISSUE THREAD

**Issue by Sonic803** [CarlosEsco/Neko#1282]
### Steps to reproduce

Trying to download a chapter that doesn't yet belong to a volume.

### Expected behavior

It should be visible.

### Actual behavior

It is not.

### Neko version

2.12.3

### Android version

Android  12

### Device

Xiaomi mi 10 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Can you provide a sample

**Comment by Sonic803** [comment]
I'm sorry, now it works😅
