### ISSUE TITLE
Crash on changing cover

### ISSUE THREAD

**Issue by alidan** [CarlosEsco/Neko#1284]
### Steps to reproduce

go to Am I actually the strongest in library
go to artwork
crash

### Expected behavior

go to Am I actually the strongest in library
go to artwork
scroll the images for the one I want
select it
set it
forget it was ever different

### Actual behavior

application crashes with an error window, this is actually a first of a popup about it crashing happening, usually it just restarts without a word about crashing. 

### Crash logs

[neko_crash_logs (5).txt](https://github.com/CarlosEsco/Neko/files/10304054/neko_crash_logs.5.txt)

### Neko version

2:12:13

### Android version

android 12

### Device

galaxt s7+

### Other details

I haven't seen anything else mention this issue but I may have not searched it with the right terms. other manga is unaffected by this, this is the only one I know right now that is effected. -

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.12.4
