### ISSUE TITLE
Mangadex login needed very frequently after current update

### ISSUE THREAD

**Issue by JaberHaisan** [CarlosEsco/Neko#1286]
### Steps to reproduce

1) Login to mangadex in neko
2) After around a day or so, Neko forgets about the login so you have to login again 

### Expected behavior

I don't have to login to mangadex in Neko frequently (every session which have a gap of a couple days) like how it was before the current update.

### Actual behavior

Now I have to login to mangadex in Neko frequently. When I use the app every couple days I have to login to mangadex for updating my library.

### Neko version

2.12.3

### Android version

Android 12

### Device

Samsung Galaxy M31

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This is an issue with MangaDex new login system. Currently the refresh token should last 30 days but it lasts 7 hours. 

There is nothing I can really do about it and they know about the issue

**Comment by JaberHaisan** [comment]
Oh okay. That's a bummer
