### ISSUE TITLE
Adding mangareader.to to merge manga sources 

### ISSUE THREAD

**Issue by Winner875** [CarlosEsco/Neko#1287]
### Describe your suggested feature

Adding mangareader.to will be much help because manga see has a lot more mangas than manga life 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
They are owned by the same person and should have the same manga.

**Comment by Winner875** [comment]
Can you add mangareader.to then ? If it's possible

**Comment by Winner875** [comment]
> They are owned by the same person and should have the same manga. 

Can you add mangareader.to then ? If it's possible because manga dex doesn't have as much as mangareader library

**Comment by CarlosEsco** [comment]
There are no plans to add any more sources at this time
