### ISSUE TITLE
consistency of scanlation team when reading 

### ISSUE THREAD

**Issue by yapudjus** [CarlosEsco/Neko#1288]
### Describe your suggested feature

when reading, if you start with, say asura scan but there's also entries for the same chapter from, say, flame scan, if i start reading from asura scan, it sometimes switch to flamescan in the next chapter, even if asura scan is available, it's not a problem if it's on the same language, but it's infuriating when it switch from English to French when going to the next chapter
it should also be noted that when a chapter gets marked as read when i finish it, it doesn't mark the same chapter from another team as read too

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Are you talking about when skip duplicates is enabled?

**Comment by yapudjus** [comment]
i do have skip duplicate enabled
the thing I'm talking about is consistency across chapters when skipping duplicates, and the fact that duplicate aren't marked as read either

**Comment by CarlosEsco** [comment]
Well duplicates marked as read is not what the option provides.

As for skip duplicates it doesn't take into account the scanlator cause it's a pain to try to get something like that working. 

Just filter out the scanlator you want then make the others as read if it's that big of issue. Then unfilter the scanlator

**Comment by CarlosEsco** [comment]
This should be slightly more consistent now
