### ISSUE TITLE
Back button on the manga exit the whole app

### ISSUE THREAD

**Issue by conztanz045** [CarlosEsco/Neko#1299]
### Steps to reproduce

- click any manga 
- click the arrow on the top of the manga

### Expected behavior

Go back in library

### Actual behavior

Exit the app

### Neko version

2.12.5

### Android version

Android 9

### Device

Oppo A12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by conztanz045** [comment]
https://user-images.githubusercontent.com/79831076/211999688-c23bde11-d2bc-4ea0-9fc3-ff8d54dffe97.mp4

**Comment by eeleater** [comment]
Same Issue on Android 13 on Galaxy Note20 Ultra.

**Comment by launqistormfist** [comment]
same issue on a Samsung galaxy tablet

**Comment by K0sh1R1zumu** [comment]
Same Issue on an Android 12 SKQ Redmi Note 11

**Comment by alidan** [comment]
for anyone who may not have realized it, and god knows I didn't till a few hours ago, you can use the phone/tablets back button to back out of the manga, and if you are like me and use a controller (I use an 8bitdo zero 2) to scroll pages, the back button on that works as well (the reason I didn't notice the system one does the same)
