### ISSUE TITLE
[Feature Request] Mark all as read or allow selecting range

### ISSUE THREAD

**Issue by cpiber** [CarlosEsco/Neko#130]
In the "Library updates" it is possible to select multiple and mark those as read.

It would be nice if there as
- a button to mark all as read
- and/or the ability to select multiple (for example https://github.com/Jays2Kings/tachiyomiJ2K allows selecting a range by long clicking on a second element)

**Comment by CarlosEsco** [comment]
does jays allow selecting range in library view?  i have something similar in chapter view.  Not the same mechanics though.

**Comment by cpiber** [comment]
Readme: "Range Select for Library and Chapters: long Press on an item then long press on another to select everything in between", not sure if that is on updates as well

**Comment by CarlosEsco** [comment]
i added this to chapter and library if you  want it for updates specifically open a new ticket
