### ISSUE TITLE
update may/may not be happening when tablet is idle/suspended/closed/standby

### ISSUE THREAD

**Issue by alidan** [CarlosEsco/Neko#1303]
### Steps to reproduce

(I am not sure the correct term to use for this, and am not sure if this is happening or if this is a my tablet kind of problem)

close the tablet when it is updating library, 
open tablet an hour or so later and see it has made 0 progress

### Expected behavior

update continues when the table is in the 'idle/suspended/closed/standby' condition

### Actual behavior

it seems to just stop waiting for the tablet to be open/on again

### Neko version

2.12.5

### Android version

android 13

### Device

galaxy tab s7+

### Other details

Its possible that this is a table specific problem and not a software one, I have no idea which, this could also be in my head but I notice that when I open neko now I don't see a wall of new things like I use to on the kindle, I notice the updating never really stopping, and it always looks about where it was before. 

if you happen to know what the problem is and its tablet related, I would appreciate the help. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
I would look through this
https://dontkillmyapp.com/samsung

**Comment by alidan** [comment]
that did it, thanks
