### ISSUE TITLE
Titles in your library should have a remove button for trackers

### ISSUE THREAD

**Issue by Curstantine** [CarlosEsco/Neko#1304]
### Steps to reproduce

1. Open a title that you have a tracker bound and is in the library.
2. Open the tracking sheet. 

### Expected behavior

There should be a button to remove trackers from titles in your library, regardless of whether they are in the library or not.

### Actual behavior

The close button only appears for titles that are not in your library.

### Neko version

4.12.5

### Android version

12

### Device

Samsung Galaxy M21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by Curstantine** [comment]
Wait, [nvm].(https://github.com/CarlosEsco/Neko/blob/48a0934e8deb593ffd3f28cfa1da39c344685742/app/src/main/java/org/nekomanga/presentation/components/sheets/TrackingSheet.kt#L261)
But why though? That button is supposed to remove a tracker, right?

**Comment by CarlosEsco** [comment]
because if you remove it, and have auto add tracker enabled it will just re add the title again.  So the remove button would be pointless.

**Comment by Efreak** [comment]
@nonproto what if auto tracker *isn't* enabled?

More importantly, what if I've tracked the wrong title? I was referring the title by a few words at a time to try and track the proper title, and when I got to two words it automatically picked the wrong title and closed the box. Searching again, there's only one result with those two words (likely this is why it automatically picked that item) however the item being tracked is *wrong*. I have no way to fix this.
![SmartSelect_20240213_042057](https://github.com/nekomangaorg/Neko/assets/749751/086385dd-94f8-4d38-b588-53ee41958f74)

**Comment by nonproto** [comment]
> @nonproto what if auto tracker *isn't* enabled?
> 
> More importantly, what if I've tracked the wrong title? I was shortening the title by a few words at a time to try and track the proper title, and when I got to two words it automatically picked the wrong title and closed the box. Searching again, there's only one result with those two words (likely this is why it automatically picked that item) however the item being tracked is *wrong*. I have no way to fix this, since the correct title is apparently not in kitsu, and there's no way to remove the tracked title.
> ![SmartSelect_20240213_042057](https://github.com/nekomangaorg/Neko/assets/749751/086385dd-94f8-4d38-b588-53ee41958f74)
> 
> Also, it's entirely possible for there to be an incorrect manga with the correct title; there's several I'm aware of that have multiple manga versions available with the same title and different authors, and titles aren't always added to all trackers; it seems wrong to force users to either track the wrong title (until the second version is added to whichever tracker) or disable automatic tracker linking everywhere. It might be worth setting the tracker value to a special case (id 0?) to disable tracking instead. (This isn't a feature request, just a thought)

There are two different things at play here .
1.  Is auto tracking (which is based off the Mal/kitsu etc id that is on mangadex.)
2.  Is the j2k feature of selecting the track search result by default  if only one is there on search.

Based off your screenshot you auto tracking enabled cause there are no x boxes
![Screenshot_20240213-073234.png](https://github.com/nekomangaorg/Neko/assets/2092019/5c67c70f-0a2a-4dc5-90be-1ee38fb682eb)

If it auto linked the wrong manga then you really need to open a ticket on mangadex to get the id updated correctly


If you manually or it selected the wrong one cause it was only result, then you need to disable auto track, remove the track.  Then reneable auto track.  

Feel free to ask for more clarification or if they doesnt solve in the discord server
