### ISSUE TITLE
Chapters top bar scrolls inconsistently with other pages

### ISSUE THREAD

**Issue by MrSimmmons** [CarlosEsco/Neko#1309]
### Steps to reproduce

1. Open manga with > 15 chaperts
1. Start scrolling down

### Expected behavior

The top app bar collapses / reappears in the same way that the search bar does on the library screen in the sense that it doesn't interfere with the page scroll

### Actual behavior

Notice how at the start of the scrolling, the page doesn't scroll and instead the top bar containing the back arrow and options menu starts to collapse. Once it has fully collapsed does the page start to scroll. The same thing happens when scrolling up where the top bar needs to finish appearing before the page actually starts moving

### Neko version

2.12.6

### Android version

Android 13 (One UI 5.0)

### Device

Samsung Galaxy S20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
#1059
