### ISSUE TITLE
[Feature Request] MangaDex sync read status down

### ISSUE THREAD

**Issue by cpiber** [CarlosEsco/Neko#131]
Currently, Neko does not care if I've read a chapter on MangaDex already, thus my list of updates is probably about 1000 items, all unread (I imported just now).

I would love it, if those chapters were to be set to read since MangaDex knows it (for most chapters). Neko already syncs read status up, why not down as well?

**Comment by CarlosEsco** [comment]
So the sync read status up is unintended, mangadex api is marking the chapter read when the data is pulled.  I will look into syncing the marked read

**Comment by CarlosEsco** [comment]
In 2.5.0
