### ISSUE TITLE
Neko continuously fails to update chapters

### ISSUE THREAD

**Issue by Reiedipo** [CarlosEsco/Neko#1310]
### Steps to reproduce

1. Neko start updating chapters, automatic or manually.
2. In the notifications, the progress bar fills up as manga titles appears one by one, as normal.
3. When the progress bar is complete, and you expect your chapters to be updated, it shows "X update(s) failed" and no titles are updated.

### Expected behavior

Chapters should be updated when neko updates on auto or user clicks update button.

### Actual behavior

Neko shows updating progress, but fails at completion.

### Crash logs

! Received http error code: 503
    - 15 Minutes 'Til They Actually Start Dating
    - A Story About a Very Ordinary Couple
    - ALIENS AREA
    - Aishiteru Game wo Owarasetai
    - Ao no Hako
    - Arafoo Otoko no Isekai Tsuhan Seikatsu
    - Asoko de Hataraku Musubu-san
    - Ayashimon
    - Bocchi no Boku ni Kyousei Kanojo ga Yattekita
    - Boku no Kanojo wa Saikoudesu!
    - Boku no Okusan wa Chotto Kowai
    - Boku no Suki na Hito ga Suki na Hito
    - Boku to Kimi (Gyaru) ga Fuufu ni Naru Made
    - Busu ni Hanataba wo.
    - Capeta
    - Childhood Friendship Is Hard
    - Class no Bocchi Gal wo Omochikaeri Shite Seisokei Bijin ni Shite Yatta Hanashi
    - Cuprum’s Bride
    - Dandadan
    - Dark Summoner to Dekiteiru
    - Dorei wo Choukyoushite Harem Tsukuru
    - Fuufu Ijou, Koibito Miman.
    - Gachiakuta
    - Ganbare, Douki-chan (Webcomic)
    - Goblin Slayer
    - Goddess Café Terrace
    - Golden Kamuy
    - Henjo - Hen na Joshi Kousei Amaguri Senko
    - Hiiragi-san is A Little Careless
    - Hime Kishi wa Barbaroi no Yome
    - I Became the Mother of the Strongest Demon Lord's 10 Children in Another World.
    - I'm A Shy and Poor Otaku but This Beautiful Rich Young Lady is Obsessed with Me
    - Ijiranaide, Nagatoro-san
    - Imaizumin Chi wa Douyara Gal no Tamariba ni Natteru Rashii~DEEP~
    - Inkya Datta Ore no Seishun Revenge - Tenshi sugiru Ano Ko wa Ayumu Re Life
    - Isekai De Te Ni Ireta Seisan Skill Wa Saikyou Datta You Desu
    - Isekai Kenja no Tensei Musou ~Geemu no Chishiki de Isekai Saikyou~
    - Isekai Nihon
    - Isekai Walking
    - It's Not Meguro-san's First Time
    - I’m Sick and Tired of My Childhood Friend’s, Now Girlfriend’s, Constant Abuse so I Broke up With Her
    - Kaiju No. 8
    - Kanan-sama wa Akumade Choroi
    - Karappo no Shoujo to Niji no Kakera
    - Keiken Zumi na Kimi to, Keiken Zero na Ore ga, Otsukiai Suru Hanashi
    - Kekkon Surutte, Hontou desu ka: 365 Days To The Wedding
    - Kimi wa Houkago Insomnia
    - Komi-san wa Komyushou Desu.
    - Kowloon Generic Romance
    - Kubo Won't Let Me Be Invisible
    - Kuchi ga Saketemo Kimi Ni Wa
    - Maid-san wa Taberu Dake
    - Majo-senpai Nippou
    - Mato Seihei no Slave
    - Maybe Meant to Be
    - Meika-san wa Oshikorosenai
    - Mission: Yozakura Family
    - Mitsuishi-san is Being Weird This Year
    - Monku no Tsukeyou ga nai Rabukome
    - My Retired Idol Wife is Cute
    - No, Miyahara, Not You!
    - Nozomanu Fushi no Boukensha
    - Orient
    - Osake wa Fuufu ni Natte Kara
    - Osananajimi ga Hisabisa ni Saikai Shitara Otagai Kyonyuu ni Natteta
    - Otonari no Tenshi-sama ni Itsu no Ma ni ka Dame Ningen ni Sareteita Ken
    - Please Go Home, Akutsu-san!
    - Realist Maou Niyoru Seiiki Naki Isekai Kaikaku
    - Rebuild World
    - Ruri Dragon
    - Saihate no Paladin
    - Satellite Coin Laundry
    - Sei-chan Capacity Over desu!
    - Seihantai na Kimi to Boku
    - Seitokai Yakuindomo
    - Sekai no Owari no Encore
    - Shed! Ryugasaki-san
    - Skip and Loafer
    - Sono Bisque Doll wa Koi wo Suru
    - Sotodura Danshi no Shimizu-kun
    - Soukyuu no Ariadne
    - Sousou no Frieren
    - Suki na Ko ga Megane wo Wasureta
    - Telework Yotabanashi
    - Tensei Kyuuketsuki-san wa Ohirune ga Shitai
    - The Apothecary Diaries
    - The Fairytale-like You Goes on the Assault
    - The Fragrant Flower Blooms With Dignity
    - The Overworked Office Lady's Café Crush
    - The Tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere Girl Getting Less and Less Tsun Day by Day
    - Tonikaku Kawaii
    - Tou no Kanri o Shite Miyou
    - Tsuki ga Michibiku Isekai Douchuu
    - UQ HOLDER!
    - Until My Bentos Are Made With the Loving Care of My Wife
    - Uzaki-chan Wants to Hang Out!
    - VERSUS
    - We'll get married someday, but for now
    - Witch Hat Atelier
    - Witch Watch
    - Yaiteru Futari
    - Yancha Gal no Anjou-san
    - Yandere Kirenai
    - Yofukashi no Uta
    - Yotsuba&!
    - Yowai 5000-nen no Soushoku Dragon, Iware naki Jaryuu Nintei: Yada Kono Ikenie, Hito no Hanashi wo Kiite Kurenai
    - Yuzukawa-san wa, Sasshite Hoshii.
    - she is beautiful

#

### Neko version

2.12.6

### Android version

Android 12

### Device

Samsung Galaxy S20 FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Dex was down for a bit when this occurred
