### ISSUE TITLE
Crash on open manga

### ISSUE THREAD

**Issue by alidan** [CarlosEsco/Neko#1316]
### Steps to reproduce

The manga opened the second time so I have no idea

### Expected behavior

not crash

### Actual behavior

what happened was I opened a new maid dragon chapter, and a wall of text popped up

### Crash logs

[neko_crash_logs (6).txt](https://github.com/CarlosEsco/Neko/files/10506375/neko_crash_logs.6.txt)

### Neko version

2.12.6

### Android version

13 sdk 33

### Device

samsung galaxy tab s7+

### Other details

I don't know if this is the full log or not, the page that popped up had a crash dump button, but I can't find that specific log and this seems really short given it was a scrollable page for the other one. if you know were the log is I can try to find it to give you a better thing to work off of.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
There is nothing in the file, as you mentioned if you can get to happen again take a screenshot the crash screen
