### ISSUE TITLE
Add "Mark as" some options

### ISSUE THREAD

**Issue by astralkill00** [CarlosEsco/Neko#1318]
### Describe your suggested feature

Open a series or title (not chapter)
Select a chapter (holding it) to pop out a mini-menu
Choose "Mark Selected As"
There should be an option like "Read" / "Unread"

Done.
![IMG_20230127_224450](https://user-images.githubusercontent.com/119454295/215116896-ac6438ba-0458-428a-93fb-331743a8367f.jpg)

### Other details

Tachiyomi has this function and it's frustrating to open a chapter everytime I need to make a chapter be in a READ status. This is usually for those who likes their latest chapter comes out on top of the previous ones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/CarlosEsco/Neko/issues/1297

Also you can swipe the chapter to mark it read
