### ISSUE TITLE
[bug] Doesn't resolve MangaDex DDoS-Guard [Error 403]

### ISSUE THREAD

**Issue by cpiber** [CarlosEsco/Neko#132]
Sometimes (e.g. when updating a big library), DDoS-Guard on MangaDex is triggered. This page is delivered with HTTP 403 and provides a Captcha-Box (see screenshot).

**Expected behaviour**
Pause everything, show WebView to user to resolve conflict.

**Current behaviour**
On manga page: Notification "Error 403"
During update: Skip
Retrieving image: Retry button, nothing helps

**Workaround**
Open https://mangadex.org / https://mangadex.cc in WebView and resolve conflict.

**Screenshot DDoS-Guard**
![image](https://user-images.githubusercontent.com/59023762/72084771-65430c00-3304-11ea-9b0a-e0d9ef6738b0.png)

**Comment by CarlosEsco** [comment]
I might need to up the delay between requests, so it doesnt trigger

**Comment by lupoonehundred** [comment]
The issue has rearised and changing it to webview for solving the Captcha-Box would fix it, I presume.

**Comment by CarlosEsco** [comment]
you should be able to 3 dot open webview solve then be fine.

**Comment by lupoonehundred** [comment]
I'm not able to re-login after I thought it was an account issue. There is no option for a webview in the 3 dots.

**Comment by CarlosEsco** [comment]
you logged out?  if you dont you can click into browse nothing loads then 3 dot at top and open in webview. alternatively if you have manga in your library open one up click 3 dot open in webview get through ddos.  then go login

**Comment by lupoonehundred** [comment]
![Screenshot_20200317-132951](https://user-images.githubusercontent.com/9563087/76899647-35a90680-6855-11ea-9811-48a11954dd4c.jpg)
This is my current view with no mangas added.

**Comment by CarlosEsco** [comment]
yea nothing you can do currently.  I will look into adding a webview in settings in next release

**Comment by lupoonehundred** [comment]
Sure, thank you for helping.

**Comment by CarlosEsco** [comment]
closing as this shouldnt be an issue now with v5 api
