### ISSUE TITLE
Content Ratings Settings

### ISSUE THREAD

**Issue by TheSeriousYoungBoy** [CarlosEsco/Neko#1321]
### Steps to reproduce

https://user-images.githubusercontent.com/119454295/215254337-c21b8e19-1ba0-43f4-a6da-aedad1daceb4.mp4

### Expected behavior

Showing NSFW content...

"file an issue on github that seasonal isn't filtered by the content rating setting" quote from 'loocool2'

### Actual behavior

Showing SFW content only

### Neko version

2.12.7

### Android version

Android 12

### Device

Xiaomi

### Other details

"file an issue on github that seasonal isn't filtered by the content rating setting" quote from 'loocool2'

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.12.8
