### ISSUE TITLE
Adding local source 2 neko

### ISSUE THREAD

**Issue by Winner875** [CarlosEsco/Neko#1328]
### Describe your suggested feature

Are the local source to neco will be good because you can add manga from your phone directly it's obviously komga that has to do with laptop server I really hope that you had this feature

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
There is no plan to add local source as a merge option at this time
