### ISSUE TITLE
[bug] Next chapter goes to different version

### ISSUE THREAD

**Issue by cpiber** [CarlosEsco/Neko#133]
When there are multiple versions available for one chapter, pulling up to go to the next chapter instead loads the next available version.

MangaDex Reader automatically groups different versions and can go to the next chapter (from the same group if available). Would expect the same behaviour (at least to get to the next chapter) from Neko.

**Comment by CarlosEsco** [comment]
currently the api only provides a list of all chapters.    #31  would address this concern.  so closing it in favor of that.
