### ISSUE TITLE
[Feature Request] Kenmei Tracking?

### ISSUE THREAD

**Issue by okaywhatfine** [CarlosEsco/Neko#1330]
### Describe your suggested feature

I've been using this Manga/Manhwa/Manhua/Webtoon tracking website called Kenmei (kenmei.co) it's a super underrated tracker that is new. It's like how any other tracker works, but it has features that others don't have, and that is the support of TL Groups/other websites such as Webtoon and Mangadex and only base their database of series according to what their "supported sites" have iirc. and I would love to have this as a tracking option in Mangadex since it's painful to open their site again and add the series that I like or read again and again instead of just adding them via Neko.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Until there is API support added this won't be added.  Scraping is against the TOS of a user of Kenmei and at this time the owner/maintainer says adding an API is on the back burner.
