### ISSUE TITLE
Neko not pushing read status to MD

### ISSUE THREAD

**Issue by AerospaceGlobe** [CarlosEsco/Neko#1334]
### Steps to reproduce

Read any chapter on Neko (inc ones in library marked as reading)
Check mangadex for same chapter 

### Expected behavior

Read any chapter on Neko 
Check mangadex for same chapter 
Read status is reflected in mangadex

### Actual behavior

Read any chapter on Neko 
Check mangadex for same chapter 
Read status not reflected in mangadex

### Neko version

2 .12.8

### Android version

Android 13

### Device

Samsung S20+

### Other details

Seems to be the case on my samsung M10, and my Neko on Windows install

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by AerospaceGlobe** [comment]
Actually did mangadex remove that feature from the API?

**Comment by CarlosEsco** [comment]
So it's read markers that get updated so make sure you are checking the little eyes
