### ISSUE TITLE
AniList tracking adds random series

### ISSUE THREAD

**Issue by elingp** [CarlosEsco/Neko#1344]
### Steps to reproduce

1. Open an untracked series.
2. Click the tracking button.
3. Click "add tracking" on AniList section.
4. (First try will fail) Click "add tracking" on AniList section again.
5. The series will be tracked, but when checked manually on AniList, two series (one random, one intended series) are tracked.

Here is a screen recording.

https://user-images.githubusercontent.com/4961046/218638633-41224f91-5fd7-47cb-a937-882af072c13f.mp4

### Expected behavior

Only the intended series will be tracked on AniList.

### Actual behavior

Two series are tracked on AniList: the first is a random series, the second is the intended series.

### Neko version

2.12.8

### Android version

Android 11

### Device

Realme X2 Pro

### Other details

It probably has something to do with the "add tracking" part that blinked at first, and then succeeded at the second try. It seems to track the random series on the first blink. This behavior didn't happen on MAL tracking. This behavior only happens on previously untracked series on AniList (i.e., if you've tracked the series before, deleted it from AL, then repeat the steps again, it will work just fine). This behavior happens from before this Neko version (forgot since when), but only now was I remember to record it.

A suggestion is probably not to automatically tracked the series after clicking "add tracking", but to show the list of possible series and let the user click the series' name as a final confirmation (Tachiyomi's behavior).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2 things.

1.  Can you enable debug logging, force close app then repeat this (verify the file has identifiable information before posting here)
2.  It only auto adds if there is 1 result and it should be using the id returned from dex (which i just check is and is correct)

**Comment by elingp** [comment]
Sorry, but I don't quite understand the first point. If it's dumping the crash logs manually from the setting, here's my result (with verbose logging on): <https://pastebin.com/8gpapp3Q>

Okay, after testing it again with four different titles, I noticed these:

* The bug happens only on AniList tracking.
* The bug happens only for a title with **one or fewer** tracking results on AniList. (i.e., when you click the title, only that title appears on the tracking result).
* The bug happens only if AniList is *the second tracker*. (i.e., it happens only if you've tracked on MAL first, then tracked it on AniList).

The five titles I tested are: (I have never tracked these titles before. I'll attach the screen recording asap)

* [*Reincarnated as an Apple*](https://mangadex.org/title/76abc539-9b38-45af-a6d7-cb02c3cca2fb/reincarnated-as-an-apple-this-forbidden-fruit-is-forever-unblemished) : One AniList tracking result. Bug **did** happen.
* [*Toki Tsukai Majutsushi no Tensei Musou*](https://mangadex.org/title/f67bd8ea-3322-4eb7-85db-431ab12b208d/toki-tsukai-majutsushi-no-tensei-musou) : One AniList tracking result. Bug **did** happen.
* [*The Time Mage's Strong New Game*](https://mangadex.org/title/1bd78711-2fe0-412d-8570-cea963c50a92/the-time-mage-s-strong-new-game-i-returned-to-the-past-to-rewrite-it-as-the-world-s-strongest) : Zero AniList tracking result. Bug **did** happen.
* [*Tensei Slime*](https://mangadex.org/title/e78a489b-6632-4d61-b00b-5206f5b8b22b/tensei-shitara-slime-datta-ken) : Multiple AniList tracking results. Bug **did not** happen.
* [*Overlord*](https://mangadex.org/title/ac4e2459-d995-45ae-8421-4c4cf4a87770/overlord) : Multiple AniList tracking results. Bug **did not** happen.

**Comment by elingp** [comment]
Reincarnated as an Apple

https://user-images.githubusercontent.com/4961046/219227503-3f9c6c5c-e1c2-49bc-a819-52cfd365a894.mp4

Toki Tsukai


https://user-images.githubusercontent.com/4961046/219227676-95b6442e-b90e-4a3d-a53b-634b2df5bafd.mp4


The Time Mage's


https://user-images.githubusercontent.com/4961046/219227812-2e813543-19fc-4d93-ad4f-677fa8f3dc1a.mp4

**Comment by CarlosEsco** [comment]
Before I dig into this further. Can you log out and relogin to anilist and let me know if it still happens

**Comment by elingp** [comment]
Hiya. I've just tried re-login from the tracking setting *and* the AniList web, but it still happens on each attempt. I tested it with the *The Time Mage's Strong New Game* title, and the same random title (*The Unforeseen Guest*) appears.

**Comment by CarlosEsco** [comment]
This is very confusing as I am still unable to replicate.  You might need to wait for a new version where the verbose logging shows the http calls.

**Comment by elingp** [comment]
All good. I'll try it on another account and device and also reinstall Neko. Perhaps it might fix the problem. I'll report back.

**Comment by CarlosEsco** [comment]
> All good. I'll try it on another account and device and also reinstall Neko. Perhaps it might fix the problem. I'll report back.

Any issue with reinstall?

**Comment by CarlosEsco** [comment]
> All good. I'll try it on another account and device and also reinstall Neko. Perhaps it might fix the problem. I'll report back.

Any issue with reinstall?
