### ISSUE TITLE
Auto tracking doesn't update linked tracker for offline chapter reads.

### ISSUE THREAD

**Issue by Chef-Food** [CarlosEsco/Neko#1357]
### Steps to reproduce

1. Read downloaded chapters offline
2. Go online to update library

### Expected behavior

The reading progress should be automatically updated to last read chapter when updating.
![Screenshot_20230222_113412](https://user-images.githubusercontent.com/83027938/220939285-c06ba002-d9da-45ce-878c-94b15c2256a4.png)

### Actual behavior

The app doesn't update the reading progress and only does so after manually rereading the last read chapter

### Neko version

2.12.8

### Android version

Android 13

### Device

Windows Subsystem For Android 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Might be resolved on next release
