### ISSUE TITLE
Crashing when opening a manga from library

### ISSUE THREAD

**Issue by Yoposoc** [CarlosEsco/Neko#1358]
### Steps to reproduce

1. I have [Ookiku Furikabutte ](https://mangadex.org/title/c411bbfb-043e-421e-bafb-e2d206ff7ac4/ookiku-furikabutte)in my Default library, with 9 chapters downloaded.
2. I tap on it to look at the chapters.
3. After 2 seconds, Neko crashes immediately.

### Expected behavior

Should open to allow browsing per chapter.

### Actual behavior

Crashes the application.

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/10831708/neko_crash_logs.txt)

### Neko version

2.12.8

### Android version

8

### Device

Galaxy Tab S3 (SM-T820)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.12.10

**Comment by Yoposoc** [comment]
This is happening again as of latest version.

**Comment by Yoposoc** [comment]
@CarlosEsco please mark this issue as open again. Or should I create a new ticket?
Here's the [neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/12571108/neko_crash_logs.txt) in case that's all that's needed.

**Comment by CarlosEsco** [comment]
Create a new ticket
