### ISSUE TITLE
App crashes whe tapping the description box

### ISSUE THREAD

**Issue by gcpadua** [CarlosEsco/Neko#1359]
### Steps to reproduce

1. Open the manga "[The Inferior Grade Strongest Sage ~From the Lowest Villager to the World's Strongest With Ease~](https://mangadex.org/title/97d2b29c-2c73-48ef-9c41-2faf8b5cf9f4/the-inferior-grade-strongest-sage-from-the-lowest-villager-to-the-world-s-strongest-with-ease) "
2. Expand the description
3. Tap the text

### Expected behavior

The description box should collapse

### Actual behavior

App crashes

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/10915503/neko_crash_logs.txt)

### Neko version

2.12.8

### Android version

Lineage OS 19.1 (Android 12.1)

### Device

Poco X3 NFC

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
#1277
