### ISSUE TITLE
[bug] myanimelist search title too long

### ISSUE THREAD

**Issue by henrik9999** [CarlosEsco/Neko#136]
**Describe the bug**
When an manga with an long name is searched on the myanimelist tracking search it does not return anything when the title is too long

**To Reproduce**
1. Go to a manga with long title (https://mangadex.org/manga/41726/)
2. Click on tracking
3. Scroll down to myanimelist click on title

**Expected behavior**
Search working

**Ideas to fix**
Cut the title to a working length

**Screenshots**
![Screenshot_20200114-233657](https://user-images.githubusercontent.com/22085664/72388673-db8da700-3726-11ea-9026-7ec6fc3d3086.png)

**Please complete the following information:**
 - Android Version: 9
 - Version: 1.5.4.1

**Comment by CarlosEsco** [comment]
fixed in 1.6.0
