### ISSUE TITLE
Chapters are unavailable for some mangas

### ISSUE THREAD

**Issue by bosslamas** [CarlosEsco/Neko#1360]
### Steps to reproduce

1. Click on a manga.
2. Sometimes, the chapters won't appear (even though they exist and are translated in the chosen language, checked on Mangadex). Example : Just a few months ago, Grapper Baki had all of its 400 chapters available on the app, now it shows absolutely nothing, even though they are still accessible on mangadex. If they do appear, they work normally and there's no problem.

### Expected behavior

Chapters should appear for all mangas, translated obviously.

### Actual behavior

Some mangas are empty.

### Neko version

2.12.8

### Android version

Android 12

### Device

Samsung A20

### Other details

I though that it may have been an issue with just that manga (Grappler Baki), but for some other mangas (which I forgot the names), it also happens. It lead me to thinking that the Mangadex API may have been broken by an update, because coincidentally, my Tachiyomi app did the same thing at around the same time, until I allowed 18+ sources in settings, then it worked as it should. Maybe because the only source on Neko is Mangadex, and that it doesn't give the same setting, something happened? Either way, some mangas don't show chapters and it's irritating, because I have to switch to Tachiyomi, and Tachiyomi's landscape zoom doesn't zoom 200%, so it looks ugly.

Please, either fix this, or allow multiple sources like in Tachiyomi. Preferably multiples sources (and local sources). Also, please pester the Tachiyomi devs to add 200% landscape zoom.

Thank you very much.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
I just checked 
https://mangadex.org/title/0ee2f134-87c6-4715-b31e-b3b1344fa5ea/baki
And
https://mangadex.org/title/ea3122bb-0c28-4669-8686-d6df1274512f/grappler-baki

Both have almost 400 hundred English chapters.

You never said what language you were looking at.

Have you verified you have no filters enabled in the manga info screen? Have you verified you have the correct languages enabled in the settings? Please ask in discord if you need more help

**Comment by bosslamas** [comment]
I'm reading them in english. I have no filters, nothing. It should work as planned, but they don't show. Just a month or two ago I read all 371 chapters of Grappler Baki in english, but now they're not on Neko anymore, yet they're still on mangadex.

**Comment by CarlosEsco** [comment]
They are on neko is what I am saying. So there is something on your end. Go to the discord neko channel and we can help debug

**Comment by arkon** [comment]
I can confirm that it shows up fine for me, so you're very likely just filtering them out.

**Comment by bosslamas** [comment]
Hi. I've tried to enable/disable any filter, i've even allowed mangas up to hentai level (knowing Grappler Baki, that could have been the problem), but no, it's still not showing. Attached here is what I see.
![Screenshot_20230317-210355_Neko](https://user-images.githubusercontent.com/127434388/226075326-16f59bdf-bb77-49f1-af73-e996b0577eb3.jpg)

**Comment by bosslamas** [comment]
Please, forget everything I said. I'm only a bonehead and i filtered chapters by unread. Thank you very much for you help, Neko is awesome.
