### ISSUE TITLE
[bug] swipe right scroll issue

### ISSUE THREAD

**Issue by jaredanson** [CarlosEsco/Neko#137]
**Describe the bug**
When you swipe right in my library section to get the filter sidebar, it will jump through your manga to farther down in the list and then bring out the side panel related to filter.

**To Reproduce**
1. Go to My Library
2. Swipe from the right
3. See it jump down in the list before the side panel comes out

**Expected behavior**
I would expect the sidebar to smoothly come out, just like when you swipe from the left. I would not expect it to jump to a certain point in the list of manga.

**Screenshots**

**Please complete the following information:**
 - Device: Pixel 2 XL
 - Android Version: 10
 - Version 1.5.4.1

**Additional context**

**Comment by CarlosEsco** [comment]
Does this happen on main Tachiyomi?

**Comment by arkon** [comment]
It does, in dev. I might just remove the fast scroller.

**Comment by CarlosEsco** [comment]
Maybe i'll mess with the side bar sensitivity.  Until i eventually switch to bottom bar

**Comment by jaredanson** [comment]
In latest prod build 0.8.4 of Tachiyomi, this behavior doesn't happen.

Also what do you mean by switching to bottom bar?

**Comment by CarlosEsco** [comment]
Stable doesnt have the fast scroller.  Which arkon is saying is causing the issue.  

Ignore the bottom bar comment thats just me talking about potential ui updates.

**Comment by jaredanson** [comment]
Ahh I see. I haven't played around with dev in Tachiyomi, do you know if this same problem happens there as well or they handled it in some way? If they haven't I imagine there will be some complaints.

**Comment by CarlosEsco** [comment]
fixed in 1.6.0

@arkon all it needed was some padding so it wasnt right on edge of screen

**Comment by arkon** [comment]
I did try that but I thought it looked bad.

**Comment by jaredanson** [comment]
@CarlosEsco thanks for the quick update, it works great.
