### ISSUE TITLE
Only update "Reading"-tracked mangas

### ISSUE THREAD

**Issue by robintourvel** [CarlosEsco/Neko#1370]
### Describe your suggested feature

I have a lot of mangas in "Completed" and "Plan to read" tracking status, that get refreshed every time. I guess this puts unnecessary load on MD servers.

This would be conceptually similar to the existing "Only update ongoing manga" in Settings/Library, but relying on "tracking status" besides of publication status.

I'd still want to get updates for completed mangas on manual updates, in case some post-end extra drops. I think this is already the behavior for "Only updated ongoing manga".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
You can also just move them to a category that you don't update

**Comment by CarlosEsco** [comment]
2.12.10
