### ISSUE TITLE
Crash when clicking on a manga that hasn't been clicked/loaded before

### ISSUE THREAD

**Issue by Viruzaum** [CarlosEsco/Neko#1373]
### Steps to reproduce

1. Go to browse
2. Click on any manga that you never clicked on before
3. It crashes while loading it

### Expected behavior

Should open the manga.

### Actual behavior

The app crashes.

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/11009917/neko_crash_logs.txt)

### Neko version

2.12.9.1

### Android version

Android 8

### Device

Samsung Galaxy S7

### Other details

Only happens the first time you click on it, after restarting the app and trying the same manga again it works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
It looks to be a bug with compose.
https://issuetracker.google.com/issues/215116019

**Comment by CarlosEsco** [comment]
Try 2.12.10

**Comment by Viruzaum** [comment]
Can confirm the bug doesn't happen anymore on 2.12.10
