### ISSUE TITLE
Crash when searching and changing 3 or more filters at once

### ISSUE THREAD

**Issue by Viruzaum** [CarlosEsco/Neko#1374]
### Steps to reproduce

1. Go to browse
2. Click on `Search`
3. Change 3 or more filters
4. Click on `Filter`
5. The app crashes

### Expected behavior

Should search without crashing.

### Actual behavior

The app crashes.

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/11009932/neko_crash_logs.txt)

### Neko version

2.12.9.1

### Android version

Android 8

### Device

Samsung Galaxy S7

### Other details

It only happens if you haven't searched before, so going from the `Home Page` in `Browse` to searching. If you search for something changing 0-2 filters first you can change how many you want after without crashing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
I think this was resolved in the last release
