### ISSUE TITLE
Enteries not being dynamically grouped by tracking status from Anilist

### ISSUE THREAD

**Issue by garvongithub** [CarlosEsco/Neko#1384]
### Steps to reproduce

1. Import a backup (I imported from j2k~184 enteries)
2. Manga are grouped normally by tracking status as expected
3. Refresh library or refresh tracking from advanced settings.

### Expected behavior

Manga should remain grouped by tracking status as it is present on site (Anilist) and refresh with new chapters

### Actual behavior

All enteries move under a new unfollowed category even though the tracking status is different.

### Neko version

2.12.9.1

### Android version

13

### Device

One plus 9 pro

### Other details

[Screen Recordings](https://imgur.com/a/tzTeuX6) 
I have also tried refreshing tracking status again, setting up neko from scratch without touching md settings.
New entries get grouped by tracking status. It's just backed up enteries suffering this problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.12.10
