### ISSUE TITLE
Crash when moving to the next chapter while reading a manga

### ISSUE THREAD

**Issue by Myskial** [CarlosEsco/Neko#1387]
### Steps to reproduce

1. Read manga until the last page
2. Swipe to go to next chapter
3. Crashed

### Expected behavior

Moving to the next chapter

### Actual behavior

It crashed

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/11072058/neko_crash_logs.txt)

### Neko version

2.12.9.1

### Android version

Android 12

### Device

Redmi Note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.12.10
