### ISSUE TITLE
Duplicate manga

### ISSUE THREAD

**Issue by Illythia** [CarlosEsco/Neko#1394]
### Steps to reproduce
1. Open library settings
2. Group library by
3. Tracking status 
4. Issue : Duplicate manga appear when sorted by tracking status.

![Screenshot_2023-04-02-23-01-09-49_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/129698114/229383472-2f191ba2-3ede-46eb-864d-90a888963850.jpg)
![Screenshot_2023-04-02-23-06-55-82_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/129698114/229383479-946067ec-2311-4546-870a-27160bcf9e9c.jpg)

### Expected behavior

There should be no duplicates.

### Actual behavior

There are multiple duplicates.

### Neko version

2.12.10

### Android version

Android 12

### Device

Realme 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by carloslos** [comment]
I'm having a similar issue, but only the mangas in the currently reading category are being duplicated.

**Comment by Bilacomy** [comment]
Also having this issue

**Comment by escalonn** [comment]
half of this issue is still present in 2.13.0, in that when categories differ by only letter case - mangadex "Plan to Read", mal "Plan to read" - the manga in these categories are duplicated. in my case this is about half of my library.

i guess the fix would be to compare category names case-insensitively for merging (if "merging" accurately describes what is currently functioning sensibly with mangadex "Reading" and mal "Reading" involving no duplication).

**Comment by CarlosEsco** [comment]
> half of this issue is still present in 2.13.0, in that when categories differ by only letter case - mangadex "Plan to Read", mal "Plan to read" - the manga in these categories are duplicated. in my case this is about half of my library.
> 
> i guess the fix would be to compare category names case-insensitively for merging (if "merging" accurately describes what is currently functioning sensibly with mangadex "Reading" and mal "Reading" involving no duplication).

This should be resolved next release.  They are supposed to be using a common tracking name.
