### ISSUE TITLE
Browse bug

### ISSUE THREAD

**Issue by conztanz045** [CarlosEsco/Neko#1397]
### Steps to reproduce

1. Go browse
2. Lastest manga
3. Open any manga chapter
4. Exit the manga and scroll down

### Expected behavior

Should load the next page of the lastest manga

### Actual behavior

Nothing happen 

### Neko version

2.12.10

### Android version

Android 9

### Device

Oppo A12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by conztanz045** [comment]
Sorry for some reason i post the video here ,here link [https://media.discordapp.net/attachments/569823838305648640/1092692299919675452/Record_2023-04-04-14-06-37_e93d65b045a4d38b75e3588ffeb6de8f.mp4](https://media.discordapp.net/attachments/569823838305648640/1092692299919675452/Record_2023-04-04-14-06-37_e93d65b045a4d38b75e3588ffeb6de8f.mp4)

**Comment by conztanz045** [comment]
https://user-images.githubusercontent.com/79831076/229781790-4a6539ad-4c05-4892-815d-a3df1981e58a.mp4

**Comment by conztanz045** [comment]
Look like the bug happen to if you bookmark or change category in lastest manga

**Comment by conztanz045** [comment]
The bug happen even if you tap on any manga on latest upload and popular new title

**Comment by Vlravyn** [comment]
This same issue exists while searching manga as well. I was able to reproduce it by these two methods 
- opening a chapter and scrolling down 
- searching for something that gives high result count and scrolling down.

The browse tab just hangs when it happens(not able to hide library entries or change view for results). I have to restart the app or go to another tab to fix it.
I'm using Android 13 on Pixel 7.
