### ISSUE TITLE
[bug] status button is cut off by the container below

### ISSUE THREAD

**Issue by jaredanson** [CarlosEsco/Neko#140]
**Describe the bug**
the status button aka reading, plan to read, dropped, etc is half cut off by the container below that contains the description, tags, heart button, and so on.

**To Reproduce**
1. click browse
2. search for "Flag Capture in the first move"
3. click on said manga
4. see it cut off. (in my case reading is cut off)

**Expected behavior**
I don't expect the button to be half cut off.

**Screenshots**

![Screenshot_20200128-193519](https://user-images.githubusercontent.com/8980095/73320812-34207200-4206-11ea-9838-ac8ddcd99352.png)

**Please complete the following information:**
 - Device: Pixel 2XL
 - Android Version: 10
 - Version 1.6.0

**Additional context**
This only happens with certain manga. I believe it has to do with the title length. If you randomly click on manga with long titles while searching through browse you can see this behavior on others. For example it also happens with "The unsuccessful yet academically unparalleled sage ~ a cheating s-rank".

**Comment by CarlosEsco** [comment]
The view scrolls.

**Comment by jaredanson** [comment]
yeah i know it scrolls. But maybe it would make sense to have that button always be visible, or outside of that view? Or not, it was just a suggestion.

**Comment by CarlosEsco** [comment]
plan is to eventually remove the button completely, and there would be a tracking card for md in the tracker tab

**Comment by jaredanson** [comment]
i kind of like the button, but it isn't a big deal. Just as long as there is some type of metadat/tracking it should be good.
