### ISSUE TITLE
Missing Chapter count edgecase

### ISSUE THREAD

**Issue by curche** [CarlosEsco/Neko#1410]
### Steps to reproduce

1. Open the manga "School Zone"
2. Observe the chapter

### Expected behavior

Series isn't really missing chapters but did go into Hiatus after recent chapter. And also has some extras (chapter number marked null)

MangaUpdates also looks fine
https://www.mangaupdates.com/series.html?id=148033

### Actual behavior

Series shows up as missing 1920 chapters

![](https://cdn.discordapp.com/attachments/725861216290865314/1094333831609323682/Screenshot_2023-04-08-19-51-50-171-edit_tachiyomi.mangadex.jpg)

### Neko version

2.12.10

### Android version

13

### Device

sm-n770f

### Other details

App version: 2.12.10 (standard, 3c06f7ad4, 185, 2023-04-02T12:55:18.579312)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.N770FXXU8HWC1
Device brand: samsung
Device manufacturer: samsung
Device name: r7
Device model: SM-N770F
Device product name: r7nsxx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by DazXL** [comment]
I see the same happening with Vagabond. I can see all chapters available on the website but the app says 215 missing chapters and I can only start reading from volume 25.

**Comment by CarlosEsco** [comment]
> I see the same happening with Vagabond. I can see all chapters available on the website but the app says 215 missing chapters and I can only start reading from volume 25.

Yours is not an app issue or related to this.  Vagabond only has vol 25 on in english.  On the website you are showing other languages.
