### ISSUE TITLE
[Feature Request] Filter by number of chapters

### ISSUE THREAD

**Issue by shogunreaper** [CarlosEsco/Neko#142]
Would it be possible to add this?

I don't like to start a manga with too few chapters so it would be nice to say search for only ones with 20, 30 or 50+ chapters.

**Comment by CarlosEsco** [comment]
Sort by unread works right?

**Comment by shogunreaper** [comment]
I'm not sure, i haven't used that yet.

why?

**Comment by CarlosEsco** [comment]
If you sort by unread you will see how many chapters to read there are for each manga. It's what the left number on covers is

**Comment by shogunreaper** [comment]
okay well i finally got around to trying this but i don't even see an option for sorting by unread.

i also don't see any numbers on the covers either

https://i.imgur.com/7Tu6AOj.png

**Comment by CarlosEsco** [comment]
Oh you meant in the browse screen. No plans to add this. As it would required extra network calls to get the numbers
