### ISSUE TITLE
Language 

### ISSUE THREAD

**Issue by MfademReal** [CarlosEsco/Neko#1429]
### Describe your suggested feature

It will be great if when I set the language to some language like German, than i could see in browser only  translated Mangas to German 

### Other details

Filter options in browser homepage 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Click the other drop down, then has available chapters checkbox
