### ISSUE TITLE
Unable return to main from manga page

### ISSUE THREAD

**Issue by AsHalt** [CarlosEsco/Neko#1435]
### Steps to reproduce

1. From main page, tap any manga
2. Tap the back button [ <- ] or swipe back

### Expected behavior

Should return to main 

### Actual behavior

Nothing happened, unless _force clear_ or _close_.

### Neko version

2.13

### Android version

13

### Device

S22+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Is there any specific way you are doing this?  I was unable to replicate it

**Comment by irdamulyar** [comment]
This issue appears after browsing multiple mangas for me, so it didnt happen immediately after tapping one manga.

**Comment by AsHalt** [comment]
> Is there any specific way you are doing this? I was unable to replicate it

was just normal browsing library or after reading one... can't say for sure which one tho.

Also it seems that, as per @irdamulyar, it happens somewhat random to me too... tho I somehow get the bug more often than not (tho my storage has been relatively full, like ~99% full, recently. But the previous OTA release was fine)

**Comment by hanahaneull** [comment]
I'm able to replicate it consistently by multi-select any manga and set the category for it.
It doesn't need to set the category for it tho', since just clicking bookmark button already able to make the screen stuck.

https://user-images.githubusercontent.com/48522963/236081359-d2172cf6-267e-43d8-a325-8645e26ac1c4.mp4

**Comment by asdkant** [comment]
This is also intermittently happening to me too. I'm on a Galaxy Tab S5e with Android 11 / OneUI 3.1, Neko is on v2.13
