### ISSUE TITLE
Alt titles are rendered in a single line in tablets

### ISSUE THREAD

**Issue by asdkant** [CarlosEsco/Neko#1437]
### Steps to reproduce

1. Open a manga with alt titles
2. Observe the alt titles list

### Expected behavior

Alt titles should be rendered in multiple lines for better readability

### Actual behavior

Alt titles are rendered in a single (sometimes VERY long) line

### Neko version

2.13

### Android version

11 with OneUI 3.1

### Device

Galaxy Tab S5e

### Other details

This is a problem with overly long titles (things in the style of "I was reincarnated and then this happened, and then that happened, and then other things happened", for example), especially since I only care for the english alt title(s), not the other languages (this may be helped with some configurable language filter for alt titles)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Can you add a screenshot

**Comment by asdkant** [comment]
![Screenshot_20230430-220548_Neko.jpg](https://user-images.githubusercontent.com/3915542/235386657-a83f1ea7-706c-419d-818d-7fc0c52f2aa7.jpg)

**Comment by asdkant** [comment]
I got Neko v2.13.1 which is supposed to incorporate the fix for this, but it keeps showing the alt titles the same way. Is there a configuration somewhere that I have to change?

**Comment by CarlosEsco** [comment]
Changed this to an option in the main appearance settings
