### ISSUE TITLE
[bug] field result is required but it was missing

### ISSUE THREAD

**Issue by henrik9999** [CarlosEsco/Neko#144]
**Describe the bug**
Once an manga is opened a toast message appears with the error shown in the issue title and the tracking now named external tab is empty and doesn't work

**To Reproduce**
1. Go to an manga in your list
2. See error

**Expected behavior**
No error and external tab working

**Screenshots**
![Screenshot_20200203-025554](https://user-images.githubusercontent.com/22085664/73620154-d5f1f580-4630-11ea-8af1-bdab0e375b53.png)
![Screenshot_20200203-025614](https://user-images.githubusercontent.com/22085664/73620163-de4a3080-4630-11ea-9a21-e2d397ba4c58.png)

**Please complete the following information:**
 - Android Version: 9
 - Version 1.6.1

**Comment by CarlosEsco** [comment]
Can you logout then log back in

**Comment by henrik9999** [comment]
I tried relogging in all the trackers on mangadex I get an problem

1. I press on logout
2. I get toast that I'm logged out
3. I click on it to login again I get the choice to logout again

**Comment by Mrfiregem** [comment]
Similar issue, if you go to the external tab on a manga that has a chapter number with a decimal (eg: 19.5), the screen is blank with no way to load (pull down doesn't work). You have to change the value from a float to an integer number for the external tab to show any trackers. Opening the manga from the library list gives the toast `For input string: "19.5"`.

If you first open the tab with the chapter number set to something without decimal, then change it on the site and go back, the toast appears but you can see and edit the trackers

**Comment by CarlosEsco** [comment]
@henrik9999 i forgot the logout was still broken. can you clear cookies.  then login and try,

**Comment by CarlosEsco** [comment]
@Mrfiregem  good to know do you have sample manga that has a 19.5?  i want to see how md handles on their site cause it looks like they only do whole numbers?  unless you know off hand how they handle.

**Comment by henrik9999** [comment]
> @henrik9999 i forgot the logout was still broken. can you clear cookies. then login and try,

i cleared the cookies and logged back in and now it works

**Comment by CarlosEsco** [comment]
i'll need to fix logout
then when result is null like that to toast to logout then back in

**Comment by DoctorPanCakes** [comment]
> @Mrfiregem good to know do you have sample manga that has a 19.5? i want to see how md handles on their site cause it looks like they only do whole numbers? unless you know off hand how they handle.
"komi can't communicate" has some .5 chapters (19.5, 47.5)

**Comment by DoctorPanCakes** [comment]
@Mrfiregem good to know do you have sample manga that has a 19.5? i want to see how md handles on their site cause it looks like they only do whole numbers? unless you know off hand how they handle.

"komi can't communicate" has some .5 chapters (19.5, 47.5)

**Comment by DoctorPanCakes** [comment]
> @Mrfiregem good to know do you have sample manga that has a 19.5? i want to see how md handles on their site cause it looks like they only do whole numbers? unless you know off hand how they handle.

"komi can't communicate" has some .5 chapters (19.5, 47.5)

**Comment by Mrfiregem** [comment]
I don't believe Mangadex tracks floats unless it's typed manually, at least not from my testing, but it still works with them (i.e. increasing to the next chapter). Maybe if the chapter field has a decimal, you can display the floor of the number to prevent the external page from bugging out

**Comment by CarlosEsco** [comment]
Good idea will look into it

**Comment by CarlosEsco** [comment]
changed toast message in 1.6.2
