### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by alidan** [CarlosEsco/Neko#1445]
### Steps to reproduce

it was a few days ago, I forget exactly what I did when the crash happened

### Expected behavior

not crash

### Actual behavior

crash

### Crash logs

![Screenshot_20230505_092933_Neko](https://user-images.githubusercontent.com/2681758/236660327-b05a6e34-3eb6-4017-afe5-cddd41c761d8.jpg)
![Screenshot_20230505_092946_Neko](https://user-images.githubusercontent.com/2681758/236660328-801cc338-64b8-44aa-9f80-c9be8a7aaecd.jpg)
![Screenshot_20230505_092956_Neko](https://user-images.githubusercontent.com/2681758/236660329-a29f57f8-226a-422e-85f8-c1cfee369baf.jpg)

### Neko version

2.13

### Android version

android 13

### Device

galaxy tab s7+

### Other details

sorry I cant give more than the screenshots, I was just reading before I went to sleep and didn't want to deal with it at the time and remembered about it a few days later. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Nothing i can do about this currently, with the given info.  Could be a compose bug or it could be something thats just not showing in that log
