### ISSUE TITLE
Duplicate "Plan to read" sections when grouping by tracking status

### ISSUE THREAD

**Issue by robintourvel** [CarlosEsco/Neko#1449]
### Steps to reproduce

After adding a bunch of manga in the "plan to read" status, I get duplicate "Plan to read"/"Plan To Read" groups.

Both groups contain the same manga mostly. The one with fewer entries contains the subset of manga tracked both on MD and MAL. The one with more entries, has the same plus the ones that are only tracked on MD:

![Screenshot_20230508_171211_Neko](https://user-images.githubusercontent.com/128147437/236862770-8a433b45-40e7-4c52-932a-2fad2301c712.png)

### Expected behavior

No duplicate grouping

### Actual behavior

Duplicate grouping differing only on title casing

### Neko version

2.13.1 (and at least a couple previous ones)

### Android version

Android 11/12

### Device

Samsung S20 FE / Samsung A10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Can you try ungrouping then regrouping

**Comment by robintourvel** [comment]
> Can you try ungrouping then regrouping

Had no effect. I also tried the rest of grouping options and they all work as expected.

**Comment by CarlosEsco** [comment]
What trackers is that one using

**Comment by robintourvel** [comment]
The ones in "Plan to read" are tracked in both MD and MAL. "Plan To Read" contains the same ones plus others only tracked in MD (because they apparently don't exist/can be found in MAL). I don't use any other trackers.
