### ISSUE TITLE
[bug] downloading a chapter mark the chapter as read on mangadex

### ISSUE THREAD

**Issue by zdzc** [CarlosEsco/Neko#145]
**Describe the bug**
When I download a chapter, it automatically marks that chapter as read on Mangadex.

**To Reproduce**
1. Go to series page
2. Download chapter

**Expected behavior**
If I download a chapter, it shouldn't mark the chapter as read.

**Screenshots**
None

**Please complete the following information:**
 - Device: Asus Zenfone Max Pro (M2)
 - Android Version: 9
 - Version 1.6.1

**Comment by CarlosEsco** [comment]
Nothing I can do about this. Mangadex API when logged in is doing this. If I pulled chapters not logged in to prevent this. Blocked groups or chapters that required logging in wouldn't work
