### ISSUE TITLE
Infinite retry button

### ISSUE THREAD

**Issue by speedycatfish** [CarlosEsco/Neko#1452]
### Steps to reproduce

Randomly, when I try reading a chapter, when it loads, it just says retry. I hit retry and nothing happens. I can read other chapters fine, and restarting the app doesn't help (when I reopen the app, that specific chapter is still stuck). So far, the only way I have fixed it is by clearing chapter cache.

https://github.com/CarlosEsco/Neko/assets/12126564/078ed191-69f7-48b7-8ab6-8ce369aa53fc

### Expected behavior

Chapter loads

### Actual behavior

Chapter doesn't load

### Neko version

2.13.1

### Android version

Android 12

### Device

One plus 7t

### Other details

Using Adguard dns

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by Zen341** [comment]
I'm using both Neko and TachiyomiJ2K, I also experience a similar bug on TachiyomiJ2K as well. After a little searching, it seems like there is a somewhat similar issue on Tachiyomi and TachiyomiJ2K (the page loaded but the retry button + open in webview still appear). I believe this is a bug from the original Tachiyomi.

**Comment by CarlosEsco** [comment]
This might get slightly addressed with next release
