### ISSUE TITLE
No search function

### ISSUE THREAD

**Issue by Joooshway** [CarlosEsco/Neko#1455]
### Steps to reproduce

Open up the app
Go to browse

### Expected behavior

Ope app
Go to browse
Clock search function

### Actual behavior

![SmartSelect_20230521_023554_Neko](https://github.com/CarlosEsco/Neko/assets/134214033/4f9b50a4-3300-46b8-bce4-3d88424e6554)

### Neko version

2.13.2

### Android version

13

### Device

Samsung s20 fe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Closing since this was an issue with the one handed UI
