### ISSUE TITLE
Can't save the most recent artwork/cover

### ISSUE THREAD

**Issue by setgafadr** [CarlosEsco/Neko#1474]
### Steps to reproduce

1. Open any comic.
2. Go to Artwork.
3. Press Save.

### Expected behavior

"Cover saved"

### Actual behavior

"Error saving cover"

### Neko version

2.13.3

### Android version

Android 12

### Device

Galaxy Tab A7 Lite

### Other details

I can save other covers but I can't save the most recent cover.
![Screenshot_20230610-074403_Neko](https://github.com/CarlosEsco/Neko/assets/87041762/9db4685f-c355-4eb3-8589-366d25272de0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Can you verify in your Android app settings that neko has file access?  If it does can you try to save a cover than attach an error log from the advanced settings
