### ISSUE TITLE
[Feature Request] Don't update manga if not in your chosen language

### ISSUE THREAD

**Issue by karehaqt** [CarlosEsco/Neko#148]
Hi there

Would it be possible to only show manga updates if they are in your chosen language?  I only read in English, but whenever I see a title has been updated and nothing appears, then it means only the non-English version has been uploaded.

Thanks in advance.

**Comment by CarlosEsco** [comment]
If you are talking about in the browse screen. Can you try going to your mangadex account and hiding other languages. Then see if they works?  If not there is nothing I can really do currently. The search in mangadex doesn't show chapters that were updated so I can't filter out manga without making extra network calls

**Comment by karehaqt** [comment]
Hi there

Setting the language to English in Browse works great, would it be possible then to set the Browse language to always default to your chosen language, rather than having to manually set it all the time?

**Comment by CarlosEsco** [comment]
thats a site setting on mangadex isnt it?  I figured it would persist through out login
