### ISSUE TITLE
mininum/no gap between chapters in webtoon mode

### ISSUE THREAD

**Issue by betengQ** [CarlosEsco/Neko#1488]
### Describe your suggested feature

Example from mangadex:
![Screenshot_20230703_092918_com android chrome_edit_174396603872867](https://github.com/CarlosEsco/Neko/assets/51523617/7ebbff5d-43f0-4b1b-8f9c-e4db00c83b35)
Example from tachiyomi:
![Screenshot_20230703_092837_eu kanade tachiyomi_edit_174417294879114](https://github.com/CarlosEsco/Neko/assets/51523617/e16cf2d6-b969-4a93-803c-9929d3e39c03)
Beside in neko:
![Screenshot_20230703_113435_tachiyomi mangadex_edit_174491553966082](https://github.com/CarlosEsco/Neko/assets/51523617/22c364d3-dc33-42eb-bce0-582e131ade29)

### Other details

i try the vertical reading mode but it didn't suit me, try to adjust the setting but still. Perhaps you can give me solution

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
The gap size there is intentional to break up the page noticeably.
