### ISSUE TITLE
[enhancement] move the "edit category" option

### ISSUE THREAD

**Issue by Mechanical-sanity** [CarlosEsco/Neko#150]
**Is your feature request related to a problem? Please describe.**

Move the "edit category" option to the library page. It would be alot more convenient 

**Describe the solution you'd like**

The option would be moved to the 3 dot menu.

**Describe alternatives you've considered**

**Additional context**

**Comment by CarlosEsco** [comment]
it will be staying in the library settings to prepare for a bottom navigation future.
