### ISSUE TITLE
Crash on startup, due to AbstractMethodError on logcat method [2.13.4]

### ISSUE THREAD

**Issue by DoubleNom** [CarlosEsco/Neko#1504]
### Steps to reproduce

Immediate crash when starting the app.

Also happen when pressing the "share logs" action button on notification.

### Expected behavior

The app should be able to start

### Actual behavior

The app crash immediately after quitting the splash screen, prompting the user that an unexpected error occurred.

"Dump crash Logs" button works, popping a notification. On that notification, it is possible to open the log but sharing it also crash the app.

"Restart the application" button works, but the app immediately crash.

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/12286158/neko_crash_logs.txt)

### Neko version

2.13.4

### Android version

Android 13

### Device

Google Pixel 6

### Other details

I tried various thing before reporting this issue.
- Flushing the app cache from android menu,
- Force closing the app from android menu,
- Restarting cellphone,
- Changing network connection (wi-fi, cellular, removing ad-guard dns) (bit random, read firebase, thought it could be a network issue).

I did not tried erasing app data as my last backup is a bit old but will do if requested.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Should be fixed in 2.13.5
