### ISSUE TITLE
[bug] some mangas say they havd no chapters

### ISSUE THREAD

**Issue by Mechanical-sanity** [CarlosEsco/Neko#151]
**Describe the bug**

Some mangas dont load chapters and just says they're empty 

**To Reproduce**
1. Go to 'mob psycho 100'
2. Open it
3. See error

**Expected behavior**

It should have shown a chapter list

**Screenshots**

**Please complete the following information:**
 - Device: samsung galaxy s8
 - Android Version: 9
 - Version 1.6.4

**Additional context**

**Comment by CarlosEsco** [comment]
Are you logged in?

Also have you tried going to the chapter list and swipe down refresh. It shows for me no issue

**Comment by Mechanical-sanity** [comment]
Try the yaoi manga "psycho" that also doesnt work. Or the unordinary webtoon.

**Comment by Mechanical-sanity** [comment]
And yes, I tried it

**Comment by CarlosEsco** [comment]
Do you have settings on the website potentially blocking?

**Comment by CarlosEsco** [comment]
Also psycho has no English chapters. So I don't know what you are expecting there
