### ISSUE TITLE
Chapters Not Syncing to Mangadex

### ISSUE THREAD

**Issue by itsaferbie** [CarlosEsco/Neko#1512]
### Steps to reproduce

1. Read a chapter of a manga using Neko.
2. Sync your library.
3. Go to Mangadex to see the chapter still have the eye icon

### Expected behavior

It should complete the chapter and make the eye have a line through it.

### Actual behavior

The eye still shows as if you did not read the chapter.

### Neko version

2.13.5

### Android version

Android 13

### Device

Google Pixel 7 Pro

### Other details

Here is a few images to help with this. I also cleared my cache, cookies, and signed out and back in to see if it would resolve.

I read Kaette Kudasai! Akutsu-san from Volume 4 to 5, and Volume 4 did not get read at all, while Volume 3 and 5 did.

It also read the last two chapters from this volume also.

This also happened with Ijiranaide, Nagatoro-san and a few others.

[Volume 4](https://files.catbox.moe/arlqfg.png)

[Volume 3 and 4](https://files.catbox.moe/rvxv3h.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Syncing Library does nothing with read markers.  You should have 'auto sync read status' enabled, and then read the chapter.  If you want to sync an older one it needs to be marked unread and then marked read.  Finally it can take a few minutes for the front end of Dex to have the correct read status after neko marks it.

**Comment by itsaferbie** [comment]
Auto Sync is enabled, and these read chapters are from a few days old.

I do notice, that one duplicate chapters (two groups), that I marked one of them as read and the chapter is not showing as read on Mangadex, however this occurs with the same group, as per my two screen shots. Those chapters are from reading on Thursday.

If there are some other steps that I could try, I wouldn't mind giving them a go, as I noticed this happened with another manga. And this hasn't been read for a few months now.

[Image](https://files.catbox.moe/8op70d.png)

Let me know your thoughts.

**Comment by CarlosEsco** [comment]
Have you verified you're not logged out on Neko?  Also that the entry has the bell checkmark on Dex?

**Comment by itsaferbie** [comment]
Yep, when I click on the option for sign in, it says Cancel or Log Out.

And I see the check next to the bell on Dex.

**Comment by CarlosEsco** [comment]
What is the reading status of the entry?  Can you manually swipe it unread then read and check the site after 5 mins

**Comment by itsaferbie** [comment]
It shows as reading, if I mark as unread then read, it does update the listing. I will keep an eye out for more of these next week as I read though more of my backlog.

**Comment by itsaferbie** [comment]
It appears to be working as intended now. If I notice it acting up again I will take note of the issues and steps to reproduce.
