### ISSUE TITLE
"Currently blocked scanlators" setting is always hidden

### ISSUE THREAD

**Issue by solntcev** [CarlosEsco/Neko#1524]
### Steps to reproduce

Open mangadex settings

### Expected behavior

"Currently blocked scanlators" setting is available

### Actual behavior

Setting dissapears on opening mangadex settings page

### Neko version

2.13.5

### Android version

Android 8

### Device

Google Nexus 7 emulator

### Other details

[Screen_recording_20230829_230645.webm](https://github.com/CarlosEsco/Neko/assets/1001265/9b04e542-8512-4550-bb9b-703459bb25ce)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
It probably shouldn't show on the search. It disappears because there are no blocked scanlators

**Comment by solntcev** [comment]
I thought that this setting used mangadex "block list". As I have some uploaders blocked, I was looking for them in Neko.

Rather then hide, better to left setting as is but if list is empty show popup "you can block groups in chapter context menu".

**Comment by CarlosEsco** [comment]
Yea neko doesn't implement or sync mangadex site blocks
