### ISSUE TITLE
Sync mangadex library to tracker on import/add a button to do it

### ISSUE THREAD

**Issue by Luminous-Journey** [CarlosEsco/Neko#1525]
### Describe your suggested feature

there should be a button to sync your mangadex library to a tracker or it would happen on importing it instead of having to click on every single manga in the app

### Other details

doing it by hand is really time consuming and irritating

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
The reason you have to click in is to limit the network calls and speed up the sync.   To get the tracker information for a manga would require an extra network call to Dex per a manga in your list + the ones to the trackers to add them. This is fine for small syncs but would take forever in a lot of scenarios
