### ISSUE TITLE
Webtoon Support

### ISSUE THREAD

**Issue by aravindchow** [CarlosEsco/Neko#1562]
### Describe your suggested feature

Just wondering what the capabilities are for adding Webtoon support to Neko. To be honest, this is more of a question than a feature request.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Webtoon like the site?  Or the reader mode

**Comment by aravindchow** [comment]
Webtoon like the site. There's a lot of media which only Webtoon provides. Again, idk if it's even possible considering the integration Neko has with mangadex

**Comment by CarlosEsco** [comment]
No plans to add that as a merged source
