### ISSUE TITLE
[Feature Request] Sync Library to MangaDex Follows

### ISSUE THREAD

**Issue by Luklek** [CarlosEsco/Neko#158]
If I add a new manga to my Library in Neko, it isn't also added to my Follows in MangaDex.

would be possible to sync newly added Library titles to MangaDex Follows?

**Comment by CarlosEsco** [comment]
As of right now no.  

When i do this eventually #53  I will make 1 property to auto link/sync or not

**Comment by CarlosEsco** [comment]
there is a manual option for a the past version or so.  Long press the manga you want to add in the library then go to 3dot menu and click sync to mangadex
