### ISSUE TITLE
Only show origin + english lang when merge searching

### ISSUE THREAD

**Issue by hanahaneull** [CarlosEsco/Neko#1584]
### Describe your suggested feature

When merging source only filter language that are from the origin country + english. Since the bar are kinda small + having horizontal scroll, It's kinda inconvenience to scroll.

Since manga4life and toonily are english source, I think only filtering specific language help narrow down the choice for source merging.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
So I don't store the language of the alt titles, what i have adjusted the ui a tad to make it a bit easier
