### ISSUE TITLE
Why i can't search any manga

### ISSUE THREAD

**Issue by blackpearl21x** [CarlosEsco/Neko#159]
I can't search any manga , a notification no results found show in bottom , when i click retry nothing change

**Comment by CarlosEsco** [comment]
can you clear your cookies in advanced settings then relogin

**Comment by blackpearl21x** [comment]
Still can't search

**Comment by blackpearl21x** [comment]
![Screenshot_20200320-194811](https://user-images.githubusercontent.com/48041537/77164906-d14fa680-6ae3-11ea-9946-318a001bdbff.png)

**Comment by CarlosEsco** [comment]
if this was a new account did you activate it after signing up?

**Comment by blackpearl21x** [comment]
It work , thanks
