### ISSUE TITLE
Configure 'Similar Manga' Update Period

### ISSUE THREAD

**Issue by wopian** [CarlosEsco/Neko#160]
There is currently no option to change when the app redownloads the 20 MB file. I infrequently add new manga so it doesn't make sense to redownload it every 24 hours in my case.

Weekly/Monthly would probably be enough for most users.

**Comment by CarlosEsco** [comment]
not configurable but is now 3 days later.  Will reevaluate at a future date if it should be longer

**Comment by wopian** [comment]
3 days is still pretty excessive for a 20 MB payload.

**Comment by CarlosEsco** [comment]
This has been updated with more options
