### ISSUE TITLE
Can Mangaupdates' custom lists be imported, or is it just the default ones?

### ISSUE THREAD

**Issue by Tenome** [CarlosEsco/Neko#1624]
### Describe your suggested feature

Edit: Now that I look over it again, it looks like it can only sync from MD/your library to MU, not the other way around.

New user here. I'm basically trying to migrate a custom MU list I have (for partial scanlations) to MD/Anilist/etc. Even to just an MDList would be helpful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Currently no

**Comment by Tenome** [comment]
Damn, oh well. I don't think there's any good way to migrate MU -> MD anymore since SyncDex stopped working.
