### ISSUE TITLE
[bug] Scoring issue (tracking)

### ISSUE THREAD

**Issue by emptypacket** [CarlosEsco/Neko#163]
**Describe the bug**
If I change a score on AniList and don't go into Neko and refresh the tracking tab manually, the next time I read it, the score gets reset after the chapter updates because Neko still thinks I haven't changed the score yet (since I haven't manually updated the tab).

**To Reproduce**
I made a short clip to demonstrate how to reproduce this issue:
https://youtu.be/_jMUfk5suE4

**Expected behavior**
After changing the score on AniList, I expected it to update on Neko without having to manually refresh the tracking tab every time (I change my scores very frequently and don't really think about doing this. I suggest allowing Neko to check AniList in the background for tracking. Maybe something similar to auto library updates but with tracking tab?

**Screenshots**
N/A (made a clip)

**Please complete the following information:**
 - Device: Samsung Tab S5E
 - Android Version: The latest ver for my device (I don't know how to name it)
 - Version: Neko ver. 1.7.2 

**Additional context**
N/A

**Comment by CarlosEsco** [comment]
fixed in 2.0
