### ISSUE TITLE
[enhancement] sync chapter read to mangadex and back

### ISSUE THREAD

**Issue by CarlosEsco** [CarlosEsco/Neko#166]
related to #131 

1.  Dont mark chapters read when downloading them/reading chapter is finished
2.  sync down read status from mangadex when possible and auto mark the chapters read 

this will allow neko to be used on multiple devices and web and have a psuedo sync

**Comment by asdkant** [comment]
When I mark a chapter as unread, it doesn't sync back to mangadex so neko marks it back as read. @CarlosEsco should I open a separate issue for this?

**Comment by CarlosEsco** [comment]
There is no current api to unmark a chapter read.  Which is why Neko doesn't mark a chapter read yet either.  I didn't want it to be a 1 way thing.

**Comment by CarlosEsco** [comment]
In 2.5.0
