### ISSUE TITLE
[enhancement] Automatically  add manga to 'reading' on anilist

### ISSUE THREAD

**Issue by Wiz1991** [CarlosEsco/Neko#167]
Currently  there is an option to sync your reading progress to AniList and it works well, however it requires the user to add the manga to his reading list on Anilist in order to sync. Hence my suggestion. Following a certai  criteria, either to have read at least a few chaptera or to be up to date, anything the user chooses, the all will automatically add that manga to the reading list and start syncing the progress.

**Comment by CarlosEsco** [comment]
renamed #53 to be more generic but the plan is for all trackers with ids to have option at some point
