### ISSUE TITLE
[enhancement] set the app from right to left - to - left to right

### ISSUE THREAD

**Issue by omriry** [CarlosEsco/Neko#168]
**Is your feature request related to a problem? Please describe.**
The default language on my phone is written from right to left so I have to use the app from right to left, that okay and all but because of that when I want to click on a chapter to read it just uses the scroll and the information tab looks a little bit weird.

**Describe the solution you'd like**
Add an option to set the app to be left to right

**Comment by CarlosEsco** [comment]
try 2.0 it should be better hopefully
