### ISSUE TITLE
[Feature Request] Library Updates: Option to open manga's page, not the latest chapter

### ISSUE THREAD

**Issue by InitialDet** [CarlosEsco/Neko#171]
As said in the title, is it possible to add a option to open de manga chapter list, instead of the chapter itself when using the "Library Updates" tab? I usually like to check the date and wich scanlator did the chapter before reading it, or even go back and read old chapters before the latest. Thank you!

Edit: Sorry, i may have choose the wrong Tag (i think i should be enhancement).

**Comment by CarlosEsco** [comment]
The new ui that i am working on wil have this option.  Will close this once its released

**Comment by arkon** [comment]
You can also tap the cover image.

**Comment by CarlosEsco** [comment]
That too
