### ISSUE TITLE
Sort by Last updated not working[bug]

### ISSUE THREAD

**Issue by franzbuenaventura** [CarlosEsco/Neko#172]
**Describe the bug**
Sort by Last updated is not working, or at least what I think it should do. 
Correct me if I'm wrong but Sort By Last updated should sort based on the last chapter that got updated (similar to Library Updates but per manga instead of per chapter) 

**To Reproduce**
1. Go to 'My Library'
2. Click on 'Funnel' to Sort by 'Last updated'
3. Scroll down to each manga and check the last chapter date
4. See that it is not consistent for each manga and dates are all over the place

**Expected behavior**
The manga are sorted by the last date it got updated (the date of the last chapter uploaded) 

**Please complete the following information:**
 - Device: [V40]
 - Android Version: [Android 10]
 - Version [e.g. 1.7.2]

**Additional context**

**Comment by CarlosEsco** [comment]
I would need screens cause checking my library it's working as designed. It's possible also a series uploaded an older chapter recently which would mess up the sort

**Comment by franzbuenaventura** [comment]
I think you are right and it might be something to do when a recent Sync with Mangadex. 
I notice that Manga that got recently sync would go directly at the top until the other manga actually gets updated. 
So I believe when they get sync from Mangadex they are considered updated. 

Which is fine in my use case of checking which manga had recently updated in my library. 

Cheers and thanks for the great work,

Justin B

**Comment by ekmz** [comment]
[1.7.2 / galaxy s7 / android 8]

I don't know if it's okay to add to this, but this is also how I have my library set up.

This is a pic from yesterday (4/27). The red outlines indicate manga with updates on 4/27. The ones with no outlines were updated the day before (4/26), or on previous days. The last manga with a blue '?' was updated on 4/16. It's like this throughout my list where it places the recently updated in weird spots, but above the halfway point (out of ~300). It's very inconsistent and random on where they are placed.

Even if I favorite the most recently updated manga, it will show up somewhere in my library, but not first where it should be and updating the library doesn't help in that regard.

I don't normally read a whole lot of manga, but this is just what I've noticed.

![InkedScreenshot_20200427-171357_Neko_LI](https://user-images.githubusercontent.com/4386321/80546956-0245b580-8985-11ea-84d5-bcc1a16d435a.jpg)

**Comment by CarlosEsco** [comment]
@ekmz can you verify that there are not chapters that made be older in number but a newer date.  For example. Maybe the current chapter is 20 with a date of March but chapter 10 was added yesterday. 

The sort is by lastest chapter date. Not latest chapter's date

**Comment by ekmz** [comment]
Sorry, I've never used 'latest chapter's date' before, so I'm only going by which chapter was last updated. But yes, I did check for this occasion and did not come across any manga that had earlier chapters added.

**Comment by CarlosEsco** [comment]
Assuming the first screen had sort by last update enabled. Can you send me the name of the blue manga also

**Comment by ekmz** [comment]
Zannen Jokanbu Black General-san by Jin (mugenjin)

**Comment by CarlosEsco** [comment]
compared some of your manga against the next release and they are sorted correctly, checked against current release they are not.  So will be fixed in next release

**Comment by CarlosEsco** [comment]
fixed in 2.0
