### ISSUE TITLE
[bug] Chapters that were added not showing up in app

### ISSUE THREAD

**Issue by KShivum** [CarlosEsco/Neko#175]
So I'm relatively new to the app, but when I go to browse and see that a manga that I have in my library has had a new chapter added, no new chapter show up in the chapter tab. However, if I go to Mangadex itself it shows the new chapter(s) and is readable. A side effect of the bug is that even though it shows that a new chapter has been added, it doesn't show in the library updates tab.

Do I need to refresh the listings or something?

I'm on a Samsung S8 Plus on Android version 8.0.0 using Neko Version 1.7.2

**Comment by CarlosEsco** [comment]
Assuming they were in English then you had to swipe refresh the chapter last in neko

**Comment by KShivum** [comment]
Yeah, refreshing it causes it to load the chapters and show up in recently updated. Also yes, I am in English

**Comment by CarlosEsco** [comment]
Yea the way the app works is it loads whatever is in db from the last library update. So enable library updates in settings so they get updated somewhat frequently. If you clicked into manga but didn't add. Next time you click into in say 2 weeks will need to be manually updated or you could clear db in advanced settings
