### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by NicRoyal** [CarlosEsco/Neko#176]
**Is your feature request related to a problem? Please describe.**
I'm frustrated looking for manga in the app. I have to specifically search for the manga I want to read. 
Eg. A friend reccomends a series, and links to the Mangadex page. I have to search for that specifically in Neko instead of it linking to the app. 

**Describe the solution you'd like**
Links to a mangadex page/manga being directed to the Neko app for that manga. 

**Additional context**
Tachiyomi has this ability for its sources. Unsure if collaboration or implementation could be copied to Neko.

**Comment by CarlosEsco** [comment]
Plans to have that eventually for time being if you take the number in the url you can search Id:###

**Comment by NicRoyal** [comment]
Thank you so much. That helps considerably!

**Comment by CarlosEsco** [comment]
done in 2.0
