### ISSUE TITLE
[Feature Request] Mark manga as complete

### ISSUE THREAD

**Issue by kelvinice** [CarlosEsco/Neko#177]
**Is your feature request related to a problem? Please describe.**
App will notice if you already read the latest chapter of the manga, and Mark a manga as complete, or dropped, both in neko app and in mangadex web(sync) and remove from favorite in neko app(so neko app won't have to search for manga update).

**Describe the solution you'd like**
Every time we read a chapter to last page, check if manga is already complete and its a last chapter of the manga.

**Describe alternatives you've considered**
A button to mark a manga as complete/dropped, and remove from favorite in neko app.

**Additional context**
Maybe call mangadex API to mark that manga as complete, then remove from favorite.

**Comment by CarlosEsco** [comment]
are you talking about from the  website -> neko?   If you finish a manga in neko you can  swipe to the external tab mark the mdlist as complete then swipe back and unfavorite the manga

**Comment by kelvinice** [comment]
> are you talking about from the website -> neko? If you finish a manga in neko you can swipe to the external tab mark the mdlist as complete then swipe back and unfavorite the manga
Yes, I already done it like that before. 

I just think it will be nice to have one button in the app to do that, or automatically done when I finish read the last chapter :D

**Comment by CarlosEsco** [comment]
I don't have plans to auto remove from library.  However it should not mark the mdlist as complete in most scenarios when a manga is finished.
