### ISSUE TITLE
[Feature Request] Comments/rating addition/port please?

### ISSUE THREAD

**Issue by guppynk** [CarlosEsco/Neko#179]
I'd really like if a comments/rating section is added to the app. Could be per chapter or the manga overall. I used to read manga from the mangazone app before migrating briefly to tachiyomi, and then to mangarock. The mangazone app had a comments section which would build a sense of community among readers, and I haven't seen that in any manga reader app since mangazone. The mangadex base website already had a rating system and comments section, and you could just port it to the Neko app or maybe create a standalone rating/comments section, either is fine. Since Neko acts as a mangadex reader, I believe the comments feature would differentiate it from the tachiyomi app. Thanks for reading, I'll be waiting for what's more to come from your app.

**Comment by CarlosEsco** [comment]
to rate you can open the manga in webview and rate there.  As for comments it already viewable by long pressing the chapter and then clicking the 3 dot at top -> view comments
