### ISSUE TITLE
Search Filter Bottom Bar Padding

### ISSUE THREAD

**Issue by goldbattle** [CarlosEsco/Neko#181]
### Device information
* Tachiyomi version: 6c1c60651a78b533a7c27b7f828036faa6bce36d
* Android phone & version:  Emulator Pixel 2 API 27

### Expected behavior
Should be able to click the my follows and random manga button (see bottom of screenshot).

![image](https://user-images.githubusercontent.com/2222562/80850954-b6954500-8bec-11ea-9c60-ca7bd6873011.png)

**Comment by CarlosEsco** [comment]
fixed in 2.0.3
