### ISSUE TITLE
[Bug] Downloaded chapter marked as read in MangaDex

### ISSUE THREAD

**Issue by kelvinice** [CarlosEsco/Neko#184]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app
---

## Steps to reproduce
1. Download a chapter in neko app
2. Check that chapter in Mangadex

### Expected behavior
Only marked as read when you already finish read that chapter.

### Actual behavior
Its already marked as read, even though just downloaded, and not read it yet.

### Other details
All downloaded chapter marked as read.
![image](https://user-images.githubusercontent.com/22559340/80855455-8c369c80-8c6b-11ea-98b7-d1fb3bc5f915.png)

Reading progress is display a right last read chapter.

![image](https://user-images.githubusercontent.com/22559340/80855517-f18a8d80-8c6b-11ea-9738-b0757e4cd344.png)

Thanks

**Comment by CarlosEsco** [comment]
Nothing i can do about to for now as its part of their api... You can enable do not mark website chapters read in settings, only downside with that is there are a few restricted manga that require login.  Eventually i plan for this #166
