### ISSUE TITLE
[Bug] Manga Thumbnail in favourites 

### ISSUE THREAD

**Issue by aouda6** [CarlosEsco/Neko#185]
After an unread chapter is read and a user returns to their library, the thumbnail for that manga no longer appears in line with the rest of the thumbnails. 

It also still shows the unread chapter number in top left corner. 

When scrolling down the library, this thumbnail detaches from its position and follows you as you scroll, appearing behind other thumbnails.

This issue can be fixed by removing the previously enabled filters at the bottom.

**Comment by CarlosEsco** [comment]
Can you share a screen

**Comment by aouda6** [comment]
New chapter update arrives:

![Screenshot_20200502_132554_tachiyomi mangadex](https://user-images.githubusercontent.com/22624539/80871127-e8ec8400-8c78-11ea-8fb8-1cbf6836b879.jpg)

New chapter update is read, then:

![Screenshot_20200502_132731_tachiyomi mangadex](https://user-images.githubusercontent.com/22624539/80871128-ea1db100-8c78-11ea-8157-5170a61ba4bc.jpg)
![Screenshot_20200502_132741_tachiyomi mangadex](https://user-images.githubusercontent.com/22624539/80871129-eab64780-8c78-11ea-9e45-00defd12ecb3.jpg)
![Screenshot_20200502_132752_tachiyomi mangadex](https://user-images.githubusercontent.com/22624539/80871132-ebe77480-8c78-11ea-9b7e-659d88d81410.jpg)
![Screenshot_20200502_132825_tachiyomi mangadex](https://user-images.githubusercontent.com/22624539/80871133-ec800b00-8c78-11ea-80ed-1b0d7aae5c97.jpg)

**Comment by CarlosEsco** [comment]
should be fixed in 2.0.3 if not reopen ticket
