### ISSUE TITLE
[Bug] Distorted thumbnails in library view when opened in split-screen mode

### ISSUE THREAD

**Issue by BraveDude8** [CarlosEsco/Neko#186]
### Device information
* Tachiyomi version: Neko 2.0.0
* Android phone & version: Asus ROG Phone II, Android 9

## Steps to reproduce
Not entirely reliable, but this has caused it twice now;
1. Have a split screen view with YouTube on top and another app on the bottom, then switch to Neko (with a chapter open)
2. Back out to the Library page

### Expected behavior
Normal appearance.

### Actual behavior
It looks like the normal library view but with a second page's worth of images added behind everything and slighly offset. See attached images.
![neko bug 1](https://user-images.githubusercontent.com/36118719/80873177-a47bdb00-8cae-11ea-9c96-d9b0737dafdc.jpg)
![neko bug 2](https://user-images.githubusercontent.com/36118719/80873181-a776cb80-8cae-11ea-817a-f6bc7ca77e84.jpg)

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
should be fixed in 2.0.3 if not reopen ticket
