### ISSUE TITLE
[Bug] Neko is calling manhua manhwa

### ISSUE THREAD

**Issue by henrik9999** [CarlosEsco/Neko#188]
### Device information
* Neko version: 2.0.2
* Android version: 9

## Steps to reproduce
1. Go to Chinese manhua 
For example https://mangadex.org/title/16069

### Expected behavior
It should say "About this manhua"

### Actual behavior
It says "About this manhwa"

### Additional
Manhwa = south korea
Manhua = Chinese

**Comment by CarlosEsco** [comment]
Nice catch will address for next release

**Comment by CarlosEsco** [comment]
fixed in 2.0.3
