### ISSUE TITLE
[Bug] Reading a chapter causes the app to crash.

### ISSUE THREAD

**Issue by ThreeFold** [CarlosEsco/Neko#189]
### Device information
* Tachiyomi version: 2.0.2
* Android phone & version: Android 10 on Samsung note 10

## Steps to reproduce
1. Open downloaded unread chapter
2. Get to end of chapter screen

### Expected behavior
Open the menu and page picker to either go back to the previous view or do other various reading mode things.

### Actual behavior
Crashes the app

### Other details
Manga it failed on:
* https://mangadex.org/manga/24249/ ch 101
* https://mangadex.org/manga/26483/ ch 21

Theme: system default (White + Black)
Reader Mode: Vertical
Rotation: Force Portrait
Background color: black
Scale: Fit Screen
Zoom start: Automatic
Both are being tracked on AniList and MD

**Comment by CarlosEsco** [comment]
should be fixed in 2.0.3 if not open a new ticket
