### ISSUE TITLE
[Bug] Anilist `jsonnull` when title of manga is really long.

### ISSUE THREAD

**Issue by jaredanson** [CarlosEsco/Neko#190]
### Device information
* Tachiyomi version: 2.0.2
* Android phone & version: Pixel 2 XL & Android 10

## Steps to reproduce
1. have anilist tracking enabled
2. In the library click on a manga whose title is very long. In the reading view, the title needs to be long enough that it still doesn't show up and requires an ellipsis.
3. click the button next to the heart that lets you change stuff about mangadex and anilist.
4. Click to add anilist tracking for this manga, and you get a `jsonnull` message.

### Expected behavior

it should be able to find the manga.

### Actual behavior

you get the error message and a loading spinner appears until you click cancel.

### Other details

if you try modifying the search in the anilist popup, it doesn't fix the issue, you just get `jsonnull` when you submit a new search.

**Comment by jaredanson** [comment]
It also does it on `Release That Witch` oddly enough, which isn't a long title and doesn't cause an ellipsis.

**Comment by henrik9999** [comment]
I also saw that sometimes anilist descriptions have the HTML tags in it

**Comment by CarlosEsco** [comment]
fixed in 2.0.3

**Comment by jaredanson** [comment]
thanks
