### ISSUE TITLE
[Similar feature bug] phone crashes when downloading the similar feature

### ISSUE THREAD

**Issue by anjinghunter** [CarlosEsco/Neko#193]
### Device information
* Tachiyomi version: neko 2.0.3
* Android phone & version: asus zenfone 3max ZC520TL android 7.0

## Steps to reproduce
1. Press 'similar manga' or 'pull latest database'
2. Around the second half of the download bar it crashes

### Expected behavior
Similar feature installed(download bar full)

### Actual behavior
Phone crashes. "System ui not responding" notice, phone auto restarts.

### Other details
![Screenshot_20200504-225950_1](https://user-images.githubusercontent.com/64697104/80990582-20ba1e00-8e69-11ea-8677-0cb7bc337dc5.jpg)

**Comment by CarlosEsco** [comment]
does this happen when you try again?

**Comment by anjinghunter** [comment]
Tried again and again. Results ate the same. I even uninstalled it then installed it again but no luck

**Comment by CarlosEsco** [comment]
try in 2.0.11 and reopen if you have same issue
