### ISSUE TITLE
[Bug] apk not installing

### ISSUE THREAD

**Issue by Trxkzz** [CarlosEsco/Neko#194]
---

### Device information
* Tachiyomi version: Neko v2.0.3
* Android phone & version: HTC M9+, Android 6.0

## Steps to reproduce
1. Download the app.
2. Install the app.

### Expected behavior
The app should install and work properly. 

### Actual behavior
Error when opening the apk file; not installing.

### Other details
![Screenshot_20200505-053400_1](https://user-images.githubusercontent.com/64820677/81030857-0137eb00-8e93-11ea-92dc-60bec2ce903b.jpg)
![Screenshot_20200505-053758_1](https://user-images.githubusercontent.com/64820677/81030860-04cb7200-8e93-11ea-9844-4138398a8751.jpg)

**Comment by CarlosEsco** [comment]
There was an issue with the release notes. 2.0+ only supports android 7

**Comment by Trxkzz** [comment]
Got it.
Thank you! :)
