### ISSUE TITLE
[Bug] Ocassionally when you finish a chapter and go to the next, it will jump to the last page of the next chapter instead of the beginning.

### ISSUE THREAD

**Issue by jaredanson** [CarlosEsco/Neko#195]
### Device information
* Tachiyomi version: 2.0.2
* Android phone & version: Pixel 2 XL and Android 10

## Steps to reproduce
1. be reading a manga with at least once chapter left to read
2. finish current chapter and swipe to start the next one
3. occasionally it will jump to the end of the next chapter instead of the beginning

### Expected behavior
it should load the next chapter and be at the beginning

### Actual behavior
occasionally it will jump to the very last page.

### Other details

this behavior seems pretty random, i've only had it happen to me 5-6 times in the past 2 days.

this might have nothing to do with it, but it always seems to happen when the next chapter loads instantly or very quickly as opposed to when it takes a while.

i thought at first it was that i had just swiped multiple times and that the chapter was only a few pages long, but i then experienced it again with a chapter that was over 30 pages and I definitely didn't swipe 30 times.

**Comment by jaredanson** [comment]
i have check for updates on, but my phone decided 20 seconds after I posted this to inform me there is a new version. I thought 2.0.2 was the most recent when i posted this.

I'll try the new version, and see if it still continues but it happens pretty random.

I see `bug fixes` listed in the release notes, but was this known about?

**Comment by CarlosEsco** [comment]
yes.  i pull in any bug fixes and changes that jay releases and this was a known issue.
https://github.com/Jays2Kings/tachiyomiJ2K/releases

**Comment by CarlosEsco** [comment]
If its not addressed then reope
