### ISSUE TITLE
[Bug] Happened again on newest version -- Ocassionally when you finish a chapter and go to the next, it will jump to the last page of the next chapter instead of the beginning.

### ISSUE THREAD

**Issue by jaredanson** [CarlosEsco/Neko#196]
### Device information
* Tachiyomi version: 2.0.3
* Android phone & version: Pixel 2 XL and Android 10

## Steps to reproduce
1. be reading a manga with at least once chapter left to read
2. finish current chapter and swipe to start the next one
3. occasionally it will jump to the end of the next chapter instead of the beginning

### Expected behavior
it should load the next chapter and be at the beginning

### Actual behavior
occasionally it will jump to the very last page.

### Other details

happened on 2.0.2 and 2.0.3

this behavior seems pretty random, but consistently will happen if you read enough. i've only had it happen to me 6+ times in the past 2 days or so.

this might have nothing to do with it, but it always seems to happen when the next chapter loads instantly or very quickly as opposed to when it takes a while.

i thought at first it was that i had just swiped multiple times and that the chapter was only a few pages long, but i then experienced it again with a chapter that was over 30 pages and I definitely didn't swipe 30 times.

**Comment by jaredanson** [comment]
@CarlosEsco just had it happen a few minutes ago on the most recent version, so i created the issue again.

**Comment by CarlosEsco** [comment]
Pulled some more upstream fixes try 2.0.4 and let me know

**Comment by jaredanson** [comment]
@CarlosEsco i see that there was a release for 2.0.4 but the app is crashing when i click on the version to make it manually check for updates. Don't know if that is specific to me or another bug.

**Comment by CarlosEsco** [comment]
I removed APK. Try now there is 2.0.5. I saw a bug I needed to fix

**Comment by jaredanson** [comment]
i was able to download 2.0.5 ill check it out and see if it continues

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi/issues/3104

looks to be potential upstream issue

**Comment by jaredanson** [comment]
hmm that isn't exactly the behavior i'm talking about. theres seems to be a save progress issue, whereas the one i'm seeing is when you finish and chapter and start a new it jumps to the end of the new chapters. it could be related, but not sure.

**Comment by jaredanson** [comment]
@CarlosEsco I just had it happen on 2.0.5

I've been busy the past few days, so I haven't been reading as much. But it just happened.

**Comment by CarlosEsco** [comment]
fingers crossed jay is hoping its fixed.  so try on 2.0.6 and let me know
