### ISSUE TITLE
Unable To Add Tracking For Manga

### ISSUE THREAD

**Issue by Kenshina** [CarlosEsco/Neko#197]
Good Morning,
Just download Neko and add all my manga I had from the regular Tachiyomi manually. I signed into all three tracking services. Then I went to a few different manga and tried to do add tracking. Every manga I have tried I get a spinning circle and nothing comes up. Regular Tachiyomi has no issues with adding tracking to new manga I doubled check that.

### Device information
* Tachiyomi version: 2.0.5
* Android phone & version: Tried it on both Galaxy Tab A Android Version 9 and Google Pixel 4 XL Android Version 10. 

## Steps to reproduce
1. Select a manga in library. 
2. Click that button at the top under the image that brings up the three tracking services at the bottom.
3. Click add tracking

### Expected behavior
After clicking add tracking the manga should appear and you click it to add tracking 

### Actual behavior
The loading circle never stops spinning.

### Other details
I am going to try different things to fix it myself and if something works I'll comment.

**Comment by CarlosEsco** [comment]
Just checked seems to be a real issue.  Will probably do a release with some more but fixes

**Comment by Kenshina** [comment]
Ok in a way that's good to know it isn't on my side, thank you for such a quick response.

**Comment by jaredanson** [comment]
i just came here to post about this. Nice to know someone else already caught the issue.

**Comment by CarlosEsco** [comment]
Just waiting for jay to do a release since he has a bunch of changes that I don't want to push out til he does

**Comment by CarlosEsco** [comment]
2.0.6
