### ISSUE TITLE
[Bug] Scanlation group filter

### ISSUE THREAD

**Issue by henrik9999** [CarlosEsco/Neko#198]
### Device information
* neko version: 2.0.5
* Android version: 9

## info

First of all I am not sure if this is an bug or intended, but if you use the filter Scanlation groups function on a manga and then read it the filtered group mangas still show up when you go to the next chapter for example

## Steps to reproduce
1. Go to a manga https://mangadex.org/manga/45903/
2. Filter a group (here "mangadods")
3. Read a chapter of the other group
4. Go to the next chapter

### Expected behavior
It should skip the chapter from the filtered group

### Actual behavior
It goes to the chapter of the filtered group

**Comment by CarlosEsco** [comment]
Bug it's fixed for next release

**Comment by windflare** [comment]
This issue still persists - I chose groups I want to read from in the filter, but when I read, it keeps showing manga from both groups I have filtered and groups I have filtered out.

**Comment by henrik9999** [comment]
Same here but without looking at the code I would just guess that this filter wasn't intended to do it anyway @CarlosEsco

**Comment by CarlosEsco** [comment]
It should work. There was a bug a few releases ago when there were multiple groups and you had filtered. I would reset the filter.  Back out of the manga back to library then go back in and reset the filter.  Then also make sure you have skip filtered enabled in your settings. If it still doesn't work. Let me know

**Comment by CarlosEsco** [comment]
Also make sure you are on latest version

**Comment by windflare** [comment]
Yes, I have done all of the steps that you mentioned @CarlosEsco . Reset, back out, reset again. Skip filtered enabled. Selected groups I want to see. And on latest version.

Thank you so much for taking a look at this!

**Comment by CarlosEsco** [comment]
Can you message me on the discord channel we can debug more there
