### ISSUE TITLE
App crashes when clicking "search" button in "browse"

### ISSUE THREAD

**Issue by Shtate** [CarlosEsco/Neko#1982]
### Steps to reproduce

1. In browse section
2. Click on "search"

### Expected behavior

Opens the search function

### Actual behavior

App crashes

### Crash logs

![Screenshot_20241127_174735](https://github.com/user-attachments/assets/a6d01f7d-68ef-4fab-8b15-36b7a5dbc41e)

### Neko version

2.18.2

### Android version

Android 14

### Device

Galaxy M23 5G ; SM-M236B/DS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Clear saved search filters in mangadex settings
