### ISSUE TITLE
[Bug] 2FA does not work in 2.x

### ISSUE THREAD

**Issue by sgallagher** [CarlosEsco/Neko#199]
### Device information
* Tachiyomi version: Neko 2.0.5
* Android phone & version: Google Pixel Slate Version 81.0.4044.141 (Official Build) (64-bit) (Android 9)

## Steps to reproduce
1. Launch Neko
2. Go to Settings->MangaDex Settings->MangaDex Login
3. Select the 2FA checkbox
4. Enter username and password

### Expected behavior
I should be prompted to enter the 2FA code.

### Actual behavior
"Unknown Error"

### Other details
Additional details and attachments.
If I remove the 2FA requirement from my MangaDex account, I am able to log in successfully.

My guess is that clicking the 2FA Checkbox is supposed to cause a new text entry field to appear, but it isn't being drawn.

**Comment by CarlosEsco** [comment]
Yea someone brought up on discord.  It's in next release

**Comment by CarlosEsco** [comment]
2.0.6
