### ISSUE TITLE
[Bug] Restoring backup is not working completely

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#202]
### Device information
* Tachiyomi version: 2.0.8
* Android phone & version: Android 10/Note9

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
When restoring backup, it should restore all that were checked to be backed up. (Manga, categories, chapters, tracking, history)

### Actual behavior
I believe it is Chapters and History that are not being backed up correctly. I am not exactly sure what the difference between them. But the read chapters are not being marked as read and history is empty. 

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Fixed in 2.0.9
