### ISSUE TITLE
[Feature Request] Open links to Mangadex from other apps in Neko

### ISSUE THREAD

**Issue by ohohohoo** [CarlosEsco/Neko#205]
### Why/User Benefit/User Problem
As someone who often browse Manga subreddit using Boost or other apps that offer similar purpose to look for a new interesting title to read, it'd be great if Neko would handle opening all links that's pointed to Mangadex so it'll open directly in Neko rather than in default browser app.

### What/Requirements
User click on mangadex links (chapter or Manga detail page) in other non browser app and it'll open the link in Neko. 

Currently, Tachiyomi Mangadex has the feature so I can open link pointing to Mangadex Manga detail page directly in the Tachiyomi. But if it's a chapter link it'll still open in default browser.

**Comment by CarlosEsco** [comment]
any actual manga url already opens in app.  chapter url currently do not.  Its on the planned feature list to handle chapter urls but i don't think they will ever open the chapter directly but should open the manga if my plan works out
