### ISSUE TITLE
[Bug] Adjust tracker menu height

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#207]
### Device information
* Tachiyomi version: 2.0.10
* Android phone & version: Note9/ Android 10

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
See full tracking list

### Actual behavior
Does not show full tracking list.

**Comment by CarlosEsco** [comment]
can you attach a screen shot

**Comment by CarlosEsco** [comment]
I assume this is same as #208 ?  if so can you close

**Comment by vipzzx** [comment]
Ahh yes. Oops. Don't know how 2 got uploaded. Sorry.
