### ISSUE TITLE
[Bug] Tracking list not fully showing

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#208]
### Device information
* Tachiyomi version: 2.0.10
* Android phone & version: Note9/ Android 10

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
See full tracking list

### Actual behavior
Does not show full tracking list.

### Other details
 
[Screen_Recording_20200517-200622.zip](https://github.com/CarlosEsco/Neko/files/4641396/Screen_Recording_20200517-200622.zip)

**Comment by CarlosEsco** [comment]
in 2.0.11
