### ISSUE TITLE
Download failed in case you start reading a chapter that is already downloading.

### ISSUE THREAD

**Issue by Kyuuso** [CarlosEsco/Neko#210]
### Device information
* Tachiyomi version: 2.0.10
* Android phone & version: Samsung Galaxy S9, Android 10.

## Steps to reproduce
1. Start downloading any manga that has much pages (or slow the download speed as it won't download before reproducing)
2. Wait for at least 1 chapter to be downloaded.
3. Read through the chapter and swipe to the next one.

### Expected behavior
If it has downloaded 1-3 pages of the new one, show them?

### Actual behavior
Even if the firsts pages has been downloaded, it will try to download them again. 
If you leave the reader, download itself will stop and throw an error.

### Other details
Discovered today due to a unusual download speed from my ISP (or the MangaDex servers today are specially slowly).

**Comment by jaredanson** [comment]
i noticed this as well today, i got impatient when downloading something.

**Comment by Kyuuso** [comment]
![20200520_001152](https://user-images.githubusercontent.com/12716750/82383685-9f4cb900-9a2e-11ea-82b6-8b037f0ddff1.jpg)
Just happened, attached screenshot of the error (even if it doesn't show much error)

**Comment by CarlosEsco** [comment]
Is this still an issue?

**Comment by Kyuuso** [comment]
I'll try to replicate it later tomorrow, thanks!

**Comment by CarlosEsco** [comment]
any update?

**Comment by Kyuuso** [comment]
Solved already, couldn't make it work before (reading while downloading)
