### ISSUE TITLE
extremely slow download and viewing speed

### ISSUE THREAD

**Issue by theowa1** [CarlosEsco/Neko#213]
It takes almost 30 seconds to load just one page and the download time for one chapter is taking way too long. 
I already changed image servers
But I can´t find a proper solution

**Comment by CarlosEsco** [comment]
Dex servers are in process of upgrade also steaming is slower than download since streaming is 1 by 1 downloading of the pages

**Comment by theowa1** [comment]
Thanks for the fast answer!
