### ISSUE TITLE
Tag Search directly in MD

### ISSUE THREAD

**Issue by itoffie** [CarlosEsco/Neko#215]
![IMG_20200522_204328](https://user-images.githubusercontent.com/64309702/82757047-89fdd300-9e10-11ea-83cf-cd5963d46974.jpg)

well it will be like a quick filter option instead of going browse then filters manually and finding that tag

tapping one of the tags will give you an option to search via library or the latest updates or maybe the whole library

**Comment by CarlosEsco** [comment]
This was added ~ 2.6.  clicking searches in mangadex, long clicking searches in library
