### ISSUE TITLE
Data saver option

### ISSUE THREAD

**Issue by heksagen** [CarlosEsco/Neko#216]
### Why/User Benefit/User Problem
(explain why this feature should be added)
Recently mangadex added a data saver option for those who have limited data plan, and slow internet and I'm one of them.

### What/Requirements
(explain how this feature would behave)
On mangadex settings an option called "data server" can be turned on/off.

**Comment by CarlosEsco** [comment]
Already added for next release

**Comment by CarlosEsco** [comment]
in 2.0.11
