### ISSUE TITLE
[Feature Request] Demographic Tag

### ISSUE THREAD

**Issue by Raidou13** [CarlosEsco/Neko#217]
### Why/User Benefit/User Problem
Can the Demographic tags (Shounen, Shoujo, Seinen, Josei) be shown in the description? It will really help.

### What/Requirements
Place it on a different row on top of the genre tags, or place it on the space below the Country flag, and also if it is included among the Genre tags can it use another color to differentiate it from the Genre tags?
And add it to the filters

**Comment by CarlosEsco** [comment]
added in 2.1.3.5
