### ISSUE TITLE
[Bug] Lots of mangas don't have all the chapters

### ISSUE THREAD

**Issue by Satanophany** [CarlosEsco/Neko#219]
### Device information
* Tachiyomi version: 2.0.13
* Android phone & version:  Xiaomi Remi Note 8 Pro. Android 10

## Steps to reproduce
1. First step: Old mangas and new mangas\manhuas don't have all the chapters or don't follow up with the new chapter releases.
2. Second step : I downloaded the app twice and still have the same issue.

### Expected behavior
Everything supposed to be there.

### Actual behavior
A lot of chapters missing and being counted at 0.

### Other details
![Screenshot_2020-05-27-01-07-42-700_tachiyomi mangadex](https://user-images.githubusercontent.com/65870561/82955063-afc4dc80-9fb6-11ea-865e-cdeea4dc5f0d.jpg)

It has 270 chapters while it shows only 25.

**Comment by arkon** [comment]
There's only 23 chapters on MangaDex: https://mangadex.org/title/45200/solo-login

**Comment by CarlosEsco** [comment]
Yea. If you are expecting to read non english chapters you need to enable the language in the setting then refesh the chapter list and enable the filter for the language
