### ISSUE TITLE
[Bug] can't view a manga

### ISSUE THREAD

**Issue by Eagle1337** [CarlosEsco/Neko#221]
### Device information
* Tachiyomi version: 2.0.13
* Android phone & version: zenfone 5z

## Steps to reproduce
1. Search up Gochuumon wa Usagi desu ka? 
2. Add it to library
3. View in library 

### Expected behavior
Get any info/ chapters. 

### Actual behavior
Blank screen, 5v2 toast

### Other details
Gochuumon wa Usagi desu ka?: For input string: "5v2"

**Comment by CarlosEsco** [comment]
this will be fixed in next release

**Comment by CarlosEsco** [comment]
was fixed forgot to close ticket
