### ISSUE TITLE
[Feature Request] Scanlation Group Search

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#222]
### Why/User Benefit/User Problem
Quickly see all manga being uploaded by the scanlation group searched. 

### What/Requirements
In filter like in J2K.

**Comment by CarlosEsco** [comment]
this was added in 2.15  prefix the search  with group:My group to search

**Comment by vipzzx** [comment]
would it be possible to fit it into the filter like in j2k?

**Comment by CarlosEsco** [comment]
I do not plan to do that as it makes little sense there since it cant used any of the other filters
