### ISSUE TITLE
[Bug] Cant Login

### ISSUE THREAD

**Issue by Adrian1709** [CarlosEsco/Neko#223]
### Device information
* Tachiyomi version:0.9.2
* Android phone :Samsung S10
* Android version: 10.0

## Steps to reproduce
1. Start Neko

2. Settings->MangaDex Settings->MangaDex login

3. Fill in Username and Password

4. Press "Login"
### Expected behavior
That i can login and use the Neko app

### Actual behavior
I cant login and it says  "Unknown Error"

### Other details
I already tried to switch my Password cause i thought i just forgot it but no it just doesn't work

![20200528_140358](https://user-images.githubusercontent.com/66068445/83139250-565ec980-a0ec-11ea-915c-58a7ad3e0da0.jpg)

**Comment by CarlosEsco** [comment]
Are you still having issues?

**Comment by Adrian1709** [comment]
Yes i tried it again right now and nothing changed

**Comment by CarlosEsco** [comment]
Did you confirm your account and have you tried using 2fa if it's enabled?

**Comment by Adrian1709** [comment]
2fa is disabled and to be honest i dont know what you mean with confirmed, if you mean mangazone then no because i never got an email from them and if you mean the neko app then yes i did.

**Comment by Adrian1709** [comment]
Ok so first thigs first
Thank you for youre help up to this point and that you were ready to answer some random dude on the internet
Now to the important part...
I dont know if you can believe me but i accualy thought up to this point that it says mangazone i only realised it right f*cking now that it accualy says mangaDEX. Like i know i wrote mangadex and i dont know accualy why but it seems that my brain thought something like "MangaDex? More like MangaZone" and cause i just searched for a way to extract my data from mangazone it came really handy for my problem. I again am really really sorry that i took youre time for something accualy so dumb and i hope you can forgive me.
I would like to delete this issue "report" i guess cause there is no problem with the app, theres just a problem with my brain.

**Comment by CarlosEsco** [comment]
Haha no problem. Just glad you figured out the issue 😀

**Comment by kentlagorski** [comment]
How do I sign up??????

**Comment by CarlosEsco** [comment]
@kentlagorski https://mangadex.org

**Comment by MrComexs** [comment]
I'm have having the same problem. I can't sign in. I went to check if I put the wrong password and username but everything was the same and it worked in my internet Brower. I did have 2FA enable but I disable it to see if that would fix it but I still wasn't able to sign in.

**Comment by MrComexs** [comment]
Neverminded even thought it said  "Unknown Error" it was able to sing me in.
