### ISSUE TITLE
[Bug] Long pressing library button restarts phone

### ISSUE THREAD

**Issue by radisheses** [CarlosEsco/Neko#225]
### Device information
* Tachiyomi version: 2.0.13
* Android phone & version: Honor 6X, Android 7.0

## Steps to reproduce
1. Long press library twice

### Expected behavior
Open up search in library tab

### Actual behavior
Restarts phone immediately without any prior warning

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
The library bottom button?

**Comment by radisheses** [comment]
> The library bottom button?

Yup, that's the one

**Comment by CarlosEsco** [comment]
Will look into the bug but either way that doesn't open the library search

**Comment by radisheses** [comment]
I see, thank you!

**Comment by CarlosEsco** [comment]
i am unable to replicate this.  if you can replicate it please reopen and attach a video
