### ISSUE TITLE
[Bug] Cannot uninstall the app

### ISSUE THREAD

**Issue by mikolajww** [CarlosEsco/Neko#227]
--

### Device information
* Tachiyomi version: 2.0.13
* Android phone & version: Huawei Mate 20 Lite / Android 10.0

## Steps to reproduce
Try to uninstall (long press on app or through settings)

### Expected behavior
The app is uninstalled

### Actual behavior
Nothing happens, the app remains.

### Other details
I downloaded it through an apk from github, no error is shown, when trying to uninstall through "Settings/Applications" the view just reloads.

**Comment by CarlosEsco** [comment]
@arkon  what is the sd card fix for this?  

either way its not an app issue but something with android 10 and your phone

**Comment by arkon** [comment]
Eject your SD card first before uninstalling.

**Comment by mikolajww** [comment]
Tried that, the result is the same. If its something with android 10 then that's unfortunate.
