### ISSUE TITLE
[Bug] Update Fails due to missing 'manga' field

### ISSUE THREAD

**Issue by anonCoder123** [CarlosEsco/Neko#228]
### Device information
* Tachiyomi version: 2.0.14
* Android phone & version: Pixel 2XL and Android 10

## Steps to reproduce
1. clicked to update all manga
2. update fails on a manga due to missing field

### Expected behavior
Should be able to handle all manga on mangadex

### Actual behavior
Fails on some manga.

### Other details
log message i received:

```
Homura Sensei wa Tabun Motenai: Field 'manga' is required, but it was missing
```

**Comment by CarlosEsco** [comment]
try in 2.0.15.1 and let me know

**Comment by anonCoder123** [comment]
@CarlosEsco updated to 2.0.15.1 and the issue persists. Same log message as well.

**Comment by CarlosEsco** [comment]
Can you remove the manga from your library.  Clear the db in advanced settings. Then re add it. That should reset the entry.  When firebase gets the stacktrace I will look into more

**Comment by anonCoder123** [comment]
@CarlosEsco there was no failure now that i did those steps.

**Comment by CarlosEsco** [comment]
Yea some how the entry got messed up the db. You should be good now

**Comment by anonCoder123** [comment]
@CarlosEsco When I searched for it after clearing to db, the name had changed. I wonder if it was trying to pull the old name.
