### ISSUE TITLE
[Bug] versioning issue

### ISSUE THREAD

**Issue by jaredanson** [CarlosEsco/Neko#229]
### Device information
* Tachiyomi version: `2.0.15` (would be on latest, but bug is preventing)
* Android phone & version: Pixel 2XL and Android 10

## Steps to reproduce
1. Be on version `2.0.15`
2. click version number to check for updates, or allow the autoupdate check to look for a new version
3. says new version is found
4. download version, and install
5. version hasn't changed
6. either click version to trigger check or wait for update to get alerted about a new version.
7. repeat steps to see its `2.0.15` again.

### Expected behavior
should download `2.0.15.1`

### Actual behavior
stuck on `2.0.15`

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
will have to wait til the next release to fix, if not you can backup, uninstall, restore.

**Comment by CarlosEsco** [comment]
Try to update now it should be fine

**Comment by jaredanson** [comment]
it worked 👍
