### ISSUE TITLE
[Bug] Neko not compatible with Android 5.1.1

### ISSUE THREAD

**Issue by Kusurisan** [CarlosEsco/Neko#230]
### Device information
* Tachiyomi version: -
* Android phone & version: Samsung Galaxy S6, Android 5.1.1

## Steps to reproduce
1. Downloading newest APK
2. Trying to install the APK
3. Seeing that it won't install because it won't support Android 5.1.1
4. be sad

### Expected behavior
It should install (like older versions did)

### Actual behavior
Error Parsing Package when install (=android 5.1.1 not supported by the APK)

### Other details
Please compile the apk in a way so older Android Users can still use Neko. It worked fine in older versions of Neko and it would be a shame if Users wouldn't be able to use Neko just because you choose in Android Studio a to high api level for the apk. you don't need to support that old versions, but atleast let them install it and use it.

**Comment by CarlosEsco** [comment]
There is no plans to support Android 6 and lower. Analytics show there are around 20 users who are on Android 6 or lower out of 7k installs.  It's not worth the extra effort to keep the support

**Comment by arkon** [comment]
"you don't need to support that old versions, but atleast let them install it and use it."

I feel like you have a large misunderstanding on how app development works. It's not just a matter of choosing a number and clicking "compile".

**Comment by arkon** [comment]
Also the Samsung Galaxy S6 got Android 7...

**Comment by Kusurisan** [comment]
> 
> 
> "you don't need to support that old versions, but atleast let them install it and use it."
> 
> I feel like you have a large misunderstanding on how app development works. It's not just a matter of choosing a number and clicking "compile".

i do know how app developement works. i did develope app's in eclipse & a while ago also on android studio. i even have my own app in the appstore. so please don't try to tell me i wouldn't know how app developement works. 

if you create a app, you choose for which api level the apk should be compiled. if you choose a minimum api level that is higher than as an example 5.1.1, android versions with 5.1.1 and below are not able to install that apk. if you choose a lower api level as an minimum requirement than 5.1.1, you will be able to install the apk on android devices who do have 5.1.1 (and lower depending on which api level you choose). 

Tachiyomi (which Neko is based on) works fine in the newest version on my device, so it is possible to do. If the developer ofcourse chooses to make it easy for himself by using new functions who aren't included / available in previous android versions, the apps will not work on older versions. but that is something that you can bypass by using functions who are available in older android versions or by program code who catch this problems by using alternative functions instead of functions included in newer android versions. If you use as an Example FunctionA but this function is only available in newer Android versions, you can check in your programcode if the app is running on an older version of android and then using FunctionB who does practically the same as FunctionA, but a little different. 

short - it's possible to do.Tachiyomi is the best example for this. and you can't tell me that the other functions included in Neko are all require functions who aren't available in older android versions.

**Comment by Kusurisan** [comment]
> 
> 
> Also the Samsung Galaxy S6 got Android 7...

yeah, if you want me to lose my root access, all app settings and years of configuration i did on my phone by upgrading to a newer version of android.. but i'm not gonna reinstall my whole operation system with all the tweaks and root configurations i created just to be able to use an single app. there is currently no working root for my device with android 7 that is working without bugs and issues. so i wouldn't even be able to upgrade to android 7. i tried that a few years ago. ended in bootloops, crashes and other glitching.

**Comment by arkon** [comment]
> Tachiyomi (which Neko is based on) works fine in the newest version on my device, so it is possible to do.

Neko is based on TachiyomiJ2K, not Tachiyomi. They diverged quite a while ago, and it's difficult to make lot of the J2K stuff work properly in older versions (mostly UI related things AFAIK).

> short - it's possible to do.Tachiyomi is the best example for this. 

I'm well aware, I maintain the core Tachiyomi app. The only reason I haven't had to bump up the minSdkVersion yet is because we don't try to do anything fancier like J2K/Neko. In the end, it comes down to the cost benefit. Is it worth struggling to support a few dozen users instead of adding more features for the other thousands? Probably not, especially when the project isn't a source of income.

> yeah, if you want me to lose my root access, all app settings and years of configuration i did on my phone by upgrading to a newer version of android.

That sucks, I guess. Unfortunately you're in a slowly sinking boat. Even looking at [these distribution stats](https://androiddistribution.io/#/), Android 5.x users only account for 9.2% of total overall Android users (that the data accounts for). Even [this famous Twitter account that many use as a bar](https://twitter.com/minsdkversion?lang=en) recommends setting the minimum at Android 6.

**Comment by CarlosEsco** [comment]
As you said it's possible. I don't want to. I don't want be limited with the API by supporting versions of Android that are hardly used.   You are welcome to fork and make an Android 5 compatible version

**Comment by Kusurisan** [comment]
> Neko is based on TachiyomiJ2K, not Tachiyomi. They diverged quite a while ago, and it's difficult to make lot of the J2K stuff work properly in older versions (mostly UI related things AFAIK).

didn't knew that, thanks for explaining me that. i did saw https://tachiyomi.org/forks/ & since Neko is listed as a fork, i expected it to be using the main Tachiyomi source, not TachiyomiJ2K.

> I'm well aware, I maintain the core Tachiyomi app. The only reason I haven't had to bump up the minSdkVersion yet is because we don't try to do anything fancier like J2K/Neko.

does this mean that Tachiyomi will (atleast for a "short" future) keep the minSdkVersion the same like currently? it would suck if it would stop working on my device since except Tachiyomi the only good manga reader is MiMangaNu.. but it's not having many sources so it's not really comfortable.

> In the end, it comes down to the cost benefit. Is it worth struggling to support a few dozen users instead of adding more features for the other thousands? Probably not, especially when the project isn't a source of income.

If Tachiyomi or Neko would be available in the Playstore (which google wouldn't allow i guess) or elsewhere, i'm sure a ton of people would pay for it - i would. 
i understand that it is a lot of work to maintain a project and you need to focus on the important stuff and pay the most attention to the users who use the project the most.. but still.. it sucks a little.

> That sucks, I guess. Unfortunately you're in a slowly sinking boat. 

i know. but without a job and without any sort of income, with an extrem old smartphone.. i can't afford a new smartphone with a newer android. and since i use my current device for a lot of important things that need a specific setup (lucid dreaming research.. miband sleep tracking & developement of apps for it etc.), i can't just change that easy.

guess i just have to say "okay, sucks." and try to find a different option. my current idea is to maybe create my own extension for Tachiyomi which sync's the reading of chapters on mangadex. the current extension for mangadex doesn't seem to support that (or it's buggy currently). that's the main reason why i wanted to use Neko (syncing of chapters i have read on mangadex).

anyway.. thanks to both of you. i wish you a nice day / night & greetings from germany.

**Comment by CarlosEsco** [comment]
Neither the extension or Neko sync what you read on Dex to app. I plan to eventually add that to Neko but it's not high priority.

**Comment by Kusurisan** [comment]
> Neither the extension or Neko sync what you read on Dex to app. I plan to eventually add that to Neko but it's not high priority.

i tried Neko 1.7.2(51) and did login inside the app into MangaDex. If i then open an manga in the app and read a chapter, and then open Mangadex on my computer.. it synced which chapter i have read. If i open a Manga i have never read in the app, then read 2 chapters, and then open the chapter overview on my computer in the browser, it shows me that i have read this 2 chapters. so it DOES sync. i tried that multiple times with different mangas.

**Comment by arkon** [comment]
> does this mean that Tachiyomi will (atleast for a "short" future) keep the minSdkVersion the same like currently?

Yes, there's no active plans to move away from it. We only dropped Android 4.x because of technical limitations.

> If Tachiyomi or Neko would be available in the Playstore (which google wouldn't allow i guess) or elsewhere, i'm sure a ton of people would pay for it - i would.

In the spirit of the original creator, we won't be charging for it. People are free to donate to him though: https://ko-fi.com/inorichi

> i know. but without a job and without any sort of income, with an extrem old smartphone.. i can't afford a new smartphone with a newer android.

It might be worth checking out some cheap Chinese phones. They're generally fairly decent for the price.

**Comment by CarlosEsco** [comment]
> > Neither the extension or Neko sync what you read on Dex to app. I plan to eventually add that to Neko but it's not high priority.
> 
> i tried Neko 1.7.2(51) and did login inside the app into MangaDex. If i then open an manga in the app and read a chapter, and then open Mangadex on my computer.. it synced which chapter i have read. If i open a Manga i have never read in the app, then read 2 chapters, and then open the chapter overview on my computer in the browser, it shows me that i have read this 2 chapters. so it DOES sync. i tried that multiple times with different mangas. i didn't tried if the other way around works, but that wouldn't be a problem / issue for me. 

Ok so this was removed in Neko it was an unintentional side effect of the Dex API.  I don't remember if I changed it for the tachiyomi extension or not
