### ISSUE TITLE
Please add My Anime List Sync function like the original Tachiyomi app. Thank you. [Feature Request]

### ISSUE THREAD

**Issue by RahulS132** [CarlosEsco/Neko#231]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Why/User Benefit/User Problem
(explain why this feature should be added)

### What/Requirements
(explain how this feature would behave)

**Comment by CarlosEsco** [comment]
MAL  already exists in this app.
