### ISSUE TITLE
Block cleartext traffic

### ISSUE THREAD

**Issue by Xalaxis** [CarlosEsco/Neko#234]
If I understand correctly, the current [network security config](https://github.com/CarlosEsco/Neko/blob/master/app/src/main/res/xml/network_security_config.xml) specifically opts out of the default Android network encryption requirement (meaning network traffic could be sent unencrypted).

Is this required?  If not, please can cleartext traffic be disallowed.  (This might be a carryover from Tachiyomi using less-secure sources)

If it is required, please can we document what cleartext traffic is required on the wiki, so users are aware.

**Comment by CarlosEsco** [comment]
Yea it can be removed it was carry over from when i rebased over j2k

**Comment by CarlosEsco** [comment]
Found a scenario where this was needed not big enough though to readd.

Open a manga in webview, click the group, click their website. Website was http

**Comment by Xalaxis** [comment]
I assume in that scenario you could still "open in Chrome" and then manually bypass the restriction that way if need be?

**Comment by CarlosEsco** [comment]
yep that is why it is not a big deal
