### ISSUE TITLE
[Feature Request] Filter chapters by release group

### ISSUE THREAD

**Issue by Xalaxis** [CarlosEsco/Neko#235]
### Why/User Benefit/User Problem
Often, the same chapters have been translated multiple times by different release groups - Particularly if the first time was awful and then the second group fixed up the old chapters as well as moving forward on a series.  The problem is that as it stands Neko will make you read chapters twice as all release groups are included.

### What/Requirements
On the chapter overview page, some sort of group selector which removes all other groups.

Alternatively, logic which automatically skips to the next chapter rather than repeating the same chapter again from a different release.

**Comment by CarlosEsco** [comment]
?? What version are you on?

**Comment by Xalaxis** [comment]
2.0.15.1, which is the latest according to the app.

**Comment by CarlosEsco** [comment]
Enable skip filtered chapters in settings
Then filter out the group.

**Comment by Xalaxis** [comment]
Oh, I see.  I was completely unaware that that panel could be swiped up as well as down.
