### ISSUE TITLE
[Bug] Some titles unsearchable with apostrophe

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#241]
### Device information
* Tachiyomi version: 2.0.15.2
* Android phone & version: Note9/Android10

## Steps to reproduce
1. Search title with apostrophe

### Expected behavior
Be able to search with apostrophe

### Actual behavior
Have different apostrophe. The one for Priscilla's works but not for siblings' because they are different. 

According to snakedoc:
![image](https://user-images.githubusercontent.com/59638889/85730220-7b346580-b6c7-11ea-8f1f-ee2c0b72fe4c.png)

### Other details
Additional details and attachments.

![](https://cdn.discordapp.com/attachments/569823838305648640/725600425910337596/20200625_023620.jpg)

![](https://cdn.discordapp.com/attachments/569823838305648640/725600426124116008/20200625_023553.jpg)

**Comment by CarlosEsco** [comment]
yea this isnt gonna get fixed on my end they are using a different ' on the website and so technically you need to type that one.  But like snake said if you dont include it shows fine in search
