### ISSUE TITLE
[Bug] Recommendation suggestion missing in webtoon reader mse

### ISSUE THREAD

**Issue by joseph619** [CarlosEsco/Neko#243]
### Device information
* Tachiyomi version: 2.0.15.2
* Android phone & version: 10

## Steps to reproduce
1. Enable webtoon reader mode
2. Go to last page of a last chapter

### Expected behavior
Recs suggestion phrase should apoear

### Actual behavior
Regular last page 

### Other details
Only happens in webtoon reader mode, RTL/LTR work fine

**Comment by CarlosEsco** [comment]
2.0.15.3
