### ISSUE TITLE
[Bug] Neko show HTTP error 429 on all manga

### ISSUE THREAD

**Issue by resnom117** [CarlosEsco/Neko#244]
- I have updated to the latest version of the app
Device information Huawei LDN-L21
* Tachiyomi version: v0.9.2
* Android phone & version: 8.0.0
Neko version: 2.0.15.2

## Steps to reproduce
1. First step go on Neko click on chapter i want to read 
2. Second step and get to see HTTP error 429

### Expected behavior
This should happen. load chapter 

### Actual behavior
This happened instead. does not load chapter but shows HTTP error 429

### Other details
Additional details and attachments.
![Screenshot_20200626-171834](https://user-images.githubusercontent.com/66078175/86006602-8284a780-ba16-11ea-9d67-8524631bb79b.jpg)
![Screenshot_20200629-003809](https://user-images.githubusercontent.com/66078175/86006604-83b5d480-ba16-11ea-881b-f2d6c7ef0bf9.jpg)
![Screenshot_20200629-003816](https://user-images.githubusercontent.com/66078175/86006606-83b5d480-ba16-11ea-805e-e336bf70c871.jpg)

**Comment by resnom117** [comment]
fergot to add  Neko version: 2.0.15.2

**Comment by CarlosEsco** [comment]
Do you have a really large library?  429 is rate limited and i need to lower the limit since people with 1k+ library manga getting updated are getting this now.

**Comment by resnom117** [comment]
yes i have a large library with a rond 1759 manga's

**Comment by CarlosEsco** [comment]
I have a commit to reduce the number of manga that can be updated at one time from 5 to 2 to hopefully fix this.

**Comment by resnom117** [comment]
i will try later when it will be fixed but i sa a other problem
![Screenshot_20200629-161454](https://user-images.githubusercontent.com/66078175/86017513-67209900-ba24-11ea-957d-442289b5e33f.jpg)

**Comment by CarlosEsco** [comment]
This should also be fixed in the next release.  I will double check it though.  (i have some commits not pushed yet)

**Comment by resnom117** [comment]
oke no problem and thank you for the help
