### ISSUE TITLE
[Bug] Crashing on start-up

### ISSUE THREAD

**Issue by R188** [CarlosEsco/Neko#245]
### Device information
* Tachiyomi version: 0.8.5
* Android phone & version: LGG6 Android 9

## Steps to reproduce
1. Click app
2. Wait until library screen shows up
3. It crashes instantly

### Expected behavior
Loads up rest of the app

### Actual behavior
Crashes

### Other details
This didn't happen until recently, my vaguest guess as to why this could've happened has to do with maybe to many downloads in queue automatically.

**Comment by CarlosEsco** [comment]
Do you have latest covers enabled?

**Comment by R188** [comment]
> Do you have latest covers enabled?

Whats is that and how do I do it?

**Comment by CarlosEsco** [comment]
Try the latest version and let me know

**Comment by R188** [comment]
> Try the latest version and let me know

just did and it's still happening. I tried deleting and reinstalling it too.

**Comment by CarlosEsco** [comment]
So can you try clearing the data in the Android settings?  You will lose everything but it should come up then

**Comment by R188** [comment]
is there a way that the data can be saved or backed up before so, or even a way to extract what my library is, since i dont really wanna lose my entire library. there is no way i can remember all of them by name.

**Comment by CarlosEsco** [comment]
Wait what is the version of app?

**Comment by R188** [comment]
it was the latest but nevermind that, i cleared the data settings and its working again. i tried to create a backup as fast as i could before the app closed but turned out to be useless since the json file was 0 bytes. i managed to write down all of the manga i downloaded so not all was lost there.

**Comment by CarlosEsco** [comment]
Nice. Reason I asked was it says .8.5 which is a tachiyomi version not a neko. So was asking
