### ISSUE TITLE
[Bug] cant log in, keeps saying unkown error

### ISSUE THREAD

**Issue by kero-howgee** [CarlosEsco/Neko#246]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi version: ?
* Android phone & version: ?

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Try now mangadex was down for maintenance

**Comment by CarlosEsco** [comment]
Do you still have issues?
