### ISSUE TITLE
[Feature Request] Allow password/pin fallback access as backup to biometric access. 

### ISSUE THREAD

**Issue by kennethtran93** [CarlosEsco/Neko#247]
### Why/User Benefit/User Problem
Sometimes the authorized finger doesn't work (e.g. Too wet, after shower, injury, etc) so access can't be granted. As Android also requires a password/pin fallback when using biometics, this should be utilized to gain access as well. 

### What/Requirements
Upon asking for biometric, instead of the Cancel option, the 'use password/pin' should be there and lead into another section to utilize authorization via password/pin. Or just try and do what Android lock screen does and have both biometric and password option shown at once, and when one is authorized continue.

**Comment by CarlosEsco** [comment]
The biometric library android provides does not support pin/password.  So this would require a new library for pin/password variations
