### ISSUE TITLE
[Bug] By enabling 'Data Save' option chapters don't load

### ISSUE THREAD

**Issue by calosgeros** [CarlosEsco/Neko#249]
### Device information
* Tachiyomi version: 2.0.15.5
* Android phone & version: Xiaomi redmi note 4 (mido), Android 9.0 Lineages Os 16.0

## Steps to reproduce
1. ENABLE DATA SAVE option
2. Try loading a chapter

### Expected behavior
Chapter being loaded 

### Actual behavior
Infinite loading or fail returning 'retry' option

### Other details
Already tried cleaning cache and data of the app, reinstalling it. Chapters loading only seems to work with data save disabled.

**Comment by CarlosEsco** [comment]
Can you provide a sample chapter?  I am not seeing this issue

**Comment by calosgeros** [comment]
Well i discovered something. Today it is working well, but the day i encountered this problem i had poor 4g connection. It is odd that at that time switching 'data save' option off seemed to solve it and allowing chapters to load correctly despite being slow while enabling the option led to fail. Is it a normal behavior?

**Comment by CarlosEsco** [comment]
Entirely depends on mangadex. Maybe when you enabled data saver it pointed you a md@home server that you didn't have good connections with.  Either way it's nothing I can control in app
