### ISSUE TITLE
Download multiple covers

### ISSUE THREAD

**Issue by ndeerova** [CarlosEsco/Neko#250]
it would be great if you could download the mangadex covers so you can select which one to use
I don't want to download the main or current, but the list of covers that appear in this page.

![image](https://user-images.githubusercontent.com/67583948/87222616-1f164600-c343-11ea-8324-959a2b5365b4.png)

**Comment by CarlosEsco** [comment]
It's on the eventual to do.  The covers were just finally added to the API. Which is why there is use latest cover now

**Comment by CarlosEsco** [comment]
2.10.0
