### ISSUE TITLE
[Feature Request] Make Filter More Obvious in the Manga Info/Chapter Pg

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#253]
### Why/User Benefit/User Problem
Be able to instantly see if there was a filter used so it is easier to tell that a filter is on/which filter is on.

### What/Requirements
Text on the top or next to the number of chapters. Ex: Show unread chapters, Scanlation group name
or make it super obvious with some change in the filter icon that there is some sort of filter on
or just have the text "Filters applied" or something

**Comment by CarlosEsco** [comment]
in newest release
