### ISSUE TITLE
[Bug] Untracked doesn't show up

### ISSUE THREAD

**Issue by mshihabdeen** [CarlosEsco/Neko#254]
#248 # Device information
* Tachiyomi version: 2.0.15.5
* Android phone & version: Lenovo K6, Android 8.1.0 LineageOS

## Steps to reproduce
1. Tap on Filters section
2. Tap untracked

### Expected behavior
Any manga in library that isn't tracked on MAL or Anilist, and is "unfollowed" on MDlist should show up

### Actual behavior
Nothing showed up.

**Comment by CarlosEsco** [comment]
in newest release
