### ISSUE TITLE
[Bug] Unable to install neko.

### ISSUE THREAD

**Issue by rijan72** [CarlosEsco/Neko#255]
**PLEASE READ THIS**

---

### Device information
* Tachiyomi version: 2.0.15.(5/4/3)
* Android phone & version: Huawei CHC-U01 (android-6.0)

## Steps to reproduce
1. First step - downloaded the apk from both tachiyomi-fork and github. Even tried previous releses
2. Second step - open the apk.

### Expected behavior
Prompt asking to confirm my install.

### Actual behavior
Parse error.

### Other details
Additional 
![Screenshot_2020-07-28-14-08-05](https://user-images.githubusercontent.com/34618572/88640051-385a1900-d0dd-11ea-9b6b-963e2eb30293.png)

ps - both tachiyomi and tachiJ2K work fine.

**Comment by CarlosEsco** [comment]
Neko is Android 2.x is Android 7+
