### ISSUE TITLE
[Bug] Cursor is not visible for the Add Tracker/Merge Manga page in Black theme(cursor color is black)

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#258]
---

### Device information
* Tachiyomi version: 2.1.1
* Android phone & version: Oneplus 6: A10

## Steps to reproduce
1. Search for the manga in the add tracker page with Black theme
2. Search for manga in the merge chapter page with Black theme

### Expected behavior
Cursor should be visible for editing

### Actual behavior
Unable to see since the color of the cursor is black!
![Neko-merge-light.jpg](https://user-images.githubusercontent.com/22503748/88878752-38c1f380-d246-11ea-8b87-79b6285b05bf.jpg)![Neko-Tracker.jpg](https://user-images.githubusercontent.com/22503748/88878764-3cee1100-d246-11ea-9b92-e81a0157f960.jpg)![J2k-tracker.jpg](https://user-images.githubusercontent.com/22503748/88878772-424b5b80-d246-11ea-8170-12a06955f60d.jpg)![Neko-merge.jpg](https://user-images.githubusercontent.com/22503748/88878784-46777900-d246-11ea-97c5-3d0bfc7300e6.jpg)

**Comment by vipzzx** [comment]
same issue on Note 9/Android 10

**Comment by CarlosEsco** [comment]
fixed in latest release
