### ISSUE TITLE
[Bug] Library updates causing the missing manga count to reset for a merged manga

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#259]
### Device information
* Tachiyomi version: 2.1.1.2
* Android phone & version: Oneplus 6 A10

## Steps to reproduce
1. Perform a library update for the merged manga

### Expected behavior
Missing count shouldn't get reset.

### Actual behavior
Missing count resets to the unmerged version

**Comment by CarlosEsco** [comment]
this was fixed already at some point
