### ISSUE TITLE
[Feature Request] merge all library

### ISSUE THREAD

**Issue by Animaline** [CarlosEsco/Neko#260]
#248 # Why/User Benefit/User Problem
It would benefit those who have a big library and who might not think to check each and every Manga to see if it needs to merge or not. It's not a problem, but it would make it really super user friendly. 

### What/Requirements
Instead of merging each Manga one by one, a "merge all" button could be added which would look at the whole library at once, automatically update the manga which are 100% same, and would ask if it would not be sure, so the user could change/select the correct. 

Ps: is there a donation button somewhere?

**Comment by vipzzx** [comment]
this would be nice. or even a filter that shows that theres missing chapters

**Comment by CarlosEsco** [comment]
no plans to add this.  I will add a couple filter options though
