### ISSUE TITLE
[Bug] Page list is empty

### ISSUE THREAD

**Issue by Animaline** [CarlosEsco/Neko#263]
### Device information
* Tachiyomi version: 2.1.1.3
* Android phone & version: Xiaomi Mi 9 MIUI 12.0.1 Android 10 

## Steps to reproduce
1. First step : merge any manga
2. Second step : download chapter
3. Third step : try to read and fail

### Expected behavior
You should be able to read the chapters

### Actual behavior
It gives me the page list is empty and autocloses the Manga page

### Other details
I tried to remove Manga and re-add, unmerge/re-emerge but still I have the same problem. 

Regards, 
Animaline

**Comment by CarlosEsco** [comment]
this is very generic.  can you provide a video.  also does it only happen on the merged chapters or the dex ones too?

**Comment by Animaline** [comment]
It only does it for the merged ones the "normal" chapters aren't affected

**Comment by CarlosEsco** [comment]
Thanks. I will have a fix out today

**Comment by Animaline** [comment]
Thank you so much for all the good work and keeping the app fresh and fun

**Comment by CarlosEsco** [comment]
fixed in latest
