### ISSUE TITLE
[Bug] Incorrect chapter sorting for merged chapters with multi uploaded chapters(chapters uploaded with multiple parts)

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#264]
### Device information
* Tachiyomi version: 2.1.1.4
* Android phone & version: Oneplus 6:A10

## Steps to reproduce
1. Merge the chapters for the below manga
https://mangadex.org/manga/881/

### Expected behavior
Sorted wrt chapter number
162.2,162.1

### Actual behavior
The chapters sorted in reverse order
162.1,162.2

![Screenshot_20200802-210311.jpg](https://user-images.githubusercontent.com/22503748/89126603-78b5fe80-d504-11ea-878b-d82916760f73.jpg)![Screenshot_20200802-203617.jpg](https://user-images.githubusercontent.com/22503748/89126605-7bb0ef00-d504-11ea-8b19-5baf7c9e1b3d.jpg)

**Comment by Animaline** [comment]
It's even worse with some Manga where the naming is different (chapter 001 vs volume 1 chp 1...)so as a result some Manga have everything mixed between classic and merged chapters ('I'll try to upload a pic)

**Comment by CarlosEsco** [comment]
@Animaline  please do.  Without a screen i cant know if its a sort issue, or intended.  Alternatively you can post them on the discord channel if thats easier

**Comment by Animaline** [comment]
Hey finally found again the Manga that caused me to respond 
![Screenshot_2020-08-21-02-38-27-037_tachiyomi mangadex](https://user-images.githubusercontent.com/65160032/90839406-bc5b9580-e357-11ea-9a15-37c904a28180.jpg)

The Manga is Shoku King
