### ISSUE TITLE
[Feature Request] Dual page option for landscape mode

### ISSUE THREAD

**Issue by ElephantOfDestiny** [CarlosEsco/Neko#265]
I love the app, but when using it on my new tablet, there seems to be a lack of the option to view two pages at once in landscape mode like most other readers allow for. Is there any possibility of adding this feature, or is it already there?

**Comment by CarlosEsco** [comment]
No plans at this time.  Most of the reader code is still Tachiyomi based
https://github.com/inorichi/tachiyomi/issues/149
