### ISSUE TITLE
[Feature Request] Tap anywhere on description area to expand or collapse

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#267]
### Why/User Benefit/User Problem
(explain why this feature should be added)
Cases where the description is super long. 
Makes it easier instead of finding the expand/collapse button
So it doesn't look like this 
![Screenshot_20200806-152859_Neko](https://user-images.githubusercontent.com/59638889/89574469-2de50100-d7fa-11ea-89e4-1d5567ea45e1.jpg)

### What/Requirements
(explain how this feature would behave)
 Like how it is in stable

**Comment by CarlosEsco** [comment]
Why is that description cancer...
