### ISSUE TITLE
[Bug] Remove download after read is not working

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#268]
### Device information
* Tachiyomi version: 2.1.2
* Android phone & version: note 9 Android 10

## Steps to reproduce
1. Turn on remove when marked read
2. Download chapters
3. Finish reading chapters

### Expected behavior
Downloads should be deleted

### Actual behavior
Downloads not deleted

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Fixed in 2.1.2.1
