### ISSUE TITLE
[Bug] Missing Chapter text not showing

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#269]
### Device information
* Tachiyomi version: 2.1.2.1
* Android phone & version: Note9 Android 10

## Steps to reproduce

https://mangadex.org/title/26630

### Expected behavior
Show chapters missing 

### Actual behavior
It doesn't show.

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
fixed in newest release
