### ISSUE TITLE
[Bug] No Wi-Fi connection available while connected to a VPN

### ISSUE THREAD

**Issue by 8227846265** [CarlosEsco/Neko#271]
## Device information
* Tachiyomi version: 2.1.2.1
* Android phone & version: Pocophone F1 // MIUI Global 11.0.9.0 (QEJMIXM)

## Steps to reproduce
1. Connect to a VPN
2. Settings > Downloads > Only download over Wi-Fi > **Enabled**

### Expected behavior
Download on Wi-Fi

### Actual behavior
Shows "No Wi-Fi connection available." and doesn't download.

### Other details

- On VPN settings. I had "Always-on VPN" enabled (Reference: https://support.google.com/android/answer/9089766#always-on_VPN). Though even if I have it disabled. It will still not download.
- On Neko, going to "Recent", then swiping up to open the Download Queue. Clicking the "Resume" button to force download doesn't work.
- Disabling "Only download over Wi-Fi" isn't ideal due to the risk of Neko running and downloading on the background while using mobile data.
- Without VPN turned on. Neko downloads without issue.
- I could read without issue. The bug just doesn't allow me to download.
- Screenshot for more details
![image](https://user-images.githubusercontent.com/66582769/89857724-69ebdd80-dbcf-11ea-810c-a3bea7ba1120.png)
![image](https://user-images.githubusercontent.com/66582769/89857797-9a337c00-dbcf-11ea-8a04-f02444a40256.png)
![image](https://user-images.githubusercontent.com/66582769/89857798-9e5f9980-dbcf-11ea-827a-bf89c7ed2899.png)

**Comment by CarlosEsco** [comment]
should be fixed in newest release
