### ISSUE TITLE
[Feature Request] sort by rating 

### ISSUE THREAD

**Issue by Animaline** [CarlosEsco/Neko#272]
### Why/User Benefit/User Problem
It's not really a problem or anything, bmjust a quick thought, sorting my Mangas by rating would help people with a big library to read first the Mangas that are highly rated and leave the poorly rated for a rainy day... Or even elete them (sub 6/10 usually isn't good) 

### What/Requirements
Exactly like alphabetical sorting, except it would use the mangadex rating system. 
![IMG_20200812_132813](https://user-images.githubusercontent.com/65160032/90010169-b3a3f900-dc9f-11ea-87fa-d31d15b2cef2.jpg)

**Comment by CarlosEsco** [comment]
in newest release
