### ISSUE TITLE
[Bug] phantom download chapter

### ISSUE THREAD

**Issue by Animaline** [CarlosEsco/Neko#273]
### Device information
* Tachiyomi version: 2.1.2.1
* Android phone & version: Xiaomi mi9 miui 12. 0.1 android 10

## Steps to reproduce
1. Download chapters
2. Read the chapter
3. The chapter is deleted but still shows as present 

### Expected behavior
The indicator should show nothing (as in 0) 

### Actual behavior
 will show 1 chapter downloaded. 
Even worse, if you manually delete the chapter, then it will show 2 chapters downloaded 

### Other details
Also, if you have this issue and another chapter is downloaded, you can get 3 chapter downloaded (with only 1 actually)  

Video to show the problem :

https://youtu.be/hxOWBLYGVJI

https://youtu.be/xGp6aZO3dA4 (2)

**Comment by CarlosEsco** [comment]
2.1.2 that was not deleting the downloaded chapters when you had delete after read enabled.  Can you run the clean downloads in advanced. And reopen the ticket if it happens again.
