### ISSUE TITLE
[Feature Request] add a way to search Scanlator groups works

### ISSUE THREAD

**Issue by Raidou13** [CarlosEsco/Neko#275]
### Why/User Benefit/User Problem
Easy way for Looking for Mangas/manhwas specific Scanlators have work on.

### What/Requirements
1. Add a filter on the "browse" area for Scanlatiaton groups or even directly be searched straight from the Search bar.
![Untitled90_20200816065216](https://user-images.githubusercontent.com/13474745/90322985-adf32f80-df8d-11ea-9e16-afa297dc7592.png)

2. Redirect from the title page to the browse by tap&holding on a chapter they have worked on and add an option to view titles that scanlatiaton group has work on .
![Untitled91_20200816065624](https://user-images.githubusercontent.com/13474745/90322989-b2b7e380-df8d-11ea-9a63-e17af77a5d09.png)

**Comment by CarlosEsco** [comment]
in the search bar at the top of browse you can type.

group: whatever group you want 

and it will search that group no plans at this time to add something more intuitive.
