### ISSUE TITLE
[Bug] Reading Webtoons/Webcomics shows Black Screen on BlueStacks

### ISSUE THREAD

**Issue by 8227846265** [CarlosEsco/Neko#276]
### Device information
* Tachiyomi version: 2.1.2.1
* Android phone & version: BlueStacks v4.220.0.1109, 32-bit Android

## Steps to reproduce
1. Download BlueStacks, 32-bit Android version
2. Install Neko, and open a Webcomics / Webtoons which has long vertical images.
3. Read a chapter. Upon opening it, you'll only a black screen and the images aren't loading even if you download the chapter.

Note: Manga which has a Left to Right reading settings doesn't have any issue.

### Expected behavior
Read the webcomics / webtoons

### Actual behavior
Black Screen

### Other details

- I want to reduce my addiction on reading thus I wanted to reduce the devices I can use to read (e.g. Smartphone / Tablet) and limit Neko to my PC through BlueStacks, an Android App Player. While I could read directly from MD's website. I find the bookmark functionality lacking versus Neko's bookmark feature.
- Screenshots
![1028 - 08 - 17 - 09 - 47](https://user-images.githubusercontent.com/66582769/90350167-d3a43580-e06e-11ea-9fcf-fa69e4789066.png)
![1030 - 08 - 17 - 09 - 48](https://user-images.githubusercontent.com/66582769/90350173-d69f2600-e06e-11ea-8101-5eedaf750d9c.png)
![1029 - 08 - 17 - 09 - 47](https://user-images.githubusercontent.com/66582769/90350178-da32ad00-e06e-11ea-8457-a85081ab2cd9.png)

**Comment by CarlosEsco** [comment]
Is this still an issue?

**Comment by 8227846265** [comment]
I'm not sure if I can test right now while MD is down. I'll publish an update once there's a source to read on Neko.

**Comment by 8227846265** [comment]
Wait nevermind. I could test it right now, The issue seems resolved now with the latest updates on both Neko and Bluestacks
![image](https://user-images.githubusercontent.com/66582769/124742850-b3fc5100-df4f-11eb-9e26-45f944eaa8c7.png)

**Comment by CarlosEsco** [comment]
Love issues that fix themselves :smile:
