### ISSUE TITLE
[Feature Request] Sort unread chapters separately at top of list when sort by unread is selected

### ISSUE THREAD

**Issue by Mikrz** [CarlosEsco/Neko#277]
## Why/User Benefit/User Problem
In the case of large categories, having to scroll to the very bottom of the list to see the unread series is rather annoying.

### What/Requirements
I think it was even doing it before the most recent update 2.1.3, though I'm not sure how it changed. When sorting within a category by Unread the unread chapters are sorted among themselves at the bottom of the list, and the rest of the list is default sorting of some kind. Tachiyomi's current behavior is to sort the unread chapters to the top, and then sort within that grouping. I find this far more sensible, and more convenient.

**Comment by CarlosEsco** [comment]
https://github.com/CarlosEsco/Neko/issues/278
