### ISSUE TITLE
[Bug] Sort by latest update not working

### ISSUE THREAD

**Issue by lilmsotaku** [CarlosEsco/Neko#281]
Device information
* Tachiyomi version: 2.1.3
* Android phone & version: Android 10 & SM-A505GN/DS

## Steps to reproduce
1. Open Library
2. Click sort by latest update

### Expected behavior
Should have shown latest manga updates saved in library

### Actual behavior
It does not show the latest manga but a little similar to sort by title/alphabetically. Shows manga from letter a onwards.

*Update*
You have to click or tap the latest update 2 to 3 times for it to work.

![Screenshot_20200817-204914_Neko](https://user-images.githubusercontent.com/69800504/90397941-2dd2e400-e0cb-11ea-8a8f-71160f50e0ef.jpg)

**Comment by CarlosEsco** [comment]
The behavior of the arrow was changed.  Down now means descending.  So newest to oldest.   If that doesnt resolve fix  please reopen
