### ISSUE TITLE
[Bug] Ratings not working on Mangadex tracking

### ISSUE THREAD

**Issue by ZellFk** [CarlosEsco/Neko#282]
### Device information
* Tachiyomi version: 2.1.3
* Android phone & version: Samsung Galaxy S20 & Android 10

## Steps to reproduce
1. Open the tracking of any manga added to library and try to update the rating of it

### Expected behavior
The rating gets updated on the manga page on Mangadex

### Actual behavior
The rating is unchanged on the website

### Other details
All other features work fine (like status update and chapter count update, if we refresh tracking the Mangadex rating gets removed) it seems the app isn't able to read the rating field from the site (some mangas I have on the website with ratings set are not showing on Neko with any ratings at all)

**Comment by CarlosEsco** [comment]
i knew there was something someone mentioned on discord that i had forgot about

**Comment by CarlosEsco** [comment]
Will be partially fixed in next release.  You can now update the rating.. But there is no way to sync from dex and back currently with the current follows structure

**Comment by ZellFk** [comment]
So Carlos thanks for the prompt response, updated here to v2.1.3.1 and the ratings seem to set correctly, but now there's another bug when I set the rating on the Mangadex one it always lowers by one point the rating itself (if I put an 8 for a manga it adds 7 to the ratings web page and on the app as well) another thing is if I refresh tracking of the manga the Mangadex rating disappears

**Comment by CarlosEsco** [comment]
Fixed in latest
