### ISSUE TITLE
[Bug] HTTP Error 429

### ISSUE THREAD

**Issue by resnom117** [CarlosEsco/Neko#284]
the issue  happen just after latest update 

### Device information
* Tachiyomi version: 2.1.3
* Android phone & version: huawei LND-L21 8.0.0 154 (C432)

## Steps to reproduce
1. First step open Neko click on recents click on view all updates
2. Second step click on Manga than click read manga but get to see HTTP error 429

### Expected behavior
This should happen. see manga

### Actual behavior
This happened instead. get to see HTTP error 429

### Other details
Additional details and attachments.

![Screenshot_20200817-215032](https://user-images.githubusercontent.com/66078175/90440559-b5265480-e0d7-11ea-81b7-ced8f6ac5264.jpg)
![Screenshot_20200817-215043](https://user-images.githubusercontent.com/66078175/90440594-c2dbda00-e0d7-11ea-9354-b614618ae9c4.jpg)
![Screenshot_20200817-215057](https://user-images.githubusercontent.com/66078175/90440601-c96a5180-e0d7-11ea-8733-51b1eb143158.jpg)

**Comment by resnom117** [comment]
I fergot to say it happen just after the last updated

**Comment by CarlosEsco** [comment]
429 is too many requests can you try again in ~30mins since your last activity.  You might have been temporarily ip banned

**Comment by resnom117** [comment]
oké alL try again in 30 min

**Comment by resnom117** [comment]
it still show HTTP error 429 I will try tomorrow and see if it still happens
