### ISSUE TITLE
Cannot install the .apk file (Parse Error)

### ISSUE THREAD

**Issue by Volttekka** [CarlosEsco/Neko#285]
Hey, I just found out about this app, and I really wanna use it, but every time I try to install it, it gives me the error message:
Parse error

There was a problem parsing
the package
                                         OK

Any idea why? I'm completely out of my element here
For reference, I was able to install the standard Tachiyomi and TachiyomiJ2K without issue

**Comment by CarlosEsco** [comment]
What version for Android are using?  Neko is Android 7+

**Comment by Volttekka** [comment]
Aww man, I think Samsung Galaxy S5 only goes up to Android 6, maybe it's about time I actually update to a new phone
