### ISSUE TITLE
[Bug] JSON document not fully consumed 

### ISSUE THREAD

**Issue by Animaline** [CarlosEsco/Neko#286]
#248 # Device information
* Tachiyomi version: 2.1.3.2
* Android phone & version: Xiaomi Mi9 

## Steps to reproduce
1. Update the library
2. Get the error 

### Expected behavior
Should be consumed? 

### Actual behavior
![Screenshot_2020-08-18-14-31-52-951_tachiyomi mangadex](https://user-images.githubusercontent.com/65160032/90513634-3f1a0000-e160-11ea-9e7a-f32bf8c8683d.jpg)
![Screenshot_2020-08-18-14-31-48-528_tachiyomi mangadex](https://user-images.githubusercontent.com/65160032/90513639-404b2d00-e160-11ea-8388-564bf4bff35b.jpg)

### Other details
No other details

**Comment by CarlosEsco** [comment]
can you umerged and try to see if it has an issue?  I assuming this is a merge issue since those chapters dont exist on dex.  Will help narrow down if its a dex issue or a merge issue

**Comment by Animaline** [comment]
Yeah, it was a merged chapter, "un merging" resolved the issue, but removed the chapter in question.

**Comment by CarlosEsco** [comment]
can you merge again and try the update?

**Comment by Animaline** [comment]
I try to "remerge" but the issue restarted

https://youtu.be/pj-YdWKZ-vY

**Comment by CarlosEsco** [comment]
This seems to be fine today?  maybe the merged source was having issues.
Can you retry?

**Comment by Animaline** [comment]
Hey,

Unfortunately I still have the issue.
But since it's only for this specific Manga maybe it's linked to the Manga itself and not the app?

**Comment by CarlosEsco** [comment]
can you remove the manga from your favorites.  Clear db in advanced settings then readd and merge and see if works?

**Comment by Animaline** [comment]
https://youtu.be/pj-YdWKZ-vY

Hey, 

Just did what you asked removed from favorites, cleared database, readded, merged, but still chapter 14.5 and 22.5 won't work

**Comment by CarlosEsco** [comment]
fixed in 2.1.3.5
