### ISSUE TITLE
[Bug] can not uplaod backup

### ISSUE THREAD

**Issue by resnom117** [CarlosEsco/Neko#287]
### Device information
* Tachiyomi version: 2.1.3.2
* Android phone & version: huawei LND-L21 8.0.0 154 (C432)

## Steps to reproduce
1. First step go on neko than go to settings
2. Second step go to backup click on restore backup 

### Expected behavior
This should happen. 1826/1826 manga restored

### Actual behavior
This happened instead. get to see 1825 error were found

### Other details
Additional details and attachments. 
![Screenshot_20200818-151732](https://user-images.githubusercontent.com/66078175/90517809-32000f80-e166-11ea-9d4e-e1bc2c4c1a49.jpg)

![Screenshot_20200818-150704](https://user-images.githubusercontent.com/66078175/90517327-8951b000-e165-11ea-8294-d64c9390a5d8.jpg)

**Comment by CarlosEsco** [comment]
https://github.com/CarlosEsco/Neko/issues/284


i probably need to look into upping the rate limit on restore.  i assume you didnt have this issue before hand

**Comment by resnom117** [comment]
I had it ones but it  fixed it self later it was a long time ago
