### ISSUE TITLE
[Bug] mangadex error: error from mangadex response code 429

### ISSUE THREAD

**Issue by munirrockin** [CarlosEsco/Neko#288]
#248 # Device information
* Tachiyomi version: 2.1.3.2
* Android phone & version: mi9t pro & android 10

## Steps to reproduce
1. reading, updating library, downloading chapter
2. repeat the first step a few times

### Expected behavior
manga chapter list will appear when refresh

### Actual behavior
mangadex error: error from mangadex response code 429, and chapter list will disappear.

### Other details
Browsing section works fine but sometimes show few manga and dont load no more, recent section show "http error 429" when triyng to select manga to read. It will work back to normal if i restart my internet connection changing my ip. Accessing mangadex via browser, (chrome,firefox,stock browser) using the same ip when the app not working also works fine and can read and load chapter list.

**Comment by CarlosEsco** [comment]
There is rate limiting issue that people are having currently.  I will address it in the next release

**Comment by CarlosEsco** [comment]
Fixed in latest
