### ISSUE TITLE
[Bug] #244 have the same problem sins yesterday HTTP errore 429

### ISSUE THREAD

**Issue by resnom117** [CarlosEsco/Neko#289]
### Device information
* Tachiyomi version: stable 0.10.4
* Android phone & version: Huawei LDN-L21 8.0.0 
 Neko version : 2.1.3.3
## Steps to reproduce
1. First step go on Neko click on chapter i want to read
2. Second step get to see HTTP error 429

### Expected behavior
This should happen. load chapter

### Actual behavior
This happened instead. does not load chapter but shows HTTP error 429 

### Other details
Additional details and attachments.

![Screenshot_20200820-144707](https://user-images.githubusercontent.com/66078175/90786593-09ae1780-e304-11ea-9598-60ae91447511.jpg)

![Screenshot_20200820-142857](https://user-images.githubusercontent.com/66078175/90786646-1f234180-e304-11ea-88a1-7bcb2c8fc9a4.jpg)
![Screenshot_20200820-142910](https://user-images.githubusercontent.com/66078175/90786676-29454000-e304-11ea-857d-991477e3c8b8.jpg)

**Comment by CarlosEsco** [comment]
Were you rate limited previously?  If so you will need to wait a day.  It should resolve after that

**Comment by resnom117** [comment]
i have no idea if i was rate limited

**Comment by CarlosEsco** [comment]
if you were getting 429 you were. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

you need to wait until you are un ratelimited up to 1 day.  the new version should prevent this from happening again

**Comment by resnom117** [comment]
oke thank you for all the help
