### ISSUE TITLE
Marking Chapter(s) (Un)Read with Swipe or Menu

### ISSUE THREAD

**Issue by JanesDiary** [CarlosEsco/Neko#291]
### Device information
* Tachiyomi version: 2.1.3.3
* Android phone & version: Galaxy S9+ @ 10

## Steps to reproduce
1. Browse for manga with a long description (Platinum End, for example)
2. Extend to view full description and tags.
3. Scroll down to the chapters list.
4. Swipe or press and hold to select "Mark previous as (in)read" for a chapter as read or unread.

### Expected behavior
The view stays on the chapter list where it is when marking (in)read.

### Actual behavior
View scrolls back up to description with the start of the description at the top of the screen.

### Other details
Clean [log file](https://github.com/CarlosEsco/Neko/files/5113299/2020-08-22-release.txt)

**Comment by gouri-panda** [comment]
Can i work on this?

**Comment by CarlosEsco** [comment]
Yep go ahead

**Comment by CarlosEsco** [comment]
@JanesDiary is this still an issue?

**Comment by JanesDiary** [comment]
Yes, I am still having the same issue.

**Comment by CarlosEsco** [comment]
closing as this screen was redesigned
