### ISSUE TITLE
[Bug] mangadex sync doesn't work

### ISSUE THREAD

**Issue by lucscamps** [CarlosEsco/Neko#292]
### Device information
* Tachiyomi version: 2.1.3.3
* Android phone & version: Galaxy M31, Android 10

## Steps to reproduce
1. Click on "sync mangadex into Neko" in the settings

### Expected behavior
Mangas should be sync

### Actual behavior
A notification in which is written only "Neko" with a option to cancel shows. Nothing else happens and sync does not work.

### Other details
![Screenshot_20200826-144110_Chrome](https://user-images.githubusercontent.com/70285690/91337727-35207e80-e7aa-11ea-8486-71f71a77c5aa.jpg)

**Comment by CarlosEsco** [comment]
do you have read/rereading follows on your mangadex follows list?

**Comment by CarlosEsco** [comment]
api changed on dex.  Next release will have this fixed

**Comment by lucscamps** [comment]
> api changed on dex. Next release will have this fixed

You answered before I did. Sorry for the delay and, most of all, thank you. =)
