### ISSUE TITLE
[Bug] Neko and MangaDex Read Sync

### ISSUE THREAD

**Issue by 8227846265** [CarlosEsco/Neko#293]
### Device information
* Tachiyomi version: 2.1.3.3
* Android phone & version: Pocophone F1 (Latest MIUI 11 Stable)

## Steps to reproduce
1. Read any manga, manhua, manhwa

### Expected behavior
The things you have read on Neko should sync on MangaDex wherein if you visit your MangaDex account. It will show that the read icon is marked.

### Actual behavior
The read icon on MangaDex website doesn't show "read" and you have to manually click the Read icons to ensure to update your reading progress.

### Other details
None.

**Comment by CarlosEsco** [comment]
How many reading/rereading follows do you have?

**Comment by 8227846265** [comment]
All in all, I have about 100+ on my read list.

**Comment by CarlosEsco** [comment]
oh i read this wrong.  Yea this isnt a bug.  Marking read on dex is not supported at this time
