### ISSUE TITLE
[Bug] Mangadex Http Error 600

I can't see or read any Mangas and I can't load my backup 

### ISSUE THREAD

**Issue by HatakeJimmy** [CarlosEsco/Neko#294]
### Device information
* Tachiyomi version: 2.1.3.3
* Android phone & version: Huawei P20 lite

## Steps to reproduce
1. First step: Opens Manga
2. Second step: Get's the error and so I can't see any chapters or read them

### Expected behavior
Should see the Chapters and read them

### Actual behavior
Http Error 600

### Other details
Additional details and attachments.

![Screenshot_20200827_233827_tachiyomi.mangadex.jpg](https://user-images.githubusercontent.com/68038995/91497628-96d20d00-e8be-11ea-8485-b5607702d442.jpg)

![Screenshot_20200827_233834_tachiyomi.mangadex.jpg](https://user-images.githubusercontent.com/68038995/91497641-9b96c100-e8be-11ea-86a6-b87d769125e4.jpg)

![Screenshot_20200827_233848_tachiyomi.mangadex.jpg](https://user-images.githubusercontent.com/68038995/91497653-9fc2de80-e8be-11ea-9e02-53ce1841a05e.jpg)

![Screenshot_20200827_233859_com.google.android.apps.docs.editors.docs.jpg](https://user-images.githubusercontent.com/68038995/91497662-a3eefc00-e8be-11ea-9287-7ef7966a0593.jpg)

**Comment by CarlosEsco** [comment]
They had to reboot servers. And are slowly recovering. mangaDex estimates for sure by end of day. But you probably will have better luck in a couple hours

**Comment by Efreak** [comment]
The problem is that when there's a 600 error, the app clears the list of available chapters. That makes it with hard to find again, especially since it means the read/update date disappears:


1. Go to history (or updates) view
2. Select an item
3. Read until end, then pull down to refresh chapter list
    - Mangadex returns a 600 error
    - Chapter list is now empty
4. Hit back button
5. Try to go back to set ratings for what I just read
6. The item I just selected is nowhere to be found in history view or updates view.
    - I no longer remember the title (some titles are translator-specific; they're not always the same as the title in the metadata) so I can't search for it
    - the only way to find it is thus to remove filters in the main view (read/unread, downloaded, etc) and sort by total number of chapters.
    - I'm not sure what happens in the future when I successfully refresh the chapter list, but I'm guessing the read status, bookmarks, read date for all chapters has now been cleared.
