### ISSUE TITLE
[Feature Request] Configurable Backup Options

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#295]
### Why/User Benefit/User Problem
Currently there are mangas with missing chapters and getting dropped because of official translation.
If a user is having a huge library and want to migrate a subset of mangas to other forks, currently we have to take whole backup and restore all(which is time consuming and inconvenient).

### What/Requirements
While performing the backup, we can add two options
1. Select the mangas from the library and take a backup.
2. Add an option in the manual backup settings, where we can select the categories and perform the backup

**Comment by CarlosEsco** [comment]
Probably won't be adding this as backup and restores times are way faster with the new backup format
