### ISSUE TITLE
[Bug] the cover of id:33537 didn't update

### ISSUE THREAD

**Issue by bodythesuper** [CarlosEsco/Neko#296]
### Device information
* Tachiyomi version: 2.1.3.5
* Android phone & version: 9

## Steps to reproduce
1. just try to refresh the cover of this manga 
id:33537
### Expected behavior
The cover should be updated to match the cover in mangadex 

### Actual behavior
the cover didn't update

### other details 
automatically refresh covers is enabled
![Screenshot_20200829_154232_tachiyomi mangadex](https://user-images.githubusercontent.com/70442647/91640192-f691fa80-ea1b-11ea-8062-f5c241666b98.jpg)
![Screenshot_20200829_154223_tachiyomi mangadex](https://user-images.githubusercontent.com/70442647/91640195-fbef4500-ea1b-11ea-9f3e-6ea87a1b0182.jpg)

**Comment by CarlosEsco** [comment]
So talked with mangadex its has something to do with ddos guard cache. And will fix itself over time. 

Neko and now sy remove the time parameter from the cover so

https://mangadex.org/images/manga/33537.jpg?1598520136
becomes
https://mangadex.org/images/manga/33537.jpg

As you can see the 2nd url still has the old image at this time.

**Comment by bodythesuper** [comment]
is it possible to add time parameter for covers to fix this problem

**Comment by CarlosEsco** [comment]
There are no plans to at this time. The time was removed for a reason which I can't remember off the top of my head 😂. If you are still having issues ping me in discord

**Comment by bodythesuper** [comment]
I actually found another manga that has the same issue its id:20796
