### ISSUE TITLE
[Bug] Missing filters in reorder filter

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#297]
### Device information
* Tachiyomi version: 2.1.3.6
* Android phone & version: note 9. Android 10

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Missing chapters and merge are not in the reorder filters 

### Actual behavior
Have the newly added filters

### Other details

![Screenshot_20200830-041342_Neko](https://user-images.githubusercontent.com/59638889/91654496-32a67900-ea77-11ea-8723-80ab8ab2bf62.jpg)

**Comment by CarlosEsco** [comment]
fixed in 2.1.3.7
