### ISSUE TITLE
[Bug] Filter for Not Tracked MDList is not working

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#299]
### Device information
* Tachiyomi version: 2.1.3.7
* Android phone & version: Note 9 Android 10

## Steps to reproduce
1. Filter Not tracked
2. Select MDList
3. Select a manga
4. Check tracking
5. Return to library

### Expected behavior
Should only show manga not being tracked on MDList.

### Actual behavior
Shows a set of manga that are tracked on MDList. After selecting a manga and returning to the library the manga will be removed from the filtered mangas.

### Other details
[Screen_Recording_20200901-042550_Neko.zip](https://github.com/CarlosEsco/Neko/files/5154878/Screen_Recording_20200901-042550_Neko.zip)

**Comment by CarlosEsco** [comment]
Was this after a restore or something?  i can't even get to the stage where the library is showing the manga even though its read

**Comment by vipzzx** [comment]
well i restored it a while back. it doesnt happen to the newly added mangas.

**Comment by Goku003** [comment]
Cesco, i have the same issue.
I think i shared the video in the channel

**Comment by CarlosEsco** [comment]
Is this still an issue?

**Comment by CarlosEsco** [comment]
in  5.2.4
