### ISSUE TITLE
[Bug] Marking manga as unfollowed on MDList is not working 

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#300]
### Device information
* Tachiyomi version: 2.1.3.7
* Android phone & version: Note 9 Android 10

## Steps to reproduce
1. Set MDList tracking to reading
2. Set MDList tracking to unfollowed
3. Check the status

### Expected behavior
Manga should be marked as unfollowed

### Actual behavior
Manga is marked as reading again.

### Other details
[Screen_Recording_20200901-043338_Neko.zip](https://github.com/CarlosEsco/Neko/files/5154908/Screen_Recording_20200901-043338_Neko.zip)

**Comment by CarlosEsco** [comment]
Can you try again after clearing cookies and relogging in.  I am unable to replicate

**Comment by vipzzx** [comment]
it is still happening after clearing cookies and relogging in

**Comment by CarlosEsco** [comment]
is just the video manga or any manga?  I assume you are on the latest version?

**Comment by vipzzx** [comment]
im on the latest version. its happening to all the manga that i have tested

**Comment by vipzzx** [comment]
there are some where it will be changed to unfollow but most are changing back to follow

**Comment by CarlosEsco** [comment]
This seems fixed now. One gotcha is the api server will return the cached result to the app. Even though the website is marked correct
