### ISSUE TITLE
[Bug] "...skipped because they were not in Mangadex

### ISSUE THREAD

**Issue by Raidou13** [CarlosEsco/Neko#301]
### Device information
* Tachiyomi version: 2.1.3.7
* Android phone & version: Mi9T Pro MIUI 12 ANDROID 10

when Restoring backup completion will say that some series are skipped because they don't exist in MD, even though the previous backup came from Neko.

### Other details
![Screenshot_2020-09-01-21-55-32-942_com discord](https://user-images.githubusercontent.com/13474745/91886246-a5079b00-ecbb-11ea-8e49-89757fb170da.jpg)

**Comment by vipzzx** [comment]
This might happen if there manga name changed?

**Comment by CarlosEsco** [comment]
added the titles to the error log
