### ISSUE TITLE
[Bug] HTTP 500 Errors

### ISSUE THREAD

**Issue by Chibi8357** [CarlosEsco/Neko#303]
### Device Information
* Tachiyomi version: 2.1.3.7
* Android phone & version: S20 and Android 10

## Steps to reproduce
1. Open App
2. Press Brows

### Expected behavior
Shows MangaDex's manga list

### Actual behavior
Shows HTTP 500 Error

### Other details
Additional details and attachments.
![Screenshot_20200904-065628_Neko.jpg](https://user-images.githubusercontent.com/70756940/92236799-c7e0ad80-ee7b-11ea-82e2-addd68e1e3da.jpg)

**Comment by CarlosEsco** [comment]
There is a known issue for some users when accessing a specific url in mangadex.  There is no current fix at this time

**Comment by CarlosEsco** [comment]
this shouldnt be an issue anymore
