### ISSUE TITLE
[Feature Request] Have a icon to indicate a manga is H like in MD

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#304]
### Why/User Benefit/User Problem
Would be nice to know if a manga is 18+ ahead of time in case the cover doesnt indicate it.

### What/Requirements
Just a small icon in the information to indicate it

**Comment by CarlosEsco** [comment]
Wouldn't this be covered by the hentai genre tag?

**Comment by vipzzx** [comment]
hmmm thats true. It would be nice to know right away once you open it in the info section.

 Well i tried.

**Comment by CarlosEsco** [comment]
gotcha

**Comment by CarlosEsco** [comment]
2.1.3.8
