### ISSUE TITLE
[Bug] App crashes when trying to open a manga externally

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#305]
### Device information
* Tachiyomi version: 2.1.3.7
* Android phone & version: OP6-A10

## Steps to reproduce
1. Add a manga to library
2. Enable hide library entries from browse (top right ...)
3. Then open the manga externally using Neko

### Expected behavior
Manga Info page will be opened

### Actual behavior
App Crashes

### Other details
If i re-enable Show Library entries, it works fine

**Comment by CarlosEsco** [comment]
2.1.3.8
