### ISSUE TITLE
[Bug] Merged chapters getting removed during Library updates if merged source is down/throws error

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#307]
### Device information
* Tachiyomi version: 2.1.3.7
* Android phone & version: OP6-A10

## Steps to reproduce
1. Perform library update when the merged source down/throws error

### Expected behavior
Merged manga shouldn't be removed from the chapter list

### Actual behavior
Merged manga gets removed from the chapter list

**Comment by CarlosEsco** [comment]
2.1.3.8
