### ISSUE TITLE
Filter chapters by language

### ISSUE THREAD

**Issue by lucscamps** [CarlosEsco/Neko#309]
### Why/User Benefit/User Problem
There are mangas which are translated by several teams, one starting where the other had stopped. It would be convenient if we could filter chapter list by language instead of (or even better, in addition to) scanlator group.

### What/Requirements
There could be an option to filter by language alongside filter by scanlator group in the sort settings of chapter lists.

**Comment by lucscamps** [comment]
More explanation on the subject: although I'm fluent in english, my mother language is portuguese and I prefer to read portuguese translated mangas. But not all mangás have a portuguese translation, and because of that I have to keep english-translation search enabled in the settings. The problem is, when the mangá DOES have portuguese translation, the app presents me a real big list of chapters, with language-interpolated results. This way I cannot simply click to download all, nor can I read in a continuous manner, without sorting by scans. But in mangas that have a lot a scan groups doing the job as time passes by, there is no way to know which group translate which language without memorizing all the names and choosing them on the scan-group sorting option.
I know it is not a prohibitive action, but it's really boring and counterproductive. On the other hand, and option to sort results by language would make it all much easier and fast.
Hope one day it could be done... <3
thnks

**Comment by CarlosEsco** [comment]
It's definitely something I'm going to add just not in the current iteration of neko.

**Comment by lucscamps** [comment]
Pleeeeeease @CarlosEsco ❤️ 
I still have faith lol  :3

**Comment by CarlosEsco** [comment]
2.10.4
