### ISSUE TITLE
Reader Mode [No Border No Space No status bar (webtoon mode]

### ISSUE THREAD

**Issue by 3dycosmo** [CarlosEsco/Neko#311]
Reading webtoon mode without space between images like this below;

![Screenshot_2020_0913_190205](https://user-images.githubusercontent.com/4585442/93031729-4fd26e80-f657-11ea-9abf-2b960be4652a.jpg)

Or could you tell me if it could be done now with changing ea few setting on filr data

---

### Reading without spaxe between images makes screenmore wide and many manhwa, manga, manhua have a connecting images so if the part that should be connect butbroken by blank space, ruin the reading immersion
(Make reading more compact screen only show images without shit space)

### No border no space
(Reading webtoon mode screen full of images so app could utilized screen to the fullest,itcould be good if it could also hide status bar android totally)

**Comment by CarlosEsco** [comment]
Reading non longstrip in webtoon will always add padding as the manga is not designed for webtoon.  There is no plan to change this.

**Comment by 3dycosmo** [comment]
> Reading non longstrip in webtoon will always add padding as the manga is not designed for webtoon. There is no plan to change this.

It doesn't have to be changed, more like an option to full image only, I mean a reader app, it should accomadated even a details just to make reader better immersion

**Comment by CarlosEsco** [comment]
The point is, I don't plan to add that option.  Non long strip comics are going to have the space

**Comment by Arcane951** [comment]
Disregarding side space i understand that needing to be there,
--- Is there any chance we could have the top bar minamize itself just to see more of the webtoon virtically I find on some monitors it could only should around half a pannel at a time its alright if not would just be nice to get a taller visual
