### ISSUE TITLE
Default category not included in global update checklist

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#312]
### Device information
* Tachiyomi version: 2.1.3.7
* Android phone & version: A10, Note9

## Steps to reproduce
1. Setting > Library > Updates 
2. Select "categories to include in gonna updates"

### Expected behavior
Default category should be included in the selection. 

### Actual behavior
Default category is not included in the selection. 

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Not gonna be fixed in this version of Neko

**Comment by CarlosEsco** [comment]
I can't remember but is this fixed now?

**Comment by CarlosEsco** [comment]
This is fixed just verified
