### ISSUE TITLE
[Bug] Can't type emojis for category

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#313]
### Device information
* Tachiyomi version: 2.1.3.7
* Android phone & version: A10, Note9

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Should be able to type emojis.

### Actual behavior
Can only paste emojis. 

### Other details
Additional details and attachments.
I have tried using Gboard and Samsung keyboard. Both don't work.

**Comment by CarlosEsco** [comment]
2.1.3.8
