### ISSUE TITLE
[Feature Request] choose different accent colours 

### ISSUE THREAD

**Issue by ghost** [CarlosEsco/Neko#315]
Some people don't like the bright green as much as others and it would more customisability 

As for what it would need, just an assortment of colours (like red, green, blue, purple etc). But I know it would be a lot of code, so maybe for 3.x? ;)

**Comment by CarlosEsco** [comment]
i do plan to have more colors on the eventual 3.x

**Comment by CarlosEsco** [comment]
Added more themes in 2.5.0
