### ISSUE TITLE
[Bug] Crash on Merge Popup

### ISSUE THREAD

**Issue by JanesDiary** [CarlosEsco/Neko#316]
### Device information
* Tachiyomi version: 2.1.3.8
* Android phone & version: Galaxy S9+, 10

## Steps to reproduce
1. Open Manga
2. Click Merge button

### Expected behavior
Merge list appears

### Actual behavior
App crashes

### Other details
[Log file](https://github.com/CarlosEsco/Neko/files/5235842/2020-09-16-release.txt)

**Comment by CarlosEsco** [comment]
fixed in 2.1.3.9  you will need to manually download the apk from the releases page
