### ISSUE TITLE
[Bug] Downloads doesn't start automatically while downloading from library

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#318]
### Device information
* Tachiyomi version: 2.1.3.9
* Android phone & version: OP6-A10

## Steps to reproduce
1. Select multiple mangas from the library
2. Select Download unread from the overflow button

### Expected behavior
Unread mangas starts downloading

### Actual behavior
The mangas queues up but gets paused due to error(unexpected error occurred)

**Comment by CarlosEsco** [comment]
unable to emulate this.  I had no issue

**Comment by Goku003** [comment]
Can you try adding 50 mangas into a categories which are new and click download unread from library by selecting the category

**Comment by CarlosEsco** [comment]
Yea will try it

**Comment by Goku003** [comment]
[2020-09-22-release.log](https://github.com/CarlosEsco/Neko/files/5261617/2020-09-22-release.log)
Attaching the log

**Comment by CarlosEsco** [comment]
possibly have it fixed for next release
