### ISSUE TITLE
[Usage] missing chapters

### ISSUE THREAD

**Issue by Zumochi** [CarlosEsco/Neko#320]
The readme mentions the following:

> * Look at an additional source for missing chapters not hosted on MangaDex
> * Ability to attempt to merge missing chapters from MangaDex with another source

This sounds awesome! However I have not been able to find out _how_ to do this exactly. Maybe I'm missing something but it isn't clear to me at least 😅

**Comment by CarlosEsco** [comment]
There is a button on the manga info page that looks like 2 arrows merging into one. That is the merge button

**Comment by Zumochi** [comment]
Oh! So it _was_ that button.
I am not getting any useful results from it though, while if I search in Tachiyomi with the extensions I have installed I get many.

What sources does this functionality use?

**Comment by Goku003** [comment]
Currently it uses mangalife as the source

**Comment by DevGosami** [comment]
at backend the add some more sources beacuse sometimes the mangas are missing like 200 chapters and those missing chapters are not found. It would really help a lot.

**Comment by Cjojojojo** [comment]
Can i request for clarification?

My situation:

I searched Spy x Family in Neko but to find it has many missing chapters, i clicked the merge button (the merging arrows) but it took me to mangas, not actual sources like MangaLife which makes me confused. I clicked the another Spy x Family manga but it did only merge, and not changed the source

**Comment by CarlosEsco** [comment]
> Can i request for clarification?
> 
> My situation:
> 
> I searched Spy x Family in Neko but to find it has many missing chapters, i clicked the merge button (the merging arrows) but it took me to mangas, not actual sources like MangaLife which makes me confused. I clicked the another Spy x Family manga but it did only merge, and not changed the source

It is a merge only option to attempt to merge missing chapters. If you need more clarification ask in the discord channel

**Comment by Cjojojojo** [comment]
Thank you for response :)
