### ISSUE TITLE
[Bug] Some manga chapters are missing

### ISSUE THREAD

**Issue by Mathew20kdroid** [CarlosEsco/Neko#322]
### Device information
* Tachiyomi version: **2.1.3.9**
* Android phone & version: **Redmi note 4** running **Custom Rom - Android 10**
### Steps to reproduce
Search for the desired manga and opening it

### Expected behavior
List of all chapters of the manga should be shown

### Actual behavior
Some chapters are missing **(Some showing no chapters)**

### Other details
Manga like **One punch man** is showing **NO** Chapters, while some like **Solo Levelling** has some of the chapters missing.
**All Chapters** of the manga can be found in the **MangaDex** Website **(English version)**....
###
![Screenshot_20200921-152906~2](https://user-images.githubusercontent.com/71634955/93755518-11255100-fc21-11ea-8ad2-defd406175bc.jpg)
![Screenshot_20200921-153132~2](https://user-images.githubusercontent.com/71634955/93755524-12ef1480-fc21-11ea-8ce0-3c839df4f284.jpg)

## By the way Love the App, Cool Design..

**Comment by CarlosEsco** [comment]
>All Chapters of the manga can be found in the MangaDex Website (English version)....
Except they can't

  OPM had all its english chapters removed a few weeks ago.  There are no english chapters on MangaDex.
![image](https://user-images.githubusercontent.com/2092019/93758949-54f36880-fbd7-11ea-8374-6d6a22998cbc.png)

As for Solo leveling it is also missing those chapters you mentioned.  Those were originally scanned by JB and they left MangaDex over a year ago. 
![image](https://user-images.githubusercontent.com/2092019/93758931-4a38d380-fbd7-11ea-8114-bb30b6f4c2fa.png)


Also fyi this is why i added the merge function.  To attempt to fill in missing or removed chapters
