### ISSUE TITLE
[Bug] Mangas disappearing from library after reading

### ISSUE THREAD

**Issue by FizN27** [CarlosEsco/Neko#323]
### Device information
* Tachiyomi version: 2.1.3.10
* Android phone & version: Galaxy Tab S5E

## Steps to reproduce
1. Open the reader for a manga
2. Read the manga for a few pages
3. Exit the reader

### Expected behavior
Manga should stay in library

### Actual behavior
Manga disappeared from library

### Other details
![Screenshot_20200923-142341_Neko](https://user-images.githubusercontent.com/71754275/93980903-70ae6880-fda9-11ea-97f7-04a56004546b.jpg)
![Screenshot_20200923-142515_Neko](https://user-images.githubusercontent.com/71754275/93980925-773ce000-fda9-11ea-8179-8f1f13afebeb.jpg)
![Screenshot_20200923-142522_Neko](https://user-images.githubusercontent.com/71754275/93980940-7dcb5780-fda9-11ea-915d-75cc1944f91e.jpg)

**Comment by CarlosEsco** [comment]
do you have any filters enabled?   I don't see why the manga would be removed as nothing is set to auto remove manga

**Comment by FizN27** [comment]
I'm so sorry, it looks like I've enabled the read tags all this time without realizing it and now all is well
