### ISSUE TITLE
[Feature Request] Please add multiple host sites

### ISSUE THREAD

**Issue by Mathew20kdroid** [CarlosEsco/Neko#324]
### Unable to find the manga i searched for...(no english version available)
I am unable to find **english translated** versions of popular mangas in **mangadex**....Thats why some manga showing **no chapters** available.....even for some popular manga series....

### Please add multiple host sites
Please add **multiple host** sites so that the users will have what they wanted to read.......
It will resolve the **chapter missing** problem.....

**Comment by CarlosEsco** [comment]
There is no plans to add more sites, that what tachiyomi is for.  You can attempt to merge and see if the manga you want get chapters. This works for most manga
