### ISSUE TITLE
[Feature Request] color coded badges for last update

### ISSUE THREAD

**Issue by Animaline** [CarlosEsco/Neko#326]
### Why/User Benefit/User Problem
Sometimes when you have tons of manga a'd some are being left aside by trad teams, it's good to know when it was last uploaded

### What/Requirements
It would be an opt-in option to have the badges always on which would change color with the aging of the Manga 

Green : just uploaded to 7 days
Yellow : 7 to 21 days since last update 
Orange : 22 to 61 days
Red : 62 to 182 
Black : 183 and more

I think that since you can already arrange Manga by date since last update it shouldn't be impossible to add this option

![IMG_20200924_014443](https://user-images.githubusercontent.com/65160032/94085138-8bafc580-fe07-11ea-9834-504bedb4dd42.jpg)

**Comment by CarlosEsco** [comment]
I think this will be confusing to users

**Comment by CarlosEsco** [comment]
Don't plan to add this
