### ISSUE TITLE
[Bug] Applying Track/Merged/Missing filters in library not working as expected when we switch to other tabs

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#327]
### Device information
* Tachiyomi version: 2.1.3.10
* Android phone & version: OP10-A10

## Steps to reproduce
1. Apply any of the above filters
2. Switch between library and others(recents)

### Expected behavior
The filters will be applied and the applied filter will be visible in the filter option

### Actual behavior
The filters are applied but in the filter panel, its not visible and we have to enable any filter and click the x mark to reset the filter.

### Other details
https://discord.com/channels/349436576037732353/569823838305648640/758603247883386912

**Comment by CarlosEsco** [comment]
Adding the details from discord 
Apply any one of the below filters and switch between library and any other page(may be recents)
1.Tracked/not tracked
2.Missing/not missing
3.Merged/ not merged
Library filter will be present but in the filter option its not visible

**Comment by CarlosEsco** [comment]
Should be fixed in 2.5.0
