### ISSUE TITLE
[Bug] No manga found when searched

### ISSUE THREAD

**Issue by timozel** [CarlosEsco/Neko#328]
### Device information
* Tachiyomi version: 2.1.3.10
* Android phone & version: Pixel 4 XL & Android 11

## Steps to reproduce
1. Search for a known manga that exists on mangadex without using any filters.

### Expected behavior
Results displayed for the searched term.

### Actual behavior
Page shows "No results found."

### Other details
Additional details and attachments.
![Screenshot_20200925-140101](https://user-images.githubusercontent.com/20260242/94305953-b0a35600-ff37-11ea-80ce-be99e3cec95f.png)

**Comment by CarlosEsco** [comment]
clear your cookies in advanced settings and relogin

**Comment by timozel** [comment]
Worked perfectly. Thanks for the quick reply. Love your app to pieces.
