### ISSUE TITLE
[Feature Request] pin tab for currently read manga

### ISSUE THREAD

**Issue by losav0** [CarlosEsco/Neko#329]
---

### Why/User Benefit/User Problem
so users dont have to scroll down to their history when they havent read a series in a while

### What/Requirements
this would be put somewhere in the recents tab and would look like the history tab but instead its pinned manga

**Comment by CarlosEsco** [comment]
Why not just sort your library by last read?

**Comment by CarlosEsco** [comment]
No plans to add, you can use drag and drop sort if need be
