### ISSUE TITLE
show all languages

### ISSUE THREAD

**Issue by CarlosEsco** [CarlosEsco/Neko#33]
would need to also filter out the langauges as option

**Comment by zarkone** [comment]
Any news about the topic?

**Comment by CarlosEsco** [comment]
Not yet but I have an idea or two on it now

**Comment by ForgenDT** [comment]
still nothing, however many readers would be interested -_-

**Comment by Kah1ro** [comment]
Any news? Shouldn't be too hard to implement since mangadex already does it...

**Comment by CarlosEsco** [comment]
well its not straight forward since tachiyomi normally makes a separate source per a language.  I will add this to this list of things to work on now that the latest release seems stable.

**Comment by CarlosEsco** [comment]
in 2.0.11
