### ISSUE TITLE
Pink lines and under image 

### ISSUE THREAD

**Issue by Animaline** [CarlosEsco/Neko#330]
### Device information
* Tachiyomi version: latest 2.1.3.10
* Android phone & version: Xiaomi Mi9 Android 12

## Steps to reproduce
1.  launch any manga
2. No idea

### Expected behavior
You shouldn't those pink like

### Actual behavior
You see the pink lines and some Manga underneath 

### Other details

You can fix the bug by going out and back in again

https://youtu.be/50UJMkujNQw

**Comment by CarlosEsco** [comment]
Yea for some some reason the "background" of the swipe sometimes shows through.

**Comment by CarlosEsco** [comment]
Screen was rewritten in 2.10.0
