### ISSUE TITLE
[Bug] Downloaded Chapter is not treated as Downloaded Chapter

### ISSUE THREAD

**Issue by EasyNV** [CarlosEsco/Neko#336]
### Device information
* Tachiyomi version: Latest, 2.1.3.10
* Android phone & version: Google Pixel 3, Android 11

## Steps to reproduce
1. Download any Manga
2. After Download finished, close the app. When I tried to reopen the App the downloaded manga is not treated as Downloaded, so when I try to read the chapter it stream again from mangadex (but the files are saved on the phone)

### Expected behavior
Downloaded manga did not stream from mangadex again

### Actual behavior
Downloaded manga is not treated as downloaded, so the app tries to stream again from mangadex

### Other details
N/A

**Comment by CarlosEsco** [comment]
I assume the chapter has  a '

There is android 11 bug with files with '.

**Comment by EasyNV** [comment]
I see, I try to download Jojo's Bizzare Adventure though.

Thanks a lot for the confirmation @CarlosEsco! :D

**Comment by CarlosEsco** [comment]
2.1.3.11
