### ISSUE TITLE
Filter Scanlation Group not working properly

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#337]
### Device information
* Tachiyomi version: 2.1.3.10
* Android phone & version: Note9/Android 10

## Steps to reproduce
1. Filter scanlation group, unselect at least 1.
2. Complete reading 1 chapter
3. Exit reader and go back to filter scanlation group
4. Previous unselected group will not be on the list.
5. Select reset to all. Popup window will close.
6. List is reset and all groups.
7. But when you open filter scanlation group again, not all groups are selected.
8. Only after selecting reset to all do they all become selected again.

### Expected behavior
Unselected scanlation groups shouldnt disappear from the list.

### Actual behavior
Scanlation groups disappear after filtering in the scanlation filter selection. 

### Other details

[Screen_Recording_20201004-062533_Neko.zip](https://github.com/CarlosEsco/Neko/files/5325038/Screen_Recording_20201004-062533_Neko.zip)

**Comment by CarlosEsco** [comment]
unable to replicate at this time

**Comment by CarlosEsco** [comment]
This is probably fine now as the code was reworked when it was switched to excludes vs includes
