### ISSUE TITLE
[Bug] Publication Complete and Complete Filtering

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#338]
### Device information
* Tachiyomi version: 2.1.3.10
* Android phone & version: Note9/Android 10

## Steps to reproduce
1. Find a completely scanlated manga(with [END] next to the last chapter) but marked as publication complete
2. Group by status
3. Those mangas will not show up as complete

### Expected behavior
Completed mangas with last chapters with [END] should be marked as completed and when filtered or grouped by status should be in the completed category.

### Actual behavior
They are still in the Publication Complete category.

### Other details
Additional details and attachments.
This one is complete and is marked as complete:
https://mangadex.org/title/34686/a-taste-of-love

This one is complete but marked as 
https://mangadex.org/title/47355/soulmate

Also how would you differentiate from a manga where the last chapter is scanlated but they are missing chapters vs a manga that is completely scanlated with no missing chapters? Would it be considered as Publication Complete or Complete because you can merge (most of the time)

**Comment by CarlosEsco** [comment]
Should have waited til i answered on discord.  But this is just a bug specific to soulmate. 

[END] chapters will not signify a manga is complete and there are no plans to do so.  What if a scanlator snipes the last chapter yet there are 100 missing chapters.  In your scenario you would never get updates on the manga if a user has don't update completed.

**Comment by CarlosEsco** [comment]
also there are no plans to have merge chapters count towards the status.  So its pretty straight forward (a bit more complex in code)

if publication status is complete
the api returned a chapter for the last chapter (sometimes they return 0)
the last chapter exists, 
there are no misssing chapters it will be marked complete

**Comment by vipzzx** [comment]
I found a few where all chapters are there but it is still marked as publication complete though

**Comment by Goku003** [comment]
I am not sure but when i tried looking into some of the completed mangas in my library and did a api call i could see, for all languages it has the last chapter.
For eg : https://mangadex.org/manga/21204/

But for below mangas which shows Publication Complete eventhough the final gb lang chapter = last chapter
https://mangadex.org/manga/1873/
https://mangadex.org/manga/9953/
For these all languages are not completed.

This is just something i come up maybe its considering all languages except the preferred language.
But while looking in the code, i felt it took the preference language and filters out language specific chapter list or something so kinda unsure.

**Comment by vipzzx** [comment]
heres some other ones with the same issue that i found in my library
https://mangadex.org/title/47503/cheating-men-must-die-and-the-prime-minister
https://mangadex.org/title/2196/wolf-girl-and-black-prince
https://mangadex.org/title/35459/imperial-edict
https://mangadex.org/title/14763/yakushoku-distopiary-gesellschaft-blume
https://mangadex.org/title/175/absolute-witch
https://mangadex.org/title/1302/serendipity
https://mangadex.org/title/5957/anata-to-scandal
https://mangadex.org/title/12295/nonscale

theres a lot more but im too lazy to find them. if you really need me to find more i can later

**Comment by CarlosEsco** [comment]
2.1.3.11
