### ISSUE TITLE
[Feature Request] Toggle for 18+ filter (SFW MODE)

### ISSUE THREAD

**Issue by plumpkid** [CarlosEsco/Neko#339]
Is it possible? I want to introduce my little sister to manga through this app, but I dont wanna stick hentai right there in the search bar as an option that's labelled..
Just a toggle in settings would be awesome.

**Comment by plumpkid** [comment]
I'd be willing to give it a shot myself but I'm very new to coding.

**Comment by CarlosEsco** [comment]
so a toggle to hide the r18 in the search menu?

**Comment by CarlosEsco** [comment]
2.1.3.11
