### ISSUE TITLE
[enhancement] Add Random option similar to website

### ISSUE THREAD

**Issue by CarlosEsco** [CarlosEsco/Neko#34]
Random number generator, pick random id?

Just take the random one from the main page?

**Comment by arsonistAnt** [comment]
Do we want this option to be be available to the user on the nav drawer? Or in the browsing catalog?

**Comment by CarlosEsco** [comment]
Hmm I think an option in browsing filters.  Press button loads a random in the search view.  Press again a new one

**Comment by arsonistAnt** [comment]
Just finished the implementation but UI wise I'm still quite unsure where to place the random button...

I guess a better way would be to add it as a spinner item `"Search random manga"`, and have `Disabled` and `Enabled` as an option. When the user presses search while its on `Enabled` it will load up a random manga.

Also here is my cruddy button placement:
![Test Implementation](https://i.imgur.com/eCxeOgO.png)

**Comment by CarlosEsco** [comment]
i like the idea of the button next to the reset, search and it just ignores anything else in the filters

**Comment by arsonistAnt** [comment]
Okay sounds good. 

I'll implement it that way, I'll also do a pull request when I'm finished setting the color themes on the dividers for Dark and Amole. 

By default the borders won't show because there is no color for the dividers on the both mentioned themes.
