### ISSUE TITLE
[Bug] Can't login

### ISSUE THREAD

**Issue by CHEEZE-FACTORY** [CarlosEsco/Neko#340]
###Device information
* Tachiyomi version: 2.1.3.11
* Android phone & version: samsung galaxya7 version 8.0.0
## Steps to reproduce
1. open app
2. browse
3. login

### Expected behavior
login

### Actual behavior
unexpected error

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Have you confirmed your account on mangadex?  Can you try clearing cookies then attempt relogin
