### ISSUE TITLE
[Bug] Sync Mangadex to Neko shows 0 count

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#341]
### Device information
* Tachiyomi version: 2.1.3.11
* Android phone & version: A10

## Steps to reproduce
1. Click Sync from Mangadex to Neko

### Expected behavior
After the sync up shows the total number of mangas pulled from dex.

### Actual behavior
It shows 0 new but the new mangas are added to the library.
 ![Screenshot_20201010-154753.jpg](https://user-images.githubusercontent.com/22503748/95674027-24e22880-0bcb-11eb-91f9-327a5b969ab4.jpg)

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
2.1.4
