### ISSUE TITLE
[Bug] Plan to Read status is not changing to Reading after reading 1 or more chapters

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#342]
### Device information
* Tachiyomi version: 2.1.4
* Android phone & version: A10

## Steps to reproduce
1. Add a manga to the library
2. Once opened and if the manga is not in mdlist, it adds to Plan to Read
3. Read 1 or more chapter

### Expected behavior
Read chapter count increments with status as Plan to Read

### Actual behavior
Read chapter count increments with status as Plan to read

![Screenshot_20201012-091725.jpg](https://user-images.githubusercontent.com/22503748/95735603-a5c02380-0ca2-11eb-9c31-580bc0c133ca.jpg)

**Comment by CarlosEsco** [comment]
fixed in newest release
