### ISSUE TITLE
[Bug] Download queue gets cleared, when Dex to Neko Experimental feature marks a chapter read in Neko.

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#345]
### Device information
* Tachiyomi version: 2.1.4
* Android phone & version: OP6-A10

## Steps to reproduce
1. Take any manga, make sure that atleast 1 chapter is read and the read chapter count in dex is reflected 
2. Download couple of chapters and let it get queued up and let it download
3. Mark a chapter unread and force refresh the manga(or wait to get it marked as read)

### Expected behavior
Downloading should continue

### Actual behavior
Download queue gets cleared

### Other details
Attaching the screen-recording

https://cdn.discordapp.com/attachments/569823838305648640/766171306340515870/20-10-15-10-58-45.mp4

**Comment by CarlosEsco** [comment]
This feature was removed and replaced with a read sync
