### ISSUE TITLE
[Bug] Chapter 0 gets marks as Read when enabling the Dex to Neko read status experimental feature.

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#346]
### Device information
* Tachiyomi version: 2.1.4
* Android phone & version: OP6-A10

## Steps to reproduce
1. Mark the status as Reading for a manga having chapter 0

### Expected behavior
It shouldn't mark chapter 0 as marked

### Actual behavior
It marks chapter 0 as marked

### Other details
Only happens for status as Reading, no issues for Plan to Read.
I guess in dex, count will be 0 so it marks chapter with 0 as read

**Comment by CarlosEsco** [comment]
This by design, but i will probably need to tweak it some.    Maybe do a ceiling instead of a floor so things like 3.1, 3.2 dont get marked read.  though that doesnt address this issue

**Comment by CarlosEsco** [comment]
In newest release
