### ISSUE TITLE
Spoiler popup/notification for new chapters skipping

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#347]
### Why/User Benefit/User Problem
Sometimes chapters might be uploaded but it skipped a few chapters. For example Ch 10 is uploaded but only Ch 1-5 were uploaded before and Ch 6-9 is missing. I read the new chapter and was super confused because I didnt notice the chapter number. Think this will be especially helpful for the people who use the start reading button.

### What/Requirements
Have a spoiler warning like how MD does it when there is a gap between chapters. 
EX: https://mangadex.org/chapter/710017

**Comment by CarlosEsco** [comment]
upstream code that can be used
https://github.com/tachiyomiorg/tachiyomi/pull/3745
https://github.com/tachiyomiorg/tachiyomi/pull/3755

**Comment by CarlosEsco** [comment]
this was added in 2.6.2
