### ISSUE TITLE
More image server options

### ISSUE THREAD

**Issue by Akarui39** [CarlosEsco/Neko#348]
I am from Asia so the server from NA/EU takes a lot time to load.

**Comment by CarlosEsco** [comment]
Are these some missing that are available on MangaDex?  Neko doesn't have any servers

**Comment by Akarui39** [comment]
I found this in Mangadex extension setting for Tachiyomi. Here, it says
rest of the world so I thought there might be more or other servers of
mangadex. Mangadex loads a lot faster selecting rest of the world. But I
love using Neko app instead.

**Comment by CarlosEsco** [comment]
What are the options on Dex's website?  Also why would you not use automatic?

**Comment by Akarui39** [comment]
Guess I should do that. I also found this in their website. Thank you for
your time 😀.

**Comment by CarlosEsco** [comment]
If its an option for rest of world i can definitely add it.

**Comment by Akarui39** [comment]
Thanks I would appreciate it if you would look into it. 😊
