### ISSUE TITLE
[Bug] Library doesn't show manga with unread chapter

### ISSUE THREAD

**Issue by jojo6611** [CarlosEsco/Neko#350]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi version: ?
* Android phone & version: ?

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Can you share a screenshot or something. You provided little detail
