### ISSUE TITLE
[Bug] New Languages to be filtered for Manga Description

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#351]
### Device information
* Tachiyomi version: 2.1.4.1
* Android phone & version: OP6-A10

## Steps to reproduce
1. Open below attached manga

### Expected behavior
Show only the description with the selected language

### Actual behavior
Shows other language as well

### Other details
https://mangadex.org/manga/43292/
https://mangadex.org/manga/36075/
https://mangadex.org/manga/46773/
https://mangadex.org/manga/44111/

**Comment by vipzzx** [comment]
Ones I found 

https://mangadex.org/title/52838
https://mangadex.org/title/37041
https://mangadex.org/title/51757
https://mangadex.org/title/36694

**Comment by CarlosEsco** [comment]
was fixed in previous release
