### ISSUE TITLE
[Feature Request] A way to mark a chapter as read individually.

### ISSUE THREAD

**Issue by Jaoheah** [CarlosEsco/Neko#354]
With some Mangas, there are multiple groups translating them, so you end up with duplicates of each chapter. The way I have been dealing with this is by making it so it skips already read chapters (an option in the settings), and then marking the duplicates as read, but there is no way to individually mark a chapter as read, I have to mark all previous chapters as read, then under that mark all previous chapters as unread and repeat so that's why I want to be able to mark individual chapters as read, and also on the official mangadex reader it does not have this problem, as it has some system that allows you to only read the manga translation from one group.

**Comment by Jaoheah** [comment]
![Screenshot_20201108-095447_Neko](https://user-images.githubusercontent.com/30870767/98468466-913f5000-21a8-11eb-98ba-053b79a1b0e4.jpg)

Just reread it and it's kind of confusing if you don't have a image of what I'm talking about.

**Comment by CarlosEsco** [comment]
Swipe the chapter right to left

You can also filter the group out in the filter settings
