### ISSUE TITLE
[Bug] Write short description here

### ISSUE THREAD

**Issue by Animaline** [CarlosEsco/Neko#355]
### Device information
* Tachiyomi version: 2.1.4.1
* Android phone & version: Xiaomi Mi9 Android 12 

## Steps to reproduce
1. Launch neko
2. Click on manga

### Expected behavior
The Manga can be read

### Actual behavior
Neko crashes

### Other details
![Screenshot_2020-11-10-10-32-51-476_com miui bugreport](https://user-images.githubusercontent.com/65160032/98655945-5ec85b00-2340-11eb-8364-b2187a19fb8d.jpg)

https://youtu.be/wMgWi5svScs

**Comment by CarlosEsco** [comment]
dupe
