### ISSUE TITLE
[Bug] Neko Crashes on Mdlist retrieval

### ISSUE THREAD

**Issue by Animaline** [CarlosEsco/Neko#356]
### Device information
* Tachiyomi version: 2.1.4.1
* Android phone & version: Xiaomi Mi9 Android 12 

## Steps to reproduce
1. Launch neko
2. Click on manga

### Expected behavior
The Manga can be read

### Actual behavior
Neko crashes

### Other details
![Screenshot_2020-11-10-10-32-51-476_com miui bugreport](https://user-images.githubusercontent.com/65160032/98655945-5ec85b00-2340-11eb-8364-b2187a19fb8d.jpg)

https://youtu.be/wMgWi5svScs

**Comment by CarlosEsco** [comment]
Is it just that manga?

**Comment by Animaline** [comment]
yes it only does it for this specific manga. 
And if I click on the small circled book (go to last unread) then I can read the chapter just fine

**Comment by CarlosEsco** [comment]
can you log into the website and send a screen of what the mdlist entry is?  like  follow status, chapter count etc.  wonder if there is some messed up value there

**Comment by Animaline** [comment]
i try to click it, but it force close instantly

**Comment by CarlosEsco** [comment]
i mean going to https://mangadex.org logging in and sending the screen from the website

**Comment by Animaline** [comment]
![Manga](https://user-images.githubusercontent.com/65160032/98702390-981dbc80-237a-11eb-85ff-ff2ca6450c5d.png)

you mean like this ?

**Comment by CarlosEsco** [comment]
yea can you try removing the rating.  then see if you can access in app?

**Comment by Animaline** [comment]
lool, it worked ><

**Comment by CarlosEsco** [comment]
can you do me 1 more thing.  Change a different mangas rating to 5 on website .  then try to open it in and see if it now crashes

**Comment by Animaline** [comment]
ok

**Comment by Animaline** [comment]
I just tried with Sousou no Frieren and nothing happened

**Comment by CarlosEsco** [comment]
ok maybe it someone got it a weird state.  I'll leave this open and look into later.  Glad its working for you

**Comment by CarlosEsco** [comment]
closing as this was switched to v2
