### ISSUE TITLE
[Feature Request] Add manga url to the share button

### ISSUE THREAD

**Issue by DuccinatorAlpha** [CarlosEsco/Neko#361]
### Why/User Benefit/User Problem
When you press share, the name, chapter no and page no. are also sent as text to the app you are sharing to, despite that, some people still are unable to find those mangas, and for them it would be nice if the url of the manga was also appended

### What/Requirements
It would be nice if the merge url is also appended. 

If you don't mind, have the url in angle brackets so that they don't embed in discord and some other similar apps that support markdown

**Comment by CarlosEsco** [comment]
This for the page share right?

**Comment by CarlosEsco** [comment]
This for the page share right?

**Comment by DuccinatorAlpha** [comment]
yeah

**Comment by CarlosEsco** [comment]
in  5.2.4
