### ISSUE TITLE
[Feature Request] Don't download chapters for filtered groups in chapter list

### ISSUE THREAD

**Issue by joseph619** [CarlosEsco/Neko#363]
### Why/User Benefit/User Problem
For filtered groups in chapter list, and an option to not download chapters from those group for that manga.

### What/Requirements
Maybe in Downloads setting, add a toggle (or checkbox) to not download filtered chapters from group in chapter list for particular manga.

**Comment by CarlosEsco** [comment]
This already happens by default

**Comment by joseph619** [comment]
Ducc told me it wasn't working for him that's why I opened this

**Comment by CarlosEsco** [comment]
it doesnt work if a new group starts scanning but that that is by design so you dont miss new chapters from a new group

**Comment by CaidenBlock** [comment]
This does not work as intended.

**Comment by CaidenBlock** [comment]
Downloading unread chapters does not take into account groups hidden by filters, and downloads them anyways.

If you wish to reopen this, you can, or I can make a new bug report that mentions this one.

**If this receives no response within the next week or so, I will open a new issue.**

I'll be taking some time in the next few weeks to learn the codebases, but I have limited Android development experience,.

**Comment by CarlosEsco** [comment]
Are you talking downloading from the library or the manga screen?  I took the original issue as during the library update

**Comment by CaidenBlock** [comment]
Updating from the library screen.

> Are you talking downloading from the library or the manga screen? I took the original issue as during the library update
