### ISSUE TITLE
Slow long strip manga

### ISSUE THREAD

**Issue by Fxxxlei** [CarlosEsco/Neko#365]
### Device information
* Tachiyomi version: ?
* Android phone & version: OnePlus 5T 6GB RAM, Oxygen OS 10.0.0 / Android 10

## Steps to reproduce
1. Download any manga that is read in long strip format and has long individual images
2. Read it and scroll

### Expected behavior
There should be no lag.

### Actual behavior
The longer the individual images, the more it lags. (Sometimes the entire chapter is one long image)

### Proposal
I propose that images with a width-height ratio larger than (arbitrary) 1:4 get automatically split into several images (at storage or at loading). This way the reader only needs to load and draw the current and surrounding parts, not the whole chapter.

Maybe an additional side effect of the proposal: added break points I can return to when exiting and reentering the reader.

**Comment by CarlosEsco** [comment]
I don't know if i plan to auto split images as thats not trivial.  An intermediate fix would be to report the chapter to MangaDex and ask them to  split the image into more than one.  

As for breakpoints that gets even more into the weeds of the image processing and i would rather auto split the image lol.    I'll leave this open if someone or I want to look at it in the eventual 3.x release

**Comment by Fxxxlei** [comment]
Splitting the images itself is easy.
I didn't manage to decouple the number of images from the number of pages, when I tried splitting pages in the WebtoonAdapter.
To know the total number of images in a chapter, I need to load a whole chapter.

The alternative would be splitting earlier, but then we would not know wether we are using the Webtoon view. Splitting in any other view would be bad.

I don't think this can be done safely and efficiently without a major overhaul of eu.kanade.tachiyomi.ui.reader and related packages.

**Comment by CarlosEsco** [comment]
check on 2.1.5 this might be fixed some

**Comment by Fxxxlei** [comment]
I have long stopped having this issue.
