### ISSUE TITLE
[Bug] All except most recent three chapters marked as read after unmarking

### ISSUE THREAD

**Issue by smilingfaces** [CarlosEsco/Neko#366]
### Device information
* Tachiyomi version: 2.1.4.1
* Android phone & version: Moto G8 Power, version 10

## Steps to reproduce
1. Open unread series with at least 30 chapters (could not reproduce in shorter series)
2. Read several chapters 
3. Return to series info page

### Expected behavior
Only read chapters are marked as read

### Actual behavior
All chapters excluding the most recent three are marked as read.
 
### Other method to reproduce
1. Mark all chapters as unread
![Screenshot_20201124-232055](https://user-images.githubusercontent.com/10076910/100183298-8c6ae380-2eac-11eb-9e50-3d1722365d3c.png)

2. Leave series page
![Screenshot_20201124-232221](https://user-images.githubusercontent.com/10076910/100183322-9f7db380-2eac-11eb-9e23-0756f5938577.png)

3. Return to series page
![Screenshot_20201124-232253](https://user-images.githubusercontent.com/10076910/100183390-cdfb8e80-2eac-11eb-964e-c05843dbd9d2.png)

This too results in unread chapters being marked as read. Cache clearing and restarting did not fix.

**Comment by CarlosEsco** [comment]
Do you have the experimental setting enabled?  If so what is the MDList chapter count at currently?

**Comment by smilingfaces** [comment]
I did have it enabled, thank you for pointing that out.

However, zero of the chapters were marked as read on MDlist
![Screenshot_20201125-100836](https://user-images.githubusercontent.com/10076910/100245949-99b4bc00-2f06-11eb-8ecb-630796bc0145.png)

**Comment by CarlosEsco** [comment]
It doesnt read from that it reads from the mdlist at the top of the 
![image](https://user-images.githubusercontent.com/2092019/100252867-62e2a400-2f0e-11eb-855e-920c0d848ed4.png)

what does it say here

**Comment by smilingfaces** [comment]
You're right. It was at 49.
