### ISSUE TITLE
[Bug] The chapter language filter replaces Hebrew with Lithuanian

### ISSUE THREAD

**Issue by ishai8** [CarlosEsco/Neko#367]
### Device information
* Tachiyomi version: 2.1.4.1
* Android phone & version: Xiaomi redmi Note 4 Android 7, MIUI 11.0.2

## Steps to reproduce
1. go to settings>MangaDex settings>Choose languages to show
2. Select Hebrew , you can also select multiple languages with hebrew, 

### Actual behavior
The chapter language filter replaces Hebrew with Lithuanian

**Comment by CarlosEsco** [comment]
was fixed in previous release
