### ISSUE TITLE
[Bug] sort by upload date not functioning as intended

### ISSUE THREAD

**Issue by acknologia** [CarlosEsco/Neko#368]
---

### Device information
* Tachiyomi version: ?
* Android phone & version: galaxy tab s7+  on android 10

## Steps to reproduce
1. Use sort by update date

### Expected behavior
Only newest updates from mangadex should populate list

### Actual behavior
Half the list is random manga that is not the most recent updates other half is recent updates.

### Other details
I am adding screen shots of the update date of the first 11 manga with available chapters. I also included what mangadex shows on their site. I have also refreshed each manga before screenshotting.
![Screenshot_20201209-023114_Neko](https://user-images.githubusercontent.com/64101826/101599968-ab976400-39c8-11eb-9d61-387adc428217.jpg)
![Screenshot_20201209-023322_Neko](https://user-images.githubusercontent.com/64101826/101600022-be119d80-39c8-11eb-991a-366c95a9836e.jpg)
![Screenshot_20201209-023335_Neko](https://user-images.githubusercontent.com/64101826/101600024-be119d80-39c8-11eb-9041-ebc5d1f39d99.jpg)
![Screenshot_20201209-023302_Neko](https://user-images.githubusercontent.com/64101826/101600026-be119d80-39c8-11eb-8da1-bd0ad3577a31.jpg)
![Screenshot_20201209-023121_Neko](https://user-images.githubusercontent.com/64101826/101600030-beaa3400-39c8-11eb-8e46-2fbf37c81640.jpg)
![Screenshot_20201209-023127_Neko](https://user-images.githubusercontent.com/64101826/101600031-bf42ca80-39c8-11eb-968a-03e31686e5bb.jpg)
![Screenshot_20201209-023133_Neko](https://user-images.githubusercontent.com/64101826/101600033-bf42ca80-39c8-11eb-86de-b229418a9e71.jpg)
![Screenshot_20201209-023143_Neko](https://user-images.githubusercontent.com/64101826/101600034-bfdb6100-39c8-11eb-9edf-8cd104c672cf.jpg)
![Screenshot_20201209-023158_Neko](https://user-images.githubusercontent.com/64101826/101600036-c073f780-39c8-11eb-9690-8b4065e3c0d7.jpg)
![Screenshot_20201209-023209_Neko](https://user-images.githubusercontent.com/64101826/101600037-c073f780-39c8-11eb-80a8-e8b5f58a6b19.jpg)
![Screenshot_20201209-023217_Neko](https://user-images.githubusercontent.com/64101826/101600039-c10c8e00-39c8-11eb-9fec-77d3ca542684.jpg)
![Screenshot_20201209-023223_Neko](https://user-images.githubusercontent.com/64101826/101600042-c10c8e00-39c8-11eb-9ce4-55e581048a3a.jpg)
![Screenshot_20201209-023229_Neko](https://user-images.githubusercontent.com/64101826/101600046-c1a52480-39c8-11eb-9e6c-c158b8e346fe.jpg)
![Screenshot_20201209-023235_Neko](https://user-images.githubusercontent.com/64101826/101600047-c23dbb00-39c8-11eb-9fb0-4e6452733ee9.jpg)
![Screenshot_20201209-023241_Neko](https://user-images.githubusercontent.com/64101826/101600051-c2d65180-39c8-11eb-9490-c4e51911326c.jpg)

**Comment by CarlosEsco** [comment]
You should be comparing it to
mangadex.org/updates/ not the front page.  The front page isn't paginated.   Also the app is not doing any sorting internally.  It's just displaying what Dex provides in the order it provides

**Comment by acknologia** [comment]
That makes sense but it's still not matching up for me. I recently switched over to android tablets and the app i use for my iPad matches manga for manga to the updates page. I did a few refreshed screenshots just now and neko doesn't match mangadex.org/updates/ either.
![Screenshot_20201210-195336_Neko](https://user-images.githubusercontent.com/64101826/101847777-00022700-3b22-11eb-89e9-75926b1568b5.jpg)
![Screenshot_20201210-195350_Neko](https://user-images.githubusercontent.com/64101826/101847784-02fd1780-3b22-11eb-946b-5bdae7791a21.jpg)
![Screenshot_20201210-195530_Neko](https://user-images.githubusercontent.com/64101826/101847785-055f7180-3b22-11eb-89c2-e29ae45ca7ff.jpg)

**Comment by CarlosEsco** [comment]
1. A little background first if you have opened a manga at any point and have not cleared your database of non library manga then whatever info you see is being served from db and not the website.   Just want to point that out in cause while this wouldnt effect sort order it could effect if something didnt show newer chapters when you clicked into it.

2.  Are these screens in app when you first click the browse button, or after you apply a filter?  If you applied a filter then its filtering based on /titles  which doesnt not respect a users blocked languges, so you could be seeing updates from other languages in app

**Comment by CarlosEsco** [comment]
Closing this for now, once Dex starts updating again repopen if you have the issue
