### ISSUE TITLE
[Bug] cover is garbled in expanded view after fix

### ISSUE THREAD

**Issue by azzy96** [CarlosEsco/Neko#372]
### Device information
* Tachiyomi version: 2.1.4.3
* Android phone & version: Samsung Galaxy Note 9 (N960F) on Android 10/OneUI 2.1

## Steps to reproduce
1. Open manga chapter selection
2. Expand manga cover

### Expected behavior
Should expand to show larger picture of cover

### Actual behavior
Bugged to hell and back, heavily garbled.

### Other details
"Update to latest cover" has been checked yet same result regardless of if checked or not. Update to the version reported 3-4 minutes before the bug but is listed in review notes as fixed.

**Comment by CarlosEsco** [comment]
if you have refresh covers enabled, you should be able to swipe refresh the manga info a few times to get it download correctly

**Comment by azzy96** [comment]
Will link to a YouTube video of screen recording to show problem, have since updated the manga title (not the cover) and has since loaded correctly.

**Comment by azzy96** [comment]
Screen recording of bug (sorry for piss poor resolution, Samsung doesn't allow nice things)

https://youtu.be/UpHulhKOxt4

**Comment by CarlosEsco** [comment]
should be fixed in 2.1.5.5
