### ISSUE TITLE
[Bug] Error loading manga licensed on mangadex

### ISSUE THREAD

**Issue by Daxxas** [CarlosEsco/Neko#373]
### Device information
* Tachiyomi version: 2.1.4.3
* Android phone & version: OnePlus 6 - Android 10 - Oxygen 10.3.7

## Steps to reproduce
1. Find "Hellper" in mangadex through neko : (this manga https://mangadex.org/manga/9065/)
2. Refresh the manga

### Expected behavior
No error

### Actual behavior
There is an error : 
```
HELLPÆŽR: Unexpected JSON token at offset 7128: Expected string or non-null literal
JSON input: .....ManScans"},{"id":52289,"name":null},{"id":697,"name":"Madman.....
```
If the manga is added to the library, each refresh the library, there will be an notification for the error a bit not cool to see every day

Thanks you for the support :)

**Comment by CarlosEsco** [comment]
fixed in latest release
