### ISSUE TITLE
[Bug] more language filter description error

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#375]
### Device information
* Tachiyomi version: 2.1.4.4
* Android phone & version: note9, android 10

### Expected behavior
Show only selected language

### Actual behavior
This happened instead.

### Other details
https://mangadex.org/title/44144/nan-hao-shang-feng

**Comment by CarlosEsco** [comment]
https://mangadex.org/manga/36246/

**Comment by CarlosEsco** [comment]
https://mangadex.org/manga/15147/

**Comment by CarlosEsco** [comment]
59218
