### ISSUE TITLE
[Bug] Favourited Webtoon/Manga did not pop out in Library

### ISSUE THREAD

**Issue by blueshidae** [CarlosEsco/Neko#376]
Webtoon/Manga did not pop out in the library after adding as favourite, those that were previously marked was gone from the library as well.

**Comment by CarlosEsco** [comment]
can you set a filter, then clear the filters in the library.  There sometimes is a bug with the filters that will have one enabled but it would show its enabled.

**Comment by blueshidae** [comment]
Ahhhh it works thanks!
