### ISSUE TITLE
[Bug] Removing manga from library triggers Download Complete notification 

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#377]
### Device information
* Tachiyomi version: 2.1.4.4
* Android phone & version: OP6A10

## Steps to reproduce
1. Add a new manga to library
2. Go to my library, unfavourite the manga and return back to library

### Expected behavior
The manga getting removed from the library 

### Actual behavior
The manga gets removed and also triggers a Download Complete notification

### Other details
https://discord.com/channels/349436576037732353/569823838305648640/794907289366429716
Note:
Happens when there is downloaded manga present in the library
If there are no mangas in the downloads(already downloaded), then it wont get triggered

**Comment by CarlosEsco** [comment]
2.1.5
