### ISSUE TITLE
[Feature Request] Filter changes to show full popup without the need to scroll

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#378]
### Why/User Benefit/User Problem
Having it pop up and without the need to scroll is more efficient. 

When I select filter, it is usually to filter scan groups but I have to scroll every time and it is not very efficient.

![Screenshot_20210102-135205_Neko.jpg](https://user-images.githubusercontent.com/59638889/103464466-e0fe4b80-4d01-11eb-9edd-0f8db32a8d00.jpg)

### What/Requirements
When selecting the filter for it to show up like this without the need to scroll down to view everything. 

![Screenshot_20210102-135210_Neko.jpg](https://user-images.githubusercontent.com/59638889/103464478-f83d3900-4d01-11eb-9c68-805eb8eb4e7d.jpg)

**Comment by CarlosEsco** [comment]
2.1.5
