### ISSUE TITLE
[Bug] Overgeared chapter 58 broken 

### ISSUE THREAD

**Issue by resnom117** [CarlosEsco/Neko#379]
---

### Device information
* Tachiyomi version: App version: 0.10.7 (standard, c87ba62, 53)
* Android phone & version: 
Android version: 8.0.0 (SDK 26)
Android build ID: LDN-L21 8.0.0.157(C432)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWLDN-Q
Device model: LDN-L21
Device product name: LDN-L21 

## Steps to reproduce
1. First step go to manga Overgeared click on chapter 58 
2. Second step get to see some pages of the chapter broken 

### Expected behavior
This should happen.  not have broken pages 

### Actual behavior
This happened instead. click on chapter 58 get to see ( the image could not be decoded ) 

### Other details
Additional details and attachments.
![Screenshot_20210105-030417](https://user-images.githubusercontent.com/66078175/103599705-12476900-4f06-11eb-93b0-23f4bec76143.jpg)

**Comment by CarlosEsco** [comment]
can you try clearing the chapter cache in advanced settings then trying again.

**Comment by resnom117** [comment]
i would love to go in advanced settings if my phone did not freeze up the second i click on advanced settings and seconds later have Neko crash 
![Screenshot_20210107-051225](https://user-images.githubusercontent.com/66078175/103850425-7ead9e00-50a7-11eb-8fc0-d4d1fa25d701.jpg)

**Comment by CarlosEsco** [comment]
Nothing I can really do if you can't even access the menu in the app
