### ISSUE TITLE
[Feature Request] New Reader UI from TachiSY(TF version)

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#380]
Time to steal the New Reader UI  from TachiSY (TF version)  to shut up TF lol 😂😂😂

![Screenshot_20210106-083429.jpg](https://user-images.githubusercontent.com/22503748/103724790-3638a680-4ffb-11eb-85c6-bc6645778a18.jpg)

**Comment by CrepeTF** [comment]
Get **YOUR** SY Comics app from:
https://github.com/CrepeTF/SY-Comics

**Comment by CarlosEsco** [comment]
2.1.5
