### ISSUE TITLE
[Bug] Overlapping of action bar on reader view.

### ISSUE THREAD

**Issue by Mano5JP** [CarlosEsco/Neko#385]
### Device information
* Tachiyomi version: 2.1.5
* Android phone & version: Note 10+ 3.0

## Steps to reproduce
1. First step
 Open a manga with fullscreen

2. Second step
Click on screen to bring action bar.

### Expected behavior
Action bar shouldn't overlapped

### Actual behavior
Action bar is overlapped

### Other details
Additional details and attachments.

With fullscreen turned on.

![Screenshot_20210110-204227_Neko.jpg](https://user-images.githubusercontent.com/64928088/104131424-464bdf80-5387-11eb-8710-5db26367a1e2.jpg)

With fullscreen turned off.

![Screenshot_20210110-204337_Neko.jpg](https://user-images.githubusercontent.com/64928088/104131436-61b6ea80-5387-11eb-8827-560136ab85ab.jpg)

**Comment by CarlosEsco** [comment]
fixed in 2.1.5.1
