### ISSUE TITLE
[Bug] Page number while reading is gone

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#387]
### Device information
* Tachiyomi version: 2.1.5.2
* Android phone & version: Note9 Android 10

## Steps to reproduce
1. Settings
2. Reader
3. Turn on "Show page number"
4. Does not show page number on the bottom of screen while reading

### Expected behavior
Should show page number

### Actual behavior
No page number shown on screen

### Other details
Additional details and attachments.

**Comment by vipzzx** [comment]
Also doesn't work when it is turned on while reading. ![Screenshot_20210111-043704_Neko.jpg](https://user-images.githubusercontent.com/59638889/104164931-aca42280-53c6-11eb-99b9-423bb2d12a39.jpg)

**Comment by CarlosEsco** [comment]
In newest release
