### ISSUE TITLE
[Feature Request] Old UI

### ISSUE THREAD

**Issue by DrainLife0** [CarlosEsco/Neko#388]
sorry for my english.

Can you leave us a choice between the new UI of the version 2.1.5.2 and the one before plz?
I prefer a lot when readering a manga to have the param (and contrast adjusment etc ...) in the top if the screen, not the bottom.

Thks.

**Comment by CarlosEsco** [comment]
No plans to to add them back to the top.  What is your use case that you are changing parameters frequently?

**Comment by DrainLife0** [comment]
The bar at the bottom is now too big, when I scroll with my thumb (I hold my tablet with one of the bottom corner), 1 in 10 I touch the slidebar for pages and change page :(
With this version I'm must hold my tab with 2 hands, to scroll with my thumb in the middle of screen or with my index finger.

Sorry, I don't have enough vocabulary to express my ideas properly.

**Comment by CarlosEsco** [comment]
Why are you scrolling with the menu always showing?  I don't plan to make this configurable

**Comment by DrainLife0** [comment]
I hide it, but when I touch the bottom of the screen it appears and I can't avoid it (with my grab).
So ok, I need to find another way to read with only one hand or be really carefull when scrooling :'(

Thanks for your time.

**Comment by CarlosEsco** [comment]
Do  you have fullscreen enabled?  If you do it should only show when pressing the middle of the screen

**Comment by DrainLife0** [comment]
I do, but it popup really often, not all the time.

**Comment by DrainLife0** [comment]
Fullscreen is enabled, here a quick video: https://streamable.com/4l5xlb
The slidebar appears 3 times, and when I read, sometimes I touch it (even if it appear quick)

**Comment by CarlosEsco** [comment]
oh see thats seems to be a bug.  did your navigation buttons always show like that when swiping?  Can you send a screenshot of your reader setting sheet. Also what android version are you using

**Comment by DrainLife0** [comment]
When I have an app in fullscreen, the buttons always hide and I have to swip like that for them to reappears.
I have android 10, on a Samsung Galaxy Tab A 2018 (SM-T590)
Here the param : ibb.co/vCWWwXp

**Comment by CarlosEsco** [comment]
maybe its something with samsung, the buttons shouldnt be showing on swipe.  Does the same thing happen on Tachiyomi?

**Comment by DrainLife0** [comment]
On Tachiyomi it's work fine, the slidebar never appears when swiping.

**Comment by arkon** [comment]
We've had similar reports from Samsung users of the toolbars randomly appearing when scrolling.

**Comment by CarlosEsco** [comment]
@DrainLife0 to you have navigation bar set to auto hide in your system settings?

**Comment by DrainLife0** [comment]
I have very few options for the nav bar, I can't change this :(

**Comment by DrainLife0** [comment]
I stop bothering you with this.
If I set the full screen option off in Neko, the nav bar is always up and the bug disappear.
It's not as "beautiful" but at least I can swipe safe ^^

Thks
