### ISSUE TITLE
[Feature Request] Bookmark from chapter list

### ISSUE THREAD

**Issue by creeper82** [CarlosEsco/Neko#391]
### Why/User Benefit/User Problem
Adding bookmarks from long click popup menu would be awesome.
Normally, you have to open reader and slide up mini chapter list. The problem however (that i don't want to mark as bug because it definitely doesn't count as one) is that everytime I mark something the list moves all the way back to the chapter you're on.

### What/Requirements
A possibility to add bookmarks from basic tap and hold menu (example on screenshot below, drawn by finger unfortunately)
![Screenshot_20210112_181326_tachiyomi mangadex_edit_29538781337157](https://user-images.githubusercontent.com/66107554/104348761-681da180-5502-11eb-8478-981b0c72b056.png)

I want to tell that it's gonna be rarely used (in my case I've already known which chapters i want to bookmark. Normally, the user probably would do it during reading).
Sorry, if I've messed something up there. I'm new on GitHub...

**Comment by CarlosEsco** [comment]
you can swipe the chapter from left to right to bookmark it
