### ISSUE TITLE
[Bug] Lag when removing favourited manga

### ISSUE THREAD

**Issue by DuccinatorAlpha** [CarlosEsco/Neko#393]
### Device information
* Tachiyomi version: Latest
* Android phone & version: idk,,,Android 11 AOSP?

## Steps to reproduce
1. Have a manga in library
2. Unfavourite it

### Expected behavior
no lag
### Actual behavior
lag

**Comment by Tigoreetur** [comment]
Have you downloaded the maga chapters?
If yes, then neko is deleating them and I think that is causing it.

**Comment by CarlosEsco** [comment]
@Tigoreetur  yea, it shouldnt though. Its definitely a bug

**Comment by CarlosEsco** [comment]
In newest release
