### ISSUE TITLE
[Bug] Unread chapters hidden by scanlator filter still show in unread count in library

### ISSUE THREAD

**Issue by Xarano-GIT** [CarlosEsco/Neko#395]
### Device information
* Tachiyomi version: 2.1.5.2
* Android phone & version: Galaxy Tab S6, Android 10

## Steps to reproduce
1. Add manga to library, note unread chapter count
2. Filter scanlator groups in that manga
3. Return to library

### Expected behavior
The unread chapter count should decrease by the amount of chapters that were hidden by the filter

### Actual behavior
Count remains the same

**Comment by CarlosEsco** [comment]
This is by design. In case a new scanlator is added you would not miss chapters.  If you are current with the series, in the library view long press the manga and click mark read.  So the scanlators you don't care about get marked read

**Comment by Xarano-GIT** [comment]
If a new scanlator is added, surely they would be ticked by default in the filter, so they wouldn't be affected by removing hidden scanlator's chapters from the count?

**Comment by CarlosEsco** [comment]
even then.  There are no plans to do this.  Take for example does it make sense to say download badge = 0 when you filter a chapter list by not downloaded?

**Comment by Xarano-GIT** [comment]
> even then. There are no plans to do this. Take for example does it make sense to say download badge = 0 when you filter a chapter list by not downloaded?

Perhaps it could be added as a global option?

**Count unread chapters from hidden scanlators - Yes/No**

**Comment by CarlosEsco** [comment]
https://github.com/CarlosEsco/Neko/issues/396
