### ISSUE TITLE
Description fixes

### ISSUE THREAD

**Issue by CarlosEsco** [CarlosEsco/Neko#400]
https://mangadex.org/title/33537

**Comment by Goku003** [comment]
https://mangadex.org/manga/36075/

**Comment by CarlosEsco** [comment]
https://mangadex.org/title/47406

**Comment by CarlosEsco** [comment]
https://mangadex.org/title/60349

**Comment by CarlosEsco** [comment]
https://mangadex.org/title/43725

**Comment by CarlosEsco** [comment]
https://mangadex.org/manga/44992/
