### ISSUE TITLE
[Feature Request] exclude finished manga from update check

### ISSUE THREAD

**Issue by Dediggefedde** [CarlosEsco/Neko#401]
It would be nice if I could mark a manga as completed and exclude it from update checks.

### Why/User Benefit/User Problem
I like to keep finished manga in the list for later rereads or if I want to buy the manga once an official localization happens. However, all mangas are checked every time I request an update, which can take a long while for a long list.

The Workaround is either remove completed mangas from my favourites and keep track elsewhere or to check on mangadex for updates and only update those single manga in the app.

### What/Requirements
For example in the manga-title screen a button to mark them as completed or to "disable updates" that sets an internal flag to exclude the manga from update checks.

**Comment by CarlosEsco** [comment]
Move them into a category that doesn't get updated

**Comment by Dediggefedde** [comment]
I just found out how to make categories and from that has to exclude them from updating, Wich is basically including what I wanted.^^

**Comment by CarlosEsco** [comment]
Another tip is you can show all in library so even if you have categories that don't update.  it will still be one giant list of manga like if you had no categories.
