### ISSUE TITLE
[Bug] Sync Mangadex manga to Neko doesn't sync a lot of mangas

### ISSUE THREAD

**Issue by ArataKamikaze** [CarlosEsco/Neko#402]
**Device information:**

    Tachiyomi version: 2.1.5.5
    Android phone & version: LG K61 on android 10

**Steps to reproduce:**

    Login to your mangadex account and on "MangaDex settings" click on "Sync MangaDex manga to Neko"

**Expected behavior:**

    All followed mangas on MDList that aren't yet on the Neko library are imported to Neko 

**Actual behavior:**
    
    No manga is imported and a message that says: "Synced 0 new manga from MangaDex" is shown on screen
    
**Other details:**
    
    It used to work before, but recently i added some mangas from mangarock to mangadex and noticed they weren't being
    imported to the app.

    I have 341 followed mangas on MD and when reinstalling Neko today the message showed around 270 mangas imported.
    
    I have tried:
    Cleaning the cache, data, database, downloaded chapters, cookies and covers.
    Refreshing tracking metadata.
    Syncing Neko to MangaDex then MangaDex to neko.
    Example Bellow:
![image](https://user-images.githubusercontent.com/49700094/105070051-7f5c1200-5a61-11eb-9735-426e210f661d.png)
![image](https://user-images.githubusercontent.com/49700094/105070129-9995f000-5a61-11eb-900b-5a05675eec80.png)
![image](https://user-images.githubusercontent.com/49700094/105070163-a9153900-5a61-11eb-854b-516937ee1c68.png)

    In Browser i can find the manga, but as you can see it has not been added to my list
![image](https://user-images.githubusercontent.com/49700094/105070303-d95cd780-5a61-11eb-9d2b-c091c50fd33d.png)
![image](https://user-images.githubusercontent.com/49700094/105070322-df52b880-5a61-11eb-8dce-d0bc11ea89c7.png)

**Comment by CarlosEsco** [comment]
In a logged in browse go to https://api.mangadex.org/v2/user/me/followed-manga
verify what the manga in this screens shows as a followed status number.  If its not 1 then its the known api server cache issue that MangaDex is looking into to fix

**Comment by ArataKamikaze** [comment]
i checked and the ones that i noticed to not be imported, didn't even show on the list

**Comment by CarlosEsco** [comment]
Yep api server cache issue. Nothing I can do until dex fixes

**Comment by ArataKamikaze** [comment]
sad

**Comment by CarlosEsco** [comment]
fixed in latest
