### ISSUE TITLE
[Bug] Weird refresh when marking chapters as read/unread/bookmark

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#403]
### Device information
* Tachiyomi version: 2.1.5.5
* Android phone & version: note9 android 10

## Steps to reproduce
1. select manga from library
2. swipe chapter to mark as read/unread/bookmark

### Expected behavior
No weird animation/refresh thing

### Actual behavior
Weird animation when swiping chapters. 

### Other details
This doesnt happen when you are in browse.
https://discord.com/channels/349436576037732353/569823838305648640/800974816067715082

**Comment by CarlosEsco** [comment]
fixed in latest
