### ISSUE TITLE
[Bug] Problem with backup file

### ISSUE THREAD

**Issue by camilo1505** [CarlosEsco/Neko#408]
### Device information
* Neko version: 2.1.5.5
* Android phone & version: Android 11 - MIUI 12.1.1 & Mi Note 10 lite

## Steps to reproduce
1. Going to Settings
2. Backup
3. Restore backup
4. Selecting the backup file

### Expected behavior
Should load the backup file and start to import all data.

### Actual behavior
Does nothing...

### Other details
i'm having problems loading a backup file into neko reader app, selecting the file does nothing.
URL video: [video](https://drive.google.com/file/d/103qFAVQWvNQt0HiWYflEFKl_F5D-7QUl/view?usp=sharing)
URL BackupFile: [File](https://drive.google.com/file/d/1j1OZx9O6m5AaZ6nqBPkMJzKBgYPcy8Ie/view?usp=sharing)

**Comment by CarlosEsco** [comment]
just checked your file, it seems fine and restored fine for me.  Make sure you are logged into all your services when doing a restore.  Backup restore is an online process my guess i mangadex had issues when you were trying
