### ISSUE TITLE
[Bug] Updates failed

### ISSUE THREAD

**Issue by cryaoooooo** [CarlosEsco/Neko#409]
### Device information
* Tachiyomi version: 2.1.5.5
* Android phone & version: Android 10 - MIUI 12.0.1 & Pocophone F1

## Steps to reproduce
1. Refresh library

### Expected behavior
It would update normally and show the latest chapter

### Actual behavior
It doesn't update and doesn't show any latest chapters and it says "updates failed" 

### Other details
I've tried uninstalling and installing it again but doesn't work. I've also tried clearing cache but it's still the same.

**Comment by CarlosEsco** [comment]
MangaDex servers are having issue, when a update does succeed there is no guarantee the latest chapter actually shows because of their cache issue.  Nothing i can do at this time.  We just have to wait
