### ISSUE TITLE
[Feature Request] Make badges only show updates for chosen scanlatots

### ISSUE THREAD

**Issue by Omniains** [CarlosEsco/Neko#410]
---

### Why/User Benefit/User Problem
Why- most of us have preferences for specific scans 
User benefit - less time to clear badges for chapters already read
User problem -thinking new chapter update is available/missed current chapter

### What/Requirements
The feature should work in tandem with the filter scanlator group feature to filter/hide chapters from badge notifications.

Seen here we have badges on manga

![Capture+_2021-02-07-03-27-25](https://user-images.githubusercontent.com/78679731/107141110-a84f2480-68f4-11eb-8aa5-d4872eef2f58.png) 

Here shows all current of preferred scanlator is read

![Capture+_2021-02-07-03-27-29](https://user-images.githubusercontent.com/78679731/107141137-dd5b7700-68f4-11eb-87bd-5365c860b638.png)

Shows preference of scanlator

![Capture+_2021-02-07-03-27-43](https://user-images.githubusercontent.com/78679731/107141145-ed735680-68f4-11eb-9437-3b5ec7d40d80.png)

Badge should not be shown till next chapter release by that scanlator.

**Comment by CarlosEsco** [comment]
This is by design, the badges on library are not meant to show info for manga specific filters.  It wouldnt make sense to set the download badge count to 0 if  were filtered by non downloaded in a manga.

**Comment by CarlosEsco** [comment]
doing it your way also prevents a user from seeing there are new releases if say reaper scan drops the manga
