### ISSUE TITLE
[Bug] Different chapters shown in-app and in webview

### ISSUE THREAD

**Issue by spamtaztik** [CarlosEsco/Neko#411]
## Device information
* Tachiyomi version: Neko 2.1.5.5
* Android phone & version: oneplus 7 pro, Android10

## Steps to reproduce
1. Refreshed chapter list for a manga (say "29-sai dokushin chuuken boukensha no nichijou"). It showed last chapter is chapter 29, updated 6 days ago.
2. Tried opening in webview. It showed last chapter is chapter 30, updated 1 hr ago (as of the time I wrote this).
3. Tried again for "dragon ego". It showed latest chapter is chapter 4 in chapter list, last updated Jan 31st.
4. Again, opened in webview. It showed latest chapter is chapter 9, updated 14 hrs ago. Actually there is a chapter 10 but it's not yet available for viewing.
5. Tried one more time for "abyss calling". App showed 3 chapters, webview showed 4.

### Expected behavior
Refreshing library (or individual manga) should load all chapters until the latest ones.

### Actual behavior
If I refreshed the library, the loading animation at upper right is moving, but after "update" is finished nothing's changed. I have some 60+ series in my library, at least one of them should be updated, no? But nothing happened. 
If I refreshed individual manga's chapter list, nothing happened too (even though there -are- new chapters in webview). 

### Other details
Actually Neko started acting weird after the MD database update/switch/whatever yesterday (or was it 2 days ago?). Before that I can update my library just fine.

Screenshots of said titles' chapter list and webview is attached.
![Screenshot_20210207-214317](https://user-images.githubusercontent.com/25314447/107150152-ffa1d300-698e-11eb-9896-84a18d394d2f.jpg)
![Screenshot_20210207-214329](https://user-images.githubusercontent.com/25314447/107150153-00d30000-698f-11eb-9d5d-2136ad8d7441.jpg)
![Screenshot_20210207-214512](https://user-images.githubusercontent.com/25314447/107150154-016b9680-698f-11eb-81c1-ee924fcc8412.jpg)
![Screenshot_20210207-214531](https://user-images.githubusercontent.com/25314447/107150155-016b9680-698f-11eb-9b6e-f590922b9ee2.jpg)
![Screenshot_20210207-214548](https://user-images.githubusercontent.com/25314447/107150156-02042d00-698f-11eb-8409-f5e081e4977b.jpg)
![Screenshot_20210207-214557](https://user-images.githubusercontent.com/25314447/107150157-029cc380-698f-11eb-99bf-a94f3f04efe8.jpg)

**Comment by CarlosEsco** [comment]
its a known issue with mangadex's cache server, i will have a work around out later today with the option to switch between servers

**Comment by spamtaztik** [comment]
Okey dokey.
Thanks much.
