### ISSUE TITLE
[Bug] App crashing after reading a manga 

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#412]
### Device information
* Tachiyomi version: 2.1.5.5
* Android phone & version: OP8T-A11

## Steps to reproduce
1. Completed reading a manga with no more chapters present
2. Press back button to go back

### Expected behavior
Should go back to library

### Actual behavior
App crashes

### Other details
Observed while reading long strip manga.
I normally read a manga directly from the library section start reading option
[2021-01-31-release.zip](https://github.com/CarlosEsco/Neko/files/5939241/2021-01-31-release.zip)

**Comment by CarlosEsco** [comment]
you still have this issue?

**Comment by Goku003** [comment]
I am not seeing the issue now.
Issue can be closed
