### ISSUE TITLE
Chapters not loading [bug]

### ISSUE THREAD

**Issue by DarkenedOrigins** [CarlosEsco/Neko#413]
When I pull down to update the new chapter will not load in even though the chapter exists and can be read on mangadex.

Example: the lady and the beast ch40 has been available since 2/6/21 but i am still unable to load it when i refresh and am stuck at ch 39. I would get an http error earlier but i do not even get that anymore.

device details:
name: oneplus 8
os: android 11

**Comment by CarlosEsco** [comment]
Update your app
