### ISSUE TITLE
Descriptions that need fixed

### ISSUE THREAD

**Issue by CarlosEsco** [CarlosEsco/Neko#419]
https://mangadex.org/title/19104

**Comment by CarlosEsco** [comment]
https://mangadex.org/title/23242

**Comment by henrik9999** [comment]
https://mangadex.org/manga/22743/
https://mangadex.org/manga/28420/
https://mangadex.org/manga/19104/
https://mangadex.org/manga/45252/

**Comment by CarlosEsco** [comment]
https://mangadex.org/title/46773

**Comment by CarlosEsco** [comment]
https://mangadex.org/title/27153

**Comment by vipzzx** [comment]
https://mangadex.org/title/35251

**Comment by CarlosEsco** [comment]
https://mangadex.org/title/44992

**Comment by CarlosEsco** [comment]
https://mangadex.org/title/44692

**Comment by CarlosEsco** [comment]
https://mangadex.org/title/35817

**Comment by CarlosEsco** [comment]
https://mangadex.org/title/34658

**Comment by vipzzx** [comment]
https://mangadex.org/title/19104

**Comment by vipzzx** [comment]
https://mangadex.org/title/59637

**Comment by vipzzx** [comment]
https://mangadex.org/title/43292
