### ISSUE TITLE
Library Transfer

### ISSUE THREAD

**Issue by MrGumms** [CarlosEsco/Neko#421]
Is there a way to transfer libraries from tachiyomi to Neko? I read that you can just use tachiyomis default backup and restore but I get a json error when I try to do that.

**Comment by henrik9999** [comment]
You need to make a legacy backup in tachiyomi. Neko will only transfer mangadex entries tho

**Comment by CarlosEsco** [comment]
see above.  Ask in the Neko channel on discord if you have any issues
