### ISSUE TITLE
[Feature Request] Add link to donate to MangaDex

### ISSUE THREAD

**Issue by akei-ai** [CarlosEsco/Neko#422]
This should be one of the priorities, seeing that mangadex is hosting the site for free, and can only continue based on their donations. So helping out the single source provider will ensure that the source lives and is providing good quality service to everyone, even the people who are new to manga.

I believe that this should be proudly on the frontpage of the app itself, as we want to help the mangadex staff do their jobs properly.

**Comment by CarlosEsco** [comment]
In the newest release
