### ISSUE TITLE
Issue (Don't know what to name it)

### ISSUE THREAD

**Issue by Ayushk222** [CarlosEsco/Neko#424]
![Screenshot_20210219-011139](https://user-images.githubusercontent.com/57125345/108415718-b6d00100-724f-11eb-9828-1f8ca949c26b.png)

It is about the message that appears. Anyone know what this means?

**Comment by CarlosEsco** [comment]
Can you explain what you were doing when the message occured

**Comment by Ayushk222** [comment]
> Can you explain what you were doing when the message occured

Refreshing the page.

**Comment by Ayushk222** [comment]
@CarlosEsco do you understand what it is?

**Comment by CarlosEsco** [comment]
The merged source is down right now

**Comment by Ayushk222** [comment]
@CarlosEsco ok. thanks!
