### ISSUE TITLE
[Feature Request] don't delete read bookmarked chapters

### ISSUE THREAD

**Issue by fiorire** [CarlosEsco/Neko#425]
### Why/User Benefit/User Problem
Makes rereading favorite chapter more convenient. Also already a feature in main Tachiyomi app 

### What/Requirements
Excluded bookmarked chapters from getting deleted after read

**Comment by fiorire** [comment]
Asked about it in discord, was told to leave a request here on github

**Comment by CarlosEsco** [comment]
In the newest release
