### ISSUE TITLE
[Bug] Mangadex data saver doesn't work

### ISSUE THREAD

**Issue by sombresu** [CarlosEsco/Neko#427]
Data saver work on Tachiyomi but not on Neko . One page can be 1MB each. 

---

### Device information
* Tachiyomi version: neko 2.1.5.6.1
* Android phone & version: Poco android 10

## Steps to reproduce
1. Turn on data saver in mangadex setting
2. Open any manga chapter

### Expected behavior
Data consumption reduced, reduced size of each pages

### Actual behavior
High quality

**Comment by holysnipz** [comment]
Might be related to this:
**[MD has announced recently that they'll DISABLE the Data-Saver system until they finished moving to new server system](https://mangadex.org/thread/423844)**

**Comment by sombresu** [comment]
I don't know but I opened and finished the same chapter from both Tachiyomi and Neko today. While Tachiyomi only spend 10MB, neko wasted a whole 30MB even though both data saver were on.

**Comment by CarlosEsco** [comment]
data saver doesn't work from dex at this time
