### ISSUE TITLE
[Feature Request] add new backup file support

### ISSUE THREAD

**Issue by GooseTheDuck** [CarlosEsco/Neko#433]
### Why/User Benefit/User Problem
Works with new backup files(proto.gz)

### What/Requirements
In the backup section there will be 3 options:  

* Create Backup (using the new .proto.gz format)
* Create Legacy Backup (using the original .json format)
* Restore Backup (which will work with .proto.gz and with .json)

**Comment by CarlosEsco** [comment]
In the newest release
