### ISSUE TITLE
Neko read chapters not synchronising with kitsu

### ISSUE THREAD

**Issue by KH1501** [CarlosEsco/Neko#434]
I acknowledge that:

- I have updated to the latest version of the app

### Device information
* Tachiyomi version: 2.1.5.6.1
* Android phone & version: xiaomi redmi 9; Android 10

## Steps to reproduce
1. Synch manga in neko to kitsu

### Expected behavior
Should synch manga and read chapters

### Actual behavior
Synchronises manga but doesn't synch read chapters

**Comment by CarlosEsco** [comment]
clear cookies, re login into mangadex and your trackers

**Comment by KH1501** [comment]
It only works when I have completed an unread chapter, not with already read chapters.
