### ISSUE TITLE
Wrong next chapter with multiple languages

### ISSUE THREAD

**Issue by Ansem93** [CarlosEsco/Neko#435]
### Device information
* Tachiyomi version: 2.1.5. 6.1

## Steps to reproduce
1. If a manga has multiple lenguages, when you finish a chapter it will send to the same chapter but different lenguage. 
Example: 

### Expected behavior
It should load the next chapter in the same lenguage, possibly of the same translator.

### Actual behavior
reading ch1 of the English translation. Finish it and go to the next chapter. It will load the ch1 in the other lenguage instead of ch2 in English 

### Other details
I don't know any nanga with multiple translator for the same lenguage, so I couldn't test it

**Comment by CarlosEsco** [comment]
If you have multiple languages enabled there is no filter for languages when reading.  You need to enable skip marked as read and mark those chapter read

**Comment by CarlosEsco** [comment]
2.10.4 you can filter out the other language now.
