### ISSUE TITLE
[Feature Request] Include "Plan To Read" for Sync MangaDex to Neko Feature

### ISSUE THREAD

**Issue by MCSilverMask** [CarlosEsco/Neko#436]
### Why/User Benefit/User Problem
personally i have a lot of manga that i plan to read and this feature will help me track and sync easily, i read from both the website and app.

currently if i want to add some manga's that i plan to read in the website, i have to change its status to reading, then turn it back to plan to read on both website and app

**Comment by CarlosEsco** [comment]
I'm a bit confused.

If you add the manga and you switch the mdlist tracking to planned to read it add it's to the website.

If you have the beta setting enabled adding the manga does this for you.

**Comment by MCSilverMask** [comment]
Yes for the last part, 

from the app to the website works great.

But whenever i use the website and mark a new manga "plan to read", it doesnt sync when i choose the option "sync MangaDex to Neko", so i have to mark it "Reading" on the website so it can sync with Neko and add it to the library.

**Comment by CarlosEsco** [comment]
in 2.2.1
