### ISSUE TITLE
[Feature Request] A way to get chapter from other sources

### ISSUE THREAD

**Issue by itskareem** [CarlosEsco/Neko#437]
I wish there's a way to get chapter from other sources like Mangapark, I know Neko is specific for Mangadex but i can't find some chapter like in Onepunch-man and others

### Why/User Benefit/User Problem
There's a lot of manga that have been taken down from Mangadex so it'd be nice if we get a way to get from other source without leaving Neko since it's the best Tachiyomi fork for me

**Comment by CarlosEsco** [comment]
Have you tried the merged button? On the manga info screen.
