### ISSUE TITLE
[Bug] manga page won't show latest chapter couple days or lost chapters

### ISSUE THREAD

**Issue by DewilNella** [CarlosEsco/Neko#438]
**PLEASE READ THIS**

---

### Device information
* Tachiyomi version: 2.1.5.6.1
* Android phone & version:  Samsung Galaxy Tab S5e (SM-T725) & Android 10 with 1 february 2021 security patch

## Steps to reproduce
1. go browse tab and select some manga from with IN LIBRARY text or without that
2. then try update manga info/chapters sliding finger in screeen from up to down.

### Expected behavior
it should update latest chapters.

### Actual behavior
won't update chapters or some times lost chapters.

### Other details
Additional details and attachments.
under link some screenshots (better os info in tablet and detailed app info from neko) and videos from those problems:
https://drive.google.com/drive/folders/1enHmc8qkEMU0Asq81fzWFw55MAInSMPy?usp=sharing
i will delete those files after when problem is solved.
here links to some mangas in videos and mangadex page:
https://mangadex.org/title/60350/housewife-x-jk
https://mangadex.org/title/51966/heroic-chronicles-of-the-three-continents

**Comment by CarlosEsco** [comment]
This is a dex api/server issue nothing i can do at this time

**Comment by beathell** [comment]
is there no info updates about mangadex API condition?

**Comment by CarlosEsco** [comment]
Make sure you have the use new api disabled in the mangadex settings
 I haven't had any issues recently, but I'm also not checking immediately after a release.  

As far update no.  Nothing we can do but wait

**Comment by CarlosEsco** [comment]
closing, if you have this issue still in 2.5.1 please reopen
