### ISSUE TITLE
[Bug] Neko crashes

### ISSUE THREAD

**Issue by DuccinatorAlpha** [CarlosEsco/Neko#442]
App crashes sometimes when you open a manga.
Crash log:
https://cdn.discordapp.com/attachments/569823838305648640/817491915888394281/neko_crash_logs.txt

**Comment by Goku003** [comment]
Crashing while library update, 
https://1drv.ms/t/s!AiTv35tre0rCj5A5zAxILwhWZZn1rA

**Comment by CarlosEsco** [comment]
both should be fixed in 2.2.2
