### ISSUE TITLE
[Feature Request] Encrypted or locked downloads folder

### ISSUE THREAD

**Issue by CyborgSemon** [CarlosEsco/Neko#443]
### Why/User Benefit/User Problem
It seems pointless to enable biometric lock on opening the app, if all the downloads are just stored in an open folder on the file system. Which in a lot of cases, just ends up getting shown as a recent file at the top of the system files app.
![Screenshot_20210306-155649_My Files](https://user-images.githubusercontent.com/26075792/110192716-bb71f780-7e94-11eb-9f95-90f3f09588f0.jpg)

### What/Requirements
The feature would be combined into the biometric lock feature. If the biometric lock feature is enabled, then all downloads would be stored in an encrypted or locked folder that would require the biometric auth to pass for it to be accessed.

**Comment by CarlosEsco** [comment]
no plans to add this.  As for seeing the images in your photo apps and what not.  It seems your phone did not add a .nomedia file add that to your folder and the file browser should ignore them, unless you directly open the folder

**Comment by CyborgSemon** [comment]
Ah ok. fair enough.
The `.nomedia` file is there however. Maybe its a bug with the android or samsung file system then?
