### ISSUE TITLE
Downloads on SD card delete themselves when I try to download more

### ISSUE THREAD

**Issue by CrowKingPro** [CarlosEsco/Neko#445]
### Device information
* Tachiyomi version: 2.2.1
* Android phone & version: Samsung Galaxy A71 5G running Android 10

## Steps to reproduce
1. Download over 25GB of manga from MangaDex onto an SD card in phone (sources other than MangaDex might not have this issue, not sure)

### Expected behavior
All Manga should download

### Actual behavior
Manga keeps downloading until around 25GB is taken up, after that, chapters start deleting themselves from the SD card as new ones are being downloaded. The folders where a series went is still there, but the folder is empty. I have 500GB free in space on the SD card. I also tried downloading a large amount on my normal phone storage and managed to download over 60GB, but started to run out of space and would like to use my SD card to store the manga on.

**Comment by CarlosEsco** [comment]
There should be nothing in the code that does this.  Can you verify you don't have something cleaning up the sd card.

**Comment by master-bob** [comment]
Software which can be used to test SD card capacity is listed below:
* Windows - [h2testw](https://www.heise.de/download/product/h2testw-50539)
* MacOS / Linux - [F3](https://fight-flash-fraud.readthedocs.io/en/latest/)
* Android - [SD Card Test](https://androidutils.io/sdcardtest/)

Unfortunately, I can not envision a way to workaround this in software. Also it appears to be an issue with a counterfeit SD card. As such I suggest this issue be closed.
