### ISSUE TITLE
[Bug] MD tracking does not allow partial chapters

### ISSUE THREAD

**Issue by Jerrk** [CarlosEsco/Neko#446]
### Device information
* Tachiyomi version: 2.2.1
* Android phone & version: note 8 android 9

## Steps to reproduce
1. change reading progress to partial chapter on mangadex
2. check reading progress on mangadex tracking in-app

### Expected behavior
mangadex tracking should allow partial chapters as same as the website does.
![](https://i.imgur.com/WGUGVN9.png)

### Actual behavior
mangadex tracking does not track partial chapters
![](https://i.imgur.com/8SJIYIe.jpg)

### Other details
not sure if bug report or feature request, but since it's possible on the MD website it should be possible in the app imo

**Comment by CarlosEsco** [comment]
Nothing i plan to fix in this version, since it would require the tracking service to be overhauled some

**Comment by CarlosEsco** [comment]
Closing this as tracking chapters isn't available on MangaDex for the foreseeable future (seems low priority for them)
