### ISSUE TITLE
[Bug] App Crashed probably related to Anilist tracking

### ISSUE THREAD

**Issue by salt0330** [CarlosEsco/Neko#447]
I just started using Anilist for tracking my manga library, then the app keep crashing that really never happened before

### Device information 
* Tachiyomi version: Neko 2.2.1
* Android phone & version: Redmi Note 5, Android 9 PKQ1.180904.001

## Steps to reproduce
The case that I found:
[1st case]
1. Set Anilist tracking
2. Start reading a chapter

[2nd case]
1. Set Anilist tracking
2. Just strolling around the App

### Expected behavior
Neko working normally, reading the chapter without crash

### Actual behavior
App crashed when tries to load the chapter. The other case is the app randomly crashed when I am strolling around the app (browse manga, see library, etc). 

### Other details
crash log that I found

[crash log 1]

--------- beginning of system
--------- beginning of main
03-08 08:17:30.229 17090 17124 E ||NEKO  : 	â”œ eu.kanade.tachiyomi.ui.reader.ReaderPresenter$updateTrackChapterRead$1$1.invokeSuspend(ReaderPresenter.kt:711)
03-08 08:17:30.229 17090 17124 E ||NEKO  : 	â”” kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-08 08:17:30.229 17090 17124 E ||NEKO  : java.io.EOFException
03-08 08:17:46.687 17090 17090 E WindowManager: 
03-08 08:17:46.687 17090 17090 E WindowManager: android.view.WindowLeaked: Activity eu.kanade.tachiyomi.ui.main.MainActivity has leaked window DecorView@8a0adce[MainActivity] that was originally added here
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:544)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.app.Dialog.show(Dialog.java:329)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at eu.kanade.tachiyomi.ui.manga.track.TrackingBottomSheet.show(TrackingBottomSheet.kt:61)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at eu.kanade.tachiyomi.ui.manga.MangaDetailsController.showTrackingSheet(MangaDetailsController.kt:1154)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at eu.kanade.tachiyomi.ui.manga.MangaHeaderHolder$19.onClick(MangaHeaderHolder.kt:105)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.view.View.performClick(View.java:6608)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.view.View.performClickInternal(View.java:6585)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.view.View.access$3100(View.java:785)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.view.View$PerformClick.run(View.java:25921)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:873)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.os.Looper.loop(Looper.java:201)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6810)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
03-08 08:17:46.687 17090 17090 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
03-08 08:17:54.228 17352 17352 E hiyomi.mangade: Not starting debugger since process cannot load the jdwp agent.
03-08 08:17:54.809 17352 17387 E SQLiteLog: (284) automatic index on C(manga_id)
03-08 08:17:54.809 17352 17387 E SQLiteLog: (284) automatic index on R(manga_id)
03-08 08:17:54.809 17352 17387 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)

[crash log 2]

--------- beginning of system
--------- beginning of main
03-08 08:09:26.642 15314 15314 E hiyomi.mangade: Not starting debugger since process cannot load the jdwp agent.
03-08 08:09:27.238 15314 15348 E SQLiteLog: (284) automatic index on C(manga_id)
03-08 08:09:27.238 15314 15348 E SQLiteLog: (284) automatic index on R(manga_id)
03-08 08:09:27.239 15314 15348 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)

**Comment by CarlosEsco** [comment]
can you clear cookies, and relogin to anilist and mangadex then try again

**Comment by salt0330** [comment]
yeah, after uninstalling the app now working fine :)
