### ISSUE TITLE
[Bug] Non english scanlators are not shown

### ISSUE THREAD

**Issue by donal56** [CarlosEsco/Neko#448]
### Device information
* Tachiyomi version:  2.2.1
* Android phone & version: Xiaomi Redmi 9 Android 10

## Steps to reproduce
1. Have an MD account with other languages configured, in my case spain spanish and latam spanish
2. Same configuration on neko
3. Search for [example manga](https://mangadex.org/title/3662/yumekuri)

### Expected behavior
Non-english scanlators chapters should appear

### Actual behavior
They dont. In the given example Ravens scans chapters should be listed but only two other english chapters are shown.

### Other details
If we open web view version from the manga page, chapters are listed as they should.

**Comment by CarlosEsco** [comment]
Do you have the other language enabled in the app?  under the mangadex settings?

**Comment by donal56** [comment]
It was already enabled. I cleared cookies and without me noticing neko started detecting all the other chapters, so its now solved. Thanks!
