### ISSUE TITLE
[Feature Request] Manga pulled from MD bookmark list should add to user's default category

### ISSUE THREAD

**Issue by Khan-MC** [CarlosEsco/Neko#450]
Mangas pulled from MD's bookmark list end up under the category "Default". Is it possible for them to be in the category I set as default for all my newly favourite-ed mangas to be in?

---

### Why/User Benefit/User Problem
Helps me sort out new mangas I recently favourite-ed. 

### What/Requirements
Mangas pulled from MD's bookmark list be in the category I set as default and not in category "Default".

**Comment by CarlosEsco** [comment]
in  5.2.4
