### ISSUE TITLE
app crashes after adding new manga

### ISSUE THREAD

**Issue by resnom117** [CarlosEsco/Neko#451]
---

### Device information
* Tachiyomi version: App version: stable 0.10.9 Neko version: 2.2.2.1
* Android phone & version: 
Android version: 8.0.0 
Android build ID: LDN-L21 8.0.0.157
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWLDN-Q
Device model: LDN-L21
Device product name: LDN-L21 

## Steps to reproduce
1. First step go to browse  search for manga
2. Second step add manga

### Expected behavior
This should happen.  add manga and let's me continue to browse manga's 

> 

### Actual behavior
This happened instead. adds mang but  app crashes 

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Can you try disabling the add to library as plan to read

**Comment by CarlosEsco** [comment]
should be resolved in 2.2.2.2
