### ISSUE TITLE
Ability to see rest of author/artists work 

### ISSUE THREAD

**Issue by AleksHR3** [CarlosEsco/Neko#452]
### Why/User Benefit/User Problem
In general, this is something that really helped me find the rest of someones work fast if one manga peaked my interest. It's also less hassle than copy paste in the search section. It just makes it easier find manga you want to read. The similar manga function doesn't show all their work. 

### What/Requirements
I think it would be nice to click on the creator's name, sending me to a new section, where you can see all their work. Name is already displayed next to the cover artwork. The placement could work well interactive.

**Comment by CarlosEsco** [comment]
Missed this on the browse redesign but it now doable, for a future release

**Comment by D-Brox** [comment]
This could even be a section in `Similar Manga`

**Comment by CarlosEsco** [comment]
You can click the author section now and then search
