### ISSUE TITLE
[Feature Request] Anime-Planet tracking

### ISSUE THREAD

**Issue by zivoy** [CarlosEsco/Neko#453]
### Why/User Benefit/User Problem
Anime-Planet's DB covers almost all of MangaDex, so it is a better tracking option than MyAnimeList in most cases. Also, AP does much better in the coverage of manhwa and manhua than MAL.
It is often linked when you click the globe icon, along with the MangaDex page and Manga Updates.

### What/Requirements
Like the MyAnimeList tracking but for Anime-Planet.

**Comment by CarlosEsco** [comment]
No plans to add anime planet unless they add a proper API.  You can use anilist, kitsu, or even MDList (which has all the manga because its from MangaDex).

**Comment by CarlosEsco** [comment]
I'll look into it
