### ISSUE TITLE
[Bug] I don't know what is wrong

### ISSUE THREAD

**Issue by RunicAce** [CarlosEsco/Neko#454]
### Device information
* Tachiyomi version: Neko 2.2.2.1
* Android phone & version:  OnePlus 7T | android 10

## Steps to reproduce
1. Try to download 'The reborn little girl won't give up' chapter 1
2. Wait

### Expected behavior
Should download with no problems

### Actual behavior
Failed to download, stopping at 34/38

### Other details
Error notification

Unexpected Json token at offset 0: Expected '{,  kind: Class'
Json input:

This is all i can see of the notification.

**Comment by CarlosEsco** [comment]
try in 2.2.2.2
