### ISSUE TITLE
Can't sign into Mangadex; Unknown Error

### ISSUE THREAD

**Issue by Hidlsh** [CarlosEsco/Neko#455]
When i try to explore the mangadex library through this app, it asks me to login - okay. When I try to login, I get "Unknown Error" everytime. 
![Screenshot_20210310-164738_Neko](https://user-images.githubusercontent.com/67646781/110708600-8a5d3400-81c0-11eb-9407-10356fb91b22.jpg)

**Comment by CarlosEsco** [comment]
Mangadex was down when you opened this.  It is back up now
