### ISSUE TITLE
[Bug] Unable to log out of MangaDex after breach

### ISSUE THREAD

**Issue by GJKrupa** [CarlosEsco/Neko#457]
### Device information
* Tachiyomi version: Neko v2.2.2.2
* Android phone & version: Samsung Galaxy Tab S7+ Android 11

## Steps to reproduce
1. Go into MangaDex settings
2. Tap logout
3. Confirm logout

### Expected behavior
The user is logged out of MangaDex and can log back in again.

### Actual behavior
There is a pop-up confirming logout but the user is still logged in even after terminating and restarting the app.

### Other details
MangDex suffered a serious data breach recently and terminated all existing user sessions as a result. I suspect a logout is attempted but fails because of an invalid session. In order to work around this I ended up having to wipe all app data and recover from a recent backup.

**Comment by vkhodygo** [comment]
I concur, I have the same issue on LOS 17.

**Comment by MCSilverMask** [comment]
i confirm it as will.

also adding the function "sync MangaDex to Neko" is not working at all

**Comment by lucscamps** [comment]
Going through the same thing here

**Comment by CarlosEsco** [comment]
You are logged out as FYI, its the apps internal just cache thinking you still are.  You can also clear your cookies in advanced settings.  Since the cookie is what determines if a user is actually logged in.

**Comment by WhitePhoera** [comment]
i did not saw that option, just cleared app data as whole.

anyway, this is bug :)

**Comment by CarlosEsco** [comment]
> 
> 
> i did not saw that option, just cleared app data as whole.
> 
> anyway, this is bug :)

glad you went nuclear when there was other options.  Its probably timing out trying to validate the logout took effect  Since logging in or out is 2 http calls now.    If their api server is updating immediately then its gonna say you are logged in when you aren't

**Comment by goldbattle** [comment]
You can always view the browse page in web-view and relogin through the webview.

**Comment by CarlosEsco** [comment]
2.2.2.3 has a more clear error message
