### ISSUE TITLE
[Bug] Library update issues after mangadex breach

### ISSUE THREAD

**Issue by KyoNendo** [CarlosEsco/Neko#458]
Manga in the library has failed to update multiple times to a unknown error. Don't know if that's helpful but thanks for reading this

**Comment by Giukia8x** [comment]
_mee too and I don't know what to do_

**Comment by goldbattle** [comment]
Try going into `Advance > Clear Cookies`, restart the app, and re-login.

**Comment by theesano** [comment]
@goldbattle  doesn't work for me, it displays :"Unexpected JSON token at offset 0" when I tried to relogin

**Comment by midi1996** [comment]
MangaDex is down for now, try again later.

**Comment by CarlosEsco** [comment]
2.2.2.3 has better error messages
