### ISSUE TITLE
[Bug] Login issues mangadex breach

### ISSUE THREAD

**Issue by bromine1** [CarlosEsco/Neko#459]
### Device information
* Tachiyomi version: ?
* Android phone & version: A51, android 11

## Steps to reproduce
1. First step

uninstall

2. Second step
login

### Expected behavior
logging in with the correct password and name should log you in, clicking on manga panels should open them and display chapters.

### Actual behavior
App says unknown error when you check it after leaving it claims you are logged in, app says "MangaDex error from Mangadex Response code 404"

### Other details
This happened after the breach, the app was failing to update most manga and I figured that uninstalling it might help. Unfortunately, logging in seems to be broken and manga seems to not load. I imagine that this isn't the fault of the Neko devs but the chaos and and update with the API, I'd just like some confirmation.

###Fix
For some reason I was not on the latest version despite downloading from here, my guess is my phone grabbed the old installer or something.

**Comment by Giukia8x** [comment]
Me too, I can't read manga

**Comment by goldbattle** [comment]
Try going into `Advance > Clear Cookies`, restart the app, and re-login.

**Comment by CarlosEsco** [comment]
What gold said.  I don't know if its region specific or not (i have no issues logging out and logging in).
- Make sure you are able to login through chrome on your phone
- Make sure you are using 2FA if you have it enabled
- Make sure you are typing in your password correctly

**Comment by Giukia8x** [comment]
What is 2fa

**Comment by Giukia8x** [comment]
?

**Comment by CarlosEsco** [comment]
Two Factor Authentication
