### ISSUE TITLE
[Bug] Write short description here

### ISSUE THREAD

**Issue by Impureshine** [CarlosEsco/Neko#460]
### Device information
App version: 0.10.9-3159 (standard, 609d8c96, 56)
Android version: 11 (SDK 30)
Android build ID: IN2020_15_210201
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus8Pro
Device model: IN2020
Device product name: OnePlus8Pro

## Steps to reproduce
1. Launch app
2. Refresh Library
3. Wait for library to update (or cancel update)

### Expected behavior
Should update all mangas in the library and give me a notification telling me which mangas updated 

### Actual behavior
After the library is "refreshed", I get a notification telling me the update failed

**Comment by CarlosEsco** [comment]
The api server seems to be causing issues for some people.  Try clearing your cookies in advanced settings.  Force closing the app.  Then relogging

**Comment by CarlosEsco** [comment]
#458
