### ISSUE TITLE
[Feature Request] avoid library updates if MangaDex is down

### ISSUE THREAD

**Issue by asdkant** [CarlosEsco/Neko#461]
### Why/User Benefit/User Problem
There's no sense in doing (size of library) requests if the site is down

### What/Requirements
Neko should be able to detect that mangadex is down (either by checking first, or keeping track of failed updates as it goes), and avoid trying to do a full lbrary update if it can't reach MangaDex. The user should also be notified differently (something like "the site seems to be down"). Maybe try to pull updates from somewhere (the twitter feed, discord, smth elese?) so the user has some more context.

**Comment by CarlosEsco** [comment]
2.2.2.3
