### ISSUE TITLE
[Bug] HTTP Error 502

### ISSUE THREAD

**Issue by Hidlsh** [CarlosEsco/Neko#462]
### Device information
* Tachiyomi version: Stable 0.10.9
* Android phone & version: A51 5G, Android 11

## Steps to reproduce
1. Open any manga 
2. Select Chapter

### Expected behavior
Should open chapter and pages

### Actual behavior
Automatically exited out of chapter and gave error: HTTP Error 502

**Comment by resnom117** [comment]
same problem here

**Comment by CarlosEsco** [comment]
Mangadex has been down for almost 24h.
