### ISSUE TITLE
[Bug] failed to login mangadex in neko

### ISSUE THREAD

**Issue by resnom117** [CarlosEsco/Neko#463]
### Device information
* Tachiyomi version: App version: stable 0.10.9 Neko version: 2.2.2.1
* Android phone & version: 
Android version: 8.0.0 
Android build ID: LDN-L21 8.0.0.157
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWLDN-Q
Device model: LDN-L21
Device product name: LDN-L21 

## Steps to reproduce
1. First step go start app
2. Second step try to login mangadex in neko

### Expected behavior
This should happen.  login mangadex account 

### Actual behavior
This happened instead. get to see  failed login

### Other details
Additional details and attachments.
![Screenshot_20210321-002806](https://user-images.githubusercontent.com/66078175/111888507-747c1a00-89dd-11eb-9444-b059af37b447.jpg)

**Comment by CarlosEsco** [comment]
The site is down and has been down for 24h
