### ISSUE TITLE
[Feature Request] Having the access to "Related series" from Mangadex's entry

### ISSUE THREAD

**Issue by Umairuem** [CarlosEsco/Neko#469]
### Why/User Benefit/User Problem
It is often required to see the related series of a manga you are reading, and going to the website mode or searching for them by general methods can be time-taking most times. So, it'll be a great feature if a manga's entry has all the related series (that are present in that entry's Mangadex site) at one place in the app too. It will make those much more accessible and easy.

### What/Requirements
On any entry in the library, there should be one section where all the "Related" series (as present in the mangadex website) are present. This can be accessible in 2 ways, either through 3 dots or through the entry's page here:
![Screenshot 2021-04-02 110257](https://user-images.githubusercontent.com/72981149/113386143-07845f00-93a3-11eb-98ec-437f7715aae1.png) 
Or if there's some better way you can implement this, it would also be appreciated.
Anyways, I think this will be a great addition to the app, as many times while reading some manga we find the need to go through the series that are related to the one we are reading.

**Comment by CarlosEsco** [comment]
If you enable similar Manga then you can see the related in the results.  
This suggestion will be in 3.x as i separated the related out from the similar
