### ISSUE TITLE
[Bug] Download notification keeps alternating

### ISSUE THREAD

**Issue by DuccinatorAlpha** [CarlosEsco/Neko#470]
When downloading 2 or more chaps simultaneously, there is a single download notification which keeps switching between the 2 chapters

It would be nice if the notification was broken up into 2

**Comment by CarlosEsco** [comment]
Is this still an issue?  The code around this has changed a bit

**Comment by CarlosEsco** [comment]
After reading on discord, there is no plans to change this. There can only be 1 notification, best i could do is make downloads go back to 1 at a time lmao
