### ISSUE TITLE
[Bug] Merging Chapters doesn't work

### ISSUE THREAD

**Issue by Gurrman375** [CarlosEsco/Neko#472]
### Device information
* Tachiyomi version: 2.3?
* Android phone & version: Android 11, Samsung A51

## Steps to reproduce
1. Enable cached api
2. Find manga
3. Merge Manga

### Expected behavior
Before it merged the chapter with no issues.

### Actual behavior
Now it attempts to search for the manga and fails to find it or gets blocked by cloud flair.

### Other details
![Screenshot_20210404-121619_Neko.png](https://user-images.githubusercontent.com/25113575/113519330-561b3000-9540-11eb-882e-194d37556d4e.png)![Screenshot_20210404-122309_Neko.png](https://user-images.githubusercontent.com/25113575/113519368-8b278280-9540-11eb-80fe-7946ead5eac1.png)

**Comment by CarlosEsco** [comment]
Mangalife is having cloudflare issues atm

**Comment by CarlosEsco** [comment]
In the browse screen, click the 3 dot and click open merged source in webview. If you can bypass the cloudflare it should work then

**Comment by Gurrman375** [comment]
Thank you.
Do you know when these issues will fix?

**Comment by CarlosEsco** [comment]
Opening the webview should resolve it.
