### ISSUE TITLE
Let merged chapters have higher priority if the user chooses to

### ISSUE THREAD

**Issue by DuccinatorAlpha** [CarlosEsco/Neko#473]
### Why/User Benefit/User Problem
sometimes life has better stuff than dex

### What/Requirements
maybe in the filter sheet there could be a button that lets you display the filtered out merged chapters and then the user can filter out the groups if they want

**Comment by CarlosEsco** [comment]
This was resolved on the details rewrite, you can filter out the "non" life scanlators
