### ISSUE TITLE
[Bug] Tracking is not working with MAL

### ISSUE THREAD

**Issue by itskareem** [CarlosEsco/Neko#474]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi version: 2.3
* Android phone & version: 7.0

## Steps to reproduce
1. Update manga chapter tracking on Neko
2. Go to tracking website and check the chapter

### Expected behavior
The same chapter you updated will be on the website

### Actual behavior
It doesn't change

**Comment by itskareem** [comment]
Even if i press update tracking metadata on settings it won't change
it works well on TachiJ2K

**Comment by CarlosEsco** [comment]
Can you add thhe manga name that is causing issues, so i have something to test against.

**Comment by itskareem** [comment]
@CarlosEsco it's with all the mangas

**Comment by CarlosEsco** [comment]
manga*  and okay.

**Comment by CarlosEsco** [comment]
This was fixed in the last release, or should have been
