### ISSUE TITLE
Non-merged chapter duplication issue

### ISSUE THREAD

**Issue by AlphaShadow897** [CarlosEsco/Neko#476]
Hi, I'm not a code-literate person so this explanation will not be consise or technical, but I'm having a problem - after updating to version 2.3 from a prior version of Neko (not sure which one, sorry) and turning on the newly added "use cached source" option for reading, most of the manga in my library have started producing duplicates of existing and non-merged chapters that act as though they weren't the same thing (reading part of one copy will not update any other copies to reflect the same change), report themselves with the same upload date/scanlation group details as the original, and do not vanish/cannot be removed in the current version of the app. I'm not sure if this problem will magically fix itself once MangaDex goes back up, but I want to report this now just in case because it is hindering my ability to use the app. As a random and possibly related aside, when I first encountered an instance of this chapter duplication, some glitch that might or might not have been related to the one I've just described set the saved page number (read: the one that gets saved to a chapter when you stop reading it and is loaded when you next click on that chapter) of all the chapters I could check to 19, which caused several crashes when trying to load chapters with less than 19 pages.

**Comment by CarlosEsco** [comment]
Do you have a screen shot you can share?  Alternatively message in the neko discord channel and I can look into there.

**Comment by AlphaShadow897** [comment]
@CarlosEsco 

> Do you have a screen shot you can share? Alternatively message in the neko discord channel and I can look into there.

I can indeed provide a screenshot of the duplicated chapters issue for you. The manwha in the screencap only has two unique chapters in the cached source, but my installation of the app has apparently taken those two chapters and cloned them four times for a total of 10 chapters (sadly, I can't show the whole list and the name of the story without taking two screencaps). 
![Uploading Screenshot_20210422-122323.png…]()
if the screenshot doesn't show up properly then I'll go to the discord and post it there

**Comment by CarlosEsco** [comment]
Discord will probably work better. I was unable to see it

**Comment by Nguyenman** [comment]
Did you ever fix this? Im having the same duplicate chapter problem.

**Comment by CarlosEsco** [comment]
> Did you ever fix this? Im having the same duplicate chapter problem.

Can you provide a screenshot

**Comment by CarlosEsco** [comment]
It's like this 
MangaDex extension is currently having issues as users may see new/duplicate chapters popping up. This is an issue on their end and will be worked at.

**Comment by CarlosEsco** [comment]
Closing this as cache source doesn't even exist anymore
