### ISSUE TITLE
[Feature Request] Support for MangaDex v5 API

### ISSUE THREAD

**Issue by sgallagher** [CarlosEsco/Neko#477]
### Why/User Benefit/User Problem
After a recent hack of MangaDex, the developers of that platform expedited their plans to move to a new version of the site. As of May 5th, 2021, they have opened the [v5 version](https://api.mangadex.org/docs.html) of the API for public beta testing. This will be the only way to interact with MangaDex moving forward.

### What/Requirements
Neko needs to migrate from its current v4 API implementation to the new v5 implementation.

**Comment by 19wolf** [comment]
What's the status of this?

**Comment by CarlosEsco** [comment]
> What's the status of this?

Still wip. Have a few more things to test and verify.

**Comment by 19wolf** [comment]
I don't mean to bug you but how's it going? Is there anything we (the users) can do to help?

**Comment by CarlosEsco** [comment]
> I don't mean to bug you but how's it going? Is there anything we (the users) can do to help?

It's done just didn't have time yesterday to debug android studio not wanting to sign the apk.  It should be out today
