### ISSUE TITLE
[enhancement] Add ranged download

### ISSUE THREAD

**Issue by joseph619** [CarlosEsco/Neko#48]
Add ranged download, where you can customize the selection of chapters to download. For example, chapter 5-17. This is one of the better features of Manga Rock missing from Tachiyomi. Current download feature isn't as user friendly.

Screenshots attached below

![0-02-01-c591cc1bcf37a544c2ba6f8c58272a3f0bda57b45410ddc59bc8da64c83d245e_d49f222](https://user-images.githubusercontent.com/34897862/55816341-10960a80-5ac0-11e9-990c-8acf7d744fe3.jpg)
![0-02-01-4484c1a028fa78f0f854692517d1d0803b46c353435640555366b2b72ec3d2a1_377efdd](https://user-images.githubusercontent.com/34897862/55816340-10960a80-5ac0-11e9-815e-81280b8afb45.jpg)

**Comment by CarlosEsco** [comment]
This actually should be done with the select between.

long press a chapter, then long press another.  then 3 dot select between

**Comment by fushinari** [comment]
@CarlosEsco This feature has now been lost since the switch to the J2K base. Any chances of bringing it back? This is why I feel like staying with OG Tachiyomi.

**Comment by CarlosEsco** [comment]
There isn't a good way to do this currently.

**Comment by fushinari** [comment]
So it's impossible?

**Comment by CarlosEsco** [comment]
at this time no.  I will look into adding it back for 3.x

**Comment by fushinari** [comment]
Nice. Should this be reopened?

**Comment by fushinari** [comment]
There is already a "Download custom range" option, but it's not as flexible as the original multi-selection feature. For example, you can't select from 10 chapters while excluding only one of them.

**Comment by CarlosEsco** [comment]
This level of downloading range will probably not return. There are several options now for alternatives
