### ISSUE TITLE
[Bug] Start and End date tracking don't work

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#485]
### Device information
* Tachiyomi version: 2.4
* Android phone & version: Oneplus 6t Android 10

## Steps to reproduce
1. Try to set start or end date

### Expected behavior
Start or end date is set

### Actual behavior
Nothing happens

**Comment by CarlosEsco** [comment]
Should be fixed in 2.5.0 but I forgot to test this one
