### ISSUE TITLE
[Bug] Trying to clean up orphaned chapters deletes all downloaded chapters

### ISSUE THREAD

**Issue by Jeglet** [CarlosEsco/Neko#487]
### Device information
* Tachiyomi version: 2.4
* Android phone & version: Samsung Galaxy S20U, Android 11

## Steps to reproduce
1. Download a chapter
2. Clean up orphaned chapters with Advanced > Clean up downloaded chapters

### Expected behavior
Deletes orphaned chapters

### Actual behavior
Deletes all downloaded chapters

**Comment by CarlosEsco** [comment]
Are you able to replicate it?  I'll have to double check the delete logic with the new folder format

**Comment by CarlosEsco** [comment]
also was it deleting old ones only (pre v5 update), or new ones?

**Comment by Jeglet** [comment]
I can replicate it every time I try to do it. It's deleting new ones too, even the ones I've added to my library after V5 update.

**Comment by Goretantath** [comment]
I have the same issue on android 10.

**Comment by CarlosEsco** [comment]
was fixed in 2.5.0
