### ISSUE TITLE
When I try to log in the log in button the writing on the button change to unknown error and nothing happens.

### ISSUE THREAD

**Issue by SiLv3r456** [CarlosEsco/Neko#488]
### Device information
* Tachiyomi version: newest 
* Android phone & version: Huawei Nova t5 & Android 10

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Log in 

### Actual behavior
Log in writing on button swichted to unknow error

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
can you try clearing your cache and relogin.  Also double check you didnt change your password when dex was backup

**Comment by SiLv3r456** [comment]
Ok´ I had changed the password and I tried both passwordat the beginning after it doesn‘t worked, I just forgot the new one.
Anyway thanks for the quick reply.
