### ISSUE TITLE
[Bug] Duplicated manga after migrating 

### ISSUE THREAD

**Issue by theresnobio** [CarlosEsco/Neko#489]
(I'm not a big tech savvy person so sorry if I'm not doing something obvious)

### Device information
* Tachiyomi version: 2.4
* Android phone & version: Nuu A7L 

## Steps to reproduce
1. Backup you're manga (I deleted it and reinstalled it because the migrating button didn't seem to work)
2. After backup is done click the migrate button 

### Expected behavior
I'm not sure what was supposed to happen but I'm guessing there should be no duplicated

### Actual behavior
I got duplicated manga

The duplicated manga also seem to act as if their own thing so if I update my manga it'll also update the duplicated one. Which seems to cause more errors than normal when updating.
Sidenote: could you please tell me about why on some manga there's more chapters in a Manga then there actually are. This has been happening before the v5 update) 
![Screenshot_20210517-093434](https://user-images.githubusercontent.com/84305225/118529420-58a0a600-b6f8-11eb-8e3d-d1d2b86d4b37.png)
![Screenshot_20210517-093416](https://user-images.githubusercontent.com/84305225/118529516-72da8400-b6f8-11eb-86c7-118ff4d2a288.png) 
![Screenshot_20210517-093407](https://user-images.githubusercontent.com/84305225/118529561-8259cd00-b6f8-11eb-9bad-2a59fb0e0002.png)

**Comment by theresnobio** [comment]
Thanks in advance!

**Comment by CarlosEsco** [comment]
Can you go me a favor take a manga that is duplicated click into the info page and click the share button
share the url here for both of them

**Comment by CarlosEsco** [comment]
Also can you provide the exact steps you did?

**Comment by theresnobio** [comment]
> Can you go me a favor take a manga that is duplicated click into the info page and click the share button
> share the url here for both of them
It seems to be the same url for both, original and duplicated, when trying to copy both urls
https://mangadex.org/title/a4e838c4-6ff9-4e4b-8f87-c3a20f36a4ce

**Comment by CarlosEsco** [comment]
interesting.  Can you remove all your entries.  Then restore the backup.  You should be fine then.  My guess is the v5 migration was running when you restored which is why it got duplicates

**Comment by theresnobio** [comment]
Ok imma try that

**Comment by theresnobio** [comment]
> interesting. Can you remove all your entries. Then restore the backup. You should be fine then. My guess is the v5 migration was running when you restored which is why it got duplicates

Thanks it worked
