### ISSUE TITLE
[Bug] Unable to login, and unable to log out, among a couple other issues.

### ISSUE THREAD

**Issue by Geoffrayylmao** [CarlosEsco/Neko#491]
### Device information
* Tachiyomi version: Stable 0.10.12
* Neko version: 2.4
* Android phone & version: Pixel 4 XL
  Android version 11

## Steps to reproduce (1a and 1b are interchangeable.)
1a. Attempt to login via Settings/MangaDex Settings/Login
* Receives **"Unknown Error"**

1b. Migrate to V5 then attempt to login via Settings/MangaDex Settings/Login (Appears as successful.)
* Receives **"Unknown Error"**

2. Go into Settings/MangaDex Settings/ and tab **"Use cached manga API source and search"**

3a. Attempt to login again via the same path **and I can login**, however none of my followed manga appears.

3b. Brings me to the "Browse" tab immediately, able to view cached manga, however Library is empty.

4. Sync MangaDex manga to Neko. I get a blank download prompt via notifications.
* Refresh Library, no manga in "Library". Restart app yields same result.

5. Attempt to login and then logout, however logging out does not work. Stay logged in even when restarting app.

### Expected behavior
I expect to be able to log out, and view followed manga.

### Actual behavior
Nothing appears, except in the Browse tab, and I cannot log out.

### Other details
Attempted reinstalling 3 times, and a few different remedies. However, nothing worked and wasn't able to figure it out.

Unknown Error Login:
![Screenshot_20210517-182849](https://user-images.githubusercontent.com/84355247/118564746-dd161780-b73e-11eb-8169-42052896a0e1.png)

Blank Download Notification when Syncing manga.
![Screenshot_20210517-183255](https://user-images.githubusercontent.com/84355247/118564764-e8694300-b73e-11eb-915b-2b28d425cdc2.png)

**Comment by CarlosEsco** [comment]
You main issue is you arent logging in.  Clear your cookies, disable use cached.  Attempt to login.   If you are getting unknown error you probably changed your password when dex was hacked or you are mistyping it.

**Comment by Goretantath** [comment]
I'm having the same issue.. Is there a reason that we have to login?

**Comment by CarlosEsco** [comment]
Neko is still tied heavily with login feel free to reach out on the discord channel if you need more help
