### ISSUE TITLE
[Feature Request] Add support For mangadex account Creation and Recovery

### ISSUE THREAD

**Issue by xavkno** [CarlosEsco/Neko#492]
### Why/User Benefit/User Problem
Currently users who want to create an account or recover an account are unable to do so unless they have knowledge of how to work with API's adding a way from within the app to do so using the Mangadex account API would solve this problem.
https://api.mangadex.org/docs.html#tag/Account

**Comment by CarlosEsco** [comment]
Yep i plan to add more of that support.  Though it probably won't be added before the MangaDex front end is back

**Comment by CarlosEsco** [comment]
Actually probably won't be added since it will require interacting with the captchas and what not, and that's not something i want to do at this time
