### ISSUE TITLE
[Bug] Choose languages to show doesn't work

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#493]
---

### Device information
* Tachiyomi version: 2.4
* Android phone & version: Oneplus 6t Android 10

## Steps to reproduce
1. Choose language English

### Expected behavior
Only show English chapters

### Actual behavior
Show every language chapter

### Other details
![Screenshot_20210522-100612.jpg](https://user-images.githubusercontent.com/51281790/119231252-8a917e00-bae5-11eb-8b3d-98fada26c130.jpg)
![Screenshot_20210522-100644.jpg](https://user-images.githubusercontent.com/51281790/119231255-8f563200-bae5-11eb-8ca0-a97e518b1081.jpg)

**Comment by KrzysztofMoryson** [comment]
I just experienced the same thing, application started downloading chapters for different languages to what I bookmarked.

**Comment by TheTabbingman** [comment]
Same happened for me and it was fine until today

**Comment by TheTabbingman** [comment]
Seems like it was a recent api update

**Comment by timozel** [comment]
Came here to report the same thing.

**Comment by TheTabbingman** [comment]
The extension has already been fixed, so neko will probably be fixed in the next update.

**Comment by CarlosEsco** [comment]
New neko is out
