### ISSUE TITLE
[Bug] Languages aren't filtered 

### ISSUE THREAD

**Issue by KH1501** [CarlosEsco/Neko#494]
### Device information
* Tachiyomi version: 2.4.1
* Android phone & version: xiaomi redmi 9 Android 10

## Steps to reproduce
1. First step
Open manga
2. Second step
Observe 

### Expected behavior
This should happen.
Manga language selected in settings should only be shown 
(in this case English) 
### Actual behavior
This happened instead.
Other languages like Russian, French and Spanish and the likes are shown as well 
Bug appeared after update from 2.4 to 2.4.1

**Comment by CarlosEsco** [comment]
This was an issue with dex api. Update your library and it should remove them
