### ISSUE TITLE
[Bug] "Clean up downloaded chapters" deletes unread chapters.

### ISSUE THREAD

**Issue by Tigoreetur** [CarlosEsco/Neko#496]
### Device information
* Tachiyomi version: 2.4.2
* Android phone & version: moto g5, 8.1.0

## Steps to reproduce
1. Use the "Clean up downloaded chapters"

### Expected behavior
Unread chapters don't get deleted.

### Actual behavior
Unread chapters get deleted.

**Comment by CarlosEsco** [comment]
#487
