### ISSUE TITLE
[Bug] Importing Legacy Backup Doesn't Overwrite

### ISSUE THREAD

**Issue by RairenMorioka** [CarlosEsco/Neko#498]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app

---

### Device information
* Tachiyomi version: 2.4.2
* Android phone & version: Samsung Galaxy S8 running Android 9

## Steps to reproduce
1. Login to MD, add AniList to trackers
2. Sync MangaDex manga to Neko
3. Import a generated version of legacy backup (snippet under additional)

### Expected behavior
Chapters marked read in legacy backup show as read in the app.

### Actual behavior
Chapters read status unchanged.

### Other details
Snippet of the backup (I can provide the full file if needed):
```json
{
  "version": 2,
  "mangas": [
    {
      "manga": [
        "/title/3bb0279f-a01d-4aa4-93e4-305800f4b83e",
        "Akatsuki no Yona",
        2499283573021220255,
        0,
        0
      ],
      "chapters": [
        {
          "u": "/chapter/519b36db-e3fe-4caa-ab44-141176d35fa9",
          "r": 1
        },
        ...
      ],
      "tracking": []
    },
    ...
  ],
  "categories": []
}
```

I did clear the app's data from the Android Settings and only logged in and restored the backup (without AniList configured) and it correctly flags the chapters as read.

The chapters it had as read didn't line up with AniList's values, either, and I didn't explicitly connect a tracker to the manga.

**Comment by CarlosEsco** [comment]
Legacy backup support has been removed in 2.5.0 so closing this
