### ISSUE TITLE
[Bug] Using certain tags don't return expected results

### ISSUE THREAD

**Issue by Jeglet** [CarlosEsco/Neko#499]
### Device information
* Tachiyomi version: 2.4.2
* Android phone & version: Samsung Galaxy S20U, Android 11

## Steps to reproduce
1. Enter browse
2. Filter to include only results tagged with crossdressing

### Expected behavior
Should show these results (results from MD extension)
![Screenshot_20210524-225102_TachiyomiJ2K](https://user-images.githubusercontent.com/31293237/119412573-66ec5480-bcec-11eb-928c-8aed89612bc9.jpg)

### Actual behavior
Shows these results 
![Screenshot_20210524-225106_Neko](https://user-images.githubusercontent.com/31293237/119412602-74a1da00-bcec-11eb-8a1f-62acd7123750.jpg)

### Other details
Both Neko and extension has default language set to English, and content ratings set to Safe and Suggestive.

**Comment by CarlosEsco** [comment]
oh man i knew i forgot something in the last release :disappointed:

**Comment by CarlosEsco** [comment]
Should be fixed in 2.5.0
