### ISSUE TITLE
Number next to the tracker icon indicating how many trackers are added

### ISSUE THREAD

**Issue by henrik9999** [CarlosEsco/Neko#501]
### Why/User Benefit/User Problem
Currently I always have to open the tracking menu to check if I have added tracking to a manga this could be prevented by showing an number next to the icon. Sy does this for example:

![Screenshot_20210526-001432](https://user-images.githubusercontent.com/22085664/119576254-ad0eea00-bdb8-11eb-8ef8-c40ffc6e0e9a.png)

### What/Requirements
Just a simple number that shows the count of trackers added

**Comment by CarlosEsco** [comment]
2.10.0
