### ISSUE TITLE
language

### ISSUE THREAD

**Issue by rbq12345** [CarlosEsco/Neko#502]
Application language cannot be changed

**Comment by CarlosEsco** [comment]
There are no plans to allow different application languages.

**Comment by rbq12345** [comment]
So it means that the application language can only use English?

**Comment by CarlosEsco** [comment]
yes

**Comment by rbq12345** [comment]
Thank you. Will other languages be added later

**Comment by CarlosEsco** [comment]
see the 1st comment i sent

**Comment by rbq12345** [comment]
Sorry to bother you, thank you for your answer, and I will continue to support you
