### ISSUE TITLE
[Bug] Field 'baseUrl' is required, but it was missing AND Unexpected JSON token at offset 0: Expected '{, kind: CLASS' JSON input: [blank here]

### ISSUE THREAD

**Issue by ayush-km** [CarlosEsco/Neko#503]
### Device information
* Neko version: 2.4.2
* Android phone & version: RealMe C12 Android 10

## Steps to reproduce
Update: So, this is happening more often now. On almost every series I try to download.
- Try downloading any chapter from MangaDex and sometimes it'll show either of the 2 errors in the title.

### Expected behavior
Chapters should download

### Actual behavior
Chapters not downloading

This happens:
![image](https://user-images.githubusercontent.com/57125345/120019795-4da41a80-c002-11eb-81f2-6833d14744a3.png)

And now this also happens:
![image](https://user-images.githubusercontent.com/57125345/120035148-8a2e4100-c017-11eb-81ee-d3d7e28be3c3.png)
This one happens a lot more often and on a lot of series

Also, whenever I try to press the v5 migration button the process ends in 2 - 3 seconds. Is this normal because I think the migration is failing?

**Comment by CarlosEsco** [comment]
Do you still have this issue?

**Comment by Ayushk222** [comment]
After the recent update the issue was gone for a few hours but then it happened again last night.

**Comment by CarlosEsco** [comment]
if it occurs on a chapter, does it consistently happen on that chapter, or does it go away eventually

**Comment by Ayushk222** [comment]
It happens on certain chapters and only goes away after a long time. Usually, it goes away the next day or a few days afterwards, sometimes it'd even go away immediately afterwards.

Take today for example, I downloaded 6 chapters of a series, except for chapter 2 the rest of them downloaded. I have been trying to download chapter 2 for 9 hours already and it still doesn't download.

**Comment by CarlosEsco** [comment]
ok i'll try to add some error logging around there in the next release.  See if we can get a better idea

**Comment by Ayushk222** [comment]
Ok. I hope everything goes well. Thanks for the help!

**Comment by CarlosEsco** [comment]
Should be fixed in 2.5.0
