### ISSUE TITLE
[Feature Request] SOCKS5 proxy

### ISSUE THREAD

**Issue by Goretantath** [CarlosEsco/Neko#504]
- I have updated to the latest version of the app

---

### Why/User Benefit/User Problem
https://www.reddit.com/r/mangadex/comments/no0cfi/mangadex_block_investigation/

### What/Requirements
Route requests through a SOCKS5 proxy to cirumvent Verison forcing TCP packets from mangadex.org to be dropped.

**Comment by CarlosEsco** [comment]
while this effects me to :sob:  I don't plan to add a proxy in app at this time.
