### ISSUE TITLE
Spy X Family

### ISSUE THREAD

**Issue by supersaiyandoyle** [CarlosEsco/Neko#505]
As far as I can tell, Spy X Family doesn't have a browse manga spot, but does have a merged source spot. Usually it's just an issue of the title being a different translation or simply a different romanization of the Japanese title, but SPYxFAMILY has that name in all languages, I tried looking up SupaiFamiri just in case, no dice.
I know Spy X Family used to be on mangadex, that's where I read it before it started getting officially translated, and even after it started being officially translated mangadex linked offsite to read it and kept track of the read chapters.
If it is in there and I'm just off, can you let me know what title I should be looking for?
Thanks.

**Comment by CarlosEsco** [comment]
This is an issue with the Dex api. Another exsmple is if you search Tokyo ghoul.  Tokyo ghoul:re doesn't show as a result. 

I'll let them know

**Comment by CarlosEsco** [comment]
Also I was able to find searching just spy
