### ISSUE TITLE
[Bug] "(Experiment) Mark MDList chapters read in app" isn't working

### ISSUE THREAD

**Issue by Bittah** [CarlosEsco/Neko#506]
### Device information
* Neko version: 2.4.2
* Android phone & version: Samsung Galaxy A71, Android 11

## Steps to reproduce
1. enable "(Experiment) Mark MDList chapters read in app" in Settings -> MangaDex settings
2. Press "Sync MangaDex manga to Neko"
3. Go to Library
4. Pull down to refresh (or open a specific manga and pull down to refresh that manga specifically)

### Expected behavior
All chapters that I've already read on MangaDex should be marked marked as read in neko.

### Actual behavior
Not a single chapter gets marked as read.

### Other details
I've also tried restarting my phone, as well as reinstalling Neko twice and enabled "(Experiment) Mark MDList chapters read in app" right after installing (once before and once after logging into MangaDex) to make sure that I didn't change some setting that could've conflicted with this function, but nothing worked.

**Comment by CarlosEsco** [comment]
Yeah that option right now doesn't work it's a pre-v5 thing. I'll be changing it and removing to something else later

**Comment by CarlosEsco** [comment]
This option was removed to prevent confusion in the latest release

**Comment by Bittah** [comment]
I just noticed that while read markers initially didn't work when the new MangaDex website launched, they finally implemented them a little while ago. Maybe it's possible for you to get them to work as well now? @CarlosEsco
