### ISSUE TITLE
[Feature Request] Add Conscrypt TLS 1.3 in Neko (pulled from upstream)

### ISSUE THREAD

**Issue by fourquestionmarksokay** [CarlosEsco/Neko#507]
### Summary
Adds a Google-made faster and battery-saving TLS library to replace the older, inefficient and sometimes broken system library found in older devices. It was also added to Tachiyomi  ([main code](https://github.com/tachiyomiorg/tachiyomi/blob/8a014ddb0c069700e367ab4eed2a4c75d3d8d072/app/src/main/java/eu/kanade/tachiyomi/App.kt#L55) and [Gradle dependency](https://github.com/tachiyomiorg/tachiyomi/blob/b03ebc1fa4d2fd4321ff736ddd9eda239fa2fdde/app/build.gradle.kts#L176)) due to these benefits, but the library itself adds up to 4 MB of APK size.

### What it Solves and User Benefits
Due to the fragmented nature of the Android ecosystem, many phones are often left on an older version of Android, sometimes even to the point of weird bugs that only exists on a single version. Google has responded to this by bringing [AndroidX](https://developer.android.com/jetpack/androidx): a set of libraries to make Android developers' lives easier and makes app development less tedious, however it doesn't cover everything (for example, media playback and encryption).

On the other hand, the limited power of smartphones (relative to desktop computers) and its sensitivity to battery life are also important to Google. SSL (really TLS) encryption usually uses AES, a standardised encryption algorithm to ensure that the only device that can read the data sent is the device who requested the data. However, it's [slow and battery-hungry](https://www.imperialviolet.org/2014/02/27/tlssymmetriccrypto.html) (note that recent flagship phones do have faster native AES instructions, but we do have our concerns on older phones which we cannot upgrade). 

To solve this, the Chrome team have added ChaCha20 and Poly1305 to the TLS standards and while there's an implementation on the older TLS 1.2, it's not standardised to the point of having two different variations: the older one was available from Android 5 and was used by Google, Facebook and CloudFlare only, and the standardised one which was only available for Android 8 devices and beyond and is the widely-supported one. It makes the decryption 3 to 5 times faster, while saving around 20-30% of the battery.

TLS 1.3 also added more benefits: [improved handshake (the process of setting up the encrypted connection) speeds](https://www.a10networks.com/blog/key-differences-between-tls-1-2-and-tls-1-3/) which benefits mobile users with high latency and the possibility of zero round-trip time requests (basically sending the request encrypted using the data from previous connections).

To make life easier for app developers, Google has developed [Conscrypt](https://github.com/google/conscrypt/) which allows seamless integration into Android apps. This allows applications to bundle updated TLS libraries instead on relying on what's on the device.

### Disadvantages
As this is an additional library, it adds additional size to the resulting APKs. Although the library is only up to 4MB in size, for some it might be too big for them.

### Requirements
Literally adding the dependency into `build.gradle` and intialising it at startup. That's it.

**Comment by arkon** [comment]
It was added to Tachiyomi mainline because there's sources where the servers only negotiate to TLS 1.3. I don't think that's the case for any of the sources used within Neko?

**Comment by fourquestionmarksokay** [comment]
@arkon:
> I don't think that's the case for any of the sources used within Neko?

I actually agree on that, MD@H requires TLS1.2 and Neko is Android > 7 so it connects, no problem. The concerns on battery life and faster setup times (especially that MD@H jumps from one node to the next for each chapters, so decreased handshake times ~~and no-one bothered 0-RTT really~~) is still valid point though.

**Comment by CarlosEsco** [comment]
I guess any future potential sources that are only TLS1.3 would be an issue.  Also if provides performance increases thats cool
