### ISSUE TITLE
[Bug] Sync mangadex to neko doesn't work

### ISSUE THREAD

**Issue by Tarumath** [CarlosEsco/Neko#509]
---

### Device information
* Tachiyomi version: 2.4.3
* Android phone & version: Samsung Galaxy Tab A 8.1.0

## Steps to reproduce
1. Click on "Sync mangadex manga to neko" button

### Expected behavior
Account library and neko library are synchronized
### Actual behavior
A synchronization notification is visible for one instant, then disapears and nothing else happen

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
There seems to be an issue with MangaDex at this moment.  Follows doesn't show on their front end either.

**Comment by CarlosEsco** [comment]
Should be fixed in 2.5.0
