### ISSUE TITLE
[Feature Request] set sorting chapters by chapter number as default

### ISSUE THREAD

**Issue by mshihabdeen** [CarlosEsco/Neko#510]
Currently, chapters for any manga are sorted by scanlation group.
To fix this I have to manually go to the chapter filter and set it to sort by chapter number

 

Please add a way to set the default sorting method to chapter number in the settings, or set the default sorting method to chapter number as a fix
---

### Why/User Benefit/User Problem
Despite being a small issue, this affects larger manga series with 100+ chapters more (try Initial D lol).

### What/Requirements
Chapters will sort from 1-100 instead of being sorted by each scanlation group

**Comment by CarlosEsco** [comment]
They aren't sorted by scanlator group, its an issue of it not updating source order when the chapter list doesn't change

**Comment by CarlosEsco** [comment]
in  5.2.4
