### ISSUE TITLE
App Crashes When Viewing Chapter List For Any Manga

### ISSUE THREAD

**Issue by kingkj52** [CarlosEsco/Neko#512]
Just read some chapters directly (clicked the notification directly to the chapter) this morning, and went through a chapter list a week ago, maybe, but now, when viewing the chapter list of any manga, the app crashes, usually with no message. This makes it impossible to read any manga that don't have a new release (e.g. a notification to go directly to the chapter). I did try restarting my phone and clearing the cache, to no avail.

**Comment by TheTabbingman** [comment]
Also started happening to me after I opened up the tracking menu

**Comment by kingkj52** [comment]
As an update, when it tries to update, or if I trigger a manual update, of the mangas (checks for new chapters), it crashes. This one always pops up with the "Neko keeps stopping" window, with options to close it or go to app info.

For more info, I have a vanilla, non rooted or modified Pixel 4 XL.

**Comment by CarlosEsco** [comment]
Logout, then relogin

**Comment by kingkj52** [comment]
That fixed it for me. Thanks! Sorry for pinging you on this. I'll add that
to the list of things to try next time.

**Comment by CarlosEsco** [comment]
Should be fixed in 2.5.0
