### ISSUE TITLE
[Bug] After a while, images/pages fail to load

### ISSUE THREAD

**Issue by KLsGAM1NG** [CarlosEsco/Neko#513]
### Device information
* Tachiyomi version: **Neko 2.4.3**
* Android phone & version: **moto g(9) plus** - **Android 10 + Magisk 23.0**

## Steps to reproduce
1. Read manga like normal.

### Expected behavior
Be able to read uninterrupted.

### Actual behavior
After about five chapters, or sometimes down to 20 pages, images seem to fail/not attempt to load. Showing the retry button, which does nothing.

### Other details
- **Clearing chapter cache in advanced settings resolves this until it happens again.** For some reason.
- This has been happening for more than a year now. It just hasn't really bothered me.
- It happens to every manga, but when it happens on one manga, it only affects that manga.
- Having a rooted phone/Magisk installed may cause this as it also happened to my previous phone. 
- [Here are the logs](https://gist.github.com/KLsGAM1NG/5d9b7230dfd39fbfa83bcdc70f6504ef) on log level EXTRA.
- It also just crashed when viewing a manga in the library for the first time in a while. [Logs](https://gist.github.com/KLsGAM1NG/ee89b6123406d9a8baaa6cb0ca8c8a0a).

**Comment by KLsGAM1NG** [comment]
The crashes were resolved with https://github.com/CarlosEsco/Neko/issues/512#issuecomment-861849838. Original problem still standing.

**Comment by iam-Ameena** [comment]
Same issue, Clearing cache resolves it but still annoying.

**Comment by CarlosEsco** [comment]
Yep I hope to have this fixed in next release

**Comment by CarlosEsco** [comment]
Should be fixed in 2.5.0
