### ISSUE TITLE
[Bug] Neko crashes when scrolling in the chapter tab

### ISSUE THREAD

**Issue by zekiz774** [CarlosEsco/Neko#514]
### Device information
* Tachiyomi version: 2.4.3
* Android phone & version: Redmi Note 6 Pro, Android 11

## Steps to reproduce
1. open any manga (tested with 2 mangas)
2. Scroll through the chapters

### Expected behavior
Scroll

### Actual behavior
App scrolls a little and crashes

### Other details
Crash log: https://del.dog/pracanulet
Idk if I read it right but it seems like it's an issue with the API implementation/the session.

**Comment by CarlosEsco** [comment]
Logout then relogin
