### ISSUE TITLE
[Bug] Write short description here

### ISSUE THREAD

**Issue by rinaTarigan** [CarlosEsco/Neko#519]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi version: neko v2.5.0
* Android phone & version:xiaomi android 9

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
view the manga when we click the browse section

### Actual behavior
can't connect to mangadex api after i update my app to v2.5.0. and i can't search the manga

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Can you message in the neko chat on discord
