### ISSUE TITLE
[Bug] Library  sort by Latest chapter not working

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#520]
### Device information
* Tachiyomi version: 2.5
* Android phone & version: OP8T-A11

## Steps to reproduce
1. Sort by Latest chapter in library

### Expected behavior
Sort the manga list either ascending or descending order

### Actual behavior
The manga list sorts wrt title in ascending order only

**Comment by CarlosEsco** [comment]
Should be fixed in 2.5.1
