### ISSUE TITLE
[Bug] Library Updates fails for the first time when we add manga by long pressing from the browse

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#522]
### Device information
* Tachiyomi version: 2.5
* Android phone & version: OP8T-A11

## Steps to reproduce
1. Add a new manga by long pressing of the manga
2. Refresh the library

### Expected behavior
It will show the update and load the manga metadata

### Actual behavior
First time it fails to pull the data and in the second refresh it fetches the data

### Other details
https://discord.com/channels/349436576037732353/569823838305648640/858718526286331914

**Comment by CarlosEsco** [comment]
Should be fixed in 2.5.1
