### ISSUE TITLE
[Bug] "More" selections can't be selected as the default.

### ISSUE THREAD

**Issue by Tigoreetur** [CarlosEsco/Neko#526]
### Device information
* Tachiyomi version: 2.5.0

## Steps to reproduce
1. Change the sort mode to "Sort by chapter number"

### Expected behavior
The button to "Set as default for all" appears.

### Actual behavior
The button to "Set as default for all" doesn't appear.

### Other details
When other changes are made and the "Set as default for all" is pressed the changes under "More" aren't selected as the defaults.

**Comment by CarlosEsco** [comment]
This was not an option before so its not a bug, unless I am misunderstanding 
https://github.com/CarlosEsco/Neko/issues/510
