### ISSUE TITLE
[Bug] MangaDex Login/Logout seems to be broken.

### ISSUE THREAD

**Issue by jaredanson** [CarlosEsco/Neko#527]
### Device information
* Tachiyomi version: 2.5.0
* Android phone & version: Pixel 2XL, Android 11

## Steps to reproduce
1. Go to settings
2. MangaDex settings
3. MangaDex Login
4. Logout
5. Nothing happens, it just closes the modal window similar as if i clicked cancel.

### Expected behavior
I would expect it to log me out, and the next time I click MangaDex Login it would ask me for my username/password

### Actual behavior
It doesn't log me out, if you click MangaDex Login a subsequent time it opens a Logout Modal window again.

### Other details
This has been happening for me for a long time, I believe it started even before Mangadex went through its issues and had to shut down for awhile. But i can't remember exactly.

**Comment by CarlosEsco** [comment]
after you click logout can you wait 3-5 seconds let me know if you log out.

**Comment by jaredanson** [comment]
@CarlosEsco i don't see any difference

**Comment by CarlosEsco** [comment]
Do you happen to the cache source enabled?

**Comment by CarlosEsco** [comment]
let me know if this works in 2.5.1

**Comment by jaredanson** [comment]
@CarlosEsco it does not, i don't see any difference

**Comment by CarlosEsco** [comment]
Are you getting an error now?

**Comment by CarlosEsco** [comment]
Can you dm me a video on discord

**Comment by jaredanson** [comment]
@CarlosEsco there is no error or any indication that anything happened. It just closes the modal as if you pressed cancel instead of logout.

**Comment by CarlosEsco** [comment]
@jaredanson  if you can get on discord and @ me we can hopefully dig into  your issues

**Comment by CarlosEsco** [comment]
fixed in 2.5.3
