### ISSUE TITLE
[Bug] Updates to chapters is not working for me.

### ISSUE THREAD

**Issue by jaredanson** [CarlosEsco/Neko#528]
### Device information
* Tachiyomi version: 2.5.0
* Android phone & version: Pixel 2XL, Android 11

## Steps to reproduce
1. Pull down on the screen to launch the update chapters
2. Update process kicks off but never gets anywhere.

### Expected behavior
It should update library

### Actual behavior
Nothing gets updated, i've let this update process go for 2 hours before killing it yesterday.

### Other details
I have done the v5 migration.

**Comment by CarlosEsco** [comment]
I'll leave this open but it should be fixed in the next release

**Comment by CarlosEsco** [comment]
Should be fixed in 2.5.1
