### ISSUE TITLE
[Bug] Can't Download Manga Chapters

### ISSUE THREAD

**Issue by hatsu20** [CarlosEsco/Neko#530]
### Device information
* Tachiyomi version: 2.5.1
* Android phone & version: OPPO F5 Youth & Android 7

## Steps to reproduce
1. Opening People Looked Down on Me for Having a Crummy Job but It Really Isn't All That Bad? manga.
2. Downloading the chapters.
3. Gives a message, "Attempt to invoke virtual method 'java.lang.String.org.jsoup.nodes.Element.data()' on a null object reference.

### Expected behavior
The chapters should be downloaded.

### Actual behavior
It gives me the message.

### Other details
![image](https://user-images.githubusercontent.com/50159250/123877245-6724e300-d96f-11eb-8d08-89eef590a3fa.png)

**Comment by CarlosEsco** [comment]
fixed in 2.5.3
