### ISSUE TITLE
[Bug] Updates to chapters still not working after 2.5.1 upgrade

### ISSUE THREAD

**Issue by jaredanson** [CarlosEsco/Neko#531]
### Device information
* Tachiyomi version: 2.5.1
* Android phone & version: Pixel 2XL, Android 11

## Steps to reproduce
1. upgrade to 2.5.1
2. it starts to update chapters, but never finishes.
3. the process hangs until you kill it. I waited for 35 minutes.

### Expected behavior
it should update the chapters

### Actual behavior
the update process never exits.

### Other details
if you try to do an update after killing the hanging update, it will revert back to the 2.5.0 behavior of never starting the update.

**Comment by X9VoiD** [comment]
Can confirm process hang during initial phases of chapter update and library-wide update (the phase when the notification hasn't shown any progress yet and just says "Neko"), but it eventually completes on my side.

**Comment by CarlosEsco** [comment]
@X9VoiD  does it eventually show the manga progress bar?  

@jaredanson because you have this an another logout issue, are you able to actually read?  Can you open a manga through the webview and it work?

**Comment by X9VoiD** [comment]
Yes the progress bar eventually shows up in the notification (that previously only shows "Neko" with cancel button, and during the moment that there's only "Neko", pressing any manga will hang the app until the progress bar shows up). The weird thing about it though is that it doesn't seem to be updated properly. The update process finishes faster than before as the changelog states but the notification only showed "some" mangas being updated and then suddenly it's done.

To clarify up some stuff:

- Open Neko
- Swipe down to update library
- "Updating Library" toast shows up
- An empty notification with "Neko" and "Cancel" button shows up

From this point on there's three branches I may take:

- Press any manga
- Neko hangs
- (Pressing cancel doesn't do anything)
- Neko's notification will eventually show a progress bar
- Neko is responsive again

or

- Press "Cancel" found in Neko's notification
- Neko is responsive again

or

- Wait until Neko's notification shows a progress bar
- Neko won't hang anymore if we press any manga

**Comment by CarlosEsco** [comment]
@X9VoiD so the change moved the processing more async, doing so the manga title has to be sent after it was processed.  Nothing is being dropped but i wouldnt be surprised if when two manga complete update they both send the title to the notification and it immediately overwrites the other one.

Thank  you for the clarifications and it looks like library update will be my next big rewrite

**Comment by jaredanson** [comment]
@CarlosEsco yes i can read manga just fine. It seems to be unrelated to chapter update and log in/out issues

**Comment by jaredanson** [comment]
@CarlosEsco just as an update, i upgraded to 2.5.2 and the chapters are still behaving the same way for me where the update process never finishes

**Comment by CarlosEsco** [comment]
@jaredanson 
In advanced settings enable log level extra
force close the app
do a library update
then when it gets stuck send the log file   located in the neko folder

**Comment by CarlosEsco** [comment]
fixed in 2.5.3
