### ISSUE TITLE
[Bug] Repeating Mangas in browse

### ISSUE THREAD

**Issue by L8teG8te** [CarlosEsco/Neko#532]
When browsing Manga at a certain point they start repeating from the beginning (see screenshot)
---

Screenshot: 
![Uploading Screenshot_20210701-120624_Neko.jpg…]()

### Device information
* Tachiyomi version: 2.5.1
* Android phone & version: Samsung galaxy S21+ 5G Android 11 

## Steps to reproduce
1. Open Neko
2. Go to browse

### Expected behavior
Show Manga from Mangadex

### Actual behavior
Shows the same couple Manga over and over

### Other details
Screenshot attached

**Comment by CarlosEsco** [comment]
Can you fix your screen shot?

**Comment by Goretantath** [comment]
I have this problem too but when I attempt to screenshot, it says the app doesn't allow screenshots..

**Comment by CarlosEsco** [comment]
> I have this problem too but when I attempt to screenshot, it says the app doesn't allow screenshots..

Turn off secure screen

**Comment by L8teG8te** [comment]
> > I have this problem too but when I attempt to screenshot, it says the app doesn't allow screenshots..
> 
> Turn off secure screen

Thanks worked for me 👍

**Comment by CarlosEsco** [comment]
Any screens of the repeating issue

**Comment by CarlosEsco** [comment]
closing as no screens have been provided
