### ISSUE TITLE
[Bug] Covers in browse say to update app on 2.5.1

### ISSUE THREAD

**Issue by Goretantath** [CarlosEsco/Neko#533]
- I have updated to the latest version of the app

---

### Device information
* Tachiyomi version: 2.5.1
* Android phone & version: Moto E 2020 edition, android10

## Steps to reproduce
1. Goto browse.
2. look at screen and see only one or 2 covers and a ton of update nag.
### Expected behavior
Covers should load.

### Actual behavior
Covers tell me to update when no update available.

### Other details
When tapping a update nag, the info page doesnt list anything and swiping down to refresh it just freezes the spinny circle animation so I have to press back on my phones bottom bar.

**Comment by Goretantath** [comment]
Also the notification for neko downloads just days Neko with a cancel button. Also one above it saying "Neko is running. Tap for more info or to stop the app.

**Comment by CarlosEsco** [comment]
1 issue per a ticket please.

Can you do the follow steps
1.  Click library on bottom nav
2.  open advanced settings
3.  clear database
4. cleared cached covers not in library
5. one the above is done then go to browse.  Any manga with the wrong cover click into and swipe refresh it

**Comment by CarlosEsco** [comment]
This should be resolved in 2.5.2
