### ISSUE TITLE
Doesn't display manga full screen in landscape mode when there is a notch

### ISSUE THREAD

**Issue by Bittah** [CarlosEsco/Neko#534]
### Device information
* Neko version: 2.5.1
* Android phone & version: Samsung Galaxy A71, Android 11

## Steps to reproduce
1. Open a chapter of any manga
2. Rotate phone to a horizontal angle to put it in landscape mode

### Expected behavior
The entire screen should be covered with the manga page.

### Actual behavior
A black column remains behind the camera notch.
![Screenshot_20210704-005520_Neko](https://user-images.githubusercontent.com/7165430/124368573-a8b0d900-dc62-11eb-8814-fa2b8ad5786f.png)

### Other details
The entire screen does properly get covered in portrait mode (while holding the phone in a vertical position), including the space next to the camera notch:
<img src="https://user-images.githubusercontent.com/7165430/124368472-9e420f80-dc61-11eb-8e14-64e6db5415c1.png" width= "33%">

Tachiyomi doesn't have this problem:
![Screenshot_20210704-004036_Tachiyomi](https://user-images.githubusercontent.com/7165430/124368474-a4d08700-dc61-11eb-8220-e84d55161de3.png)

**Comment by CarlosEsco** [comment]
At this time this is expected.   In most manga there is no benefit of drawing behind the notch as it cuts into the image.

**Comment by Bittah** [comment]
The notch is tiny and obstructs so little that I barely even notice it most of the time, so cutting off the entire column behind it is far less desirable since it makes the screen significantly smaller for no good reason.

**Comment by CarlosEsco** [comment]
Sure but it would probably actually require a change in https://github.com/Jays2Kings/subsampling-scale-image-view

**Comment by CarlosEsco** [comment]
There are no plans to change this and J2K does not plan to either.  It makes little sense to allow drawing behind the notch when it would end up covering the image.

**Comment by MMariusch** [comment]
Don't really get it why not. Currently notches are minority. Front camera is also getting smaller by each generation. Fullscreen in vertical works correctly i.e. camera and top notification bar are ignored so the image fill the whole display. It looks really good and I don't think that someone will report this as an problem.

Also if it were a option then everyone could decide if they want this or not.
