### ISSUE TITLE
[Bug] Cant Login (Unknown Error)

### ISSUE THREAD

**Issue by Bhomz365** [CarlosEsco/Neko#535]
### Device information
* Tachiyomi version: 2.3
* Android phone & version: Oppo A3s, 8.1.0

## Steps to reproduce
1. Start Neko
2. Settings->MangaDex Settings->MangaDex login
3. Fill in Username and Password
4. Press "Login"

### Expected behavior
That I can log in and browse MangaDex.

### Actual behavior
Cant login and it keeps saying "Unknown Error".

### Other details
I've been using Neko for a year then I decided to delete it 4 months ago and now it won't let me log in. I also tried changing my password because maybe I forgot it.
![212174925_130064259172767_4048056157738087398_n](https://user-images.githubusercontent.com/86921605/124390504-88465480-dd1e-11eb-851c-3cb6176ddfcb.jpg)

**Comment by CarlosEsco** [comment]
Update to the newest version please

**Comment by Bhomz365** [comment]
Thank you very much! ... sorry I didn't know 2.5.1 was the latest, for some reason 2.3 won't update to the latest, so I had to download the 2.5.1 apk file.

**Comment by CarlosEsco** [comment]
Can you login now?

**Comment by Bhomz365** [comment]
Yes, now it works fine thank you very much!
