### ISSUE TITLE
[Feature Request] Remove "show recently used sources" from App Shortcut settings

### ISSUE THREAD

**Issue by fleurc** [CarlosEsco/Neko#537]
### Why/User Benefit/User Problem
While it is merged from the J2K tachiyomi, it is a completely useless option in the settings of the app. By removing this it may unclutter and not confuse newcomers that think the feature is properly implemented and works.

### What/Requirements
The removal of the highlighted option from the settings, and possibly (if it isn't tangled with other important code) the removal of its code.
![App Shortcuts](https://user-images.githubusercontent.com/35513885/124533330-834dd780-dde8-11eb-87b7-00c729fa82aa.jpg)

**Comment by CarlosEsco** [comment]
Yep that wasn't supposed to be there :)
