### ISSUE TITLE
[Bug] App crashes when tapping "General" in settings

### ISSUE THREAD

**Issue by Paoleddu** [CarlosEsco/Neko#538]
As for the title, the app crashes when I try to open the "General" page in the settings;
it also crashes when I try to use the "search settings" functionality.

---

### Device information
* Tachiyomi version: 2.5.2
* Android phone & version: Samsung Z Flip 5G/SM-F707B - Android 11

## Steps to reproduce
1. First step: tap the three dots in the top right corner
2. Second step: tap "Settings"
3. Third step: tap "General"/tap "Search settings"

### Expected behavior
The "General" page should open

### Actual behavior
The app crashes

**Comment by Paoleddu** [comment]
https://user-images.githubusercontent.com/87008838/124571733-5c26f280-de48-11eb-8e3a-9d86136eb3aa.mp4

**Comment by CarlosEsco** [comment]
This will be fixed in next release its related to the theme changes that were done

**Comment by CarlosEsco** [comment]
fixed in 2.5.3
