### ISSUE TITLE
[enhancement] Add Language Flag in Manga Info 

### ISSUE THREAD

**Issue by as280093** [CarlosEsco/Neko#54]
As Manga are classified in 3 categories 
  
Manga info name eg.
![Catttpture](https://user-images.githubusercontent.com/25240839/56486029-edbe1a00-64f3-11e9-8a51-d1bef561794d.PNG)

| Sr.No |  Manga Type |  Api Line | Flag Icon |
| ------ | -------------- | ---------- | :---: |
| 1. | Manga |  ` "lang_name":"Japanese","lang_flag":"jp",` |  ![jp](https://user-images.githubusercontent.com/25240839/56486909-f95f1000-64f6-11e9-815f-9394cfe55b9c.png "Japanese")  |
| 2. | Manhwa |  `"lang_name":"Korean","lang_flag":"kr",` |  ![kr](https://user-images.githubusercontent.com/25240839/56486826-ae44fd00-64f6-11e9-8115-7b59a2996771.png "Korean") |
| 3. |  Manhua  |  `"lang_name":"Chinese (Simp)","lang_flag":"cn",` |  ![cn](https://user-images.githubusercontent.com/25240839/56486799-97060f80-64f6-11e9-996e-786bfc4f9f6c.png "Chinese (Simp)") |

Adding this in Manga info will help in understanding the manga style and if possible we can add auto reading style like for Manhwa Webtoon is required and if the flags data from MangaDex are stable then we can capture the flag data and auto change reading style to webtoon for korean and chinese language 

This will add 2nd feature called auto reading style. 

Here is the flags zip files, If this feature comes out 

| Sr.No | File name | img dimensions* | file size* |
| ----- | ------- | :-----: | ------- |
| 1. | [flags-mini.zip](https://github.com/CarlosEsco/MangaDex/files/3102485/flags-mini.zip) | ~30 px | 76.9KB |
| 2. | [flags-normal.zip](https://github.com/CarlosEsco/MangaDex/files/3102497/flags-normal.zip) | 550 px | 1.29MB |
|3. |  [flags-big.zip](https://github.com/CarlosEsco/MangaDex/files/3102501/flags-big.zip)  | 1600 px | 6.64MB |  
| 4. |  [flags-ultra.zip](https://github.com/CarlosEsco/MangaDex/files/3102509/flags-ultra.zip) | 2560 px | 11.3MB |

**Comment by CarlosEsco** [comment]
so i am going to add 3 flags.  but they support more then just these 3 when searching..

**Comment by CarlosEsco** [comment]
In 1.0.7
