### ISSUE TITLE
[Bug] Source sort order not working on new chapters

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#562]
### Device information
* Tachiyomi version: 2.5.2
* Android phone & version: Oneplus 6t Android 10

## Steps to reproduce
1. Sort by source order

### Expected behavior
Should sort by source order

### Actual behavior
Puts newly uploaded chapters first

### Other details
![Screenshot_20210707-135400.jpg](https://user-images.githubusercontent.com/51281790/124814061-29a1f600-df2b-11eb-9523-1267a8280b55.jpg)
Also it doesn't do this with all manga only some

**Comment by CarlosEsco** [comment]
This seems to be an api issue.  But will keep open until it's fixed

**Comment by CarlosEsco** [comment]
Should be fixed now they just release API change
