### ISSUE TITLE
[Bug] Library Update process shuts down after a couple titles

### ISSUE THREAD

**Issue by Valandil12** [CarlosEsco/Neko#563]
### Device information
* Tachiyomi version: 2.3.2
* Android phone & version: moto g power, android 11

## Steps to reproduce
Slide down screen in Recents to update library

### Expected behavior
The process should run and go through the library and update all of the titles

### Actual behavior
The process crashes after 2   ##titles
![Screenshot_20210707-170000](https://user-images.githubusercontent.com/87097546/124829175-413aa800-df46-11eb-965e-2b2a99843ac7.png)

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Please update to 2.5.2 then try

**Comment by Valandil12** [comment]
My apologies, I mistyped there. I am on 2.5.2

**Comment by CarlosEsco** [comment]
Can you try again in ten mins or so. They have been making some API bug fixes so that might have solved this

**Comment by Valandil12** [comment]
Yep, it still is having the same issue. I'm not sure if it has anything to
do on my end or what.

**Comment by Valandil12** [comment]
This should be the full log from the start of the library update, if it helps at all

> 1625698640180|D|||NEKO-TIMER|fetching chapters from Dex took 680 ms
> 1625698640189|D|||NEKO-TIMER|Fetch Chapters for  10,000 Light-Year Binoculars took 698 ms
> 1625698640712|D|||NEKO-TIMER|Manga Detail for  10,000 Light-Year Binoculars took 1220 ms
> 1625698640713|D|||NEKO-TIMER|Chapter and Manga Details for  10,000 Light-Year Binoculars took 1223 ms
> 1625698640740|D|||NEKO-TIMER|library manga 10,000 Light-Year Binoculars took 1254 ms
> 1625698640742|D|||NEKO|	├ eu.kanade.tachiyomi.source.online.handlers.MangaHandler.fetchMangaAndChapterDetails(MangaHandler.kt:26)
> 	└ eu.kanade.tachiyomi.source.online.MangaDex.fetchMangaAndChapterDetails$suspendImpl(MangaDex.kt:81)
> fetch manga and chapter details
> 1625698640767|I|||NEKO|	├ eu.kanade.tachiyomi.source.online.MangaDexLoginHelper.isAuthenticated(MangaDexLoginHelper.kt:44)
> 	└ eu.kanade.tachiyomi.source.online.MangaDexLoginHelper$isAuthenticated$1.invokeSuspend(Unknown Source:14)
> check token is authenticated false
> 1625698640768|I|||NEKO|	├ eu.kanade.tachiyomi.network.TokenAuthenticator$refreshToken$1.invokeSuspend(TokenAuthenticator.kt:36)
> 	└ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> Token is invalid trying to refresh
> 1625698641830|D|||NEKO-TIMER|Manga Detail for  30-sai made Doutei de Itara Mahou Shoujo ni Narimashita took 1085 ms
> 1625698641838|D|||NEKO-TIMER|fetching chapters from Dex took 1094 ms
> 1625698641840|I|||NEKO|	├ eu.kanade.tachiyomi.source.online.MangaDexLoginHelper.refreshToken(MangaDexLoginHelper.kt:55)
> 	└ eu.kanade.tachiyomi.source.online.MangaDexLoginHelper$refreshToken$1.invokeSuspend(Unknown Source:14)
> refreshing token
> 1625698641882|D|||NEKO-TIMER|Fetch Chapters for  30-sai made Doutei de Itara Mahou Shoujo ni Narimashita took 1138 ms
> 1625698641883|D|||NEKO-TIMER|Chapter and Manga Details for  30-sai made Doutei de Itara Mahou Shoujo ni Narimashita took 1140 ms
> 1625698641936|D|||NEKO-TIMER|library manga 30-sai made Doutei de Itara Mahou Shoujo ni Narimashita took 1195 ms
> 1625698641937|D|||NEKO|	├ eu.kanade.tachiyomi.source.online.handlers.MangaHandler.fetchMangaAndChapterDetails(MangaHandler.kt:26)
> 	└ eu.kanade.tachiyomi.source.online.MangaDex.fetchMangaAndChapterDetails$suspendImpl(MangaDex.kt:81)
> fetch manga and chapter details
> 1625698642011|E|||NEKO|	├ eu.kanade.tachiyomi.data.library.LibraryUpdateService$updateChaptersJob$3.invokeSuspend(LibraryUpdateService.kt:320)
> 	└ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 25: Expected start of the object '{', but had ':' instead
> JSON input: {"result":"ok","statuses":[]}
> 1625698642013|D|||NEKO|	├ eu.kanade.tachiyomi.source.online.handlers.MangaHandler.fetchMangaAndChapterDetails(MangaHandler.kt:26)
> 	└ eu.kanade.tachiyomi.source.online.MangaDex.fetchMangaAndChapterDetails$suspendImpl(MangaDex.kt:81)
> fetch manga and chapter details
> 1625698643742|E|||NEKO|	├ eu.kanade.tachiyomi.data.library.LibraryUpdateService$updateChaptersJob$3.invokeSuspend(LibraryUpdateService.kt:320)
> 	└ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 25: Expected start of the object '{', but had ':' instead
> JSON input: {"result":"ok","statuses":[]}
> 1625698656919|D|||NEKO|	├ eu.kanade.tachiyomi.ui.base.controller.BaseController$1.preDetach(BaseController.kt:47)
> 	└ com.bluelinelabs.conductor.Controller.detach(Controller.java:984)
> Detach view for RecentsController@26165b9
> 1625698661123|D|||NEKO|	├ eu.kanade.tachiyomi.ui.base.controller.BaseController$1.preAttach(BaseController.kt:43)
> 	└ com.bluelinelabs.conductor.Controller.attach(Controller.java:942)
> Attach view for RecentsController@26165b9
> 1625698664520|D|||NEKO|	├ eu.kanade.tachiyomi.ui.base.controller.BaseController$1.preDetach(BaseController.kt:47)
> 	└ com.bluelinelabs.conductor.Controller.detach(Controller.java:984)
> Detach view for RecentsController@26165b9

**Comment by Valandil12** [comment]
Also, I just checked to see if I could update individual titles manually, and it seems like for some titles it does work. I'm not sure if the search is just crashing at an early step or what. I have noticed that with the regular Tachiyomi app that it will crash if I search for some titles across multiple sources, though I'm not sure how that might relate to this issue

**Comment by CarlosEsco** [comment]
fixed in 2.5.3

**Comment by PeepeeEnthusiast** [comment]
Same issue and persist after update.

**Comment by CarlosEsco** [comment]
> Same issue and persist after update.

Can you message on the neko channel on discord
