### ISSUE TITLE
[Bug] crash opening reader settings

### ISSUE THREAD

**Issue by giosann** [CarlosEsco/Neko#564]
### Device information
* Tachiyomi version: 2.5.2
* Android phone & version: galaxy tab s6 - android 11

## Steps to reproduce
1. Open a chapter
2. Press the reader setting button

### Expected behavior
Reader settings should open

### Actual behavior
App crashes

### Other details
Recording:

https://user-images.githubusercontent.com/10052873/124905564-75fe3c00-dfe6-11eb-88a0-23a741ffa8a7.mp4

Logs:

[2021-07-08-release.txt](https://github.com/CarlosEsco/Neko/files/6783704/2021-07-08-release.txt)

**Comment by giosann** [comment]
I don't know if it is related or relevant but the app is also always reading from left to right and any change in the general reader settings is ignored. I can't test it in the chapter reader settings since it crashes.

https://user-images.githubusercontent.com/10052873/124906047-f45ade00-dfe6-11eb-9cb2-b20df4ee2a5d.mp4

**Comment by CarlosEsco** [comment]
Thanks for all info will look into for the next release

**Comment by CarlosEsco** [comment]
Believe this is related to theme issue and should be fixed in the next release

**Comment by CarlosEsco** [comment]
fixed in 2.5.3
