### ISSUE TITLE
[Bug] A few manga chapters aren't visible in drop down & Browse doesn't work

### ISSUE THREAD

**Issue by Northinger** [CarlosEsco/Neko#566]
### Device information
* Tachiyomi version: Latest
* Android phone & version: Xiaomi Resmi 9 Pro & Android 11

## Steps to reproduce
1. Do a global update
2. Updated chapter number is on the cover, but aren't in the manga page.
3. Can be read with read latest on cover image
### Expected behavior
Updated chapters should be visible.

### Actual behavior
Updated chapters are only available through read latest button on manga cover.

### Other details
So far it is only with two manga. Other info I can give is that latest chapters aren't shown in browse section. I'm not sure if this is a API issue, but manual updates work fine while updated chapters aren't in the browse section. Even if I try to sort by updated. 

[Here I recorded the issue I'm having](http://imgur.com/a/5IZ7bwt)

**Comment by CarlosEsco** [comment]
For manga like that can you go into filters, and reset the scanlator.  My guess is its hiding it and not showing that its filtered

**Comment by Northinger** [comment]
After a library update, chapters for one of the two series became visible. For other one new chapters are added and visible while the gap is still there and looks invisible to me in drop down. A new issue I can add is that one manga became unaccessible. It can be found in my follows, but can't be searched through browse. Chapters can be read and are visible but refreshing manga page in app returns mangadex error: unknown error.

**Comment by CarlosEsco** [comment]
For your other issue. Open a new ticket and attach the crash log after you get the error

**Comment by Northinger** [comment]
Error message after a library update simply says " Isekai Shikkaku: unknown error".  And below is the error I get after refreshing manga page manually. 

![IMG_20210710_002546](https://user-images.githubusercontent.com/87140863/125137996-785fb380-e116-11eb-9b8f-6180e1dcaee5.jpg)

**Comment by CarlosEsco** [comment]
like i said open a new ticket and provide a crash log
