### ISSUE TITLE
[Bug] Library Updates for individual category is not queueing up if library updates is in progress

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#567]
### Device information
* Tachiyomi version: 2.5.2
* Android phone & version: OP8T-A11

## Steps to reproduce
1. Check for library updates for one category
2. Add one more category for the update

### Expected behavior
The library updates should include the manga which is there in second category

### Actual behavior
The manga in the second category is queueing up.

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
Can you check if this works like you think in j2k still

**Comment by Goku003** [comment]
Yeah, that works in j2k.
Even neko shows, category added to the queue but that doesn't happens

**Comment by CarlosEsco** [comment]
in  5.2.4
