### ISSUE TITLE
[Bug] Brows sort order filter not working

### ISSUE THREAD

**Issue by Pikayoda** [CarlosEsco/Neko#568]
### Device information
* Tachiyomi version: V2.5.2
* Android phone & version: one+ 6T, Android 10

## Steps to reproduce
1. Go to browse and then filters.
2. Set "sort" filter to either "created at" or "updated at".

### Expected behavior
The mangadex list should show up in the requested order.

### Actual behavior
Nothing show up but an error message, making it impossible to see newly added chapters.

### Other details
The content of the error message :
"Unexpected JSON token at offset 7069
Expected start of the object '{' but had ':' instead"

**Comment by CarlosEsco** [comment]
fixed in 2.5.3
