### ISSUE TITLE
Merge option should read description to check for alt-title

### ISSUE THREAD

**Issue by Caio99BR** [CarlosEsco/Neko#571]
### Why/User Benefit/User Problem
Some mangas have the translated title as main title on ML, and this cause "No results found"

### What/Requirements
The app should search with alt name too or search the title in the description of ML

Example: Zannen Jokanbu Black General-san (No results found), but the alt-title is written on ML description (Precarious Woman Executive Miss Black General is on ML)

**Comment by CarlosEsco** [comment]
I don't think an automated way of doing this makes sense.  
Take for example
https://api.mangadex.org/manga/e78a489b-6632-4d61-b00b-5206f5b8b22b

Even when the data is corrected there are 4+ alt titles for en

Showing the alt titles makes the most sense, allowing the user to copy and search with those
