### ISSUE TITLE
[Bug] Marking read/unread in library view registering UI change

### ISSUE THREAD

**Issue by alvioh4** [CarlosEsco/Neko#574]
### Device information
* Tachiyomi version: Neko 2.5.3
* Android phone & version: 11

when u Delete/use mark as read  to much sometimes app bug that manga u delete/mark as read it does nothing and  any u cant read manga online still can from downloaded manga, i manage to "fix" this by force close apps

**Comment by CarlosEsco** [comment]
This is in the library view only correct?

**Comment by alvioh4** [comment]
> This is in the library view only correct?

yes

**Comment by CarlosEsco** [comment]
in  5.2.4
