### ISSUE TITLE
Library Updates removing downloaded chapters

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#575]
### Device information
* Tachiyomi version: 2.5.3
* Android phone & version: OP8T-A11

## Steps to reproduce
1. Either do a library updates or manually refresh the manga which has a merged source and has downloaded chapters from merged source

### Expected behavior
The downloaded chapters remains as it is

### Actual behavior
It deletes the downloaded chapters

### Other details
After manually refreshing one, it showed a pop-up. Chapters has been removed but all the chapters are present, maybe url would have changed but it happens like daily(thats what i observed) and if i keep it, it matches with the chapters as well.![Screenshot_20210711-082803.jpg](https://user-images.githubusercontent.com/22503748/125201954-fd6dd880-e28e-11eb-9ffa-29bbd6a9f31e.jpg)

Even though it shows Chapters removed, still the downloaded chapters matches with the newly one and re-download is not necessary.

As a workaround, i enabled keep the source removed chapters.

**Comment by CarlosEsco** [comment]
Is this repeatable, or only with old merge manga?

**Comment by Goku003** [comment]
It happened for two consecutive days, maybe i can give it a try.
But its not old merge, becz next day when i update it gets deleted

**Comment by Goku003** [comment]
I will close this, since i didnt see the same behaviour recently
