### ISSUE TITLE
[Bug] Library Updates doesn't progress if one of the manga update fails

### ISSUE THREAD

**Issue by Goku003** [CarlosEsco/Neko#576]
### Device information
* Tachiyomi version: 2.5.3
* Android phone & version: OP8T-A11

## Steps to reproduce
1. Refresh the library

### Expected behavior
It should refresh all the manga and in the end show the notification for errored once

### Actual behavior
The updates will stop at the point when one errors out

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
in  5.2.4
