### ISSUE TITLE
Chapters intermittently not being marked as read after reading

### ISSUE THREAD

**Issue by asdkant** [CarlosEsco/Neko#582]
### Device information
* Tachiyomi version: neko 2.5.3
* Android phone & version: android 11 w/ oneUI 3.1

## Steps to reproduce
1. Read the latest chapter which is unread
2. Go back to chapter list

### Expected behavior
Chapter should now show as read

### Actual behavior
Chapteris shown as unread

### Other details
After killingand starting neko the chapter *is* marked as read, so it seems something is not being synchronized/updated somewhere

**Comment by CarlosEsco** [comment]
This seems to related to the chapter not loading issue, and should be :crossed_fingers: in the next release

**Comment by asdkant** [comment]
@CarlosEsco another symptom that looks related and I just observed (it happened a few times, and it's an intermittent issue):
- read chapters, when going to the chapter list they still appear as unread
- marked them as read, whent to the manga list and the manga in question still has the unread count badge as before (it shouldn't even be there, since I marked all the chapters as read)

**Comment by CarlosEsco** [comment]
gonna close as i wasn't able to replicate this after i fixed this (https://github.com/CarlosEsco/Neko/issues/521)
