### ISSUE TITLE
[Bug] Can't migrate to 5v Mangadex

### ISSUE THREAD

**Issue by Shtate** [CarlosEsco/Neko#583]
I acknowledge that:

- I have updated to the latest version of the app

## Steps to reproduce
1. Try syncing library to my Mangadex follows
2. Start 5v migration

### Expected behavior
Neko migrates to 5v Mangadex

### Actual behavior
Doesn't migrate. Notification shows that some manga were migrated, but the rest (something like 90%) still aren't and it's stuck that way

### Other 
Syncing library to follows starts, but does nothing. Syncing never goes away, even when restart my phone or forcefully stop the app it pops back up when I turn Neko back up. Migration always halts at the same percentage (or amount of bar)

Android version 10

**Comment by Shtate** [comment]
Neko version 2.5.3
Phone is Galaxy Xcovers 4s

**Comment by Shtate** [comment]
Update: finally turned off syncing for good and tried migration again, same issue as before.

**Comment by CarlosEsco** [comment]
I'm confused.  You have a pre v5 library that you are trying to sync and to v5 migrate?  What is the order you are doing these things?

V5 migration only needs to be done once and it should be the first thing that is done if you are coming from a pre v5 library

**Comment by Shtate** [comment]
i tried to sync it first and only later noticed the 5v migration.

**Comment by Shtate** [comment]
Then I stopped the syncing in my phone's app settings and tried the migration again. Everytime I try to migrate I get the same result.

**Comment by CarlosEsco** [comment]
Is your library not on v5 already?  If so  you dont need to migrate.  

If it was an old v3 library then can you enable extra logging, force close app, then try to v5 migrate.  Afterwards attach the neko log folder that is inside the neko folder on your phone

**Comment by Shtate** [comment]
the extra logging method didn't work and I don't know how to check which version my library is.

**Comment by CarlosEsco** [comment]
extra logging is for you to send a file here.

As for checking library is v3 or not.  Pick a manga and swipe refresh it.  If it refreshes fine you are not on the old v3

**Comment by Shtate** [comment]
None of the manga I tried refreshed.

**Comment by Shtate** [comment]
[2021-07-12-release[1].txt](https://github.com/CarlosEsco/Neko/files/6802385/2021-07-12-release.1.txt)

**Comment by CarlosEsco** [comment]
Can you do the following (this will be the fastest solution)
1.  Make a backup of your libaray
2.  Uninstall Neko
3. install Neko again
4. Login into MangaDex again
4. Restore backup
5.  v5 Migrate
6. Verify you can swipe refresh a manga

**Comment by Shtate** [comment]
Seems to work now, thanks.
