### ISSUE TITLE
duplicate sort options in filter view

### ISSUE THREAD

**Issue by kyjibo** [CarlosEsco/Neko#584]
duplicate 'sort by' radio buttons at the top and bottom of the filter view now - don't think the ones up top do anything anymore(although there is a mechanism that offers to set it default for all, so maybe port that to the bottom set before removing it)
![Screenshot_20210712-132436_Neko](https://user-images.githubusercontent.com/2566398/125337734-f4274f00-e314-11eb-9483-a9ed375ca01f.png)

**Comment by CarlosEsco** [comment]
Just verified and they are working as design.
The top one's are for sorting new on top, or new on bottom

the bottom is for sorting in the mangadex sort order, or the chapter number

so if i did chapter number, and oldest then it will start at chp 1
if i did chapter number and newest then it will start the list at the last chp
