### ISSUE TITLE
[Bug] Navigation bug.

### ISSUE THREAD

**Issue by brian4548** [CarlosEsco/Neko#586]
---

### Device information
* Tachiyomi version: neko version 2.5.3
* Android phone & version: Fire HD 10 9th Generation 

## Steps to reproduce
1.  main page -> settings -> reader -> default reading mode
2.  Select "left to right"
3.  Scroll down to Webtoon
4.  Under the options for Webtoon set "Navigation Layout" to default.
5.  Select a Webtoon (I used Solo Leveling).
6.  Move hands toward the bottom half of the screen. Tap the left side of the screen then the right side repeatedly. 

### Expected behavior
The outcome should result in an up, down, up, down movement of the page.

### Actual behavior
If you repeat this enough it will switch to "L-Shape Navigation" which will cause the page to move up,up,up,up instead of up,down,up,down. 

### Other details
You can go into the settings and reselect "default"(default being "left to right") but it will eventually switch back to "L-shape". Also worth noting the only way to get "left to right navigation" is by setting it as I previously stated in the steps listed. You cannot select "Left to Right" by scrolling to lets say Webtoon and setting it in the options there.  *SEE VIDEO* *VIDEO FOLLOWS STEPS ABOVE BUT IS MADE SHORTER DUE TO TIME CONSTRAINT*

https://user-images.githubusercontent.com/71535163/125533693-67943063-2ff5-4981-b838-c02638f1ba8f.mp4

**Comment by CarlosEsco** [comment]
So i think there is a disconnect.

Neko forces webtoon layout on long strip tagged manga from MangaDex.  So it ignores your reading mode defaults.

You would need to change your navigation layout to Right and Left, then invert the tapping if you wanted to click left side of screen to scroll down, and right side to scroll up

![image](https://user-images.githubusercontent.com/2092019/126086317-33c08cc2-1ca3-4e9b-a7c2-77caaafffe07.png)

**Comment by brian4548** [comment]
Ah ok interesting. Thanks. I initially did it that way because I am so used to doing it that way from using tachiyomi. I guess I should have explored the app a bit more.
