### ISSUE TITLE
[Bug] incognito mode

### ISSUE THREAD

**Issue by Sidepunch** [CarlosEsco/Neko#587]
### Device information
* Neko version: v2.5.3
* Android phone & version: 10 or G & V8.1.0

## Steps to reproduce
1. First step : turn-on incognito mode.
2. Second step : read any manga till it's latest chapter. Then remove neko from recent tabs of phone.

### Expected behavior
This should happen. Pauses reading history and not mark chapters as read.

### Actual behavior
This happened instead. Marked chapters as read and later after reading the whole manga and closing neko, the manga showed in history. 

### Other details
Additional details and attachments.
![Screenshot_20210714-082204](https://user-images.githubusercontent.com/86877694/125553474-540a8f2c-1f8c-4b02-ad28-44fc0857e8a8.png)

**Comment by CarlosEsco** [comment]
in  5.2.4
