### ISSUE TITLE
[Bug] biometrics security bug

### ISSUE THREAD

**Issue by Sidepunch** [CarlosEsco/Neko#590]
### Device information
* Neko version: V2.5.3
* Android phone & version: 10orG & V8.1.0

## Steps to reproduce
1. First step: settings → security→lock with biometrics
2. Second step: restart neko and unlock it . Then you get "unlock to access library"  screen again. 
3. Or it crashes after first try and when you open Neko it opens without biometrics.

### Expected behavior
This should happen. It should have unlocked in first time.

### Actual behavior
This happened instead. You have to "unlock" it twice. Or it crashes after first try.

### Other details
Additional details and attachments.
![Screenshot_20210714-182545](https://user-images.githubusercontent.com/86877694/125625611-ecd83c1b-dae9-431e-be9f-c668f3a28cfc.png)

**Comment by CarlosEsco** [comment]
Does this also happen in J2K?

**Comment by Sidepunch** [comment]
> Does this also happen in J2K?

I was going to report it for tachiJ2K but thanks for asking,
Yes it happens with tachiJ2K but instead of unlocking twice it crashes after first try and opens with biometrics after

**Comment by CarlosEsco** [comment]
in  5.2.4
