### ISSUE TITLE
[Bug] Not keeping what page your on

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#593]
### Device information
* Tachiyomi version: 2.5.4
* Android phone & version: Android 10 OnePlus 6t

## Steps to reproduce
1. Read part of a chapter

### Expected behavior
keep your page number to resume reading

### Actual behavior
Starts you at the first page

**Comment by CarlosEsco** [comment]
redownload 2.5.4 https://github.com/CarlosEsco/Neko/releases/tag/2.5.4
i had fixed this before i put it back up
