### ISSUE TITLE
[Feature Request] Parallel downloading

### ISSUE THREAD

**Issue by whitespace-negative** [CarlosEsco/Neko#594]
Add settings to download more than 2 manga at once.

### Why/User Benefit/User Problem
This will benefit all users, and especially those that are planning to switch platforms, either from Desktop to mobile, or from other apps to Neko. Also, downloading more mangas at once is a must since the downloading speed is dependent to the servers the manga is being downloaded from.

### What/Requirements
Add settings to download more than 2 manga at once.

**Comment by CarlosEsco** [comment]
Parallel download already exists for chapters

**Comment by whitespace-negative** [comment]
uhh sorry, i updated my issue cuz i accidentally pressed the enter button, lthe issue should be "Add settings to download more than 2 manga at once"

**Comment by CarlosEsco** [comment]
I don't have any plans to bump it more than 2 at once just to prevent too much load going to md@hosts at once time.  Chapters already take only on average ~10s to download so its definitely fast as is.  If you want it to be faster you could always use data saver.
