### ISSUE TITLE
Ability to set default tags for search

### ISSUE THREAD

**Issue by asdkant** [CarlosEsco/Neko#596]
### Why/User Benefit/User Problem
Sometimes you just don't like a genre or category. MD used to have hiding certain tags as a feature but not in the newer version, so it could be implemented in the app (and maybe just defer to MD later when it's reimplemented)

### What/Requirements
Somewhere in the config where I can pick a list of tags I want to avoid.

**Comment by CarlosEsco** [comment]
That's doable through api just like doing defaults with content rating currently

**Comment by CarlosEsco** [comment]
As of 2.11.0 you can set the filters how you want in the browse screen then save it, and set it as a default for every search
