### ISSUE TITLE
Pure black mode doesn't make everything black

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#597]
### Device information
* Tachiyomi version: 2.5.4.1
* Android phone & version: Android 10 Oneplus 6t

## Steps to reproduce
1. Set Pure black dark mode to on

Chapter loading screen isn't black it's grey
Reader settings in a chapter isn't black it grey
When you have background color on smart (by theme) the background is grey not black

**Comment by CarlosEsco** [comment]
2.5.5
