### ISSUE TITLE
Missing chapter placeholder

### ISSUE THREAD

**Issue by vkhodygo** [CarlosEsco/Neko#601]
### Why/User Benefit/User Problem
There is a *missing chapters* counter but no actual way to tell which chapters are actually missing aside from scrolling through them manually and checking the numbers.

### What/Requirements
The list could have placeholders for individual chapters that are not active but show what one needs to look for.

**Comment by CarlosEsco** [comment]
2.12.4.  Clicking the missing chapter number now shows the estimated missing chapters
