### ISSUE TITLE
[Feature Request] Downloaded chapters label

### ISSUE THREAD

**Issue by vkhodygo** [CarlosEsco/Neko#602]
### Why/User Benefit/User Problem
Due to many reasons such as poor connection or current issues with chapter loading one needs to download chapters from time to time. That and space limitations mean we can't have all titles downloaded at the same time. 

### What/Requirements
Rather than checking all titles one by one it would be great to see an indicator showing that there are some downloaded chapters (as well as their total number?).

**Comment by CarlosEsco** [comment]
There is already a label, you need to enable download badges in the library.   There is an option in the filter sheet in the library view
