### ISSUE TITLE
Bottom Library category failed to update

### ISSUE THREAD

**Issue by legacy9899** [CarlosEsco/Neko#604]
### Device information
* Tachiyomi version: Neko 2.5.4.1
* Android phone & version: android 11, Redmi 8A Pro

## Steps to reproduce
1. First step
Update two bottom library category

### Expected behavior
Library update normally

### Actual behavior
Library failed to update, no code error provided

### Other details
Neko Library backup file
https://drive.google.com/file/d/1610LZRvDDp0rY9f4u1BvuH4kcmh6RquS/view?usp=drivesdk

Error log

https://drive.google.com/file/d/160CsOvIxTPrJfoXaEhVUaicGoiZGQPB8/view?usp=drivesdk

Also video for bug detail on Cesco discord DM

**Comment by CarlosEsco** [comment]
let me know if you still have this issue In 2.6.0

**Comment by CarlosEsco** [comment]
Reopen if still an issue on 2.7.0
