### ISSUE TITLE
One-shot manga Tracking Error 400 

### ISSUE THREAD

**Issue by legacy9899** [CarlosEsco/Neko#605]
### Device information
* Tachiyomi version: Neko 2.5.4.1
* Android phone & version: Android 11, Redmi 8A Pro

## Steps to reproduce
1. First step
So when I tried to track a one-shot manga, when the chapter status is already read it will give error 400, when I tried to unread it, tracker able to find the manga. I already try to relog and it ended up with same error. Also I succeed to reproduce the bug with another one shot manga

### Expected behavior
Tracker should able to detect manga normally

### Actual behavior
Error 400, relog not able to solve the problem

### Other details
Video bug detail
https://discord.com/channels/349436576037732353/569823838305648640/866645098178281477

**Comment by CarlosEsco** [comment]
2.5.5
