### ISSUE TITLE
Manga with no groups for scanlator cause issues

### ISSUE THREAD

**Issue by deidouji** [CarlosEsco/Neko#606]
### Device information
* Tachiyomi version: Neko v2.5.4.1
* Android phone & version: Galaxy A51

## Steps to reproduce
Open chapter list for some manga

### Expected behavior
There used to be "unknown group" for chapter uploader (author? idk what the term is), now there isn't anything
Filtering upload groups should show all groups

### Actual behavior
There isn't "unknown group" for chapter uploader (As far as i can tell, all manga with unknown group uploaders are affected)
"unknown group" isn't listed in filter as it's not tagged to any chapters, creating ghost unreads if you hit "ok" on filter group instead of "reset all". Can be fixed if you hit "reset all" but issue will persist if you exit out of chapter list and open it again (Some manga have been affected, not sure if it'll be the same for everyone but 
https://mangadex.org/title/3fba42cf-2ad6-4c30-a7ab-46cb8149208a
https://mangadex.org/title/c26269c7-0f5d-4966-8cd5-b79acb86fb7a)

### Other details
https://cdn.discordapp.com/attachments/569823838305648640/866705198662287410/Screenshot_20210719-113650_Neko.jpg
https://cdn.discordapp.com/attachments/569823838305648640/866509785121685524/Screen_Recording_20210718-223944_Neko.mp4

**Comment by CarlosEsco** [comment]
For my record 
Relationship is missing so it needs to default to No Group
https://api.mangadex.org/chapter/a51131e6-372d-4f63-a40c-1ae28f224b7a

**Comment by CarlosEsco** [comment]
2.5.5
