### ISSUE TITLE
[Bug] Sync MangaDex Follows only works for "Reading"

### ISSUE THREAD

**Issue by solntcev** [CarlosEsco/Neko#607]
### Device information
* Tachiyomi version: 2.5.4.1
* Android phone & version: Huawei MediaPad T5, Android 8

## Steps to reproduce
1. Set status of any manga on mangadex to "Complete"/"On Hold"/"Plan to read"/"Dropped"
2. Select any of "Complete"/"On Hold"/"Plan to read"/"Dropped" in Sync dialog
3. Sync
### Expected behavior
Manga appears in library

### Actual behavior
"Synced 0 new manga from MangaDex"

Looks like v5 splits following and reading status.
How can I import "Plan to watch" items to library?

**Comment by CarlosEsco** [comment]
This isn't a bug, the setting specifically says from your follow list.  At this time you can't sync non follows. I plan to implement it down the line

**Comment by CarlosEsco** [comment]
#611
