### ISSUE TITLE
[Bug] Duplicated items in library

### ISSUE THREAD

**Issue by cvalenciaec** [CarlosEsco/Neko#608]
Hi,

When migrating to v5, I noted that some manga didn't migrated, so I did a Mangadex sync to my device to try to fetch the correct manga, but now I have duplicates: one is the unmigrated manga and other one is the pulled one from Mangadex, how I can delete duplicates from library?

Regards
---

### Device information
* Tachiyomi version: latest
* Android phone & version: 

## Steps to reproduce
1. check manga on library
2. 2 results on library

**Comment by CarlosEsco** [comment]
If you have a backup. Clear your entire library, clear db in advanced settings, then restore the backup. Then do v5 migrate again

**Comment by cvalenciaec** [comment]
thanks, I did remove it manually the duplicated ones and run again v5 migrate, then it worked.
