### ISSUE TITLE
Automatically track new chapter release with user's follow list when possible, instead of using Tachyiomi's library refresh

### ISSUE THREAD

**Issue by Jvs34** [CarlosEsco/Neko#614]
### Why/User Benefit/User Problem
I've got more or less 1200 manga I follow on MangaDex and while I understand that my Tablet is at death's door, library refreshes take a solid 20/30 minutes checking for manga that most likely get new chapters once a year.

It's pretty wasteful to check for every single manga for new chapters so I propose to make use of the [API's follow list](https://api.mangadex.org/docs.html#operation/get-user-follows-manga-feed) for automatic refreshes when the user is logged in.

### What/Requirements
When the app has to do an automatic refresh it'll call the [API for the user feed](https://api.mangadex.org/docs.html#operation/get-user-follows-manga-feed) if the user is logged in, using the timestamp from the last chapter it fetched as an input to any of the query parameters (I'm not sure which one would be best here, do chapters that have to be approved get "updated" by the api? would they get pushed up to the top of the feed or remain at the bottom when they were uploaded?).

The idea is to only get the chapters that the app hasn't checked yet, if there's an empty response nothing needs to be checked.

Once the list of chapters that have been updated has been fetched, make the mangadex backend add the chapter if it doesn't exist (with info from the feed response) or update it (in case chapter title or some other stuff was updated by the uploader).

**Comment by CarlosEsco** [comment]
#344
