### ISSUE TITLE
Version 2.5.5 Update issue

### ISSUE THREAD

**Issue by Gurrman375** [CarlosEsco/Neko#618]
### Samsung A51 5G
* Neko version: 2.5.5
* Android phone & version: Andriod 11 One UI v 3.1

## Steps to Reproduce
      1) Go to about.
      2) Check for updates.

### Expected Outcome
Show a popular message stating there is no need to update.

### Actual Outcome
Popup with the message to download the same version 2.5.5

**Comment by CarlosEsco** [comment]
This is fixed now, if you get prompted download one more time.
