### ISSUE TITLE
Not updating MyAnimeList chapters automatically

### ISSUE THREAD

**Issue by TheTabbingman** [CarlosEsco/Neko#621]
### Device information
* Neko version: 2.5.5.1
* Android phone & version: OnePlus 6t Android 10

## Steps to reproduce
Read a chapter

### Expected behavior
Update amount of chapters you've read

### Actual behavior
Doesn't change chapters

**Comment by CarlosEsco** [comment]
Working fine here, try logging out and relogin.  I did notice though that the update isn't immediate in the ui and required to back out then go back into the manga

**Comment by TheTabbingman** [comment]
Logging out and back in seems to have fixed it
