### ISSUE TITLE
Kitsu Tracking Error

### ISSUE THREAD

**Issue by supersaiyandoyle** [CarlosEsco/Neko#622]
I decided to add tracking to all of my manga in my library, and when I got to the series "Bouken-ka ni Narou! ~Skill Board de Dungeon Kouryaku~", adding tracking to kitsu gave me the notification "Index: 0, Size: 0", and "No Results Found".
I know the series itself is on kitsu, and so far it's the only one that's giving me problems.

**Comment by CarlosEsco** [comment]
You are on 2.5.5.1?

**Comment by supersaiyandoyle** [comment]
Yes.

**Comment by CarlosEsco** [comment]
> Yes.

So it looks like the api is returning the wrong result

**Comment by CarlosEsco** [comment]
Will add a check to ignore kitsu id's if the the data is being sent back wrong

**Comment by CarlosEsco** [comment]
fixed in 2.5.6
