### ISSUE TITLE
Being able to sync V5 mangadex status with neko categories

### ISSUE THREAD

**Issue by Ashzoldyck** [CarlosEsco/Neko#624]
I wonder if its possible to sync the Lists status to mangadex into the categories tags in Neko .Because everytime I add a title in Neko library, it goes to the 'Reading' status in V5 Mangadex...Would it be possible if I add the title to 'Plan to read' tag in Neko and it syncs with the same corresponding list status in V5 Mangadex?

**Comment by CarlosEsco** [comment]
you need to set the status in the manga indvidually through the tracker, at this time you can't batch sync to something not reading

**Comment by CarlosEsco** [comment]
#619
