### ISSUE TITLE
Sync frozen, and "cancel" button broken.

### ISSUE THREAD

**Issue by Kzitold** [CarlosEsco/Neko#625]
### Device information
* Neko version: 2.5.5.1
* Android phone & version: Samsung Galaxy S10 Android 11

## Steps to reproduce
I guess "Sync Library Manga to Follows."

### Expected behavior
idk. **Not** breaking.

### Actual behavior
Here's a video.
https://www.dropbox.com/s/qvyan2dtgr9jile/Screen_Recording_20210727-071418_One%20UI%20Home.mp4?dl=0
That progress bar hasn't moved a pixel over night.

**Comment by Kzitold** [comment]
It appears re-logging fixed it.

**Comment by CarlosEsco** [comment]
Were you reading before hand and got the infinite load reading bug? https://github.com/CarlosEsco/Neko/issues/598  Its know to cause issues through out the app once it happens
