### ISSUE TITLE
Neko name changed and deleted all my manga after I tried fixing it 

### ISSUE THREAD

**Issue by theresnobio** [CarlosEsco/Neko#628]
### Device information
* Neko version: v2.5.5.1
* Android phone & version: Nuu A7l android 8.1.0
![Screenshot_20210728-074021](https://user-images.githubusercontent.com/84305225/127424564-7f5d3a60-7a9e-45d0-afa8-3d93f78f4f4e.png)

## Steps to reproduce
I don't know how the name changed it just did when I was going to use it this morning. I tried turning off my phone completely and back on. 

### Expected behavior
the name should've been just "Neko" before turning off my phone completely

### Actual behavior
The name changed to "eu.kanade.tachiyomi.App" before turning off my phone completely. The app didn't want to open and kept immediately saying that it stopped working.  When I turned back on my phone  the name changed back to "Neko" but when I went to read some manga all of it was deleted. 
### Other details
I'm not really sure if this should be here but I think that it should be acknowledged because it could really mess some people's experience of this app. Also I was able to use a old backup but it was from the 14 of June, so if you know a way to get the other missing i'll be grateful for that as well

**Comment by CarlosEsco** [comment]
Nothing i can really do about this, unless you can repeat it or know how it changed.
