### ISSUE TITLE
only connect to api.mangadex.org using https

### ISSUE THREAD

**Issue by The0mega** [CarlosEsco/Neko#629]
Neko (v2.5.5.1) curently try's to connect to http://api.mangadex.org getting a http/301 back and redirects to https://api.mangadex.org with every request.

Only connecting to https will speed up the communication with mangadex, and also increase security because Neko also sends it's mangadex session cookie **_plaintext_** over the air/internet with it's http request.

**Comment by CarlosEsco** [comment]
good catch
