### ISSUE TITLE
Global update settings crash

### ISSUE THREAD

**Issue by Spodeian** [CarlosEsco/Neko#634]
### Device information
* Neko version: 2.5.6
* Android phone & version: Samsung S10 & Android v11

## Steps to reproduce
* Go to Global updates settings
* Open Categories drop down
* Set something to be excluded

### Expected behavior
A category has an X in a tick box

### Actual behavior
App crashes

### Other details
I only have one category other than Default

**Comment by CarlosEsco** [comment]
Can you export the crash log in advanced settings and attach it here (do so after the app crashes)

**Comment by CarlosEsco** [comment]
In 2.6.0
