### ISSUE TITLE
My Anime List gives Error 401

### ISSUE THREAD

**Issue by fleurc** [CarlosEsco/Neko#635]
# Device information
Neko version: 2.5.6
Android phone & version: Asus Zenfone Max Pro M2 & Android v11

# Steps to reproduce
Search for new Manga
Add new manga to library
Add tracking of My Anime List

# Expected behavior
My anime list finds manga (or not depending on title)
Adds "plan to read" tracking in it

# Actual behavior
No matter the title MAL will always give HTTP Error 401
Then say "No results"

## Other details
MAL works perfectly with TachiJ2K, so the problem only happens in Neko.

**Comment by CarlosEsco** [comment]
Http 401 is unauthorized which means you should try to logout then relogin

**Comment by fleurc** [comment]
Works, still weird that this is the second time it happens with Neko but not with J2K
