### ISSUE TITLE
Top bar auto / manual minamizing

### ISSUE THREAD

**Issue by Arcane951** [CarlosEsco/Neko#636]
### Why/User Benefit/User Problem
Disregarding side space I understand that needing to be there.

---> Is there any chance we could have the top bar minamize itself just to see more of the webtoon virtically I find on some monitors it could only show around half/ two thirds a pannel at a time its alright if not it would just be nice to get a taller visual

### What/Requirements
how hovering a mouse near the top screan it would auto slide down and be visable and when the mouse is not near the top of the screan it would slide up out of sight.
Or even just a switch/ toggle option just like dark mode as in order to hide the top bar following as you scroll.

if in html a mouse hover code section i think is easy but i have not coded html in a fair number of years

**Comment by CarlosEsco** [comment]
The top bar does show the entire time only, to hide it click the middle of the screen

**Comment by Arcane951** [comment]
https://cdn.discordapp.com/attachments/636448054332882953/879506528699289650/Screenshot_from_2021-08-23_17-22-54.png

The top bar like here? It wont go away for me though

**Comment by CarlosEsco** [comment]
That isn't Neko
