### ISSUE TITLE
Add a shortcut to browse latest releases (for all mangadex) in the bottom bar

### ISSUE THREAD

**Issue by asdkant** [CarlosEsco/Neko#642]
### Why/User Benefit/User Problem
I tend to browse the latest releases to see if there's anything interesting, but I have to go through more UI interactions that I'd like (three taps instead of one). 

### What/Requirements
An icon in the bottom bar (the one with library/recents/browse) that gets me directly to the latest releases. Since the bottom bar has a lot of unused space this should not be too much of an issue.

I think it's be even better if the bottom bar could be customized, but I can't think off the top of my head any other buttons I'd put there.

**Comment by CarlosEsco** [comment]
There are plans to add 1 more bottom nav button, but probably not latest, if anything latest will be a tab or button on the top of browse similar to  how the recents/history screen

**Comment by CarlosEsco** [comment]
New button was scrapped, its now one less click for you though
