### ISSUE TITLE
New chapters not showing in manga page

### ISSUE THREAD

**Issue by gcpadua** [CarlosEsco/Neko#644]
### Device information
* Neko version: 2.5.6
* Android phone & version: Poco X3, Android 11

## Steps to reproduce
Update the library and sometimes the new chapters will not show in the manga page (the chapter is still available at the recents tab and the unread counter at the library show the correct number of unread chapters)
### Expected behavior
The new chapters should appear in the manga page
### Actual behavior
The new chapters don't appear in the manga page
### Other details
![Screenshot_20210812-001818](https://user-images.githubusercontent.com/73405789/129133298-f5266a40-c1af-471d-820d-de5a0690e18b.png)
![Screenshot_20210812-001823](https://user-images.githubusercontent.com/73405789/129133342-e4abb8fa-1db8-4214-a2d0-dd18b90a555a.png)

![Screenshot_20210812-001846](https://user-images.githubusercontent.com/73405789/129133711-f5d9ab04-5c7d-4e31-94e8-1ba6c4fa57fa.png)

**Comment by CarlosEsco** [comment]
looks like a scanlator filter bug,  can you click the filter-> then click scanlator then click reset .  They will probably show then

**Comment by gcpadua** [comment]
It looks like this is indeed the problem. When I open the scanlator filter I can see that one of the is not marked, but when I enable the group and click ok, the app crashes. I tried to do this until I got the option to copy the crash log url.
https://katb.in/kat7480

**Comment by CarlosEsco** [comment]
click the reset filter, then close the dialog.  It wont crash next time you open it.

**Comment by gcpadua** [comment]
Looks like this fixed the problem. Thanks for the help!
