### ISSUE TITLE
Manga/ Manhua entries in library showing up as not in library on the browse page

### ISSUE THREAD

**Issue by ayush-km** [CarlosEsco/Neko#647]
### Device information
* Neko version: 2.5.6
* Android phone & version: RealMe C12 Android 11

I have already migrated to V5 a long time ago.
This is an issue that I think is present in J2K as well. I would go to the browse page of some source and see entries in my library showing up as not in the library. I would add them from there which would result in duplicate entries and then after a while I'll go to the same source browse page again only to discover the same problem again so now when I add that entry I'll have 3 same entries.

This is one way to reproduce it. Take backup from J2K and restore it in Neko. Then go to the browse page in Neko to find that the restored entires show up as not in the library.

### Screenshots:
I couldn't capture any because of this annoying thing in Neko and J2K where screenshots can't be captured because the page contains sensitive information. Please fix that. It is very hard to report anything without proper screenshots.

**Comment by ayush-km** [comment]
I should also mention that with J2K this problem happens mostly with Toonily and rarely with MD

**Comment by CarlosEsco** [comment]
@ayush-km turn off secure screen setting then you take screen shots.

**Comment by ayush-km** [comment]
> @ayush-km turn off secure screen setting then you take screen shots.

Isn't there any other way to do it? My siblings constantly try to open my apps and see what I have on them and some of the stuff I have is questionable. And I sometimes forget to lock my phone. How about a feature where when secure screen is enabled have another option which controls where screenshots should be blocked or not.

**Comment by CarlosEsco** [comment]
secure screen is built into android, disable when you want to take screenshots, and enable when you don't.  Anyways thats unrelated to this ticket.  Please provide screens if possible

**Comment by ayush-km** [comment]
![Screenshot_2021-08-17-17-27-40-66_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/57125345/129725817-3c2cdd69-9ec4-49b4-91c2-9f254c37fada.jpg)
![Screenshot_2021-08-17-17-27-59-63_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/57125345/129725827-5712d66a-befc-4dde-a929-73ffc3e56f82.jpg)
![Screenshot_2021-08-17-17-28-11-95_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/57125345/129725832-6f991017-2f7e-44a4-aaf9-8ae6ef171116.jpg)
![Screenshot_2021-08-17-17-28-27-23_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/57125345/129725837-586c820f-f0d8-4467-a3f4-017d13512a67.jpg)

**Comment by CarlosEsco** [comment]
Thanks can you do me 1 more favor.

open each manga click the share button and send the urls here.

**Comment by ayush-km** [comment]
The URLs are a little different. I guess this is because of the ever-evolving V5 API.

This is the URL for the entry on the browse page: https://mangadex.org/title/77bee52c-d2d6-44ad-a33a-1734c1fe696a
This is the URL for the entry that was originally in the library: https://mangadex.org/manga/77bee52c-d2d6-44ad-a33a-1734c1fe696a

I tried opening the second link in a browser and it redirects to the first link.

**Comment by CarlosEsco** [comment]
thanks

**Comment by ayush-km** [comment]
> thanks

np.

**Comment by CarlosEsco** [comment]
When the next release comes out (no eta)  you will need to remove the ones you restored from j2k, clear the db in advanced settings, then restore again

**Comment by ayush-km** [comment]
ok. thanks!
