### ISSUE TITLE
[enhancement] Change Navigation header to Image 

### ISSUE THREAD

**Issue by as280093** [CarlosEsco/Neko#65]
Navigation header image:

![navigation_header_image](https://user-images.githubusercontent.com/25240839/56564016-c71ee280-65ca-11e9-8027-e86dcac813ca.jpg)

And for the image icon, My guess is you should create `CircularTranform` class file which will convert any square image  in circular fashion.  This will reduce one `res` file and we can use Launcher icon as profile as `CircularTranform` will convert it to circle.
As in future if icon is changed it will directly reflect to `Navigation_Header.xml` no need for creating circular image.

**Here is what it will look :**
![Screenshot_2019-04-23-11-32-14-938_neko_standard](https://user-images.githubusercontent.com/25240839/56565076-2e3d9680-65cd-11e9-9441-b83e40972c58.png)

I also have a idea of putting username in Navigation header, The reason is that every time the app will launched it will check for cache expiration if cache is expired username will be set to `guest` user can see if he is login or not and reducing time to go to settings for login and there is side dropdown for login and once login is done get username and set there instead of guest, Dropdown i will include `LogOut` and other functions like sync in future 

**Here is what it will look :**

| **Guest**  | **Dropdown_Menu** | 
| :----------: | :----------------------: |
| ![Screenshot_2019-04-23-11-32-14-938_neko](https://user-images.githubusercontent.com/25240839/56565531-3c3fe700-65ce-11e9-9d1b-a2152aefe8bc.png) | ![Screenshot_2019-04-23-11-32-14-938_neko logini](https://user-images.githubusercontent.com/25240839/56565577-5c6fa600-65ce-11e9-8c56-c91536cdb31a.png) |

**Reference for circular frame: (point 9th)**
https://www.androidhive.info/2013/11/android-sliding-menu-using-navigation-drawer/

**Comment by CarlosEsco** [comment]
Closing since we went with the new icon on black

**Comment by CarlosEsco** [comment]
Will revisit login at a later date as it will require a bigger rework
