### ISSUE TITLE
Show raw link on manga info screen

### ISSUE THREAD

**Issue by sad-kato** [CarlosEsco/Neko#659]
### Why/User Benefit/User Problem
(explain why this feature should be added)
Users can easily get links for the raws and purchase them as well as check the latest chapter/volume available for the raws.

### What/Requirements
(explain how this feature would behave)
This feature can be added in the WebView sheet where links to mangadex, manga updates and anime planet are. Or a new button can also be added.

**Comment by CarlosEsco** [comment]
In 2.7.0
