### ISSUE TITLE
NSFW content is unreadable

### ISSUE THREAD

**Issue by ShockedCoder** [CarlosEsco/Neko#664]
### Device information
* Neko version: 2.5.6
* Android phone & version: Galaxy Note 20 - Android 11

## Steps to reproduce
search for anything with the `pornographic` tag
### Expected behavior
Ability to see and read the chapters
### Actual behavior
Can't see how many chapters there are nor can you read them
### Other details
Mangadex added a prompt that you need to accept before being able to see the content

**Comment by sinistergrin97** [comment]
I'm facing the same issue. Is there any fix to it currently?

**Comment by Zurkei** [comment]
As far as I can tell it has to do with this line 32 here: [code](https://github.com/CarlosEsco/Neko/blob/2840df421d51e495b3486983823683f1eaf285ac/app/src/main/java/eu/kanade/tachiyomi/network/services/MangaDexService.kt#L32)
It is not including the contentRating[] query which defaults to exclude pornographic.

When using that api path with the default contentRating[] query on a nsfw id it will come respond with no chapter.

**Comment by Zurkei** [comment]
A commit has been added that resolves this issue and so it should be fixed in the next release I believe.

**Comment by CarlosEsco** [comment]
I have been on vacation so have a lot of j2k commits to pick up, there will be a release soonish

**Comment by CarlosEsco** [comment]
In 2.6.0
