### ISSUE TITLE
Not detecting updates

### ISSUE THREAD

**Issue by NinjaDebugger** [CarlosEsco/Neko#668]
On the website, I can see several series have updated in english, even when using the web viewer in neko, but the app won't detect and download them.

**Comment by NinjaDebugger** [comment]
On further examination, not only is it not showing the latest updates, but the browse panes, both latest and general, are showing only comics by a single group, Bilibili.

**Comment by Zurkei** [comment]
This appears to be an issue with the MangaDex api, when requesting for the latest updates from the api it is not matching what is actually listed under latest updates on the website and skips over some manga. At least when it comes to the browse page.

I'm not able to replicate new chapters not being detected and downloaded.

**Comment by NinjaDebugger** [comment]
If you go to a recently updated bilibili comic, for example, "Finger Girls", right now Neko shows me that it was last updated 3 days ago with chapter 50.2 while the website shows 5 chapters uploaded since then.  This may be a bug exclusive to these bilibili uploads, I seem to be getting updates normally on several other manga today.

**Comment by Zurkei** [comment]
Okay  I see what you mean now. The reason that is happening is that the new chapters are set to be published to mangadex at a later date but can be accessed early through the publishers website.

Using your example of "Finger Girls",  chapter 53.2 is set to be published to mangadex in 14 days on Sept. 25. Whereas chapter 50.2 has already been published to mangadex. Once a chapter is published to mangadex the images will be available to mangadex api but not before. As such Neko does not currently display chapters not published to mangadex even though the chapter is available on the publishers own website.

**Comment by NinjaDebugger** [comment]
That makes a lot of sense, thank you.  I'll make a feature request about it.

**Comment by CarlosEsco** [comment]
As an fyi the next release will support those not yet published chapters
