### ISSUE TITLE
Chapters scheduled for publishing show on updated list but don't show in chapter list.

### ISSUE THREAD

**Issue by NinjaDebugger** [CarlosEsco/Neko#669]
It's very confusing to users that the update list is clogged with seemingly non-updated manga when actually what's been updated is chapters scheduled to be published.

I'd like to see scheduled chapters displayed with at least a disabled link and a mark for how long they're scheduled to wait, if possible, or otherwise a notation that it's a scheduled chapter and will be published eventually.

**Comment by CarlosEsco** [comment]
In 2.6.0
