### ISSUE TITLE
Browse and Latest only showing manhua

### ISSUE THREAD

**Issue by Northinger** [CarlosEsco/Neko#671]
### Device information
* Neko version: Latest
* Android phone & version: Xiaomi Redmi Note 9 Pro - Android 11

## Steps to reproduce
Open browse to see comics, or try to list them by latest
### Expected behavior
I should be seeing all the entries, but only way to see something other than Chinese is to change language in browse settings. 
### Actual behavior
Browse is only showing manhua
### Other details
I installed neko again after a factory reset, and thus issue started appearing. Tried to clean files and opened again, reinstalled, but nothing worked so far. I'm logged in to mangadex in both settings and trough a manhua links in webview. 

![IMG_20210912_040632](https://user-images.githubusercontent.com/87140863/132967513-0641a034-9216-41bb-a9c6-b0db681e07dd.jpg)
![IMG_20210912_040644](https://user-images.githubusercontent.com/87140863/132967514-70313244-61fa-46aa-abc3-6437f6d9baf9.jpg)

**Comment by CarlosEsco** [comment]
That because Bilibili is uploading a ton of stuff.
