### ISSUE TITLE
Default theme (Neko Pure) unread count is black on black

### ISSUE THREAD

**Issue by damiannmm** [CarlosEsco/Neko#672]
### Device information
* Neko version: 2.6.0
* Android phone & version: Pixel 4, 10

## Steps to reproduce

Change the theme to light (Neko Pure); open the library navigation

### Expected behavior

After opening the library navigation, unread count is black on black

### Actual behavior

After opening the library navigation, unread count should be white on black

### Other details

Tried with white and black OS' theme, but nothing changes. All other themes seems fine.

<details>
<summary>Show example</summary>
<br>
<img src="https://user-images.githubusercontent.com/1107336/132995359-e6aadf89-6f5e-472a-b656-674054820bdf.jpeg" height="480">
</details>

**Comment by CarlosEsco** [comment]
Dang I knew something theme wise would come up.. grey wolf has some minor issues also

**Comment by CarlosEsco** [comment]
Should be fixed in 2.7.0
