### ISSUE TITLE
Default sorting option for browse

### ISSUE THREAD

**Issue by Manson-22** [CarlosEsco/Neko#673]
### Why/User Benefit/User Problem
Neko defaults to searching by latest chapter of any manga in any language. Previous updates of Neko sorted by follows. 

### What/Requirements
In either the filter button or the settings you could set default sort and direction, just like how the filter button works atm.

**Comment by CarlosEsco** [comment]
As of 2.11.0 you can set the filters how you want in the browse screen then save it, and set it as a default for every search
