### ISSUE TITLE
[Bug] After update Neko is unable to update 933 of my manga

### ISSUE THREAD

**Issue by fleurc** [CarlosEsco/Neko#678]
After i updated Neko, 93 of my manga appear with the same error. It keeps saying there's a missing "results" field.

Here's the error list as Neko gave me.

`` 67% Inertia: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing A Story About Treating a Female Knight, Who Has Never Been Treated as a Woman, as a Woman: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Ane Naru Mono: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing BLOOD - The Last Vampire 2000: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Beast Complex: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Blue Period: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Bullet Armors: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Burn the Witch: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Catulus Syndrome: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Chikyuu wa Boku ga Mawasu: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Classmate, Kamimura Yuuka wa Kou Itta: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Dadadadan: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Demon King's Rules x Witch's Covenant: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Dorohedoro: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Finger Girls: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Freezing: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Gekijouban Madokaâ˜…Magica - [Shinpen] Hangyaku no Monogatari: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Golden Kamuy: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Hanakaku - The Last Girl Standing: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Hebi Onna Hajimemashita: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Hellsing: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Hellsing - The Dawn: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Houseki no Kuni: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing I Shaved. Then I Brought a High School Girl Home.: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing I Want Your Underwear!: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Ijiranaide, Nagatoro-san: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Imawabi no Dakini: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing JoJo's Bizarre Adventure Part 1 - Phantom Blood (Official Colored): Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing JoJo's Bizarre Adventure Part 2 - Battle Tendency (Official Colored): Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing JoJo's Bizarre Adventure Part 3 - Stardust Crusaders (Official Colored): Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing JoJo's Bizarre Adventure Part 4 - Diamond is Unbreakable (Official Colored): Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing JoJo's Bizarre Adventure Part 5 - Vento Aureo (Official Colored): Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing JoJo's Bizarre Adventure Part 6: Stone Ocean (Colored): Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing JoJo's Bizarre Adventure Part 7 - Steel Ball Run (Official Colored): Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing JoJo's Bizarre Adventure Part 8 - JoJolion (Official Colored): Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Jumyou wo Kaitotte Moratta. Ichinen ni Tsuki, Ichimanen de.: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Kaifuku Jutsushi no Yarinaoshi: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Kamen Rider & Mahou Shoujo Madokaâ˜…Magica - Puella Magi Dikeedo Magica (Doujinshi): Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Kuroshitsuji: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Little Witch Academia: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Looking up to Magical Girls: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Made in Abyss Official Anthology: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Magi: Sinbad no Bouken: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Mahou Shoujo Kazumiâ˜…Magica ~The Innocent Malice~: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Mahou Shoujo Madokaâ˜…Magica: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Mahou Shoujo Madokaâ˜…Magica ~The different story~: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Mahou Shoujo Orikoâ˜…Magica: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Mahou Shoujo Site: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Mahou Shoujo Suzuneâ˜…Magica: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Maria Holic: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Medaka Box: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Mononoke: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Mononoke Sharing: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Mousou Telepathy: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Narikawari: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Nisekoi: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Noragami: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Noragami - Clash, O Ye Gods of Calamity: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Organ Divider: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Otome Game no Hametsu Flag shika nai Akuyaku Reijou ni Tensei shite shimatta...: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Pandora Hearts: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Paru's Graffiti: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Persona 5: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Pop Team Epic: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Rosario to Vampire: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Rosario to Vampire Season II: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Senpai wa Otokonoko: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Shingeki no Eroko-san: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Shoujo Shuumatsu Ryokou: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Shuumatsu no Valkyrie: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Sousou no Frieren: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing The Ancient Magus' Bride: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing The Duke of Death and His Black Maid: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing The Enigma of Amigara Fault: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing The Wolf That Picked Something Up: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing The Wrong Way to Use Healing Magic: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing This Chubby Girl Can't Stop Acting Like a Little Devil: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Tobaku Datenroku Kaiji: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Tobaku Datenroku Kaiji: Kazuya-Hen: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Tobaku Hakairoku Kaiji: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Tokusatsu Gagaga: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Tokyo Ghoul:re: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Toriko: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Uzaki-chan wa Asobitai!: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Vagabond: The LAST Manga Exhibition Complete Catalogue: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Vinland Saga: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Witch Hunter: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Wonder Cat Kyuu-chan: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Youjo Senki: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Yuusha Goikkou no Kaerimichi: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Yuusha ga Shinda!: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing Zombie-Loan: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing xxxHOLiC Rei: Field 'results' is required for type with serial name 'eu.kanade.tachiyomi.source.online.models.dto.ChapterListDto', but it was missing

**Comment by CarlosEsco** [comment]
Are you on 2.6.1?

**Comment by fleurc** [comment]
When i wrote it there wasn't 2.6.1 am updating to it now

**Comment by CarlosEsco** [comment]
There was i released 2.6.1 yesterday because MangaDex made breaking api changes

**Comment by fleurc** [comment]
Just updated, solved the issue completely, thank you
