### ISSUE TITLE
*bug* Cannot login on Neko

### ISSUE THREAD

**Issue by MTNdew4** [CarlosEsco/Neko#680]
I am able to login on mangadex, but when I try to login on Neko I get "unknown error"

**Comment by CarlosEsco** [comment]
What version of the app are you on?

**Comment by MTNdew4** [comment]
6.2.1

**Comment by CarlosEsco** [comment]
Can you verify your login information and can login to the website directly

**Comment by charnezzed** [comment]
Confirm same issue, can't login using version 6.2.1

Login in browser works fine.

Login window just hangs forever in app when trying to sign in.

**Comment by CarlosEsco** [comment]
Try force closing app then trying again

**Comment by MTNdew4** [comment]
The issue persists

**Comment by CarlosEsco** [comment]
Can you export the error the log (verify it has no login sensitive info) then post here

**Comment by CarlosEsco** [comment]
Let me know if you have any luck in 2.7.0

**Comment by CarlosEsco** [comment]
2.7.1.4 should show an error message now. Let me know what it is

**Comment by MTNdew4** [comment]
After the latest update I'm now getting a message that says "Error trying to login http:401"
@![Screenshot_20211201-021639](https://user-images.githubusercontent.com/50174073/144197959-d856fbbf-1b91-4d12-be0a-56790d792b3c.png)

**Comment by CarlosEsco** [comment]
This is an issue with you and MangaDex

from MangaDex

401 means either:
- Your username/password is wrong
- Your user is unverified
- Your user is banned
