### ISSUE TITLE
Comikey not working

### ISSUE THREAD

**Issue by anwarbariibrahim** [CarlosEsco/Neko#682]
### Device information
* Neko version: 2.6.1
* Android phone & version: Note 9, android 11

## Steps to reproduce
Open any chapter with comikey as source
### Expected behavior
Chapter open (apparently redirect to their website or something idk)
### Actual behavior
HTTP error 403

**Comment by Zurkei** [comment]
Comikey currently responds with a http 403 forbidden access when Neko makes an api request for the chapter.

**Comment by CarlosEsco** [comment]
Comikey was disabled in 2.7.0 until a fix is found
