### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by ShockedCoder** [CarlosEsco/Neko#683]
### Device information
* Neko version: 2.6.1
* Android phone & version: Galaxy Note20 - Android 11

## Steps to reproduce
1) Reload 1-3 mangas
2) Search for anything
3) Try to open a chapter
### Expected behavior
1) It will check for new chapters and update the chapter list if there are any new chapters.
2) It will load the results of the search
3) It will load the pages of the chapter
### Actual behavior
1) The loading will freeze at the beginning of the loading anim, and not ahow any new chapters
2) It will load endlessly not showing any results
3) It will load endlessly without a single page
### Other details
For a Tachiyomi fork specialized for MangaDex, surprisingly Tachiyomi works better.

**Comment by ShockedCoder** [comment]
I meant 2.6.1

**Comment by CarlosEsco** [comment]
https://github.com/CarlosEsco/Neko/issues/598

force close your app

**Comment by ShockedCoder** [comment]
> https://github.com/CarlosEsco/Neko/issues/598
> 
> force close your app

I've already done that, and I don't wanna force close my app every 2 chapters.

**Comment by CarlosEsco** [comment]
Then force close, and download for now

**Comment by ShockedCoder** [comment]
Didn't see the issue you quoted at first, but it worked. Thanks.

**Comment by ShockedCoder** [comment]
It broken again and clearing the cache doesn't work anymore
