### ISSUE TITLE
Entire Neko app fails to load anything after reading exactly 3 chapters or when changing currently reading manga

### ISSUE THREAD

**Issue by ValStarfyre** [CarlosEsco/Neko#684]
### Device information
* Neko version: 2.6.1
* Android phone & version: 
* - Samsung J7, Android 11
* - Samsung Galaxy A71, Android 11

## Steps to reproduce
Launch Neko, read 3 chapters
### Expected behavior
Following chapters should be able to load correctly and access to other manga is possible (manga sync should also work correctly) 
### Actual behavior
After 3 chapters (or when switching manga) the entire app enters a timed out state; Nothing can load and that includes other manga and any ongoing manga sync will fail.
### Other details
Manga sync or manga list can still load as intended  before reading 3 chapters

**Comment by CarlosEsco** [comment]
https://github.com/CarlosEsco/Neko/issues/598
