### ISSUE TITLE
Webtoon reading mode displaying breaks between imagines

### ISSUE THREAD

**Issue by Rmattp** [CarlosEsco/Neko#690]
### Device information
* Neko version: 2.6.2
* Android phone & version: Google Pixel 2 XL - Android 11

## Steps to reproduce
  1. Open webtoon not tagged `Long Strip` on mangadex
  1. Change reader mode from default to webtoon

### Expected behavior
 * There should be no boarders between the images

### Actual behavior
 * There are boarders between imagines causing breaks in the image stream.

### Screenshot
![Screenshot_20210920-132736](https://user-images.githubusercontent.com/31457818/134046948-c6a46bad-42d5-4cf2-b850-3362e6345f94.png)

**Comment by CarlosEsco** [comment]
this working as designed.  Non Webtoons are forced to have space to make them "paged".  Open a request on MangaDex website and mention its missing the longstrip tag.  Once they add that you will be good.
