### ISSUE TITLE
App losing connection

### ISSUE THREAD

**Issue by Soggins** [CarlosEsco/Neko#691]
### Redmi Note 10 Pro
* Neko version: 2.6.2
* Android phone & version: Android 11 MIUI 12

App loses internet connection randomly and doesn't reconnect until closed entirely and restarted.

Does stop the update of mangas, the load of next pages, unable to search or check manga or its information unless it's saved locally.

Been happening before 5.6

Disabled battery optimization to check if fhat was the problem, it wasn't

**Comment by CarlosEsco** [comment]
More than likely this is the pinned issue in the repo.

**Comment by MrComexs** [comment]
This happens with me when a read three chapters.

**Comment by CarlosEsco** [comment]
do this and it will probably be resolved https://github.com/CarlosEsco/Neko/issues/598#issuecomment-942768834
