### ISSUE TITLE
Lock with biometric bug

### ISSUE THREAD

**Issue by ayush-km** [CarlosEsco/Neko#692]
### Device information
* Neko version: 2.6.2
* Android phone & version: RealMe C12 & Android 11

I have `lock with biometrics ON` and `lock when idle set to always` and the app doesn't ask for my fingerprint when I open it from the recent tasks, close it then reopen it, or even when I lock my phone and then reopen it.

I have even tried clearing the cache but still doesn't ask for fingerprint.
I have even tried opening the app with power-saving mode turned ON and OFF but still doesn't ask for fingerprint.
I have also checked with TachiyomiJ2K and it is asking me for authentication (for now at least).

This has never happened before (not even with this version) and just started 15 minutes ago.

I have recorded my phone screen and upload the video here ---> [Neko lock with biometrics bug](https://imgur.com/a/fYGEdSm)

**Comment by CarlosEsco** [comment]
Should be fixed in 2.7.0
