### ISSUE TITLE
Downloaded chapters showing up as not downloaded in recents

### ISSUE THREAD

**Issue by ayush-km** [CarlosEsco/Neko#693]
### Device information
* Neko version: 2.6.2
* Android phone & version: RealMe C12 & Android 11

When I download chapters the download icon in recent for all sections (Grouped, All, History, Updates) show the chapter as not been downloaded. This has been happening for quite a while now and I just didn't have the time to report until now. Btw, this doesn't happen in TachiyomiJ2K.

The video of the bug ---> [Downloaded chapters showing up as not downloaded](https://imgur.com/a/0oeKKpL)

**Comment by CarlosEsco** [comment]
you still having this issue in 2.7.3?

**Comment by ayush-km** [comment]
> you still having this issue in 2.7.3?

Yes. Here are the screenshots.

![Screenshot_2021-12-27-23-37-00-98_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/57125345/147499283-fd06364b-d617-4a7e-9989-3f870e53fd54.jpg)
![Screenshot_2021-12-27-23-38-00-32_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/57125345/147499288-b48aa991-d08a-4a47-bd63-ceff035b2738.jpg)
![Screenshot_2021-12-27-23-38-31-29_e93d65b045a4d38b75e3588ffeb6de8f](https://user-images.githubusercontent.com/57125345/147499289-5ee5a4b7-378a-4307-8f6a-8cd072beefc7.jpg)

**Comment by CarlosEsco** [comment]
2.7.3.1

**Comment by ayush-km** [comment]
Thanks for fixing this!
