### ISSUE TITLE
Some unread chapters not showing up

### ISSUE THREAD

**Issue by Dyl-M** [CarlosEsco/Neko#696]
## Device information

* Neko version: 2.6.2
* Android phone & version: Redmi Note 7 (MIUI 12.0.3) w/ Android 10

## Steps to reproduce

1. Synchronize the library (as usual).
2. Open the series' page with its notification indicating the amount of unread chapters.

### Expected behavior

Unread chapters show up.

## Actual behavior

For some series, unread chapter aren't showing up while Neko's well displaying the number of unread chapters.
For now, I have only noticed this problem with 2 series:

- [Hannari Girori no Yoriko-san](https://mangadex.org/title/7143d818-9512-49e8-b94e-751286898508/hannari-girori-no-yoriko-san)
- [Learning The Hard Way (NSFW)](https://mangadex.org/title/195ee876-a11f-4985-ba5b-5a4cc3e09899/learning-the-hard-way)

## Other details

Screenshots for [Hannari Girori no Yoriko-san](https://mangadex.org/title/7143d818-9512-49e8-b94e-751286898508/hannari-girori-no-yoriko-san)

![Screenshot_2021-09-27-09-46-48-545_tachiyomi mangadex](https://user-images.githubusercontent.com/57560342/134868022-5d9c8089-a480-409f-9ba9-46111621bb2e.jpg)
![Screenshot_2021-09-27-09-46-39-475_tachiyomi mangadex](https://user-images.githubusercontent.com/57560342/134868025-77f82aaa-b527-4719-bb52-9951a788dfbc.jpg)
![Screenshot_2021-09-27_Mangadex](https://user-images.githubusercontent.com/57560342/134868029-8a29ab2a-8715-47c1-8bb9-d1e37020dd09.jpg)

**Comment by CarlosEsco** [comment]
Are you sure the manga isn't in a category not being updated?  If you swipe update the manga page it should show no issue

**Comment by Dyl-M** [comment]
I didn't set any category so far, so I'm not sure categories' update is the reason here. Or perhaps you're mentioning a feature I don't know.

**Comment by Dyl-M** [comment]
Indeed. After a kind of "hard" reset (cache & app data + MD logout), the problem is solved.
