### ISSUE TITLE
Allow languages to be enabled per a manga instead of for the whole library

### ISSUE THREAD

**Issue by Bilacomy** [CarlosEsco/Neko#701]
Right know you can only tag chapter language for the entire app, which doesn't really work well if you use multiple ones, cause for example I want to read Tokyo Revengers in Portuguese cause there isn't a translation in English , but for me to do that I need to enable Portuguese to the entire app making so all of my other manga have duplicated chapters, duplicated new chapter notifications and automatically download every new chapter twice (one for each language), and this continues to get worse with each adicional one (I use Spanish too so everything is tripled)

That's why I think it would be good if we were able to set the desired language in each manga to avoid this problems

**Comment by CarlosEsco** [comment]
Thinking over this I think it would be better to be able to filter a language out https://github.com/CarlosEsco/Neko/issues/309
