### ISSUE TITLE
Specify day of the week to update library

### ISSUE THREAD

**Issue by MrSimmmons** [CarlosEsco/Neko#707]
### Why/User Benefit/User Problem
(explain why this feature should be added)
When auto updating the library weekly, it would cool to be able to specify the day of the week that the update is called. Currently I have my settings set to weekly with wifi and chargeing enabled and it always wants to update on a Wednesday or Thursday. However I mainly do my reading in the weekend so it would be nice to be able to set it to update on a Friday night or a Saturday.

### What/Requirements
(explain how this feature would behave)
When the weekly option is set, show a drop-down that allows the user to select what day of the week they would like the update to begin (device time)

**Comment by CarlosEsco** [comment]
Probably won't add a specific option to choose a day.  An easy way to actually schedule it for the day you want is to disable library update, then on the day you want around the hour you want it to update enable weekly then.  Then it should update roughly the same time that day each week.
