### ISSUE TITLE
Cannot Unfollow manga

### ISSUE THREAD

**Issue by eemelis** [CarlosEsco/Neko#716]
### Device Information
* OnePlus 9 Pro
* Android version 11
*  Neko Version 2.6.2

### Steps to reproduce
1. Change reading status to Unfollowed
2. Refresh the manga

### Expected behavior
Manga is unfollowed/removed from MD library

### Actual behavior
Manga reading status is returned to its previous state after refreshing the manga

**Comment by eemelis** [comment]
@CarlosEsco Nothing changed. The problem is only with Unfollowing. I can change the reading status to anything else without a problem.

**Comment by CarlosEsco** [comment]
I'm not able to emulate this.

**Comment by CarlosEsco** [comment]
do you still have this issue on 2.7?

**Comment by eemelis** [comment]
> do you still have this issue on 2.7?

Yes, it is still an issue.

Here are 2 different screen captures showing it returning its status.
https://imgur.com/a/Insh1Ly

**Comment by CarlosEsco** [comment]
@eemelis  are you on the discord channel?

**Comment by CarlosEsco** [comment]
Update to 2.7.1.2 and try to unfollow, when it fails please dump the crash log in advanced settings and send it here

**Comment by eemelis** [comment]
[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/7614455/neko_crash_logs.txt)

There is the crash log. Also I joined the Discord. Username is Ceph#1875
