### ISSUE TITLE
Manually downloaded manga chapters not downloading

### ISSUE THREAD

**Issue by Mortus06** [CarlosEsco/Neko#717]
### Device information
* Neko version: 2.6.2
* Android phone & version: Samsung S20 Ultra 5G
Android 11

## Steps to reproduce
Manually clicking the download button of a manga chapter
### Expected behavior
The downloaded is initialized and gradually completed
### Actual behavior
The download icon turns gray with a spinning circle (the normal "queued" chapter download icon) but never initialises the download

### Other details
This issue only occurs with manually selected chapters: automatically fetched chapters are downloaded without any issues

**Comment by CarlosEsco** [comment]
Is there a specific chapter you have this issue with?  Or all

**Comment by Mortus06** [comment]
@CarlosEsco the problem occurs with every chapter I try to download manually

**Comment by CarlosEsco** [comment]
Can you logout and then force close app, then relogin

**Comment by Mortus06** [comment]
I was reluctant to do so but you're actually right, thank you and sorry for this trouble :D
