### ISSUE TITLE
[bug] "No result found" when viewing browse menu logged in

### ISSUE THREAD

**Issue by Mrfiregem** [CarlosEsco/Neko#72]
When I log into my account through the app, I am no longer able to view entries in the browse pane, even while searching.
I have tried opening both web view and external browser (the  same in my case" to pass Cloudflare checks, but to no avail.  
I use 2FA on my account, so that may or may not be part of it.

1. Fresh install of the app
2. View the browse pane, dismiss the login prompt and see manga load
3. Log in through settings menu or browse's popup
4. Get No results found

Version info:
 - Device: LG K30
 - Android Version: 8.1.0
 - Version: 1.0.5

**Comment by CarlosEsco** [comment]
Once you are logged in. Go to your library. Then back to browse does it load?

**Comment by Mrfiregem** [comment]
No it does not. I've imported a backup from Tachiyomi and can view and open those manga no problem, so I don't think it's a connection problem, either.

**Comment by Mrfiregem** [comment]
I've also tried removing 2FA and logging in as well as removing excluded tags to see if that interfered with it, but nothing changed.

**Comment by CarlosEsco** [comment]
Can you go on the tachiyomi discord and either message me or message in the neko channel.  Will be easier to help debug.

**Comment by CarlosEsco** [comment]
[Neko-dev-debug.zip](https://github.com/CarlosEsco/Neko/files/3163591/Neko-dev-debug.zip)

**Comment by CarlosEsco** [comment]
view wasnt set to detailed on mangadex website.
