### ISSUE TITLE
Ability to change the margin for chapters in webtoon format

### ISSUE THREAD

**Issue by SergeantEli** [CarlosEsco/Neko#724]
### Why/User Benefit/User Problem
(explain why this feature should be added)
There is some manhua/manhwa that is meant to be read in long strip format but sometimes Neko will put it as my default (right to left) which I would then change to Webtoon mode. It then results in a gap between panels in the chapter.

![Screenshot_20211031-111114_Neko](https://user-images.githubusercontent.com/67759206/139591490-74ce5121-bde3-4560-bf90-3ed89e05ae71.jpg)
> This is a screenshot from Neko of the first chapter of [this](https://mangadex.org/title/0bca50c1-e3ac-4a2e-bc9b-9d8984c81dd3/i-lost-the-leash-of-the-yandere-male-lead) manhwa by Tartali Scans.

By allowing the margins to be changed the user would be able to minimize or remove these gaps to allow better enjoyment when reading.
### What/Requirements
(explain how this feature would behave)
Similar to the mangadex website it would add an option in the reader settings or quick menu when in webtoon reading mode to choose how large or small the user wants the panel margins to be.

![image](https://user-images.githubusercontent.com/67759206/139592139-baf23a4c-6760-4677-a2cd-4be98a80701a.png)
> This is a screenshot of the settings in the website version of mangadex.org and it is possible on the mobile version as well

##### Small Note
In Tachiyomi J2K it automatically detects long strip format chapters and removes the gaps beforehand.

**Comment by CarlosEsco** [comment]
Webtoons are already auto detected.  The problem is whatever series you are reading is missing the tag.  Open the series in webview then report the series saying it's missing the longstrip tag.

The margin exists for people who read non webtoons in a webtoon reader to distinguish between pages.

**Comment by Rubberxgum** [comment]
How about adding a continuous vertical mode with margin then make the webtoon mode without margin regardless of the long strip?
