### ISSUE TITLE
Failure to Sync MangaDex Follows

### ISSUE THREAD

**Issue by Ryenu** [CarlosEsco/Neko#734]
### Device information
* Neko version: 2.6.2
* Android phone & version: Note 20 Ultra & Android 11

### Expected behavior

When pressing Sync MangaDex follows in the settings app should pull new follows from the MangaDex site

### Actual behavior

App shows a notification for syncing follows but the notifications disappears and no follows are synced.

### Other details

Have tried logging out and back into MangaDex as well as force closing and opening the app and also a full data delete into backup.

**Comment by CarlosEsco** [comment]
Did you verify you actually followed them and didn't just change their reading status?  Dex v5 following is not the same as reading status so both is needed for the sync to work

**Comment by Ryenu** [comment]
Yes i just went and tried following a random manga to see if that was it and it still didnt sync just popped up the notification then went away with no update or pop-up like usual.

**Comment by Ryenu** [comment]
If it helps pushing follow to MangaDex still works as intended its only pulling from MangaDex that is broken.

**Comment by CarlosEsco** [comment]
You have the bell clicked right?

![Screenshot_20211106-174104.png](https://user-images.githubusercontent.com/2092019/140624656-4115eb6c-964b-42a3-b1c6-0558af016edd.png)

**Comment by Ryenu** [comment]
Yes

**Comment by Ryenu** [comment]
Issue seems to have fixed itself.
