### ISSUE TITLE
Can't Download After Updating Library

### ISSUE THREAD

**Issue by hatsu20** [CarlosEsco/Neko#740]
### Device information
* Neko version: 2.6.2
* Android phone & version: Realme C21, Android 11

## Steps to reproduce
1. Updating library.
2. Downloading chapters. 
3. Can't download chapters even after changing to mobile data. 
4. Force close the app, the re-open. 
5. Tries to download again, it works. 
### Expected behavior
Immediately downloading. 
### Actual behavior
Have to force close the app, and re-opening it to be able to download. 
### Other details
Video of the bug: https://files.catbox.moe/1zhp4i.mp4

**Comment by CarlosEsco** [comment]
Can you do the backup restore thing. Mentioned in the pinned (infinite load) issue.

**Comment by hatsu20** [comment]
Already tried the solution, and it works like a charm! Thank you so much!
