### ISSUE TITLE
Reading progress not syncing on library refresh

### ISSUE THREAD

**Issue by Jerrk** [CarlosEsco/Neko#749]
### Device information
* Neko version: 2.6.2
* Android phone & version: Galaxy Note 8 & Android 9

## Steps to reproduce
1. update your reading progress outside of neko (i.e read a chapter while logged in on a browser on your PC.)
2. update your neko library
3. reading progress is not updated until you enter the title page in neko

### Expected behavior
the reading progress should update when updating the library.

### Actual behavior
the reading progress is updated after the library is updated AND the title is viewed

### Other details
[heres a video of the issue](https://thumbs.gfycat.com/DrearyUnhappyAmmonite-mobile.mp4)
as you can see on the badge it disappears after i enter the title page because i've already read the chapter on mangadex.org in my browser.

**Comment by CarlosEsco** [comment]
This isn't quite a bug, just a feature that isnt added yet

**Comment by Jerrk** [comment]
If i change the "reading status" from say "reading" to "dropped" this does not update on library refresh.
i have to open the title page for the "reading status" to refresh.

**Comment by CarlosEsco** [comment]
As expected, updating status from library refresh is still not a thing
