### ISSUE TITLE
Manga cover resizes with title size till it disappears

### ISSUE THREAD

**Issue by Xiamthy** [CarlosEsco/Neko#753]
### Device information
* Neko version: 2.7.0
* Android phone & version: Galaxy Tab 3 10.1 (Android 7)

## Steps to reproduce
Open Manga with a long title on a tablet 
### Expected behavior
Manga Cover should stay the same size on the left side and title should be beside the cover
### Actual behavior
Manga Cover on the left disappears when title is too long
### Other details
Screenshots show how the cover resizes with the title length or even disappears.
Another one on discord tried it with their tablet and also had that problem.

![Screenshot_20211123-085136](https://user-images.githubusercontent.com/64652938/142987984-67f4a217-370a-4554-91c1-721798adfc24.png)
![Screenshot_20211123-085205](https://user-images.githubusercontent.com/64652938/142987985-8a671385-9d87-44d0-bc47-b5c9b2e5f48c.png)
![Screenshot_20211123-085221](https://user-images.githubusercontent.com/64652938/142987989-51760135-b388-4901-b292-81548760543c.png)

**Comment by CarlosEsco** [comment]
This should have been fixed in 2.7.2
