### ISSUE TITLE
Progress bar not respecting Reading Mode

### ISSUE THREAD

**Issue by AviKav** [CarlosEsco/Neko#754]
### Device information
* Neko version: 2.7.0
* Android phone & version: Moto G Stylus - A11 (Oct. patch)

## Steps to reproduce

Have effective Reading Mode as Right to Left

### Expected behavior

Progress bar is Right to Left

### Actual behavior

Progress bar is Left to Right

### Other details

Chapter progress and page count numbers appear to be on the correct sides

![image](https://user-images.githubusercontent.com/18518861/143005449-0e3798f6-6ef9-4304-981b-df46b2f499cf.png)

**Comment by dddlr** [comment]
Can confirm on Neko 2.7.0 and Android 11 (Galaxy S10e)

2.6.2 had the correct behaviour so I think this is a regression



2.6.2: (correct)

![Screenshot_20211127-122138_Neko.png](https://user-images.githubusercontent.com/2908767/143660864-fe2d6efd-7c71-4a19-8202-e2ad8621d3c2.png)

2.7.0: (wrong)

![Screenshot_20211127-122300_Neko.png](https://user-images.githubusercontent.com/2908767/143660859-d62704a2-1c02-43c1-b121-75fd2f0ac7e8.png)
