### ISSUE TITLE
Having the ability to mark everything in your library as read

### ISSUE THREAD

**Issue by Ruuubickk** [CarlosEsco/Neko#756]
Hi, I have as of two days ago started using your fork to finally read manga on my phone, and after syncing everything with my mangadex library realised that my reading progress wasn't transferred, which means every single chapter showing as available in the "Unread" chapter sorting.

Having the ability to either transfer my progress for chapters read would be idea, but I'm guessing there's a reason that isn't implemented, so I'm wondering if being able to mark everything as read would be a suitable option in the meantime, as I would then have parity over the mangadex website.

It's also only an action that needs to be performed once, or every so often just in case you end up reading a lot on other devices and it doesn't automatically sync your progress.

The same way the Mark as Read button exists right now, having that option on a library scale would be convenient in my use case, unless there is a better way to go at it, given your tight UI layout already.

Thanks !

**Comment by CarlosEsco** [comment]
Do you have the enable sync option?  If so if you click into a manga the reading status will sync

**Comment by CarlosEsco** [comment]
Also there is already a mark all as read option on the library.  Long click  and select the manga then click the 3 dot then mark as read
