### ISSUE TITLE
Sort by Chapter Number is broken

### ISSUE THREAD

**Issue by X9VoiD** [CarlosEsco/Neko#759]
### Device information
* Neko version: 2.7.0
* Android phone & version: LG G7 Android 10

## Steps to reproduce
- Go to Library
- Pick "Monster no Goshujin-sama"
- Sort by chapter number

### Expected behavior
- Chapters are sorted according to chapter number.

### Actual behavior
- Chapters are not sorted accordingly.

![Screenshot_20211126-170513](https://user-images.githubusercontent.com/10338031/143557863-c6c14731-6efb-4510-857c-c58c46d2002c.png)

### Other details
- This bug is a regression and does not happen on previous release version of Neko.
- It can happen with and without merged manga on multiple manga/webtoons.
- I'm not sure if this is a problem too upstream so I decided to open the issue here first. :bread:
- May provide other manga/webtoons where the bug can be reproduced upon request.

**Comment by CarlosEsco** [comment]
#752
