### ISSUE TITLE
Chapters out of order even when it's sorted in chapter number order

### ISSUE THREAD

**Issue by theresnobio** [CarlosEsco/Neko#760]
### Device information
* Neko version: 2.7.0
* Android phone & version: LG Stylo 5 Android version: 10

## Steps to reproduce 
Tap on a manga and look through chapters in chapter number order.
### Expected behavior
It should be going up in chapter number order like 1,2,3,4.... 
### Actual behavior
It goes out of order like 5,6,7,1,2,3
### Other details

This happened after the new update

![Screenshot_20211126-184759](https://user-images.githubusercontent.com/84305225/143666162-b94037ad-5475-4bd2-b6f5-9ddecd51d04d.png)
![Screenshot_20211126-184748](https://user-images.githubusercontent.com/84305225/143666164-6434fdf3-9765-4aba-80a7-239f8ea9fdc5.png)
![Screenshot_20211126-184730](https://user-images.githubusercontent.com/84305225/143666165-be2cc488-099d-434f-9972-cea003874796.png)

**Comment by CarlosEsco** [comment]
#752
