### ISSUE TITLE
Expanding one category expands all categories

### ISSUE THREAD

**Issue by Blockshift758** [CarlosEsco/Neko#762]
### Device information
* Neko version: 2.7.1
* Android phone & version: Realme C25 (android 11)

## Steps to reproduce
Tap a category
### Expected behavior
The category tapped is the only one to expand or close
### Actual behavior
All other categories also expand or closes after tapping one
### Other details

[Categories behavior](https://youtube.com/shorts/_4OW1oH0V3g?feature=share)

**Comment by CarlosEsco** [comment]
2.7.3
