### ISSUE TITLE
Can't update manga

### ISSUE THREAD

**Issue by Ikhsan1412** [CarlosEsco/Neko#763]
Just update to 2.7.1 and the manga won't update at all via global refresh nor per manga refresh.

Device: Huawei Nova 7i running on android 10 EMUI 11.0.0 (not using HarmonyOS)

**Comment by CarlosEsco** [comment]
can you try some of the solutions in https://github.com/CarlosEsco/Neko/issues/598

**Comment by gavliador** [comment]
I have the same issue.

**Comment by Ikhsan1412** [comment]
> can you try some of the solutions in #598

normally I do that on older version, but it's no longer effective on newest version

**Comment by CarlosEsco** [comment]
Are you on the discord channel.  Can you message me in the neko channel

**Comment by Ikhsan1412** [comment]
> Are you on the discord channel. Can you message me in the neko channel

I'm not on Neko discord, where do I get the invite link?

**Comment by CarlosEsco** [comment]
It's the Tachi one on the main GitHub neko page

**Comment by NinjaDebugger** [comment]
Been having the same issue since early yesterday morning.  None of the solutions for the previous bug worked, nor did restarting the phone.  In order to get updates working again, I had to uninstall and revert to an older version.

**Comment by NinjaDebugger** [comment]
Went on discord, after backing up, uninstalling, reinstalling previous version, and updating THAT, updates seem to be working again.  Not sure WTF.

**Comment by gavliador** [comment]
Uninstalling and reinstalling worked for me too. Everything works fine now ☺️.

**Comment by CarlosEsco** [comment]
Anyone still having this issue can you update to the latest (2.7.1.2) and dump the crash log in advanced settings after it doesn't update

**Comment by Ikhsan1412** [comment]
> Anyone still having this issue can you update to the latest (2.7.1.2) and dump the crash log in advanced settings after it doesn't update

This is [my dump](https://pastebin.com/DkSLFHWg)

**Comment by CarlosEsco** [comment]
Thanks

**Comment by CarlosEsco** [comment]
Gonna close this as this is the same issue.

https://github.com/CarlosEsco/Neko/issues/764

**Comment by CarlosEsco** [comment]
> > Anyone still having this issue can you update to the latest (2.7.1.2) and dump the crash log in advanced settings after it doesn't update
> 
> This is [my dump](https://pastebin.com/DkSLFHWg)

Can you open a new ticket just saying something like bug and attach this file.  It's unrelated to the updating but the error you have is a different thing

**Comment by Ikhsan1412** [comment]
> > > Anyone still having this issue can you update to the latest (2.7.1.2) and dump the crash log in advanced settings after it doesn't update
> > 
> > 
> > This is [my dump](https://pastebin.com/DkSLFHWg)
> 
> Can you open a new ticket just saying something like bug and attach this file. It's unrelated to the updating but the error you have is a different thing

Done
So my problem is entirely different matter?

**Comment by CarlosEsco** [comment]
Your problem should be resolved the file you uploaded with an error should be unrelated

**Comment by Ikhsan1412** [comment]
ah okay, thanks for the explanation
