### ISSUE TITLE
Manga with large amount of chapters get stuck updating

### ISSUE THREAD

**Issue by Jeglerjeg** [CarlosEsco/Neko#764]
### Device information
* Neko version: 2.7.1.2
* Android phone & version: S20U A11

## Steps to reproduce
Add a manga with a large amount of chapters to your library, e.g. Kingdom, and attempt to update your library
### Expected behavior
Library finishes updating
### Actual behavior
Library update gets stuck
### Other details
Crash logs:
[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/7614826/neko_crash_logs.txt)

**Comment by CarlosEsco** [comment]
Funny enough this error wasn't the error preventing the updating but I did fix both in the newest version
