### ISSUE TITLE
Bug report (dev's ask me to do this tho)

### ISSUE THREAD

**Issue by Ikhsan1412** [CarlosEsco/Neko#767]
### Device information
Android version: 10 (SDK 29)
Android build ID: JEF-N29 11.0.0.169(C301E7R3P2)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWJEF
Device model: JEF-NX9

* Neko version: 2.7.1.2 (standard, 3f51090, 132, 2021-11-28T19:29:48.420474)
* Android phone & version: 10 (SDK 29)

## Steps to reproduce
Refresh the manga list by hold and dragging down

### Expected behavior
The manga is updating

### Actual behavior
No load/update

### Other details
[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/7622566/neko_crash_logs.txt)

**Comment by CarlosEsco** [comment]
Fixed in 2.7.1.4
