### ISSUE TITLE
Think neko isn't recognizing special accents. Not completely sure. 

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#769]
### Device information
* Neko version: 2.7.1.3
* Android phone & version: Note 9 Android 10

## Steps to reproduce
1. Download manga with accent in title. The one I currently have issue with is called La Forêt
2. Restart app (force stop and open again)
3. Downloaded chapters not marked as downloaded

### Expected behavior
Show chapters are downloaded

### Actual behavior
Chapters not marked as downloaded.
But chapters can still be read offline.

**Comment by vipzzx** [comment]
![Screenshot_20211130-021807_Neko.jpg](https://user-images.githubusercontent.com/59638889/144003474-ff52f7b3-af0c-47d4-a10e-89c3e0b7424d.jpg)
![Screenshot_20211130-021938_Neko.jpg](https://user-images.githubusercontent.com/59638889/144003488-a20ec643-b5b2-4ac3-ac0e-446d68a43e3d.jpg)
![Screenshot_20211130-021948_My Files.jpg](https://user-images.githubusercontent.com/59638889/144003499-8f042c4b-fced-4af1-ad8e-9a26a84e86e0.jpg)

**Comment by CarlosEsco** [comment]
Can you check if this is an issue on j2k

**Comment by vipzzx** [comment]
Not an issue in j2k.

**Comment by vipzzx** [comment]
seems to be working properly now after i cleared data and added the manga back in. this was the one that was giving -1 as a source when i went to restore in j2k
https://discord.com/channels/349436576037732353/569823838305648640/919312609264697397
