### ISSUE TITLE
manga dex to neko catalog delay[bug]

### ISSUE THREAD

**Issue by Darkvramp** [CarlosEsco/Neko#77]
**Describe the bug**
The catalog for Neko, that pulls from mangadex is either behind somehow or is missing something from mangadex for a time. This time period is short, and whenever Neko requests the user library updated, it seems to pull all the updated chapters, but there is this delay, where if you were not explicitly looking at both the site and Neko(I know I'm crazy) you would not notice anything is wrong, and only manually requesting for the chapter in the catalog, by pulling down on the chapters list do you generally get the full list.

**Screenshots**
this first screenshot is from mangadex site, where the manga has 44 chapters
![Screenshot_20190530-130903_Firefox-2](https://user-images.githubusercontent.com/48525649/58655282-66787900-82df-11e9-889b-e7292eaa10ca.jpg)
the second one is from Neko in the chapter description where it shows how many it has( it also showed up in the catalog like it would have been recently updated.
![Screenshot_20190530-131018_Neko-1](https://user-images.githubusercontent.com/48525649/58655431-ab041480-82df-11e9-91a4-bef7e59a407d.jpg)
this screenshot is also from Neko from the chapter list screen
![Screenshot_20190530-131022_Neko-1](https://user-images.githubusercontent.com/48525649/58655465-bf481180-82df-11e9-9165-0b09b883e102.jpg)
this last screenshot is from Neko where I manually updated the chapter list
![Screenshot_20190530-131115_Neko-2](https://user-images.githubusercontent.com/48525649/58655537-ef8fb000-82df-11e9-9633-43f90d1513a8.jpg)

**Please complete the following information:**
 - Device: Galexy S7
 - Android Version: [e.g. Android 8.0.0]
 - Neko Version [e.g. 1.0.5]

**Comment by Darkvramp** [comment]
![Screenshot_20190531-052833_Firefox](https://user-images.githubusercontent.com/48525649/58700453-aaae5c80-8365-11e9-95bd-9b31a16cf883.jpg)
![Screenshot_20190531-052910_Firefox](https://user-images.githubusercontent.com/48525649/58700459-af731080-8365-11e9-8678-883195986bb4.jpg)
![Screenshot_20190531-052919_Neko](https://user-images.githubusercontent.com/48525649/58700468-b7cb4b80-8365-11e9-8c11-ca36d5750b7e.jpg)
![Screenshot_20190531-052924_Neko](https://user-images.githubusercontent.com/48525649/58700478-bef25980-8365-11e9-9a84-e3906a915a19.jpg)
![Screenshot_20190531-052929_Neko](https://user-images.githubusercontent.com/48525649/58700494-c87bc180-8365-11e9-91d8-d35b2caba62f.jpg)
![Screenshot_20190531-052929_Neko](https://user-images.githubusercontent.com/48525649/58700505-d3365680-8365-11e9-8b90-71b15b98433a.jpg)
![Screenshot_20190531-052933_Neko](https://user-images.githubusercontent.com/48525649/58700512-d6c9dd80-8365-11e9-9429-44c2cacc32ca.jpg)

**Comment by CarlosEsco** [comment]
closing and reopening in a different ticket
