### ISSUE TITLE
Get error codes when trying to add MAL/Kitsu tracking

### ISSUE THREAD

**Issue by Na9Cl7** [CarlosEsco/Neko#770]
### Device information
* Neko version: 2.7.1.3
* Android phone & version: s10+ Android version 11

### Actual behavior: 
an error code MAL[http error 500]/ Kitsu[http 415]

**Comment by Na9Cl7** [comment]
![Screenshot_20211130-025328_Neko](https://user-images.githubusercontent.com/95275989/144010897-e4bc1942-e5b3-4349-b9ae-7eebe871497b.jpg)

**Comment by Na9Cl7** [comment]
![Screenshot_20211130-032430_Video Player](https://user-images.githubusercontent.com/95275989/144011438-f850b55a-dd43-43de-b0e8-a16b73494916.jpg)

**Comment by CarlosEsco** [comment]
Fixed in 2.7.1.4
