### ISSUE TITLE
Can't update library

### ISSUE THREAD

**Issue by Shtate** [CarlosEsco/Neko#771]
### Device information
* Neko version: v2.7.1.3
* Android phone & version: Galaxy xcovers 4s /Android 11

## Steps to reproduce
Update library in Library or Recents
### Expected behavior
Library updates (bar fills up)
### Actual behavior
Says that library is updating, but is stuck on the first manga (bar doesn't fill up)
### Other details
Manually updating manga works fine

**Comment by CarlosEsco** [comment]
can you attach a crash log

**Comment by Shtate** [comment]
> can you attach a crash log

content://tachiyomi.mangadex.provider/ext_cache_files/neko_crash_logs.txt

**Comment by CarlosEsco** [comment]
that link doesnt work

**Comment by Shtate** [comment]
> that link doesnt work
[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/7624664/neko_crash_logs.txt)

**Comment by CarlosEsco** [comment]
Update to 2.7.1.4 if it still happens dump a log again. There was an error with the logs

**Comment by Shtate** [comment]
[neko_crash_logs (1).txt](https://github.com/CarlosEsco/Neko/files/7625398/neko_crash_logs.1.txt)

**Comment by CarlosEsco** [comment]
Ok that's not showing anything still so it's not crashing. Can you go into the neko folder delete the log file, enable extreme logging in advanced settings in app, force close app, then try. When it gets stuck send the log file

**Comment by Shtate** [comment]
[neko_crash_logs (2).txt](https://github.com/CarlosEsco/Neko/files/7625483/neko_crash_logs.2.txt)

**Comment by CarlosEsco** [comment]
@Shtate its not the crash log after you enabled debug logging, its a the file in the neko folder.  Delete it, emulate the issue, then go into a file explorer and send that file.

**Comment by CarlosEsco** [comment]
@Shtate @Ikhsan1412  can you logout then login then try.  That last log looks like you are getting failed auth attempts

**Comment by Ikhsan1412** [comment]
> @Shtate @Ikhsan1412 can you logout then login then try. That last log looks like you are getting failed auth attempts

yep, work for me. Thanks!

**Comment by Leoooob** [comment]
> @Shtate @Ikhsan1412 can you logout then login then try. That last log looks like you are getting failed auth attempts

This fixed the issue for me. A few times when I've had issues syncing it seems the error gets swallowed silently, is there anything on the cards for error handling on syncing? Probably the most frustrating kind of issue to have IMO

**Comment by CarlosEsco** [comment]
I will create a ticket for the reauth stuff, i just feel i'll finally figure it out, and then they will change the auth like they are planning :rofl:

**Comment by Leoooob** [comment]
It's a pretty small niggle now that there's a workaround at least. The number of times I force-stopped the app and then cleared the cache 😂

**Comment by Shtate** [comment]
I tried the logout then login method and it worked, thank you
