### ISSUE TITLE
Downloaded chapter not saving in the right location

### ISSUE THREAD

**Issue by ExodosPavilion** [CarlosEsco/Neko#777]
### Device information
* Neko version: 2.7.1.4
* Android phone & version: Samsung A7 (2017) running android version 8.0.0

## Steps to reproduce
Change the "Download Location" in settings to somewhere other than default (try sd card as well)
Download a chapter

### Expected behavior
Chapter is downloaded to the newly defined location

### Actual behavior
Chapter is downloaded to default location (app tells me default is /storage/emulated/0/Neko/downloads)

### Other details
The other options provided by the app don't work either. It will persistently download to the default location

**Comment by kazundo** [comment]
I have the same problem as you I can no longer download the chapters or update my manga library !!!

**Comment by CarlosEsco** [comment]
> I have the same problem as you I can no longer download the chapters or update my manga library !!!

your issue is unrelated to this.  See the pinned in the github issue repo

**Comment by CarlosEsco** [comment]
2.7.3

**Comment by ExodosPavilion** [comment]
Confirmed working from update 2.7.3. Thanks.
