### ISSUE TITLE
Updating Library dosen't work

### ISSUE THREAD

**Issue by KnightRevan** [CarlosEsco/Neko#778]
### Device information
* Neko version: 2.7.1.4
* Android phone & version: Samsung A01 Android 10

## Steps to reproduce
Refresh library 

### Expected behavior
To download new chapters or tell there are no new chapters
### Actual behavior
The notification pops up, but the bar doesn't move and no new chapters show up in recents
### Other details
I have tried logging out and back in, but it just doesn't work

Here is the logs

App version: 2.7.1.4 (standard, bb37f43, 134, 2021-11-30T11:22:39.107261)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A015AUCU3AUA1
Device brand: samsung
Device manufacturer: samsung
Device name: a01q
Device model: SM-A015A
Device product name: a01quc--------- beginning of main
12-08 01:51:30.688 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:32.259 13481 13481 E ViewRootImpl: sendUserActionEvent() mView returned.
12-08 01:51:36.649 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:38.065 13481 13481 E ViewRootImpl: sendUserActionEvent() mView returned.
12-08 01:51:40.163 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:40.274 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:41.374 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:46.238 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:49.870 13481 13481 E InputMethodManager: prepareNavigationBarInfo() rootView is null
12-08 01:51:51.030 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.048 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.056 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.072 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.089 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.106 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.123 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.156 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.172 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.256 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.273 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.289 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.306 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:51.325 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:51:52.196 13481 13481 E ViewRootImpl: sendUserActionEvent() mView returned.
12-08 01:52:06.385 13481 13481 E DecorView: mWindow.mActivityCurrentConfig is null
12-08 01:52:07.824 13481 13481 E ViewRootImpl: sendUserActionEvent() mView returned.

**Comment by CarlosEsco** [comment]
try some of the things at the bottom of this issue.

https://github.com/CarlosEsco/Neko/issues/598
