### ISSUE TITLE
library not updating

### ISSUE THREAD

**Issue by rewgge** [CarlosEsco/Neko#781]
### Device information
* Neko version: 2.7.1.4
* Android phone & version: android 10 miui global 12.0.10

## Steps to reproduce
try to manually update library

### Expected behavior
Library updates

### Actual behavior
library does not update and progress bar is stuck

### Other details
![IMG_20211211_130452](https://user-images.githubusercontent.com/87353003/145683376-8f9226d8-3d1c-4da6-8c88-ef14635b8677.jpg)

progress bar has been stuck on the first manga for more than 30 minutes

**Comment by CarlosEsco** [comment]
Force close app, log out relogin
