### ISSUE TITLE
Not showing Mangas skipped because they were not MD

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#782]
### Device information
* Neko version: 2.7.1.4
* Android phone & version: Note 9 Android 10

## Steps to reproduce
Restore backup 

### Expected behavior
Restore all mangas and be able to open log for missing mangas 

### Actual behavior
No logs 

### Other details
![20211211_132432.jpg](https://user-images.githubusercontent.com/59638889/145687935-0de78bea-5b91-4bf3-a29c-4bbab4058a03.jpg)

**Comment by CarlosEsco** [comment]
2.7.3
