### ISSUE TITLE
Browse items fail to load if too many in a row are in library and "hide titles in library" is on

### ISSUE THREAD

**Issue by apotheon-** [CarlosEsco/Neko#783]
### Device information
* Neko version: 2.7.1.4
* Android phone & version: Huawei Mediapad M5 Lite, Android 8

## Steps to reproduce
- Go to "Browse" Tab
- Disable"hide titles in library" (eye icon has to be crossed) 
- For any given sorting mode ("Number of follows" for example):
- &nbsp;&nbsp;&nbsp; Long tap first 20 entries (without any gaps) to add them into library
- Enable "hide titles in library" (eye icon has to be not crossed)

### Expected behavior
- When "hide titles in library" get enabled, the list of items should appear without those already in library

### Actual behavior
- When "hide titles in library" get enabled, the list is empty (no items shown)

### Other details
- This is reproducible in all sorting modes
- If the sequence of 20 libraried items start anywhere at k*20+1, the previous items may be shown, but the behaviour of next failing to load will persist.
- This behaviour can be circumvented by identifying each 20 libraried sequence (ex. 1-20, 41-60) and breaking it by removing a single item from library belonging to this sequence. It will cause the list to go on until it runs out of items to load for real.
- This is probably related to how batches of items are fetched/parsed, a list of top 20 items with 20 of these exluded would yield an empty object or no object at all, which could be interpreted as end of list, hence browser does not fetch next batches
- Sequence length seems to correlate to actual batch size from MdUtil
`const val mangaLimit = 20`

**Comment by apotheon-** [comment]
IMO left side of `val hasMoreResults = mangaListDto.limit + mangaListDto.offset < mangaListDto.total` check should be decreased by amount of titles in library.

**Comment by CarlosEsco** [comment]
2.7.3
