### ISSUE TITLE
Syncing after reading

### ISSUE THREAD

**Issue by Galaxtxc** [CarlosEsco/Neko#788]
### Device information
* Neko version: 2.71.4
* Android phone & version: Google Pixel 4a Android 12

## Steps to reproduce
Log in to anilist
Settings > Tracking > Sync on > Anilist
### Expected behavior
Syncing after reading a chapter 
### Actual behavior
Not syncing and syncs instead with Refreshing tracking metadata (Settings>Advanced)
### Other details

Tried with cell and wifi data

**Comment by CarlosEsco** [comment]
you have the manga linked in the manga info page?

**Comment by Galaxtxc** [comment]
Issue Resolved. Thank you!
