### ISSUE TITLE
[bug] SOLVED Notch space not used in reading mode

### ISSUE THREAD

**Issue by tonarii** [CarlosEsco/Neko#79]
**Describe the bug**
Hi, i already posted on tachiyomi, but i think this fork is more up to date. 
Is it possible to make this app notch friendly and be able to have a full screen page in reading mode?

**Expected behavior**
I'd like a full screen reading, with the notch space used.

**Please complete the following information:**
 - Device: Xiaomi Mi 9
 - Android Version: miui 10.2.26.0 / android 9 pkq1.181121.001
 - Version 1.0.8

**Additional context**
I tried to install android studio to play with and try this myself, but this is so much a pain in the a.. i have every time a java error... i tried so many version of java, and android studio, change configurations but always an error and i can't export the apk.
Thanks a lot for this great app.

**Comment by CarlosEsco** [comment]
I saw this on tachiyomi but why would you want it?  It's not like you can read in the notch space

**Comment by tonarii** [comment]
Hi, yes but when i say notch space i mean the space on the sides of the notch. The notification space. 
It's weird to have a rounded screen on one side and a straight one on the other side.
It's more an estetic issue but if it's simple and easy to fix, i would really appreciate this feature.

**Comment by tonarii** [comment]
I managed to do it by adding a style.xml file inside the values-28 folder and adding those lines : 

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Base.Theme.AppCompat" parent="@style/Base.V28.Theme.AppCompat" />
    <style name="Base.Theme.AppCompat.Light" parent="@style/Base.V28.Theme.AppCompat.Light" />
    <style name="Base.Widget.AppCompat.Toolbar" parent="@style/Base.V28.Widget.AppCompat.Toolbar" />
    <style name="Base.Widget.Design.AppBarLayout" parent="@style/Base.V28.Widget.Design.AppBarLayout" />
    <style name="Base.V28.Theme.AppCompat" parent="@style/Base.V23.Theme.AppCompat">
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
    <style name="Base.V28.Theme.AppCompat.Light" parent="@style/Base.V23.Theme.AppCompat.Light">
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
    <style name="Base.V28.Widget.AppCompat.Toolbar" parent="@style/Base.V7.Widget.AppCompat.Toolbar">
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
    <style name="Base.V28.Widget.Design.AppBarLayout" parent="@style/Base.V21.Widget.Design.AppBarLayout">
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
</resources>`

Might need to clean this because i'm not a dev ^^
Also, i think that Tachiyomi is not running under sdk 28 isn't it ? So i could not use the same code to add notch support to it ? Because all my manga are on this app...but maybe i can just move them from one app to the other.

**Comment by CarlosEsco** [comment]
been super busy will try to look at this when i get a chance.

**Comment by tonarii** [comment]
like that that works great for me on both Neko and Tachiyomi.
The important part is this line :
`<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>`
