### ISSUE TITLE
chapters won't update

### ISSUE THREAD

**Issue by RileyKemp** [CarlosEsco/Neko#790]
### Device information
* Neko version: 2.7.1.4
* Android phone & version: OnePlus 8 pro, Android 11 build 11.0.9.9IN11AA

## Steps to reproduce
Open app and swipe to refresh 

### Expected behavior
Chapters updated

### Actual behavior
Hangs on first manga, won't update any even if I cancel the update queue and just try to update one. 

### Other details
This also occurs on auto update.

**Comment by CarlosEsco** [comment]
logout, relogin

**Comment by RileyKemp** [comment]
Thanks, I feel foolish for not trying that first.
