### ISSUE TITLE
"Sync MangaDex follows" won't sync all manga.

### ISSUE THREAD

**Issue by Tigoreetur** [CarlosEsco/Neko#795]
### Device information
* Neko version: 2.7.1.4
* Android phone & version: Moto G5, 8.10

## Steps to reproduce
Delete all manga.
Use "Sync MangaDex follows"

### Expected behavior
All manga is synced.

### Actual behavior
Only 200 are synced.

**Comment by CarlosEsco** [comment]
You are syncing from dex to neko?  Are you sure they are all followed?

**Comment by Tigoreetur** [comment]
Yes, no, I thought they were but they weren't. They were under library but not followed.
