### ISSUE TITLE
Red H badge not showing properly

### ISSUE THREAD

**Issue by vipzzx** [CarlosEsco/Neko#800]
### Device information
* Neko version: 2.7.2
* Android phone & version: Note 9 Android 10

## Steps to reproduce
Filter to show only pornographic
Select any manga
Red H badge is blocked by cover

### Expected behavior
Red H badge shouldn't be blocked

### Actual behavior
The badge is blocked 
![Screenshot_20211223-201717_Neko.jpg](https://user-images.githubusercontent.com/59638889/147304277-cdc26dcc-a7ac-4b2d-acf3-5f2a33f56ae4.jpg)

**Comment by CarlosEsco** [comment]
2.7.3
