### ISSUE TITLE
Browse tab not showing true latest updated manga

### ISSUE THREAD

**Issue by JumpyJacko** [CarlosEsco/Neko#805]
### Device information
* Neko version: 2.7.3.2
* Android phone & version: Samsung Galazy S8, Android ver. 9

## Steps to reproduce
Go to browse tab.

### Expected behavior
Show latest updated manga on Mangadex, such as these titles:

![Screenshot_20220103-132825_Chrome.jpg](https://user-images.githubusercontent.com/48436180/147896063-7f040459-11ca-46c6-b5f3-05165e57bf64.jpg)

### Actual behavior
Shows different manga.

Browse
![Screenshot_20220103-132900_Neko.jpg](https://user-images.githubusercontent.com/48436180/147896088-70eda966-5b45-4800-a2b6-7ebc546ede73.jpg)

Browse > Latest
![Screenshot_20220103-132908_Neko.jpg](https://user-images.githubusercontent.com/48436180/147896097-634a62a1-2777-4b2b-8d4f-01686ae68ee7.jpg)

### Other details
This might be a Mangadex api issue, but I'm not too sure.

**Comment by CarlosEsco** [comment]
So there are a few issues all with the api.

1.  when using the manga list api (which the browse does) you can not filter by translated language so latest shows everything.
2.  The manga plus script on MangaDex side is putting dates in 2030s  so thats why you see things like Assassination Class room on the top 

There's nothing i can do on my end at this time.

**Comment by asdkant** [comment]
@CarlosEsco can you somewhat make it so neko ignores invalid dates until the root cause is fixed? it's pretty annoying and that seems like a reasonable temporary solution

**Comment by CarlosEsco** [comment]
Will look into

**Comment by CarlosEsco** [comment]
latest screen now handles the future dates properly.

**Comment by asdkant** [comment]
I'm still having to scroll past the same mangas every time when browsing latest (JP+KR, sort by latest update)

**Comment by CarlosEsco** [comment]
> I'm still having to scroll past the same mangas every time when browsing latest (JP+KR, sort by latest update)

You need to click latest in the filter sheet.  Sort by latest in browse is basically useless because it doesn't respect your reading language choice
