### ISSUE TITLE
Show Tracker Links in Webview External Links screen

### ISSUE THREAD

**Issue by curche** [CarlosEsco/Neko#809]
### Why/User Benefit/User Problem
Right now, only External Links shown are Anime-Planet, Mangaupdates, Dex, Raw, EngTL (as per [source](https://github.com/CarlosEsco/Neko/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/external/ExternalLink.kt))
Being able to open links to Trackers Websites (Anilist, MAL, Kitsu) would be nice to have as well. Yes, it shows up thru Tracker Sheet (if logged in and added tracking) but I'm not sure if there is a particular reason to not see all external links in one place

### What/Requirements
Add Anilist, MAL, Kitsu links as icons in External Links screen
However, since the screen would now have too many links:
 Maybe there could be a button for just Webview and then a sheet with all external links stuff
 OR Pin Webview to always be in the bottom of the sheet, everything else arranged however at top. Showing everything onto a Grid works too
 OR Subsections like Similar Manga section 
 OR maybe something else (just wrote some ideas that came to mind while I was writing this)

**Comment by CarlosEsco** [comment]
fixed in 2.8.0 added a few more external links while i was at it.
