### ISSUE TITLE
Fields [data, datasaver, hash] are required

### ISSUE THREAD

**Issue by Sousetsu** [CarlosEsco/Neko#811]
### Device information
* Neko version: 2.7.1.2
* Android phone & version: Note 10+ V:11

## Steps to reproduce
Trying to read any manga chapter, tried several series to same behavior
### Expected behavior
Opens to Manga
### Actual behavior
Opens and instantly closes the manga and gives the error message as seen in attachment
### Other details

![Screenshot_20220110-042237_Neko](https://user-images.githubusercontent.com/31942650/148745283-efc3da35-be85-4140-9486-e1e1ce7ac536.jpg)

**Comment by CarlosEsco** [comment]
update your app
