### ISSUE TITLE
Latest shows a Filter button even though it cannot filter

### ISSUE THREAD

**Issue by curche** [CarlosEsco/Neko#812]
### Device information
* Neko version: 2.7.3.2
* Android phone & version: Mi A2 (jasmine-sprout), A12 (custom ROM)

## Steps to reproduce
1. Open App and switch to Browse
2. Tap on Filter
3. Tap on Latest

### Expected behavior
Moves to new screen which shows Latest using /chapter but with no Filtering possible

### Actual behavior
Takes you to a new screen with Latest chapters that also shows a Filter button that doesn't work at all

### Other details
Screenshot attached
![Screenshot_20220113-004939_Neko_1](https://user-images.githubusercontent.com/72807749/149208297-f7307c8a-79b2-404d-9bc3-6ea2165b0544.png)

**Comment by CarlosEsco** [comment]
fixed in 2.8.0
