### ISSUE TITLE
comikey didn't support

### ISSUE THREAD

**Issue by rinaTarigan** [CarlosEsco/Neko#822]
### Device information
* Neko version: newest v 2.7.3.2
* Android phone & version: xiaomi mi a1, android 9

## there's manga that the sources or tracking come from comikey, but the manga can't loaded or downloaded. Said that the source doesn't support.
Example in promise cinderella newest update manga source is from comikey, but the manga can' loaded or downloaded. 
thank you

**Comment by CarlosEsco** [comment]
added long press option to open in webview for chapters
