### ISSUE TITLE
Pages in reader turn theme's color when using arrow key on WSA

### ISSUE THREAD

**Issue by Daxxas** [CarlosEsco/Neko#832]
### Device information
* Neko version: 2.8.0
* Android phone & version: Windows Subsystem for Android

## Steps to reproduce
1. Open a random manga in neko
2. Use arrow to browse manga

### Expected behavior
Pages stay normal like this :
![image](https://user-images.githubusercontent.com/21078787/151430491-b741cd00-14ec-4944-b77b-f75e38e8461c.png)

### Actual behavior
Pages turn neko theme's color like this : 
![image](https://user-images.githubusercontent.com/21078787/151430446-d0367cbc-870b-4ddc-b10b-c653ed5133e0.png)

### Other details
The fix already exists in vanilla tachiyomi but j2k didn't pull the fix (https://discord.com/channels/349436576037732353/569823838305648640/936309389931991050)

**Comment by CarlosEsco** [comment]
will be fixed in 2.8.0.1 which should be out soon
