### ISSUE TITLE
Manga titles in similar tab not visible with pure black mode

### ISSUE THREAD

**Issue by PiBits-314** [CarlosEsco/Neko#836]
### Device information
* Neko version: 2.8.0.1
* Android phone & version: Oneplus 7, Android 11 (Oxygen OS 11.GM57AA)

## Steps to reproduce
Appearance -> switch on Pure black mode
Open any manga page, go to it's similar manga

### Expected behavior
Manga titles are visible

### Actual behavior
Manga titles are not visible in any view (list or tiles)
Only the percent match can be seen

![image](https://user-images.githubusercontent.com/78010820/151804575-bc097915-48a9-463e-9d50-2ee1e5282e8b.png)
![image](https://user-images.githubusercontent.com/78010820/151804611-49e4b9ef-4aec-41f2-ba92-9b5eaba7516f.png)
(Manga used is "Wonder cat kyuu-chan" for this example)

### Other details
When the pure black mode is turned off, the titles are visible.

**Comment by CarlosEsco** [comment]
fixed in 2.8.0.2
