### ISSUE TITLE
Download keeps stopping and skipping

### ISSUE THREAD

**Issue by Rubberxgum** [CarlosEsco/Neko#838]
### Device information
* Neko version: version 2.8.0.1
* Android phone & version: Redmi Note 10 - Android 12 (custom ROM)

## Steps to reproduce
 Download manga.

### Expected behavior
 The manga will keep downloading until all the chapters are downloaded.

### Actual behavior
 Some chapter stops downloading in the middle and skips to the next chapter.

### Other details
 The chapters that are skipped starts downloading again when I paused and start the download.

![Screenshot_20220202-053542_Pixel Launcher.png](https://user-images.githubusercontent.com/90501519/152055474-5f52f005-9489-4482-9a7d-16f590b531df.png)

**Comment by MedKing3** [comment]
Why is this being ignored? Am I the only one experiencing it?

**Comment by CarlosEsco** [comment]
I do not have this issue, and can't replicate it, so not much I can do if you can't provide more information or logs

**Comment by MedKing3** [comment]
How to take logs? I haven't had this issue since turning on data saver but I'm asking just in case.

**Comment by CarlosEsco** [comment]
> How to take logs? I haven't had this issue since turning on data saver but I'm asking just in case.

Can dump the error log in advanced settings
