### ISSUE TITLE
[bug] New Follows tab does not display anything

### ISSUE THREAD

**Issue by leotaku** [CarlosEsco/Neko#84]
**Describe the bug**
When I go to the "Follows" tab using the sidebar, I am presented with an empty page and a popup displaying the following text:

```
Attempt to invoke virtual method 'java.lang.String'   [Retry]
```
Pressing the Retry button causes the notification to redisplay.

**To Reproduce**
1. Go to 'Follows'
2. See the Error

**Expected behavior**
Be shown a Screen with all series that I follow on the Mangadex site.

**Please complete the following information:**
 - Device: [e.g. Galaxy s10e]
 - Android Version: [e.g. Android 9.0]
 - Version [e.g. 1.1.0]

**Comment by CarlosEsco** [comment]
fixed in 1.1.1

If anything besides a reading follow status was in follows it was causing this error.
