### ISSUE TITLE
Wrong dates messes up the order of the manga list

### ISSUE THREAD

**Issue by BenjaCagliero** [CarlosEsco/Neko#840]
### Device information

* Neko version: v2.8.0.1
* Android phone & version: S21 ultra Android 11

## Steps to reproduce

Open the app and go to your library and order it by release date then go to the first one (assuming it's set to show the newest first). If you can't do it try following Ayakashi Triangle or Dandadan, with the English version of the chapters.

### Expected behavior

It should  order the mangas by the time a chapter is released, and in each chapter show when it was really released, like in the mangadex website.
![Screenshot_20220205-105946_Neko.jpg](https://user-images.githubusercontent.com/90117823/152645422-b0bd1d8f-7038-43be-8f81-e176c0f25076.jpg)

### Actual behavior

Particularly with MangaPlus Scanlator group it shows the release date for their recent chapters to be December 31 of 2037, putting those chapters first on the list.
![Screenshot_20220205-105704_Neko.jpg](https://user-images.githubusercontent.com/90117823/152645359-334fd8a9-e913-4daf-933a-d79ee4f943f0.jpg)
![Screenshot_20220205-111549_Neko.jpg](https://user-images.githubusercontent.com/90117823/152645533-ce1f9cb7-19e1-49a6-ae7d-9002dde40a8f.jpg)

### Other details

It probably happens because mangadex redirects you to MangaPlus's website when you open their chapters.
And it happens in quite few mangas, all scanlated by them.

**Comment by xeroxthebeautiful** [comment]
I've been having the same issue for days now. My app and android version are the same too. Nearly all of them are MagaPlus and say December 31st 2037 but at least one is from Bilibili and says February 12th 2022.

**Comment by CarlosEsco** [comment]
fixed in 2.8.0.2
