### ISSUE TITLE
Mark mangadex chapters as read on the website when replacing a read merged chapter

### ISSUE THREAD

**Issue by Jeglerjeg** [CarlosEsco/Neko#843]
### Why/User Benefit/User Problem
Currently mangadex chapters get marked as read in the app when they replace an already read merged chapter, but this isn't reflected on the website. Using the async read status setting should ideally mark them as read, so they don't need to be checked off manually on the website.

### What/Requirements
When having async read status on, read merged chapters replaced by mangadex chapters should be marked as read on the website.

**Comment by CarlosEsco** [comment]
merged chapters don't replace anymore, and the logic of when a dex chapter would replace a merged chapter was completely outside area where marked read occurs so it would have required a major refactor.  

If  down the line this occurs you  can just swipe the new dex chapter read in neko and it will mark it read on the site.
