### ISSUE TITLE
Customizable browse filtering shortcut

### ISSUE THREAD

**Issue by asdkant** [CarlosEsco/Neko#844]
### Why/User Benefit/User Problem
Nearly every time I browse mangadex, I filter by:
- JP + KR original language (not CN since there's A LOT (see [this reply](https://github.com/CarlosEsco/Neko/issues/671#issuecomment-917534732) for #671 ) and I'm mostly not interested)
- sort by latest uploaded (won't go into the limitations of the API that doesn't allow language filtering)
- I don't even bother with filtering out tags I'm not interested in, since that'd be too much to do

Doing this *every single time* is bothersome.

### What/Requirements
Either a way to customize the default filtering (something like what #673 is asking for, but more complete), or a way to "save" filter settings and have a shortcut handy.

**Comment by CarlosEsco** [comment]
As of 2.11.0 you can set the filters how you want in the browse screen then save it, and set it as a default for every search
