### ISSUE TITLE
Enhancements for the browse view

### ISSUE THREAD

**Issue by asdkant** [CarlosEsco/Neko#845]
### Why/User Benefit/User Problem
It's common for me to want to go through the latest MD releases, get updates for the very latest of what I'm following, and check out new stuff. Having to go into the page of a given manga and wait for the app to load the updated info incurs in a lot of lag, so having a way to operate from the list view would be useful

### What/Requirements
- badges for unread/download count (it's okay if it just pulls local information and it's only for stuff I'm following)
- a way to update a manga from the list view, or a switchable feature that automatically pulls updated for followed manga when it appears in the browse view 
  - maybe with some rate-limiting to avoid spamming the API?
  - maybe a way to be able to multi-select and tell the program "check updates for all of these"
- a way to tell neko to download updates from a given manga (or a selection) straight from the list view

**Comment by CarlosEsco** [comment]
No plans ATM to do any of these.  The UX for download/update doesn't really fit with the current patterns.  Badges would be too much especially with in library badges.
