### ISSUE TITLE
Group Deeplink: Shows Non-English manga in results

### ISSUE THREAD

**Issue by curche** [CarlosEsco/Neko#846]
### Device information
* Neko version: 2.8.0.1
* Android phone & version: 12

## Steps to reproduce
1. Open this group link - https://mangadex.org/group/e17834de-79b2-4c23-b6e7-e93e94118409/wicked-house-translation OR just search `grp:e17834de-79b2-4c23-b6e7-e93e94118409`
2. Observe that the results contain this manga:  [Fate/Grand Order - Zettai Gohan Sensen Artoria (Doujinshi)](https://mangadex.org/title/4dbf66fe-1713-444b-aa26-68a0e46806e4/fate-grand-order-zettai-gohan-sensen-artoria-doujinshi)
3. Open the manga to check if there are any chapters by the group we searched for in 1. i.e. Wicked House Translations

### Expected behavior
Since we searched for the group's chapters, we should be able to see that

### Actual behavior
There is no chapter under this group in this manga. When you check WebView, you realise there was actually a Vietnamese chapter done by the group! (Neko uses MangaDex (EN))

### Other details
This could be filtered out by passing [`translatedLanguages`](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/8b18e2f12e41fa7fb25db24688cca1d22e8398cd/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt#L160) in the Search query

**Comment by CarlosEsco** [comment]
fixed in 2.8.0.2
