### ISSUE TITLE
Titles without any ratings have bugged flag visuals

### ISSUE THREAD

**Issue by Jeglerjeg** [CarlosEsco/Neko#847]
### Device information
* Neko version: 2.8.0.1
* Android phone & version: S20U A12

## Steps to reproduce
Open a title without any ratings

### Expected behavior
Flags render normally

### Actual behavior
Flag renders on top of follow count 
![image](https://user-images.githubusercontent.com/31293237/153057732-27a3aa74-be62-4d25-af6e-c95d9524dcdf.png)

**Comment by CarlosEsco** [comment]
fixed in 2.8.0.2
