### ISSUE TITLE
MangaPlus titles episodes are set 31 of December of 2037

### ISSUE THREAD

**Issue by Niinebits** [CarlosEsco/Neko#857]
Titles uploaded by Mangaplus are showing at the top of the library when sorted by last updated... i really dont know if this is a bug but i just wanted to post it somewhere, since i dont know if its a neko or mangadex bug. or if its something else.
![Screenshot_20220215-025002](https://user-images.githubusercontent.com/44558443/154002283-d9187ca2-f048-489b-b557-4a9529044c04.png)
![Screenshot_20220215-024951](https://user-images.githubusercontent.com/44558443/154002287-e0b60a
![Screenshot_20220215-024936](https://user-images.githubusercontent.com/44558443/154002295-ecdd0a10-5a87-4e38-87ed-28af6c563b61.png)
c6-64a8-4f46-a6d9-90817248acd1.png)

**Comment by CarlosEsco** [comment]
fixed in 2.8.0.2 you will need to swipe refresh the chapter list to refresh it
