### ISSUE TITLE
Neko stopped pulling manga updates from mangadex

### ISSUE THREAD

**Issue by Kortzy** [CarlosEsco/Neko#858]
### Device information
* Neko version: 2.8.0.1
* Android phone & version: google pixel 4a android version 12

## Steps to reproduce
 
update manually the library or wait for the timed update

### Expected behavior

search and find the new chapters of followed manga

### Actual behavior

doesn't update the newest chapters

### Other details

this is the case since 28 dec 2021
the notification for neko library update appears but even if I leave it for a full day it doesn't update a single entry.

**Comment by CarlosEsco** [comment]
If you have discord we can help debug this easier.
