### ISSUE TITLE
[bug] Login button missing

### ISSUE THREAD

**Issue by sunny-lan** [CarlosEsco/Neko#87]
**Describe the bug**
On the login popup, there is no login button. 

**To Reproduce**
1. Go to Browse
2. The login menu shows up, but there is no button to actually log in. This occurs even if I type in the correct username and password.

**Expected behavior**
There should be a button to log in.

**Screenshots**
![Screenshot_20190927-001223](https://user-images.githubusercontent.com/14915260/65741857-aef04980-e0bb-11e9-8e3e-8b9bc88ef08d.png)

**Please complete the following information:**
 - Device: BLU Advance 5.2
 - Android Version: Android 7.0
 - Version 1.1.2

**Additional context**
N/A

**Comment by CarlosEsco** [comment]
Do you have a custom theme or anything going on?

**Comment by sunny-lan** [comment]
No, everything is default.

**Comment by CarlosEsco** [comment]
Were you in landscape?

**Comment by sunny-lan** [comment]
No

**Comment by CarlosEsco** [comment]
So i think this is a bug in the dialog library, but i am unable to upgrade the dialog library at this time.  Will have to be done later

**Comment by CarlosEsco** [comment]
fixed in 1.4.2
