### ISSUE TITLE
Artist no longer showed in library

### ISSUE THREAD

**Issue by legacy9899** [CarlosEsco/Neko#874]
### Device information
* Tachiyomi version: Neko 2.8.0.2
* Android phone & version: Android 12 DerpFest Custom ROM, Redmi 8A Pro
## Steps to reproduce
Open any manga with different author and artist
### Expected behavior
Both author and artist showed in the apps
### Actual behavior
Only author name visible, but artist no longer visible in the apps
### Other details
![Screenshot_20220301-082255_DerpLauncher](https://user-images.githubusercontent.com/87656247/156087221-3325e0a3-f045-4f82-a7e1-88233352bbda.png)
![Screenshot_20220301-082315_DerpLauncher](https://user-images.githubusercontent.com/87656247/156087225-ea8ac8e3-3f1c-43da-9758-83ff4a676c0d.png)

**Comment by CarlosEsco** [comment]
Fixed in 2.9.0
