### ISSUE TITLE
When scanlator groups are filtered out, they are still downloaded when "Download Unread" chapters is selected

### ISSUE THREAD

**Issue by Rudoal** [CarlosEsco/Neko#882]
### Device information
* Neko version: 2.8.0.2
* Android phone & version: Android 12 Samsung S21+

If you filter out scanlator groups and go to download the unread chapters through the "Next Unread" or "All Unread", the groups filtered out are still downloaded. This behaviour is also reflected in the reader, when the chapter is finished and you go to the next chapter, the next chapter would be of the group filtered instead of skipping that chapter and going to the next available not filtered chapter.

**Comment by CarlosEsco** [comment]
Added in 2.9.0
