### ISSUE TITLE
Add a "Delete Downloaded Chapters" from library screen

### ISSUE THREAD

**Issue by Rudoal** [CarlosEsco/Neko#883]
### Why/User Benefit/User Problem
If you want to batch delete downloaded chapters of manga in your library, selecting them and pressing delete downloaded chapters would be faster than going into each manga itself and deleting the chapters. This feature is available in [SY](https://cdn.discordapp.com/attachments/569823838305648640/953434565844803654/Screenshot_20220315-232819_TachiyomiSY.png) where the library delete popup shows the option instead of [no option.](https://cdn.discordapp.com/attachments/569823838305648640/953434316849958982/Screenshot_20220315-232715_Neko.png)

### What/Requirements
(explain how this feature would behave)

**Comment by CarlosEsco** [comment]
2.9.4
