### ISSUE TITLE
Showing the "Art" section of the manga

### ISSUE THREAD

**Issue by MCSilverMask** [CarlosEsco/Neko#894]
### Where
In each manga in mangaDex website, there is a section called art,which shows various cover arts of the manta either with volume book cover or centerfold, etc.

### Why/User Benefit
Its a feature I love about mangadex,my request might be niche, but mangadex put it there for a reason

### Requirements
As you see fit to either adding an art button to the button raws under the manta info, or make it so its tabbed

**Comment by CarlosEsco** [comment]
2.10.0
