### ISSUE TITLE
[Feature Request] Directly browse to manga instead of requiring search

### ISSUE THREAD

**Issue by mrpeanut188** [CarlosEsco/Neko#90]
MangaDex has disabled guest searches as part of DDoS mitigation, and as far as I can tell there is no way to browse directly to a manga to add it to my library. This means anything that doesnt show up on the front page is unreachable as any search results in 0 results. I have seen the search disabled in the past and I think there needs to be a way to directly browse to mangas to accommodate for users without verified accounts.

**Comment by CarlosEsco** [comment]
#44 will address that.  Though neko is designed more to make a user login if they want to use it.

**Comment by mrpeanut188** [comment]
Thanks, I actually made an account but their email verification isn't sending properlu so I'm waiting to hear back from their support email. This is more of the reason why I actually suggested this as even though I've signed up I am still locked out of search and as such all Neko functionality besides the front page.

**Comment by AviKav** [comment]
What email provider do you use?

**Comment by mrpeanut188** [comment]
It's a @hotmail.com address.

**Comment by CarlosEsco** [comment]
made login mandatory so this isnt required anymore
