### ISSUE TITLE
Add Download button to chapter update notification

### ISSUE THREAD

**Issue by ArdaxHz** [CarlosEsco/Neko#915]
This feature is already available in the original Tachiyomi. It adds a "Download" button to the chapter notification, next to "View chapters" and "Mark as read".

Tachiyomi:
![image](https://user-images.githubusercontent.com/70710586/165411374-366963c9-5d6e-488a-b8c9-e07898f328c9.png)

Neko:
![image](https://user-images.githubusercontent.com/70710586/165411415-c7b44aec-3b3e-455f-be1d-847439900377.png)

**Comment by CarlosEsco** [comment]
2.10.11
