### ISSUE TITLE
Error when trying to log in

### ISSUE THREAD

**Issue by 0x0D0ALineBreak** [CarlosEsco/Neko#918]
### Device information
* Neko version: 2.8.0.2
* Android phone & version: Galaxy A71 5G, android ver. 11

## Steps to reproduce
Go to Setting > MangaDex Settings > MangaDex Login
Enter username & password
Press "Log in"
### Expected behavior
Log in as normal
### Actual behavior
Button changes to "Unknown error", error message appears stating "Error trying to login https code: 401"

**Comment by CarlosEsco** [comment]
401 means unauthorized.  I would make sure you can login to your account through the MangaDex website, and that you have confirmed your account.
