### ISSUE TITLE
False http 451 error on select neko manga [bug]

### ISSUE THREAD

**Issue by Darkvramp** [CarlosEsco/Neko#94]
Select manga in neko(in my case Survive as the hero's wife) throws a http 451 error when the manag is still present both in the web veiw and the browser veiw of neko. Just not in the normal manga viewer. It is also present in the normal firefox browser on my phone.
My phone has android 8.0.0
With neko version. 1.1.2
It is not a productive kind of error, and it seems to be selective to either this manga, or from others comments in the discord, to a select few others when it should not occur.

**Comment by CarlosEsco** [comment]
in 1.2
