### ISSUE TITLE
"Wi-Fi only" but using mobile data

### ISSUE THREAD

**Issue by Jerrk** [CarlosEsco/Neko#941]
### Device information
* Neko version: 2.8.0.2
* Android phone & version: Galaxy Note 8, Android 9

## Steps to reproduce
Unknown

### Expected behavior
Neko should only use Wi-Fi

### Actual behavior
Neko is using Mobile Data

### Other details
I haven't touched my settings for months and all of a sudden today i get a data warning and my data usage looks like this:
![](https://i.imgur.com/8OrKHWy.jpeg)

Both my library and download settings are for Wi-Fi only
![](https://i.imgur.com/XakI9og.jpeg) ![](https://i.imgur.com/PPqgGEi.jpeg)

My phone is always on a VPN as well if that has anything to do with it.

i can see that 2 titles had a mass-update earlier today and i would assume those are the culprits but i don't understand why they would've been using my mobile data when that hasn't ever been an issue before from what i'm aware of.

**Comment by CarlosEsco** [comment]
Wifi only does account for browsing, opening manga not in library, reading non downloaded manga, loading/downloading new covers not in library.  Are you sure you didn't do any of those.

**Comment by Jerrk** [comment]
I had not opened Neko all day until i got the mobile data warning.

**Comment by CarlosEsco** [comment]
Fixed in 2.9.0

**Comment by Jerrk** [comment]
this issue (or a very similar one) appears to be back. there appears to have been a big update to a couple of manga i follow today coinciding with me moving out of wi-fi range which gave me the mobile data usage warning again.

Same use-case as before: havent opened neko all day, "only download over wi-fi" turned on, connected to VPN, moving out of wi-fi range and then getting the mobile data warning.

Version: 2.13.5

if you think this is a different problem i could open a new issue for it.

**Comment by CarlosEsco** [comment]
@Jerrk did it actually download anything or was it a library update? Is library update restricted to only over wifi?

**Comment by Jerrk** [comment]
i'm am certain it was downloading because when i got the warning i paused the neko downloads and cleared the download queue (which was very long).

"library update restrictions" is set to "wi-fi" and "battery not low"

**Comment by CarlosEsco** [comment]
interesting, cause there hasn't been any code change for this area in a while.  Can you try switching both those settings to not wifi, and back to wifi.  Maybe the setting wasnt working

**Comment by Jerrk** [comment]
I'll do that and get back to you if it happens again 👍
