### ISSUE TITLE
[bug] Recently read's resume works wrong

### ISSUE THREAD

**Issue by DancingXXL** [CarlosEsco/Neko#95]
I have all chapters marked as readed. Currenly I'm re-reading manga and noticed that resume works badly with that condition. It moves you to the next chapter (first page) instead of resuming the last one.

**To Reproduce**
1. Mark all chapters as readed
2. Start to read one of chapters
3. Exit and try to resume it via Recently read's
4. You are on the next chapter...

**Expected behavior**
I think it must resume it as it was unreaded.

App version: 1.1.2

**Comment by CarlosEsco** [comment]
in 1.2
