### ISSUE TITLE
Mangadex java.security.cert.certpathvalidatorexception: Trust anchor certification path not found.

### ISSUE THREAD

**Issue by cvalenciaec** [CarlosEsco/Neko#957]
### Device information
* Neko version: 2.8.0.2
* Android phone & version: Huawei Media Lite 10 & Android 7.0

## Steps to reproduce
Try to open Mangadex search or update library or read a chapter from library

### Expected behavior
Everything works fine

### Actual behavior
everything fails with trust anchor certificate issue

### Other details
this is the same behaviour as this issue : https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11895 , in my device Tachiyomi was failing too with same issue and applying solution provided in above link worked but same fix (add letsencrypt cert to device) didn't worked for Neko; also, this only happens with Neko and "open with webview", if I use "open with browser" Chrome can open succesfully Mangadex.

**Comment by Jabir-Srj** [comment]
I am also having a similar problem.
Samsung Galaxy Note 5 running Android 7.0

**Comment by cvalenciaec** [comment]
I made a Neko backup and imported it in TachiyomiJ2K app with Mangadex source and it worked, I think I will stay with J2K app.

**Comment by CarlosEsco** [comment]
Tomorrow now. Some other things came up that I need to do before the release

**Comment by CarlosEsco** [comment]
Fixed in 2.9.0 you still will need to do the manual install of the cert.
