### ISSUE TITLE
Manga title displayed incorrectly when viewed on landscape on tablet mode

### ISSUE THREAD

**Issue by gcpadua** [CarlosEsco/Neko#961]
### Device information
* Neko version: 2.8.0.2
* Android phone & version: Amazon Fire HD 10 2021, Android 9

## Steps to reproduce
Open the page of any manga with a large enough title (Example: https://mangadex.org/title/d587a5c2-842a-4fc5-a323-cddb5e41a2cb/the-white-mage-who-was-banished-from-the-hero-s-party-is-picked-up-by-an-s-rank-adventurer-this)

### Expected behavior
The title is displayed correctly

### Actual behavior
The title flickers, changing size constantly

### Other details
Example image:
![Screenshot_20220523-003548](https://user-images.githubusercontent.com/73405789/169739528-7ce2d104-3017-4f66-9807-4ba5706856d8.png)

**Comment by CarlosEsco** [comment]
https://github.com/CarlosEsco/Neko/issues/881
