### ISSUE TITLE
MangaUpdates tracking doesn't automatically update chapters read

### ISSUE THREAD

**Issue by Jeglerjeg** [CarlosEsco/Neko#963]
### Steps to reproduce

1. Add MangaUpdates as a tracker
2. Read a chapter

### Expected behavior

Chapters read should update after a chapter is read

### Actual behavior

Chapters read does not automatically update

### Neko version

2.9.0

### Android version

Android 12L

### Device

S20U

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
damn MU users 😆

**Comment by CarlosEsco** [comment]
@Jeglerjeg this seems to be working fine for me, its the mark as read setting that doesnt seem to work only in the Manga Info

**Comment by Jeglerjeg** [comment]
Seems to be working for me now as well, not sure why it didn't earlier 🤷
