### ISSUE TITLE
Merging chapters doesn't merge chapters from season 2

### ISSUE THREAD

**Issue by Rubberxgum** [CarlosEsco/Neko#966]
### Steps to reproduce

1. Open "Study Group" manhwa
2. Select the merge button.

### Expected behavior

It should merge the missing chapters from season 1 and season 2 from Mangalife/see.

### Actual behavior

It only merges chapters from season 1.

### Neko version

2.9.0

### Android version

Android 12 

### Device

Redmi Note 10

### Other details

There are already 41 chapters on season 2 from Mangalife. It used to include chapters
 from season 2 when merging. I know because I read up to S2 - chapter 10  using Neko. But I stopped reading for a while and removed it from my library.

![Screenshot_20220526-143335_Pixel Launcher](https://user-images.githubusercontent.com/90501519/170433536-7b7f827c-d34e-40e5-a832-a1a5dbd4f0fa.png)
![Screenshot_20220526-143227_Neko](https://user-images.githubusercontent.com/90501519/170433551-4b1b93e9-fde3-4c6a-aae5-f25cd0e1cf0a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Hmm, first time mange life has reset chapters after the season ends, and the official source and MangaDex did not.

**Comment by CarlosEsco** [comment]
The deduplication logic has been removed in 2.11.5
