### ISSUE TITLE
Author of manga jittering on tablet mode

### ISSUE THREAD

**Issue by gcpadua** [CarlosEsco/Neko#970]
### Steps to reproduce

Open the Neko App on tablet mode
Open any manga with a large author name

### Expected behavior

The author's name should not jitter and be displayed correctly

### Actual behavior

The author names jitters like it is trying to resize to fit the screen but it never fits

![scrcpy_yH8HsIUY89](https://user-images.githubusercontent.com/73405789/170608348-c116eae7-02f5-4ae6-bacb-cd6626e6bce4.gif)

### Neko version

2.9.0

### Android version

10

### Device

Amazon Tire HD 10 2021

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.9.1
