### ISSUE TITLE
Doesn't load pages

### ISSUE THREAD

**Issue by GyuminLeo** [CarlosEsco/Neko#971]
### Steps to reproduce

1. Open chapter
2. Failed to load pages: Fields [englishPopup,spanishPopup] are required for type with serial name 'ErrorResult; but they were missing

### Expected behavior

Manga should be loaded or downloaded

Spy x Family doesn't load

### Actual behavior

Error: Failed to load pages: Fields [englishPopup,spanishPopup] are required for type with serial name 'ErrorResult; but they were missing

### Neko version

2.9.0

### Android version

12

### Device

LG Velvet LTE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
What chapter specifically is causing the issue? MangaPlus ones?  Can you shared the crashlog after you it happens.

**Comment by GyuminLeo** [comment]
> > What chapter specifically is causing the issue? MangaPlus ones? Can you shared the crashlog after you it happens.

Currently I can only find Spy x Family 

https://drive.google.com/file/d/1FpfXOvKHb8rbOfOIV2YLCnMfd4YqdDmZ/view?usp=drivesdk

Here is the log

**Comment by CarlosEsco** [comment]
2.9.1
