### ISSUE TITLE
Unable to select words from WebView

### ISSUE THREAD

**Issue by Rubberxgum** [CarlosEsco/Neko#977]
### Steps to reproduce

1. Open a manga
2. Select the "Open external links" button
3. Select and open any external link.
4.  Long press a word from the link that you opened on WebView

### Expected behavior

The word should be selected and you should be given an option to copy the word that you selected.

### Actual behavior

The WebView closes.

### Neko version

2.9.0

### Android version

Android 12

### Device

Redmi Note 10

### Other details

https://user-images.githubusercontent.com/90501519/170871049-4b2760b5-5076-455d-b0c6-fc8a3b3f92b1.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.9.1
