### ISSUE TITLE
MangaPlus manga chapters not loading

### ISSUE THREAD

**Issue by X9VoiD** [CarlosEsco/Neko#985]
### Steps to reproduce

1. Navigate to [Kabushiki Gaisha Magi Lumiere](https://mangadex.org/title/35b9f818-926b-4f4a-aa2b-0ac068986a73/kabushiki-gaisha-magi-lumiere)
2. Open Chapter 28.5

### Expected behavior

Chapter should open just fine.

### Actual behavior

Chapter view closes and a toast pops up saying `Serializer for 'MangaPlusResponse' is not found. Mark the class as @Serializable or provide the serializer explicitly.`

### Neko version

2.9.1

### Android version

Android 12

### Device

LG G7

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
2.9.1.1
