### ISSUE TITLE
[bug] Neko crashes on Android 10 devices

### ISSUE THREAD

**Issue by arsonistAnt** [CarlosEsco/Neko#99]
**Describe the bug**
Application crashes on devices that's on Android 10.0 (API 29). 

**To Reproduce**
1. Run on device that has API 29.
2. See "Neko keeps stopping" launch error.

**Expected behavior**
App should launch with no issue.

**Screenshots**
![launch_error](https://user-images.githubusercontent.com/15347566/67238162-89780680-f401-11e9-8562-f68217f832cd.png)

**Please complete the following information:**
 - Device: [Pixel 3XL]
 - Android Version: [ Android 10]
 - Version [10.0]

**Additional context**
Here is the stack output [error](https://pastebin.com/pqUFg2Eu). If you look at the stack trace there seems to be an issue with the old version of Android-Iconics when it calls the getValue method of the ReflectionUtils object. 

I think this problem occurs because of the new Android 10.0 [update ](https://developer.android.com/about/versions/10/non-sdk-q#q-list-changes) restricting the use of reflection to get certain attributes. It seems like updating to the newer version of Android-Iconics will fix this problem. 

In my [fork](https://github.com/arsonistAnt/Neko/commit/94213a0036fab7989d2836f9e29d2948311b0f63) I was able to update iconics successfully & being able to launch the app. It required a bit of refactoring of some old methods that were used because of some lib changes.  I don't know if this is the correct way to go about this issue but if its okay I can make a pull request to apply these changes. 

_I think any use of reflection in this app should be closely considered due to restrictions placed on them in Android 10.0._

**Comment by CarlosEsco** [comment]
Thanks. I hadn't tested the androidx version on Android 10 yet.  Feel free to make a pull request

**Comment by arsonistAnt** [comment]
Seems like there's some reflection usage in the PageIndicatorTextView class that's also causing a crash. I'll make a pull once I fix that as well.
