### ISSUE TITLE
Cant update any manga for new chapters

### ISSUE THREAD

**Issue by Lukafateburn** [CarlosEsco/Neko#996]
### Steps to reproduce

Do not know how to reproduce
But did try to log into mangadex and could do with the same information used in the app 

### Expected behavior

Manga should be updated

### Actual behavior

Get this error message

### Crash logs

Error trying to view chapters java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### Neko version

2.9.1.1

### Android version

Android 7

### Device

Honor 8 FRD-L09

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Same steps from Tachiyomi need to be done here.  See this reddit thread
https://www.reddit.com/r/mangadex/comments/v7jw0s/tachiyomi_extension_not_working/
