### ISSUE TITLE
Fullscreen mode in horizontal not filling the screen 

### ISSUE THREAD

**Issue by MMariusch** [CarlosEsco/Neko#998]
### Steps to reproduce

1. Rotate phone to horizontal
2. Open a manga chapter

### Expected behavior

It should fill the whole screen.

### Actual behavior

Currently the screen gets filled, but there is still a margin (black area) where the front camera is. While zooming this area also doesn't get filled.

![IMG_20220613_212149_092245](https://user-images.githubusercontent.com/49458986/173430387-180394a6-6b81-4d12-8104-2b724c3dc648.png)

As you can see. The punch hole in my phone is really small. I often read novels in apps that fill the whole screen and that hole doesn't bother me. It would be nice to have a real fullscreen. Alternatively this could be an option so that everyone can customis they reader to they like.

### Neko version

2.9.1.1

### Android version

Android 12

### Device

Redmi Note 10 Pro

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/CarlosEsco/Neko/issues/534
